.markdownlint/style.rb
deploy/docs/Performance.md

Add performance troubleshooting (fluent-bit mem buf limit)
---

Add performance troubleshooting (fluent-bit mem buf limit)

---

vagrant/logs-keeper/logs-keeper.py

Logs keeper is script which keeps rotated files. It can be used to check if all logs were read and send correctly through the pipeline 
---

Add logs-keeper to vagrant

---

deploy/helm/sumologic/templates/events-statefulset.yaml
deploy/helm/sumologic/templates/metrics-statefulset.yaml
deploy/helm/sumologic/templates/statefulset.yaml
deploy/helm/sumologic/values.yaml

Allow setting `securityContext` for each fluentd container separately in logs, events and metrics statefulsets.
---

Allow setting securityContext per container in fluentd statefulsets

---

deploy/helm/sumologic/upgrade-2.0.0.sh
tests/upgrade_v2_script/static/fluent_bit.input.yaml
tests/upgrade_v2_script/static/fluent_bit.log
tests/upgrade_v2_script/static/fluent_bit.output.yaml
tests/upgrade_v2_script/static/fluent_bit_image.input.yaml
tests/upgrade_v2_script/static/fluent_bit_image.log
tests/upgrade_v2_script/static/fluent_bit_image.output.yaml
tests/upgrade_v2_script/static/fluent_bit_no_image.input.yaml
tests/upgrade_v2_script/static/fluent_bit_no_image.log
tests/upgrade_v2_script/static/fluent_bit_no_image.output.yaml

Convert this: https://github.com/helm/charts/blob/master/stable/fluent-bit/values.yaml#L5
```
image:
fluent_bit:
repository: fluent/fluent-bit
tag: 1.3.7
pullPolicy: Always
```
into this: https://github.com/fluent/helm-charts/blob/fb1f611236a3d4b4f56514bb1d05b23820f8a409/charts/fluent-bit/values.yaml#L9
```
image:
repository: fluent/fluent-bit
tag: 1.3.7
pullPolicy: Always
```

The v2 migration script fix - migrate Fluent Bit image key instead of deleting it

---

deploy/helm/sumologic/values.yaml

Backport db1e9f89bd2153e043409e1e465784880898f4f9 and b02fc8d3cdb55a34b9ed6c70928ef0352b96f7dd from https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1442

[Backport release-v2.0] Use the ECR repository for dependencies: Fluent Bit, Telegraf and Falco

---

deploy/helm/sumologic/upgrade-2.0.0.sh
tests/upgrade_v2_script/static/fluent_bit.input.yaml
tests/upgrade_v2_script/static/fluent_bit.log
tests/upgrade_v2_script/static/fluent_bit.output.yaml
tests/upgrade_v2_script/static/fluent_bit_image.input.yaml
tests/upgrade_v2_script/static/fluent_bit_image.log
tests/upgrade_v2_script/static/fluent_bit_image.output.yaml
tests/upgrade_v2_script/static/fluent_bit_no_image.input.yaml
tests/upgrade_v2_script/static/fluent_bit_no_image.log
tests/upgrade_v2_script/static/fluent_bit_no_image.output.yaml

Backport b8d9c62349f4b125305218cc1cc714301145cd73 and 577e2a8d5331e8a0af047639e83ee24f3f3b6564 from https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1444

[Backport release-v2.0] The v2 migration script fix - migrate Fluent Bit image key instead of deleting it

---

deploy/helm/sumologic/Chart.yaml

List of commits since `v2.0.2`:
* 15d55392 Prepare v2.0.3-rc.0
* 4e3a8a3a fix: v2 migration script - info on new default value for fluent-bit.image.pullPolicy key instead of just adding it
* d50a3281 fix: v2 migration script - migrate fluent-bit.image.fluent_bit key instead of deleting it
* 0a1c9a50 fix: use the ECR repository for dependencies: Fluent Bit, Telegraf and Falco
* c13df764 doc: fix comments in values.yaml - use double hash at the beginning of a line
* 71c135ae Update additional_prometheus_configuration.md
* f01184ef Allow setting securityContext per container in fluentd statefulsets

Prepare v2.0.3-rc.0

---

deploy/docs/ContainerLogs.md
deploy/helm/sumologic/README.md
deploy/helm/sumologic/values.yaml

Add containerd Fluent Bit Parser
Remove quetes for crio Parser to remove time parsing errors
Related to https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1418 https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1417 https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1414
---

Add information for CRI-O and containerd log parsing

---

deploy/docs/ContainerLogs.md
deploy/helm/sumologic/README.md
deploy/helm/sumologic/values.yaml

Add information for Docker, CRI-O, containerd log parsing
---

[Backport #1441] Add information for Docker, CRI-O, containerd log parsing

---

vagrant/Makefile
vagrant/README.md

Fix #1453
Backport to 2.0 in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1367
---

Fix #1453, remove build-setup from Makefile and README

---

deploy/helm/sumologic/Chart.yaml

Changes since `v2.0.2`:
* b12ff77f Prepare v2.0.3
* c159c714 Fix #1453, remove build-setup from Makefile and README
* 8ce61f39 Prepare v2.0.3-rc.1
* dd2a6163 Add information for Docker, CRI-O, containerd log parsing Add containerd Fluent Bit Parser Remove quetes for crio Parser to remove time parsing errors
* 1d85fcd4 Prepare v2.0.3-rc.0
* 4e3a8a3a fix: v2 migration script - info on new default value for fluent-bit.image.pullPolicy key instead of just adding it
* d50a3281 fix: v2 migration script - migrate fluent-bit.image.fluent_bit key instead of deleting it
* 0a1c9a50 fix: use the ECR repository for dependencies: Fluent Bit, Telegraf and Falco
* c13df764 doc: fix comments in values.yaml - use double hash at the beginning of a line
* 71c135ae Update …

Prepare v2.0.3

---

.github/workflows/backport_bot.yaml

Change from `GITHUB_TOKEN` to a personal access token because of [this](https://github.com/tibdex/autosquash/blob/17fa441faea2c28da8c0dbad1156c7709e93b96d/.github/workflows/autosquash.yml#L27-L33)
> The built-in secrets.GITHUB_TOKEN cannot yet be used because of this limitation:
> https://github.community/t5/GitHub-Actions/Triggering-a-new-workflow-from-another-workflow/td-p/31676
> In the meantime, use a token granting write access on the repo:
> - a GitHub App token
>   See https://github.com/marketplace/actions/github-app-token.
> - a personal access token
>   See https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line.

Change backport bot token

---

deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/logs-pdb.yaml
deploy/helm/sumologic/templates/metrics-pdb.yaml

Up until now logs pdb was created unconditionally. Change this so that it depends on `.Values.sumologic.logs.enabled` and `.Values.fluentd.logs.enabled`.
While at it, add `sumologic.metadata.name.logs.pdb` template to be consistent with metrics pdb.
---

Make pdb definitions and usage consistent

---

deploy/helm/sumologic/Chart.yaml

Bump metrics-server from 5.0.2 [bitnami/metrics-server/Chart.yaml](https://github.com/bitnami/charts/blob/a473ab8047931eafb8cc3850de943ed4efffa47a/bitnami/metrics-server/Chart.yaml) to 5.5.0 [bitnami/metrics-server/Chart.yaml](https://github.com/bitnami/charts/blob/41be44c267b104762815b6963bae864fdc0b91d0/bitnami/metrics-server/Chart.yaml)
This is to address the following warning during installation:
```
W0304 17:00:52.357213   96795 warnings.go:67] rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
```
which comes from
https://github.com/bitnami/charts/blob/a473ab8047931eafb8cc3850de943ed4efffa47a/bitnami/metrics-server/templates/role-binding.yaml#L2
and which in 5.5.0 uses …

Bump metrics-server to 5.5.0

---

deploy/helm/sumologic/conf/setup/main.tf
tests/terraform/static/all_fields.output.yaml
tests/terraform/static/collector_fields.output.yaml
tests/terraform/static/conditional_sources.output.yaml
tests/terraform/static/custom.output.yaml
tests/terraform/static/default.output.yaml
tests/terraform/static/disable_default_metrics.output.yaml
tests/terraform/static/strip_extrapolation.output.yaml
tests/terraform/static/traces.output.yaml

Previous requirement of `~> 2.6` as per [terraform doc](https://www.terraform.io/docs/language/expressions/version-constraints.html#version-constraint-syntax) allows rightmost segment to increment. Let's refine the requirement to `~> 2.8.0
` so that we only get patch version releases.

Refine requirements for sumologic-terraform-provider to ~> 2.8.0

---

deploy/helm/sumologic/values.yaml

This will use https://github.com/SumoLogic/sumologic-kubernetes-setup/releases/tag/v3.0.0 which is based on terraform 0.13.
The image contains the same version of terraform as 2.0.1 used to but it aligns with semver versioning i.e. bumping terraform from 0.12 to 0.13 is a braking change to users and should hence be a major bump not a patch version bump.

Bump setup image to 3.0.0

---

vagrant/scripts/get-kubeconfig.sh

vagrant: add script to get kubeconfig for vagrant cluster
---

vagrant: add script to get kubeconfig for vagrant cluster

---

vagrant/scripts/get-kubeconfig.sh

```
➜  sumologic-kubernetes-collection git:(main) ✗ ./vagrant/scripts/get-kubeconfig.sh
renamed '/home/drosiek/.kube/config' -> '/home/drosiek/.kube/config.bkp.1615300532'
```
---

vagrant: get-kubeconfig: add verbose for moving old config

---

deploy/docs/Troubleshoot_Collection.md

After removing the alias in 2.0 we should have also updated the docs with new prometheus pod name from `kube-prometheus-stack` chart.

Fix prometheus pod name in troubleshooting doc

---

deploy/helm/sumologic/README.md
deploy/helm/sumologic/conf/events/events.conf
deploy/helm/sumologic/values.yaml

Add overrideOutputConf property fro events
Fixes  #1496
---

events: add overrideOutputConf property

---

deploy/helm/sumologic/conf/common.conf

Fixes #1185
It also catches `fluentd.pod.healthcheck`s which are sent in kubernetes as liveness and readiness probes
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/529c984c572d7ccc98a89b3c4aedc60db94feceb/deploy/helm/sumologic/templates/statefulset.yaml#L123-L135
Reference in FluentD docs: https://docs.fluentd.org/deployment/logging#capture-fluentd-logs

Fix match fluent.** deprecation warning

---

deploy/docs/Best_Practices.md
deploy/helm/sumologic/values.yaml

This change upgrades Fluentd image from `v1.12.0-sumo-2` to `v1.12.0-sumo-3` with the following changes in it:
- Add source category prefix and replace dash annotations (#158)
- docs: Update README on kubernetes_sumologic plugin (#157)
It also adds documentation about the added annotations.

feat: Add source category prefix annotation

---

deploy/docs/Installation_with_Helm.md

Specify `--version` flag when installing with helm so that users don't get surprised by getting e.g. 2.0 (with breaking changes) installed.
Addresses https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1502

Specify 1.3 release when installing with helm

---

deploy/helm/sumologic/values.yaml

It's a backport of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1510 with FluentD version https://github.com/SumoLogic/sumologic-kubernetes-fluentd/releases/tag/v1.12.0-sumo-2.1
---

Upgrade Fluentd image to 1.12.0-sumo-2.1

---

deploy/helm/sumologic/conf/setup/setup.sh
deploy/helm/sumologic/templates/setup/setup-job.yaml
deploy/helm/sumologic/values.yaml
tests/terraform/static/all_fields.output.yaml
tests/terraform/static/collector_fields.output.yaml
tests/terraform/static/conditional_sources.output.yaml
tests/terraform/static/custom.output.yaml
tests/terraform/static/default.output.yaml
tests/terraform/static/disable_default_metrics.output.yaml
tests/terraform/static/strip_extrapolation.output.yaml
tests/terraform/static/traces.output.yaml

We need to debug the setup job sometimes.
This PR adds the possibility to make the setup sleep indefinitely so that the setup can be done manually.
---

feature: Add a debug mode to the setup job

---

deploy/helm/sumologic/conf/setup/setup.sh
tests/terraform/static/all_fields.output.yaml
tests/terraform/static/collector_fields.output.yaml
tests/terraform/static/conditional_sources.output.yaml
tests/terraform/static/custom.output.yaml
tests/terraform/static/default.output.yaml
tests/terraform/static/disable_default_metrics.output.yaml
tests/terraform/static/strip_extrapolation.output.yaml
tests/terraform/static/traces.output.yaml

Whenever a user encounters an error that is received from Sumo Logic API it's somehow lost.
This PR addresses that by explicitly checking for expected `.remaining` key in the returned JSON and it explicitly logs the received JSON whenever an error occurs.
Fixes: #1523

Check API errors when getting fields quota in setup job

---

ci/push-helm-chart.sh

To mitigate the following error:
```
$ helm upgrade --install collection --namespace sumologic sumologic/sumologic \
-f /sumologic/values.perk.yaml \
--create-namespace \
--version 2.1.0-rc.0-3-g5482116e84c5075b589a504f61f0f204a15a61e8
Release "collection" does not exist. Installing it now.
Error: failed pre-install: warning: Hook pre-install sumologic/templates/setup/setup-serviceaccount.yaml failed: ServiceAccount "collection-sumologic-setup" is invalid: metadata.labels: Invalid value: "sumologic-2.1.0-rc.0-3-g5482116e84c5075b589a504f61f0f204a15a61e8": must be no more than 63 characters
```
use only 10 SHA characters in dev version instead of 40.

Use only 10 SHA characters for dev builds instead of 40

---

deploy/README.md
deploy/helm/sumologic/Chart.yaml

Fluent Bit to 0.15.1
Metrics Server to 5.8.1
Upgrade correspoding documentation
---

Upgrade subcharts

---

deploy/docs/Installation_with_Helm.md

Specify `--version` flag when installing with helm so that users don't get surprised by getting e.g. 2.0 (with breaking changes) installed.
Addresses https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1502

Release 2.0 document installation of specific version

---

deploy/helm/sumologic/conf/logs/logs.kubernetes.sumologic.filter.conf
deploy/helm/sumologic/values.yaml

We need to expose these properties, but don't want to advertise them, so no README update.

Add chart properties for per-container annotations

---

deploy/README.md
deploy/helm/sumologic/Chart.yaml

Upgrade the following subcharts:
* Fluent Bit to 0.15.4 (app version 1.7.3)
* Metrics Server to 5.8.3

chore: Upgrade Fluent Bit and Metrics Server subcharts

---

.github/workflows/pull_requests.yml
Makefile
ci/markdown_link_check.sh

* use `actions/checkout@v2` and not `actions/checkout@master`
* make markdown link checks required for tests to run
* add `markdown-link-check` makefile target to run locally
---

Tweak CI for markdown-link-check and add makefile target

---

deploy/helm/sumologic/values.yaml

Added Remote/Write Configs for Kafka metrics: 
List of Metrics are on following dochub page:
https://help.sumologic.com/07Sumo-Logic-Apps/10Containers_and_Orchestration/Kafka/Kafka_Metrics
Metrics follow following format:
```
```
---

SUMO-162341: Adding remote write configs for Kafka Metrics

---

deploy/helm/sumologic/values.yaml

remote write config for mysql telegraf metrics

---

deploy/README.md
deploy/helm/sumologic/Chart.yaml

Downgrade fluent-bit and prepare v2.1.1-rc.1
---

Downgrade fluent-bit to 1.6.10

---

deploy/helm/sumologic/values.yaml

Changes:
- chore: Upgrade Fluentd from 1.12.1 to 1.12.2
- feat(kubernetes_sumologic): Set default per-container annotation prefix to "sumologic.com/"
- fix(enhance_k8s_metadata): Fix duplicated service names in metrics metadata
https://github.com/SumoLogic/sumologic-kubernetes-fluentd/releases/tag/v1.12.2-sumo-0

chore: Upgrade Fluentd from v1.12.1-sumo-2 to v1.12.2-sumo-0

---

fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/service_monitor.rb
fluent-plugin-enhance-k8s-metadata/test/resources/endpoints_list.json
fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_service_monitor.rb

This backports https://github.com/SumoLogic/sumologic-kubernetes-fluentd/pull/184 from v2 release.

 fix: Fix duplicated service names in metrics metadata

---

deploy/README.md

Updated Fluentd to v1.12.2 in v2.1.1.

docs: Update version matrix (Fluentd) for v2.1.1

---

ci/markdown_links_lint.sh

Make `markdown-links-lint` work on Darwin by using `ggrep`.
---

Make markdown-links-lint work on Darwin

---

deploy/helm/sumologic/values.yaml

This PR enables metrics for PostgreSQL 
---

Enabling remote write for postgresql metrics

---

deploy/helm/sumologic/conf/logs/fluentd/logs.source.containers.conf

Ingest stacktraces from fluentd (even for [warn]), so we can see them in sumologic 
---

feat: ingest stacktraces from fluentd

---

deploy/docs/Troubleshoot_Collection.md

add instruction how to disable gzip compression
---

docs: add instruction how to disable gzip compression

---

deploy/docker/Dockerfile
deploy/helm/sumologic/conf/setup/main.tf
deploy/kubernetes/setup-sumologic.yaml.tmpl
tests/terraform/static/all_fields.output.yaml
tests/terraform/static/collector_fields.output.yaml
tests/terraform/static/conditional_sources.output.yaml
tests/terraform/static/default.output.yaml
tests/terraform/static/strip_extrapolation.output.yaml
tests/terraform/static/traces.output.yaml

update terraform to 0.13.7 due to following error:
```
Initializing the backend...
Initializing provider plugins...
- Checking for available provider plugins...
Error verifying GPG signature for provider "sumologic"
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.
- Downloading plugin for provider "kubernetes" (hashicorp/kubernetes) 1.11.4...
Warning: registry.terraform.io: For users on Terraform 0.13 or greater, this provider has moved to SumoLogic/sumologic. Please update your source in required_providers.
Error: unable to verify signature …
```

update terraform to 0.13.7

---

.github/workflows/backport_bot.yaml

Allow backport job to run on PR coming from forks. This can be achieved by changing `pull_request` to [`pull_request_target`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target).
Related blog post: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
--- 
Example of a failed backport job due to a missing secret:
> Error: Input required and not supplied: app_id
https://github.com/SumoLogic/sumologic-kubernetes-collection/actions/runs/835990115

Allow backport job to run on PR coming from forks

---

deploy/docs/Best_Practices.md

docs: add mysql multiline example and indtruction how to change scrape interval for metrics
---

docs: add mysql multiline logs example and instruction how to change scrape interval for metrics

---

deploy/helm/sumologic/README.md
deploy/helm/sumologic/templates/events-statefulset.yaml
deploy/helm/sumologic/templates/metrics-statefulset.yaml
deploy/helm/sumologic/templates/statefulset.yaml
deploy/helm/sumologic/values.yaml

Labeling statefulset pvcs (#1597)

---

deploy/helm/sumologic/values.yaml

Before https://github.com/falcosecurity/charts/issues/230 gets resolved let's add `application_rules.yaml` explicitly to our chart.
---

Add application_rules.yaml to falco.rulesFile

---

deploy/README.md

Updating the Kubernetes clusters versions which are supported
---

SUMO-165923 Updating the versions of kubernetes clusters

---

deploy/helm/sumologic/values.yaml

Values.yaml file updated to include metrics regex for Nginx Plus.
---

adding regex for Nginx Plus metrics.

---

deploy/helm/sumologic/Chart.yaml

Update falco subchart to 1.11.1
Changelog between 1.11.1 and 1.7.10 ( ref: https://github.com/falcosecurity/charts/blob/master/falco/CHANGELOG.md#v1111)
```
* Upgrade to Falco 0.28.1 (see the [Falco changelog](https://github.com/falcosecurity/falco/blob/0.28.1/CHANGELOG.md))
* Bump up version of chart for `Falcosidekick` dependency to `v3.5.0`
* Add `falcosidekick.fullfqdn` option to connect `falco` to `falcosidekick` with full FQDN
* Bump up version of chart for `Falcosidekick` dependency
* Upgrade to Falco 0.28.0 (see the [Falco changelog](https://github.com/falcosecurity/falco/blob/0.28.0/CHANGELOG.md))
* Update rulesets from Falco 0.28.0
* Bump up version of chart for `Falcosidekick` dependency
* Bump up version of chart for `Falcosidekick` dependency
```
---

Update falco subchart to 1.11.1

---

deploy/docs/Best_Practices.md

Add instruction how to exclude metrics in fluentd
---

docs: add instruction how to filter metrics in Fluentd

---

deploy/docs/Terraform.md
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/values.yaml
tests/terraform/static/all_fields.output.yaml
tests/terraform/static/collector_fields.output.yaml
tests/terraform/static/default.output.yaml
tests/terraform/static/disable_default_metrics.output.yaml
tests/terraform/static/strip_extrapolation.output.yaml

Remove duplicated collector source category from configuration

Remove duplicated collector source category from configuration

---

deploy/helm/sumologic/values.yaml

In https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/690 the prometheus additionalLabels were updated to use `sumologic.com/app` instead of `app`. The entry for `collection-fluent-bit` was missed, causing the helm chart to fail when using the built in prometheus stack due to duplicate labels.
This change should fix that so the built in prometheus stack works with collection-fluent-bit.
---

Fix additionalLabels in collection-fluent-bit

---

deploy/helm/sumologic/values.yaml

forward kube_hpa_status_condition metric
solves #1605 
---

feat: forward kube_hpa_status_condition metric

---

deploy/helm/sumologic/values.yaml

solves #1612
BREAKING CHANGE: This can be a breaking change in case someone added own remoteWrite
---

refactor(prometheus): unify application metrics urls

---

deploy/docs/existingPrometheusDoc.md

`--export` is now deprecated [ref#1](https://github.com/kubernetes/kubernetes/pull/73787) so don't use it.
---

docs: remove deprecated --export flag from 'kubectl get' call

---

deploy/helm/sumologic/values.yaml

fix fluent-bit's imageSecrets comment to align what's actually expected in fluent-bit's chart: https://github.com/fluent/helm-charts/blob/fluent-bit-0.12.1/charts/fluent-bit/values.yaml#L20
---

fix: fix fluent-bit's imageSecrets comment

---

.github/workflows/check_pr_labels.yaml

Prevent merging when `do-not-merge/hold` label is added.
This PR uses: https://github.com/marketplace/actions/verify-pull-request-labels
---

feat(ci): add github action PR label checker

---

.github/workflows/check_pr_labels.yaml

`pull-request-number: '${{ github.event.pull_request.number }}'` is required 😞 
---

fix(ci): fix ci label checker - provide required pr number

---

.github/workflows/check_pr_labels.yaml

Revert to using `verify-pr-label-action` action but forked and updated so that it doesn't require a "positive" valid label set.
ref: https://github.com/pmalek-sumo/verify-pr-label-action
---

refactor(ci): use forked label checker to allow empty valid label set

---

deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml
tests/tracing/static/collection-monitoring-false.output.yaml
tests/tracing/static/simple.output.yaml

Fix .Values.sumologic.sourceName for OTC in Helm chart

---

deploy/helm/sumologic/values.yaml

Changes since v1.12.2-sumo-0:
- feat: Build images for ARM
- chore(deps): bump fluent/fluentd from v1.12.2-debian-1.0 to v1.12.2-debian-1.1
- chore(deps): Upgrade `rexml` gem to 3.2.5 fix CVE-2021-28965
- chore(deps): Upgrade `rdoc` gem to 6.3.1 to fix CVE-2021-31799
- chore(deps): Upgrade `addressable` gem to 2.8.0 to fix a vulnerability reported by Sysdig
- chore(deps): Upgrade `ruby` in builder image from 2.6.6 to 2.6.8
- chore(deps): Upgrade all system packages in Docker image

fix(deps): Upgrade Fluentd from v1.12.2-sumo-0 to v1.12.2-sumo-2

---

vagrant/values.yaml

chore(vagrant): avoid sending receiver-mock logs and use containerd parser

---

deploy/helm/sumologic/values.yaml

Namespace duplicates namespace metadata
host duplicates node metadata
_sourceHost is not available in metrics created by Fluentd

fix(helm/metrics/otc): remove unnecessary metadata

---

deploy/helm/sumologic/Chart.yaml

To avoid seeing deprecation warnings:
```
W0903 17:09:48.543353 3969710 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0903 17:09:48.548234 3969710 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W0903 17:09:49.378986 3969710 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0903 17:09:49.380322 3969710 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, …
```

chore: bump telegraf operator subchart to 1.2.0

---

deploy/helm/sumologic/conf/traces/traces.otelagent.conf.yaml
deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml
deploy/helm/sumologic/templates/metrics/fluentd/statefulset.yaml
deploy/helm/sumologic/values.yaml
tests/tracing/static/collection-monitoring-false.output.yaml
tests/tracing/static/simple.output.yaml

feat(deploy/otc): ensure backward compatibility for tpl change

---

deploy/helm/sumologic/values.yaml

docs: add links to documentation for OTC receivers, processors and exporters in values.yaml 
---

docs: add links to documentation for OTC receivers, processors and exporters in values.yaml

---

deploy/helm/sumologic/values.yaml

Metrics coming from Fleuntd does not have `host` metadata.
Example metrics coming from Telegraf receiver:
```
Metric #0
Descriptor:
-> Name: node_namespace_pod:kube_pod_info:
-> Description: 
-> Unit: 
-> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2021-09-07 11:07:05.914 +0000 UTC
Value: 1.000000
ResourceMetrics #74
Resource labels:
-> host: STRING(collection-sumologic-otelcol-metrics-1)
-> namespace: STRING(kube-system)
-> node: STRING(sumologic-kubernetes-collection)
-> pod: STRING(hostpath-provisioner-75fdc8fccd-c8xzs)
-> prometheus: STRING(sumologic1/collection-kube-prometheus-prometheus)
-> prometheus_replica: STRING(prometheus-collection-kube-prometheus-prometheus-0)
``` 
---

fix: remove host metadata coming with metrics from Telegraf receiver

---

deploy/helm/sumologic/Chart.yaml

In order to avoid seeing deprecation warnings:
```
W0511 14:48:20.326099  73417 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0511 14:48:51.928880  73417 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
```
let's bump `kube-prometheus-stack` subchart to `12.10.0` which in turn bumps from `5.8.*` [link](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-12.3.0/charts/kube-prometheus-stack/Chart.yaml#L47) to `6.1.*` [link](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stac …

chore: bump kube-prometheus-stack to 12.10.0

---

vagrant/README.md

https://www.virtualbox.org/ is now down
---

fix: change link to VirtualBox

---

deploy/helm/sumologic/values.yaml

Fix configuration for otc metrics pipeline:
- remove configuration for adding host metadata
host metadata is not available for metrics coming from Fluentd
- remove configuration for namespace labels and pod annotations added as metadata
namespace labels and pod annotations cannot be added in Fluentd metrics pipeline
---

Fix configuration for otc metrics pipeline

---

deploy/helm/sumologic/values.yaml

- rename label service to prometheus_service, add delimiter set to '_' 
service label is visible in Sumo as prometheus_service in metrics coming from Fluentd
delimiter is used when for example pod is associated with more than one service,
delimiter is going be used to join them
metadata in Sumo:
tested with:
```
statefulset:
image:
repository: public.ecr.aws/sumologic/sumologic-otel-collector-dev
tag: d35b54257c68170e8ce1bb1f35048871e69d7238-amd64
```
---

fix(otc-metrics): rename label service to prometheus_service, add delimiter set to '_'

---

deploy/helm/sumologic/values.yaml

Added Remote/Write Configs for SQLserver metrics:
List of Metrics are on following page:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sqlserver
Metrics follow following format.
``` 
```
---

Adding remote write configs for SQLserver Metrics

---

deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/chart-configmap.yaml

Given I'm running with Fluentd as logs and/or metrics metadata provider,
When I switch to OtelCol as logs and/or metrics metadata provider in place (with `helm upgrade` as opposed to `helm uninstall` and `helm install`),
Fluent Bit and/or Prometheus is not able to pick up the new configuration and keeps trying to send data to Fluentd service, which doesn't exist anymore.
To properly fix that, we would need to introduce a breaking change
in Fluent Bit and/or Prometheus configuration. This should be done in v3.0.
For now, let's disguise OtelCol statefulset as Fluentd by naming its service with the name of the Fluentd service, so that Fluent Bit and Prometheus can keep using the Fluentd service name, even though there's really OtelCol under the hood.
Fixes #1741

fix: fix switching between fluentd and otelcol

---

.github/workflows/check_pr_labels.yaml

The gist of this is to avoid failures on PRs from forks like this: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1747/checks?check_run_id=3616995450

fix(ci): don't run PRs labels check on pull_request events to prevent failures on PR from forks

---

deploy/docs/Installation_with_Helm.md
deploy/docs/Non_Helm_Installation.md
deploy/docs/SideBySidePrometheus.md

whne option `kube-prometheus-stack.prometheusOperator.prometheusInstanceNamespaces` is set
Pod for Prometheus is not create and in logs there is following error:
`level=info ts=2021-09-16T08:41:08.622312669Z caller=listwatch.go:88 component=prometheusoperator msg="namespace not found" namespace=[sumologic]`
but sumologic namespace is available
Tested version:
```
$ helm ls -A
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
my-release      sumologic       2               2021-09-16 08:28:05.740943426 +0000 UTC deployed        sumologic-2.1.5 2.1.5 
```
For reference part of configuration for namespaces in scope for Prometheus Operator from kube-prometheus-stack:
```
##
prometheusOperator:
##
namespaces: {} …
```

docs: improve documentation for installation on OpenShift

---

deploy/helm/sumologic/values.yaml

add '_origin' metadata to metrics to keep the same format as for metrics from Fluentd
in Prometheus '_origin' metadata is not available
---

feat(otc-metrics): add '_origin' metadata to metrics to keep the same format as for metrics from Fluentd

---

vagrant/provision.sh

Given 1.18 is already unsupported bump the version to 1.21

chore: bump k8s version in vagrant to 1.21

---

deploy/helm/sumologic/values.yaml
vagrant/values.yaml

This requires new release of https://github.com/SumoLogic/sumologic-otel-collector/ which will include the already merged changes and additionally the following unmerged PRs:
* https://github.com/SumoLogic/sumologic-otel-collector/pull/236
* https://github.com/SumoLogic/sumologic-otel-collector/pull/239

otelcol: add systemd logs pipeline

---

deploy/helm/sumologic/values.yaml

Rely on source metadata set by source processor and don't construct it in the exporter.

fix(otelcol): use source metdata set by sourceprocessor

---

deploy/helm/sumologic/values.yaml

- unify exporting for systemd, collectd and containers logs
- add filtration for systemd like we already have in fluentd
- add kubelet pipeline

Add kubelet, systemd filtration and refactor containers exporter

---

deploy/helm/sumologic/values.yaml

namespace comes with metrics from telegraf receiver
waits for new version of otelcol with https://github.com/SumoLogic/sumologic-otel-collector/pull/228
---

fix(otc-metrics): remove namespace from extracted metadata

---

deploy/helm/sumologic/values.yaml

It seems that `filterprocessor` doesn't validate the `match_type` used in its config.
I've created an issue for that: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5382
In the meantime let's just correct it in our `values.yaml`

fix(otelcol): fix match_type in filterprocessor's config for logs pipeline

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
vagrant/values.yaml

In oder to keep the metadata enrichment behavior from fluentd which is to extract the second element from `fluent.tag` https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/d87aab8d99d63c3ff364c72b85aa9cd2cba4855f/deploy/helm/sumologic/conf/logs/fluentd/logs.source.systemd.conf#L78 let's do the same in otelcol's config and set that as source name for systemd logs.
Additionally document the change in Changelog;.

fix(otelcol): fix systemd logs' source name

---

deploy/helm/sumologic/values.yaml

Istio writes logs to Stdout. In Sumo Logic logs are coming as combined logs, like : 
`{"timestamp":1625774729582,"log":"[2021-07-08T20:05:23.034Z] \"GET /ab2g HTTP/1.1\" 400 - missing_host_header - \"-\" 0 0 0 - \"-\" \"-\" \"-\" \"-\" \"-\" - - 10.12.9.6:8080 10.128.0.49:50180 - -\n[2021-07-08T20:05:24.092Z] \"GET /ab2h HTTP/1.1\" 400 - missing_host_header - \"-\" 0 0 0 - \"-\" \"-\" \"-\" \"-\" \"-\" - - 10.12.9.6:8080 10.128.0.42:43773 - -","stream":"stdout","time":"2021-07-08T20:05:26.246470661Z"}`
Note: 
- First log line starts with **[2021-07-08T20:05:23.034Z**
- Second log line starts with **[2021-07-08T20:05:24.092Z**
However, Istio application is writing these logs at different lines; when we check log file at Istio Pod. Example of above logs splitted correctly by Istio: …

Fixing regex for Istio logs, splitting istio logs

---

deploy/helm/sumologic/values.yaml

Added Remote/Write Configs for Varnish metrics:
List of Metrics are on following page:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/varnish
Metrics follow following formart
``` bash 
```
---

update regex varnish remotewirte

---

deploy/helm/sumologic/values.yaml

Added Remote/Write Configs for Memcache metrics:
List of Metrics are on following page:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/memcache
Metrics follow following formart
``` bash 
```
---

Adding remote write for memcache

---

deploy/helm/sumologic/values.yaml

host attribute is being used by telegraf
and application dashboards

fix(helm/otelcol/metrics): revert host attribute

---

deploy/helm/sumologic/Chart.yaml

Notable changes since https://github.com/SumoLogic/sumologic-kubernetes-collection/releases/tag/v2.1.5
```
- Fixing regex for Istio logs, splitting istio logs (#1781)
- docs: improve documentation for installation on OpenShift
- chore: bump telegraf operator subchart to 1.2.0 (#1723)
- feat(helm): add sumologic.serviceAccount.annotations so custom annotation cen be added #1716
```

Prepare v2.1.6

---

deploy/helm/sumologic/values.yaml

- feat(otc-metrics): remove exclude section for source processor in metrics pipeline
it is not currently used for Fluentd
- feat(otc-metrics): rename container label to OTC convention
---

fix(otc-metrics): remove exclude section for source processor in metrics pipeline

---

deploy/helm/sumologic/values.yaml

This change unfortunately requires us to "hardcode" the `source_name` and `source_category` configuration options because the options that were used until now: `.Values.fluentd.logs.containers.sourceName` and `.Values.fluentd.logs.containers.sourceCategory` have keys specified in Sumo conventions.
Those cannot be used since at the stage in the pipeline where source processor resides we are still using OT naming convention.
Change in chart stems from change in OT distro's config (specifically in sourceprocessor): https://github.com/SumoLogic/sumologic-otel-collector/pull/254

chore(otelcol): bump ot distro version to 0.29.0-beta.0

---

deploy/helm/sumologic/values.yaml

In order to match what's being sent with fluentd let's drop the source metadata set by sourceprocessor which in some cases is not filled properly due to missing k8s metadata, e.g. (mark the `undefined` in `_sourceHost`)
```
coredns_cache_hits_total{
container="coredns"
endpoint="http-metrics"
prometheus="sumologic/collection-kube-prometheus-prometheus"
server="dns://:53"
cluster="microk8s"
instance="10.1.34.69:9153"
job="coredns"
namespace="kube-system"
pod="coredns-588fd544bf-xwxzc"
prometheus_replica="prometheus-collection-kube-prometheus-prometheus-0"
prometheus_service="collection-kube-prometheus-coredns"
type="denial"
_origin="kubernetes"
k8s.container.name="coredns"
pod_labels_k8s-app="kube-dns"
pod_labels_pod-template-hash="588fd544bf"
replicaset="coredns-588fd544bf" …
```

fix(otelcol): delete source metadata from resource attributes

---

deploy/helm/sumologic/values.yaml

To match what fluentd is sending let's attach `node` attribute by adding it to k8sprocessor config to include it in metadata enrichment.
For reference, this is an entry sent by fluentd:
```
coredns_cache_hits_total{
_origin="kubernetes"
cluster="kubernetes-pmalek-vagrant-otc-cluster-1",
container="coredns",
deployment="coredns",
endpoint="http-metrics",
instance="10.1.34.69:9153",
job="coredns",
namespace="kube-system",
node="sumologic-kubernetes-collection",
pod_labels_k8s-app="kube-dns",
pod_labels_pod-template-hash="588fd544bf",
pod="coredns-588fd544bf-xwxzc",
prometheus_replica="prometheus-collection-kube-prometheus-prometheus-0",
prometheus_service="collection-kube-prometheus-coredns",
prometheus="sumologic/collection-kube-prometheus-prometheus",
replicaset="coredns-588fd544bf", …
```

feat(otelcol): add node name as attribute to metrics

---

deploy/helm/sumologic/templates/logs/common/service.yaml
deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/metrics/common/service.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml
deploy/helm/sumologic/values.yaml

~~For now let's piggy back on the values (ports `24231`) used in the services: [for logs](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/e1f8406d818aa6036450279ced0b809e9807c525/deploy/helm/sumologic/templates/logs/common/service.yaml#L27-L30) and [for metrics](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/48492ff1779fc070eb9acda92b0fb8790ef073e6/deploy/helm/sumologic/templates/metrics/common/service.yaml#L21-L24)~~
This PRs adds `otelcol-metrics` port (`8888`) to scrape metrics from otelcol instances.
At the same time let's remove the default metrics prefix (`otelcol`) from exposed metrics.
Example of what metrics are exposed as of now:
```
exporter_queue_size{exporter="sumologic",service_instance_id="ecedcfd8-3c05-40e4-aca7-a383e9340201"} 0 …
```

feat(otelcol): add metrics port for otelcol and set empty prefix in otelcol's flags

---

Vagrantfile

Trying to bring up Vagrant with Virtualbox 6.1.28 with the current setup results in the following error:
As it turns out, Virtualbox 6.1.28 restricts the IP addresses permitted in host-only networks to 192.168.56.0/21. Strangely, there isn't any mention of this in the [changelog](https://www.virtualbox.org/wiki/Changelog). This restriction can be lifted via vbox config, but we don't care what our guest IP is, so changing that instead is simpler.
See: https://www.virtualbox.org/manual/ch06.html#network_hostonly for more information. The relevant passage is:
> On Linux, Mac OS X and Solaris Oracle VM VirtualBox will only allow IP addresses in 192.68.56.0/21 range to be assigned to host-only adapters. For IPv6 only link-local addresses are allowed. If other ranges are desired, they can be …

fix: change Vagrant IP address for vbox 6.1.28 compat

---

deploy/docs/Installation_with_Helm.md

Current docs are not clear that the default install will deploy Prometheus and can lead you to the other installation models incorrectly.

Add clarity on installation

---

CHANGELOG.md

Backport of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1884
---

[Backport of #1884] docs: update changelog, add link to 2.2.0 release

---

deploy/docs/Installation_with_Helm.md

prometheus-operator creates a kubelet Service when started, but the kube-prometheus-stack doesn't remove it on uninstall. This can cause problems with duplicated metric if multiple releases with different names are installed in the cluster. Pending a fix upstream, document the steps necessary to remove the Service when uninstalling the Helm release.
This partially addresses #1101 
---

docs(helm): add uninstall step for the kubelet Service

---

ci/shellcheck.sh
deploy/helm/sumologic/templates/_api_versions_helpers.tpl
deploy/helm/sumologic/templates/logs/common/pdb.yaml
deploy/helm/sumologic/templates/logs/fluentd/pdb.yaml
deploy/helm/sumologic/templates/metrics/common/pdb.yaml
deploy/helm/sumologic/templates/metrics/fluentd/pdb.yaml
tests/README.md
tests/functions.sh
tests/metadata_logs_otc/config.sh
tests/run.sh
tests/shared_config.sh
tests/upgrade_script/run.sh
tests/upgrade_v2_script/run.sh

The idea behind this change is to support newer version of `PodDisruptionBudget` (`policy/v1beta1/PodDisruptionBudget` vs `policy/v1/PodDisruptionBudget`)
and to get rid of deprecation warnings when installing our chart:
```
$ helm upgrade --install collection sumologic/sumologic
Release "collection" does not exist. Installing it now.
...
W1118 17:09:13.651675 2835438 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W1118 17:09:13.654276 2835438 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
...
W1118 17:09:14.026749 2835438 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; …
```

feat(helm): add PodDisruptionBudget api version helm chart helpers

---

ci/push-helm-chart.sh

Publish versions for git tags to the dev repository. This causes a bit of duplication, as the same commit can be published to the dev repository with two different versions, but it ensures that it's always possible to derive the dev version from just the repository state, irrespective of whether a tag is present or not.
Fixed some shellcheck warnings while at it as well.
This also helps fix an issue in our e2e tests. See [this](https://jira.kumoroku.com/jira/browse/SUMO-155789) internal issue.
---

ci: publish tag versions to the dev repository

---

deploy/docs/Installation_with_Helm.md
deploy/docs/Non_Helm_Installation.md

Improvements in OpenShift documentation, manual backport of #1761 & #1854
---

[Manual backport of #1761 & #1854] Improvements in Openshift documentation

---

CHANGELOG.md
deploy/helm/sumologic/templates/traces/otel-agent/daemonset.yaml
deploy/helm/sumologic/templates/traces/otelcol/deployment.yaml
deploy/helm/sumologic/values.yaml
tests/tracing/static/collection-monitoring-false.output.yaml
tests/tracing/static/simple.output.yaml

- Update OpenTelemetry Collector version to v0.38.1-sumo
- Move insecure parameter to separate configuration variable
- Fix OTLP/HTTP metadata tagging
- Update [Cascading Filter processor][v0.38.1-cfp] to a new version which adds new features such filtering
by number of errors and switches to a new, [easier to use config format][v0.38.1-cfp-help]
- Change the default number of traces for Cascading Filter to 200000
---
[v0.38.1-cfp]: https://github.com/SumoLogic/opentelemetry-collector-contrib/tree/v0.38.1-sumo/processor/cascadingfilterprocessor#cascading-filter-processor
[v0.38.1-cfp-help]: https://help.sumologic.com/Traces/Getting_Started_with_Transaction_Tracing/What_if_I_don't_want_to_send_all_the_tracing_data_to_Sumo_Logic%3F

Update OTC to v0.38.1-sumo

---

deploy/README.md

1.17 on EKS and 1.18 on GKE don't allow new clusters to be created; 1.19 on GKE shouldn't either according to GCP's schedule. As we can't test on these platforms, we can't officially support them.
See https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar and https://cloud.google.com/kubernetes-engine/docs/release-schedule#schedule_for_static_no-channel_versions.
---

chore: remove support for EOL K8s platform versions

---

CHANGELOG.md
deploy/README.md

E2E tests pass for GKE 1.21, so we should consider it officially supported.
---

chore: add support for GKE 1.21

---

vagrant/values.yaml

This has already been done in fluentd:
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/f4d95bc71b9974f32bab700bb79c1725f111ee6d/vagrant/values.yaml#L159-L166
but when using otelcol as logs provider it doesn't make an effect hence this PR.

chore: filter out receiver-mock's logs in fluent-bit's config

---

deploy/helm/sumologic/Chart.yaml

Changelog: https://github.com/falcosecurity/charts/blob/master/falco/CHANGELOG.md#v1162
This bumps the base falco image from `0.27.0` to `0.30.0` (already copied manually to https://gallery.ecr.aws/sumologic/falco)

chore(deps): bump falco subchart to 1.16.2

---

deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/events/fluentd/statefulset.yaml
deploy/helm/sumologic/templates/logs/fluentd/statefulset.yaml
deploy/helm/sumologic/templates/metrics/fluentd/statefulset.yaml
deploy/helm/sumologic/templates/traces/otel-agent/daemonset.yaml
deploy/helm/sumologic/templates/traces/otelcol/deployment.yaml
deploy/helm/sumologic/values.yaml
tests/helm/tracing/static/collection-monitoring-false.output.yaml
tests/helm/tracing/static/simple.output.yaml

Addition of the [Sumologic exporter](https://github.com/SumoLogic/opentelemetry-collector-contrib/tree/main/exporter/sumologicexporter) to the Tracing OT Collector pipeline. This will add possibility to send received metrics on the OTC receiver (OTLP protocol) side to Sumo. 
---

Sumologic exporter and metric pipelines into OT Collector & agent

---

CHANGELOG.md
ci/_build_functions.sh
deploy/docs/Kube-Prometheus.md
deploy/docs/Non_Helm_Installation.md
deploy/docs/additional_prometheus_configuration.md
deploy/docs/existingPrometheusDoc.md
deploy/docs/standAlonePrometheus.md
deploy/docs/v2_migration_doc.md
deploy/helm/sumologic/Chart.yaml
deploy/helm/sumologic/values.yaml
tests/helm/functions.sh
vagrant/k8s/logs-generator.yaml
vagrant/k8s/receiver-mock.yaml

Updating some dependencies necessary for ARM support:
* telegraf-operator from 1.2.0 to 1.3.3 (1.3.0 is when they added ARM support)
* kube-state-metrics from implicit 1.9.7 to 1.9.8
* kubernetes-setup to from 3.0.0 to 3.1.1
* kubernetes-tools from 2.2.3 to 2.6.0
I updated the tools version to 2.6.0 everywhere we explicitly mention it in the documentation. I think this is fine, but let me know if you see some kind of problem.
Ran E2E tests on this and they passed.
---

Dependency upgrades for ARM support

---

deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/events/fluentd/statefulset.yaml
deploy/helm/sumologic/templates/logs/fluentd/statefulset.yaml
deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/metrics/fluentd/statefulset.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/traces/otelcol/deployment.yaml
tests/helm/functions.sh
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml
tests/helm/run.sh
tests/helm/tracing/static/collection-monitoring-false.output.yaml
tests/helm/tracing/static/simple.output.yaml

Helm template render tests where broken in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1865 (by introduction of a subshell in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1865/files#diff-dd0c9cda3917fccebea6cea8d3fb46f46e4fbbeda2d6939864c9aaa9fc9c9571R29-R39)
Hence they were not reporting issues which they should report: e.g. https://github.com/SumoLogic/sumologic-kubernetes-collection/runs/4371102809?check_suite_focus=true#step:4:75
This PR fixes that by using a temporary file to report test success/failures https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1924/files#diff-a13b01bb0c50ed17f62903dbcbb0a1df693e4e0a921eefc8dd078fff56bc57f3R18 and by fixing already accumulated breakage in templates.

fix(helm): fix helm template render tests

---

deploy/README.md

docs: update support matrix - add OpenShift 4.8, manual backport of #1925

[Manual backport of #1925] docs: update support matrix - add OpenShift 4.8

---

tests/integration/Makefile
tests/integration/helm_helpers_test.go
tests/integration/helm_otc_metadata_installation_test.go
tests/integration/main_test.go
tests/integration/values/values_otc_metadata.yaml

Add OTC related integration metadata integration tests.
* use the following [`values.yaml`](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/add-sumo-ot-distro-metadata-integration-tests/tests/integration/values/values_otc_metadata.yaml)
* add some [assertions](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/add-sumo-ot-distro-metadata-integration-tests/tests/integration/helm_otc_metadata_installation_test.go)

tests: add otc metadata integration tests

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

This version has an important fix reducing the number of API server calls from the metrics metadata enrichment plugin by a significant amount. See: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/pull/369
---

chore: bump fluentd version to 1.12.2-sumo-10

---

tests/integration/helm_default_installation_test.go
tests/integration/helm_otc_metadata_installation_test.go
tests/integration/internal/k8s/pods.go
tests/integration/values/values_default.yaml
tests/integration/values/values_otc_metadata.yaml

Use utilities from terratest to check pod availability instead of rolling our own. Our tests would actually pass despite some containers getting OOM killed.
The reason our containers were getting OOM killed were rather strict resource limits set for them in values.yaml we use for tests. Remove those limits, they don't serve any real purpose right now.

Fix pod readiness checks in integration tests

---

deploy/docs/Non_Helm_Installation.md

The `-it` will not work when cat values.yaml file is piped before kubectl invocation.
But it works with `-i` which works in both cases (with and without the `cat values.yaml |`)
So just change all the occurences to `-i`.

docs: replace -it with -i for the kubectl runs

---

deploy/README.md

Backport 6b8a0eabd86dccbfb0c3a531c8499389ecbb8747 from #1964

[Backport release-v2.2] docs: fix the Fluent Bit version in the versions matrix

---

tests/integration/helm_default_installation_test.go
tests/integration/helm_otc_metadata_installation_test.go
tests/integration/internal/constants.go
tests/integration/internal/receivermock/receiver_mock.go
tests/integration/internal/stepfuncs/assess_funcs.go

Add tests for the presence of metrics we expect to send to the receiver. Uses receiver-mock's `/metrics-list` endpoint. 
Adding it to the existing Features for now, as I don't want to duplicate setup in a new Feature, and it's not yet clear how we want to deal with this structurally.

Add an integration test for presence of expected metrics

---

Makefile

Recent versions of helm (`3.7.2` for me) report the following deprecations:
```shell
$ make helm-lint
helm lint --strict \
--set sumologic.accessId=X \
--set sumologic.accessKey=X \
deploy/helm/sumologic/
==> Linting deploy/helm/sumologic/
[WARNING] templates/logs/fluentd/pdb.yaml: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
[WARNING] templates/metrics/fluentd/pdb.yaml: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
Error: 1 chart(s) linted, 1 chart(s) failed
make: *** [helm-lint] Error 1
$ echo $?
2
```
which doesn't seem to be easily solvable (e.g. by configuration) so disable the `--strict` check and rethink this later.
Example of a failed CI …

fix(makefile): work around helm lint strict check

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

Thanos upstream doesn't upload Docker images for arm64 to their registry yet. We're going to use our own image until that changes. The image is completely unmodified, using Thanos' own build process.
I ran integration tests on this change in an ARM EKS cluster and they passed. Considering how little Thanos does for us, I think it's safe to merge this.
---

chore: bump Thanos image to our build of v0.23.1

---

deploy/helm/sumologic/templates/traces/otel-agent/daemonset.yaml

---
Tested on:
```
sumologic:
accessId: "dummy"
accessKey: "dummy"
endpoint: http://receiver-mock.receiver-mock:3000/terraform/api/
clusterName: "cluster-1"
traces:
enabled: true
otelagent:
enabled: true
```

Fix Otel Agent Template

---

tests/integration/Makefile
tests/integration/README.md
tests/integration/go.mod
tests/integration/helm_default_installation_test.go
tests/integration/helm_otc_metadata_installation_test.go
tests/integration/internal/constants.go
tests/integration/internal/k8s/tunnel.go
tests/integration/internal/receivermock/labels.go
tests/integration/internal/receivermock/receiver_mock.go
tests/integration/internal/stepfuncs/assess_funcs.go
tests/integration/internal/stepfuncs/debug.go
tests/integration/internal/stepfuncs/kubectl.go
tests/integration/internal/strings/strings.go
tests/integration/main_test.go
tests/integration/yamls/receiver-mock.yaml

* add tests making asserts on actual metrics labels (using https://github.com/SumoLogic/sumologic-kubernetes-tools/releases/tag/v2.7.0)
* change `strings.NamespaceFromT(t)` to include a partial timestamp so that users can run tests one after another without needing to wait for namespace to terminate
* add README change about `TEST_ARGS` in integration tests
* extract metrics to a separate feature
* introduce `receivermock.NewClientWithK8sTunnel()`
* introduce `k8s.TunnelForReceiverMock()`

test(metrics): add metrics labels test

---

.markdown_link_check.json
ci/markdown_link_check.sh
deploy/docs/opentelemetry_collector.md

This link sometimes causes issue even though retries are (theoretically?) enabled.
Exemplar failed CI build: https://github.com/SumoLogic/sumologic-kubernetes-collection/runs/4555434282?check_suite_focus=true

docs: ignore flaky yq book link

---

CHANGELOG.md
deploy/helm/sumologic/templates/clusterrole.yaml

This was observed when running integration tests with OTC:
```
E1214 14:59:05.716479       1 reflector.go:138] k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v1.Job: failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:test-helm-default-ot-metadata-930:rel-1045518918-sumologic" cannot list resource "jobs" in API group "batch" at the
E1214 14:59:07.282898       1 reflector.go:138] k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v1.CronJob: failed to list *v1.CronJob: cronjobs.batch is forbidden: User "system:serviceaccount:test-helm-default-ot-metadata-930:rel-1045518918-sumologic" cannot list resource "cronjobs" in API grou
```
and reported internally by @sburton-sumo

fix(helm): add job and cronjob to clusterrole's permission set

---

CHANGELOG.md
deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

This PR adds port 8888 (aka `metrics`) to otelcol's pods (both metrics and logs) so that it can be used to gather otelcol's metrics
This should actually be done already but it seems we missed this somehow. Our docs already mention this:
```
`otelcol.metrics.enabled` | Enable or disable generation of the metrics from Collector.
```

fix(helm): add metrics port to otelcol pods

---

tests/integration/helm_traces_enabled_test.go
tests/integration/values/values_helm_traces_enabled.yaml

Related to recent problem fixed in: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1975
This PR adds a test with traces enabled to verify that traces work with the chart by actually installing it in a cluster.
Depends on https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1971

test(traces): add integration test for enabled traces

---

.github/workflows/dev_builds.yml

Don't run unit tests like it was run in https://github.com/SumoLogic/sumologic-kubernetes-collection/actions/runs/1592967035 i.e. the `TestValuesFileFromT` UT which shouldn't run.

fix(ci): only run integration test in dev builds

---

tests/integration/helm_default_installation_test.go
tests/integration/helm_otc_metadata_installation_test.go
tests/integration/internal/constants.go
tests/integration/internal/logsgenerator/logsgenerator.go
tests/integration/internal/receivermock/receiver_mock.go
tests/integration/internal/stepfuncs/assess_funcs.go
tests/integration/internal/stepfuncs/logs.go
tests/integration/yamls/receiver-mock.yaml

Test log collection and delivery by generating a set of logs using logs-generator and then making assertions about the receiver having received them using the receiver's log counting API.
No systemd logs because:
* they don't have any metadata to query over, need https://github.com/SumoLogic/sumologic-kubernetes-tools/pull/193 first
* By default, kind doesn't enable persistence for journald, and the logs live in `/run/logs/journal` instead of `/var/log/journal` - and we don't have the former mounted in fluent-bit containers

test(integration): add tests for log count and basic metadata

---

CHANGELOG.md
ci/_build_functions.sh
deploy/docs/Kube-Prometheus.md
deploy/docs/Non_Helm_Installation.md
deploy/docs/additional_prometheus_configuration.md
deploy/docs/existingPrometheusDoc.md
deploy/docs/standAlonePrometheus.md
deploy/docs/v2_migration_doc.md
tests/helm/functions.sh
tests/helm/sumologic.yaml
tests/integration/internal/constants.go
tests/integration/yamls/receiver-mock.yaml
vagrant/k8s/logs-generator.yaml
vagrant/k8s/receiver-mock.yaml

Update tools to fix an issue with external binaries being built for amd64 on arm. This affected helm, kubectl and yq.
---

chore: update kubernetes-tools to 2.9.0

---

CHANGELOG.md
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/logs/collector/otelcol/configmap.yaml
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/templates/logs/collector/otelcol/serviceaccount.yaml
deploy/helm/sumologic/templates/logs/common/service-headless.yaml
deploy/helm/sumologic/templates/logs/common/service.yaml
deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc/config.sh
tests/helm/logs_otc/static/basic.input.yaml
tests/helm/logs_otc/static/basic.output.yaml
tests/helm/logs_otc_daemonset/config.sh
tests/helm/logs_otc_daemonset/static/basic.input.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
vagrant/values.yaml

This is an alpha feature without a stable API. It only supports container logs from docker-shim. Fluent-bit needs to be manually disabled to avoid duplicate logs.
The namespacing in the internal configuration is currently a bit messy -  we have a top-level `sumologic.logs` key, which should probably be `sumologic.metadata.logs`, same with metrics. Same thing is true about the directory structure within the Helm chart. I'd like to change both of those in a separate PR after merging this one. Then this collector can live under `sumologic.logs.*` instead of `sumologic.logs.collector.*`.
The configuration for otelcol was originally prepared by @astencel-sumo, he gets credit for it actually doing the right thing.
---

feat: add experimental otelcol log collector

---

CHANGELOG.md

Cherry-picked by hand from `release-v2.3`

chore: add missing 2.3.2 changelog entry

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc/static/basic.output.yaml

Add a batch processor to the otelcol log collector's pipeline, in an attempt to make its semantics closer to Fluent-Bit's. `batch_size` is set to the same value as the metadata enricher.
`timeout` is set to the same value as fluent-bit's Flush.
---

feat: add batching to otelcol log collector

---

Makefile

It is manual backport of #1972.
Needed to merge https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2022 in which I want to correct documentation.

[manual backport of #1972] fix(makefile): work around helm lint strict check (#1972)

---

tests/integration/helm_default_installation_test.go
tests/integration/helm_otc_metadata_installation_test.go

Related to what's described in : https://github.com/SumoLogic/sumologic-otel-collector/pull/384

test(integration): increate wait time to 5 min so that pod ownership labels are present

---

CHANGELOG.md
deploy/README.md

With some recent image upgrades, we now officially support ARM, minus Falco. Internal E2E tests are passing for EKS on Graviton2 nodes, so we can claim this with a good amount of confidence. This should also resolve https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1565.
---

docs: claim official ARM support

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

`scheduler_binding_duration` is deprecated in Kubernetes 1.21 and the generic framework extension metrics are the replacements. See: https://github.com/kubernetes/kubernetes/pull/96447.
I've tested this in kind by patching the control plane components. I'll submit those changes separately alongside tests for other control plane metrics.
---

feat: export scheduler_framework_extension_point_duration metrics

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

1.14 is pretty old and contains quite a few vulnerabilities. I ran E2E tests on 1.21 and they passed without issue.
---

chore: update telegraf to 1.21

---

tests/integration/internal/constants.go
tests/integration/values/values_common.yaml
tests/integration/yamls/cluster.yaml

With some configuration changes to the kind cluster, it's possible to see control plane metrics in integration tests. I've based the tests on ServiceMonitor definitions in values.yaml, and it turns out there's a few metrics which have been deprecated since the original config was written. I've clearly marked them in test definitions and added TODOs to remove them.
---

test(integration): include control plane metrics in integration tests

---

.github/workflows/pull_requests.yml
tests/helm/functions.sh

It's easier to run the Helm tests locally if they use the latest major version of yq, as the versions are actually incompatible.

test(helm): don't use yq for template tests

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

Backport the Telegraf update to 2.4.
---

[Backport release-v2.4] chore: update Telegraf to 1.21.2

---

tests/integration/helm_default_installation_test.go
tests/integration/helm_otc_metadata_installation_test.go

It seems that sometimes we don't get 10 logs from kubelet ([failed CI](https://github.com/SumoLogic/sumologic-kubernetes-collection/runs/5034342403?check_suite_focus=true)) so decrease the number so that we don't get any more false failures.

test(integration): decrease expected kubelet logs count

---

CHANGELOG.md
deploy/README.md

docs(readme): add support for AKS 1.22 (backported from #2075)
---

[v2.4.x] docs(readme): add support for AKS 1.22

---

tests/integration/internal/constants.go

Tests for kube-scheduler metrics are flaky in some environments. Disabling them until the issue is resolved.
Tracking the issue in #2079

test(integration): disable kube-scheduler metrics

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc/static/basic.output.yaml
tests/integration/helm_otelcol_logs_test.go
tests/integration/internal/stepfuncs/assess_funcs.go
tests/integration/values/values_helm_otelcol_logs.yaml

Add CRI log format support to the OTC log collector. This gives us containerd support and enables integration tests for the collector on kind. Based on https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/kubernetes/otel-collector-config.yml courtesy of @sumo-drosiek 🙇 .
---

feat: add cri support to experimental otelcol log collector

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/metadata_logs_otc/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml
tests/integration/values/values_helm_otelcol_logs.yaml

This pipeline was enabled by default by mistake, as the default configuration doesn't need it, and the k8s_tagger within puts some additional load on the API server. I'm commenting it out as we can't use conditional logic directly in values.yaml.
---

fix: disable the metadata pipeline for OTC log collector by default

---

deploy/helm/sumologic/values.yaml
tests/integration/helm_otc_metadata_installation_test.go

Do not add host dimension to metrics. If this is not set, it is set to otelcol name what is misleading
---

feat(otelcol/metrics): do not add host to metrics

---

CHANGELOG.md
deploy/helm/sumologic/templates/metrics/remote-write-proxy/deployment.yaml
tests/helm/functions.sh
tests/helm/remote_write_proxy/static/basic.output.yaml

Fix an error in the Deployment for the remote write proxy, where the configmap hash target was incorrect. 
The reason template tests didn't catch this, is that Helm template errors weren't treated as a test failure. Fix this as well.
---

fix: invalid checksum source for remote write proxy deployment

---

deploy/docs/Best_Practices.md

Add instruction how to set custom api server address for fluentd and otc
---

docs(best_practices): add section to set custom k8s API server for otc and fluentd

---

CHANGELOG.md
deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml
deploy/helm/sumologic/values.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

This also changes the default settings to the following:
```yaml
livenessProbe:
periodSeconds: 10
timeoutSeconds: 3
failureThreshold: 3
readinessProbe:
periodSeconds: 10
timeoutSeconds: 3
failureThreshold: 3
```
---
Default until now for otc:
```yaml
livenessProbe:
failureThreshold: 3
httpGet:
path: /
port: 13133
scheme: HTTP
periodSeconds: 10
successThreshold: 1
timeoutSeconds: 1
```
For comparison fluentd probes are set like so:
```yaml
livenessProbe:
failureThreshold: 3
httpGet:
path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
port: 9880
scheme: HTTP
initialDelaySeconds: 300
periodSeconds: 30
successThreshold: 1
timeoutSeconds: 3
```

feat: add otelcol's liveness and readiness probes configuration

---

deploy/docs/Best_Practices.md
deploy/helm/sumologic/values.yaml

HPA looks at request CPU for scaling.
Fluentd reaches 1 core at max.
Example:
When CPU request is set to eg. `3` (or `3000m`) with HPA's `targetCPUUtilizationPercentage: 50` means that HPA aims to get every Fluentd to 1.5 core utilization which won't happen.
Hence it will not scale it out.
CPU request for Fluentd should be always `1000m` at max.

chore: add warning for increased cpu limit for Fluentds

---

deploy/helm/sumologic/values.yaml

Comments text should start with double `#` and be adjusted with the key they comment.

docs: fix remoteWriteProxy comment hashing and indentation

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

All the metadata StatefulSets have requests.cpu set to 500m. Combined with a targetCPUUtilizationPercentage of 50 on the HPA, this meant that they'd try to keep an absolute CPU utilization of 250m = 500m * 0.5.
Changed the CPU utilization on the HPA to 100, so now the absolute utilization is 500m = 500m * 1.0.
---

fix: make metadata StatefulSets scale above 0.5 average CPU usage

---

deploy/docs/Security_Best_Practices.md

Add some example Network Policies illustrating how to limit collection components to only necessary networking capabilities.

docs: add NetworkPolicy examples to security best practices

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

Backport https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/331d6469e5c299bb5b8a943fd01e9cdffa699cc1 from https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2114

[Backport release-v2.5] fix: make metadata StatefulSets scale above 0.5 average CPU usage

---

deploy/docs/Installing_Behind_Proxy.md
deploy/docs/Security_Best_Practices.md
deploy/docs/Working_with_container_registries.md

Document how to integrate the Helm Chart with a TLS intercepting proxy and a custom CA certificate.
Also add a brief note about upgrading while rehosting container images.

docs: using a custom CA certificate

---

deploy/helm/sumologic/values.yaml

enable persistence for all metric exporters
---

feat(otelcol/metrics): enable persistence for all metric exporters

---

deploy/helm/sumologic/values.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml
tests/integration/helm_default_installation_test.go
tests/integration/helm_otc_metadata_installation_test.go
tests/integration/helm_otelcol_logs_test.go
tests/integration/internal/logsgenerator/logsgenerator.go
tests/integration/internal/stepfuncs/logs.go

Fixes: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/2118
Related release: https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.0.50-beta.0

chore: bump sumo ot distro to 0.0.50-beta.0

---

CHANGELOG.md
deploy/docs/Best_Practices.md

docs: add fluentd buffers vs DPM calculations info for metrics

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

it is Fluent Bit 1.6.10 with updated dependencies,
image repository: https://github.com/SumoLogic/fluent-bit-docker-image

chore: change Fluent Bit image to public.ecr.aws/sumologic/fluent-bit:1.6.10-sumo-1

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

Adjust metric otelcol config based on internal tests
---

feat(otelcol/metrics): adjust metric otelcol configuration

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

Drop container label for non-container kube state metrics. It requires to extract `kube_pod_status_phase` which shouldn't have container label but should have `pod`/`service` labels.
Fixes #2097
---

feat(metrics): drop container label for non-container kube state metrics

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

We [do not allow any capability in openshift](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/d4d8ab61ed31608732e01d7877bce88d38ab5939/deploy/helm/sumologic/templates/scc.yaml#L21) and there is no need for any in another clusters
---

feat(fluent-bit): drop all capabilities for container

---

vagrant/values.yaml

- fix otelcol configuration for pipelines
- remove k8s_uid attribute
- do not scrape receiver-mock logs by otellogs

fix(vagrant): fix vagrant configuration for otc

---

CHANGELOG.md
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/values.yaml

Support tolerations, nodeSelector and affinity for otellogs daemonset
---

feat(otellogs): support tolerations, nodeSelector and affinity for daemonset

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc/static/basic.output.yaml

add multipart merge configuration for docker and cri for otellogs
---

feat(otellogs): add multipart merge configuration for docker and cri

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc/static/basic.output.yaml

increase it to prevent data loss
during reading huge file from beginning I observed some data loss
because previous value was relatively low

chore(otellogs): increase send_batch_size to 10240

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

The current liveness probe doesn't actually check liveness in any meaningful way - it merely checks if the health_check extension is functional. We really don't want it to cause restarts under load, which it can with the current settings. Increase the timeout and period to mitigate this. We can revisit once the liveness check is more meaningful.
---

fix: increase OTC liveness timeout and period

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

related release: https://github.com/prometheus/node_exporter/releases/tag/v1.3.1
old release: https://github.com/prometheus/node_exporter/releases/tag/v1.0.1

chore(deps): bump prometheus node exporter tag to 1.3.1

---

CHANGELOG.md
deploy/docs/Best_Practices.md
deploy/docs/fluentd_otc_comparison.md
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml
tests/helm/tracing-gateway-loadbalancing/static/otelgateway-true.output.yaml

upgrade OTC to 0.0.58-beta.0
change memory limit for otc to be 75% of available memory with 20% spike
---

chore(otelcol): upgrade to 0.0.58-beta.0

---

deploy/helm/sumologic/values.yaml
tests/integration/helm_otc_metadata_installation_test.go

drop unwanted routing metric attribute
---

feat(metrics/otelcol): drop unwanted routing metric attribute

---

.github/workflows/changelog.yaml

Check similar to https://github.com/SumoLogic/sumologic-otel-collector/pull/541, with the label changed to `skip-changelog` for consistency with the rest of our labels.

ci: add a PR check for changelog changes

---

.github/workflows/backport_bot.yaml

Running it on arbitrary PRs with the pull_request_target trigger is a security risk.

fix(ci): only run the backporter on merged PRs

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

Having the `kube-prometheus-stack` subchart generate the ServiceMonitor to scrape Prometheus' own metrics does not work correctly in a setup with an external Prometheus operator in a different (higher) version.
By "does not work correctly" I mean that the ServiceMonitor points to a Service that does not see any pods and in effect, Prometheus cannot scrape its own metrics.
This is because different versions of Prometheus operator create different labels on Prometheus pods.
To fix this, let's disable the `kube-prometheus-stack` subchart's built-in ServiceMonitor and create our own, just like we do for other collection resources (Fluent Bit, Fluentd, Otelcol).

fix: use custom ServiceMonitor for Prometheus' own metrics

---

CHANGELOG.md
deploy/helm/sumologic/conf/setup/setup.sh
tests/helm/terraform/static/all_fields.output.yaml
tests/helm/terraform/static/collector_fields.output.yaml
tests/helm/terraform/static/conditional_sources.output.yaml
tests/helm/terraform/static/custom.output.yaml
tests/helm/terraform/static/default.output.yaml
tests/helm/terraform/static/disable_default_metrics.output.yaml
tests/helm/terraform/static/strip_extrapolation.output.yaml
tests/helm/terraform/static/traces.output.yaml

It's allowed to left `sumologic.endpoint` empty. In such case `SUMOLOGIC_BASE_URL` is empty and breaks logic of `get_remaining_fields` and other API calls.

fix: Handle empty or invalid Sumo base URL

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

it is Fluent Bit 1.6.10 with updated dependencies,
image repository: https://github.com/SumoLogic/fluent-bit-docker-image

chore: change Fluent Bit image to public.ecr.aws/sumologic/fluent-bit:1.6.10-sumo-2

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

it is Fluent Bit 1.6.10 with updated dependencies,
image repository: https://github.com/SumoLogic/fluent-bit-docker-image

[Backport of #2254] chore: change Fluent Bit image to public.ecr.aws/sumologic/fluent-bit:1.6.10-sumo-2

---

CHANGELOG.md
deploy/docs/Best_Practices.md
deploy/docs/fluentd_otc_comparison.md
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml
tests/helm/tracing/static/collection-monitoring-false.output.yaml
tests/helm/tracing/static/simple.output.yaml
vagrant/values.yaml

- Upgrade otc version to [v0.49.0-sumo-0](https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.49.0-sumo-0)
- Remove usage of `metadata_attributes`
- Stop moving out record attributes for systemd
- Move `_collector` to resource attributes for containers
- remove `k8s.pod.uid` for vagrant
- update docs for using containerd and fluent-bit 
- remove `http_listener_v2_path` in routing processor instead of exporter for metadata/metrics
---

feat(metadata/otc): upgrade to v0.50.0-sumo-0

---

CHANGELOG.md
deploy/docs/Best_Practices.md
deploy/helm/sumologic/values.yaml

Thanos now has official ARM Docker images, so we can go back to using the upstream repository.
---

chore: update Thanos to v0.25.2

---

CHANGELOG.md
deploy/helm/sumologic/conf/setup/monitors.sh
deploy/helm/sumologic/values.yaml
tests/helm/terraform/static/all_fields.output.yaml
tests/helm/terraform/static/collector_fields.output.yaml
tests/helm/terraform/static/conditional_sources.output.yaml
tests/helm/terraform/static/custom.output.yaml
tests/helm/terraform/static/default.output.yaml
tests/helm/terraform/static/disable_default_metrics.output.yaml
tests/helm/terraform/static/disabled_monitors.output.yaml
tests/helm/terraform/static/monitors_with_email_notifications.output.yaml
tests/helm/terraform/static/monitors_with_single_email.input.yaml
tests/helm/terraform/static/monitors_with_single_email.output.yaml
tests/helm/terraform/static/strip_extrapolation.output.yaml
tests/helm/terraform/static/traces.output.yaml

Changes:
* the monitors will be installed inside "Sumo Logic Integrations > Kubernetes" folder
* `sumologic.setup.monitors.notificationEmails` is able to handle a single email passed as a string
* fix: removed spaces from variables in email templates

Monitors in integrations folder

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

The new version reloads ServiceAccount tokens periodically, correctly handling token expiration enabled in K8s 1.21.
This fixes #2280 
---

chore(deps): upgrade fluentd to 1.14.6-sumo-3

---

README.md

Support officially ended on 17.05. This simply changes the README to reflect that.

docs: end support for v2.1

---

CHANGELOG.md
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml

The resources were already defined in `values.yaml`
in the `otellogs.daemonset.resources` property,
but this property was not being used in the daemonset template.

fix(otellogs): set resources on Otelcol logs collector daemonset

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

[Backport release-v2.8] chore(deps): upgrade fluentd to 1.14.6-sumo-3

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

[Backport release-v2.2] chore(deps): upgrade fluentd to 1.14.6-sumo-3

---

CHANGELOG.md
deploy/README.md

Amazon EKS end of support: March 31, 2022
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

chore: remove support for EKS with Kuberentes 1.18

---

CHANGELOG.md
deploy/README.md

Support for Kubernetes version 1.18 will be removed in Kops 1.24 (currently alpha release is available)
https://kops.sigs.k8s.io/releases/1.24-notes/#other-breaking-changes

chore: remove support for Kops with Kubernetes 1.18

---

CHANGELOG.md
deploy/README.md

https://cloud.google.com/kubernetes-engine/docs/release-schedule

chore: add support for GKE with Kuberentes 1.22

---

CHANGELOG.md
deploy/docs/Working_with_container_registries.md
deploy/helm/sumologic/templates/metrics/remote-write-proxy/deployment.yaml
tests/helm/remote_write_proxy/static/full_config.input.yaml
tests/helm/remote_write_proxy/static/full_config.output.yaml

Until now, it was not possible to specify imagePullSecrets
for the nginx image used by remote-write-proxy.
This change makes the remote-write-proxy use the pull secrets
specified in `sumologic.pullSecrets`, the same pull secrets that are used
by other components of the chart (Fluentd, OTC).

feat(metrics): add imagePullSecrets to remote-write-proxy

---

CHANGELOG.md
deploy/helm/sumologic/conf/events/events.conf
tests/helm/events/static/customSourceCategory.input.yaml
tests/helm/events/static/customSourceCategory.output.yaml

A bug was introduced in v2.8.0 (#2222)
that made the `fluentd.events.sourceCategory` non-functional.

fix(events): fix setting source category

---

CHANGELOG.md
deploy/README.md

https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar

chore: remove support for AKS with Kubernetes 1.19 & 1.20

---

CHANGELOG.md

This change did not make it into this release.

docs(changelog): remove the v2.9.0 release note about OT fork to OT distro change

---

deploy/helm/sumologic/values.yaml

The docs on the `kube-prometheus-stack.enabled` and `fluent-bit.enabled` flags contained confusing comments on "breaking other functionality".
I have clarified these docs in response to a customer question.

docs: clarify subchart enabled flags

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/metadata_logs_otc/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml
vagrant/values.yaml

`sourceName` and `sourceHost` have been set differently than for fluentd flow. This PR unifies it
---

fix(logs/metadata): fix logs metadata for systemd

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

`kube-state-metrics` v1.9.8 collects metrics about `Ingress` and `CertificateSigningRequest` resources using outdated API versions:
- `extensions/v1beta1` for `Ingress`
- `certificates.k8s.io/v1beta1` for `CertificateSigningRequest`
These API versions have been [removed in Kubernetes v1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22). We don't use those metrics anyway, so let's just tell kube-state-metrics to not collect metrics about these resources.

fix(metrics): remove outdated API calls

---

CHANGELOG.md
deploy/docs/scraped_metrics.md
deploy/helm/sumologic/values.yaml
examples/kube_prometheus_stack/values-prometheus.yaml

This adds the following metrics from [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/v1.9.8/docs/service-metrics.md):
- kube_service_info
- kube_service_spec_external_ip
- kube_service_spec_type
- kube_service_status_load_balancer_ingress
This should help answer questions like:
- what is the type of a given service?
- what is the cluster IP of a given service?
- what is the external IP of a given service?

feat(metrics): add service metrics

---

CHANGELOG.md
deploy/helm/sumologic/templates/_helpers.tpl
tests/helm/opentelemetry_operator_instrumentation_cr/static/instrumentation.output.yaml
tests/integration/helm_opentelemetry_operator_enabled_test.go

Set shorter names to OT Operator resources.
Reson:
```
one or more objects failed to apply, reason: Instrumentation.opentelemetry.io "stag-collection-sumologic-opentelemetry-operator-instrumentation" is invalid: metadata.labels: Invalid value: "stag-collection-sumologic-opentelemetry-operator-instrumentation": must be no more than 63 characters
```
---

Shorter OT Operator label value

---

deploy/docs/Troubleshoot_Collection.md

Update instruction: `### Send data to Fluentd stdout instead of to Sumo`
---

docs(troubleshoot_collection): update fluentd stdout config

---

vagrant/Makefile
vagrant/k8s/prometheus-adapter.yaml

add prometheus-adapter to vagrant's makefile
See https://github.com/kubernetes-sigs/prometheus-adapter for more informations
I am adding it here, because it take me some time to set it up, and It can be useful in the future. We can close it if you don't like it
---

chore(vagrant): add prometheus-adapter to vagrant's makefile

---

deploy/docs/SideBySidePrometheus.md
deploy/docs/existingPrometheusDoc.md

docs: add information about installation on OpenShift 4.9
docs: fix command to install on OpenShift with existing Prometheus - for normal k8s cluster kube-prometheus-stack is disabled

docs: add information about installation on OpenShift 4.9

---

CHANGELOG.md
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc/static/basic.output.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/logs_otc_daemonset/static/complex.output.yaml
tests/helm/metadata_logs_otc/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml
tests/integration/helm_otelcol_logs_test.go
tests/integration/values/values_helm_otelcol_logs.yaml
vagrant/values.yaml

Add support for journald receiver. This behaves like fluent-bit with one small exception. Units for filtering are taken from different place.
```
```
---

feat(otellogs/systemd): add support for systemd logs to otellogs

---

CHANGELOG.md
deploy/helm/sumologic/templates/traces/otel-agent/daemonset.yaml
deploy/helm/sumologic/templates/traces/otel-gateway/deployment.yaml
deploy/helm/sumologic/templates/traces/otelcol/deployment.yaml
deploy/helm/sumologic/values.yaml
tests/helm/tracing-agent-loadbalancing/static/otelagent-gateway-disabled.output.yaml
tests/helm/tracing-agent-loadbalancing/static/otelagent-gateway-enabled.output.yaml
tests/helm/tracing-gateway-loadbalancing/static/otelgateway-true.output.yaml
tests/helm/tracing-otelcol/static/collection-monitoring-false.output.yaml
tests/helm/tracing-otelcol/static/simple.output.yaml

PR adds `pprof` extension to the `otelagent`, `otelgateway` and `otelcol` collectors.
---

feat(tracing): add pprof extension to the collectors

---

CHANGELOG.md
deploy/helm/sumologic/templates/scc.yaml

without this change Prometheus Pod was not created on OpenShift 4.10
in side by side deployment of k8s collection
I observed following error:
```
Warning  FailedCreate  5m44s (x6 over 5m44s)       statefulset-controller  create Pod prometheus-collection-kube-prometheus-prometheus-0 in StatefulSet prometheus-collection-kube-prometheus-prometheus failed error: pods "prometheus-collection-kube-prometheus-prometheus-0" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{2000}: 2000 is not an allowed group, spec.initContainers[0].securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000420000, 1000429999], …
```

feat(openshift): add projected volumes to SecurityContextConstraints

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

update fluentd to [1.14.6-sumo-4](https://github.com/SumoLogic/sumologic-kubernetes-fluentd/releases/tag/v1.14.6-sumo-4)
---

feat: update fluentd to 1.14.6-sumo-5

---

deploy/docs/fluentd_otc_comparison.md

Newest version of markdownlint complaints about unescaped square brackets.

fix(docs): make the new version of markdownlint happy

---

deploy/docs/opentelemetry_collector.md

OT is in beta in the sense that the configuration will change in v3, but it is production-ready with the configuration we provide by default. Clarified this in the documentation.

docs: clarify production-readiness of OT

---

.github/workflows/pull_requests.yml

This used to be the latest version, and v1.48 started throwing some mysterious gofmt-related errors.

ci(integration-tests): set golangci-lint version to 1.47

---

CHANGELOG.md
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/setup/job.yaml
deploy/helm/sumologic/templates/setup/secret.yaml

Adds some additional security. The setup Job is run as a Helm pre-install hook, so it gets deleted after it finishes. While it was running, it was possible to read the credentials from the Pod definition. With this change, they're stored in a Secret instead.
---

feat: store Sumo credentials for the setup Job in a Secret

---

CHANGELOG.md
deploy/helm/sumologic/conf/setup/main.tf
tests/helm/terraform/static/all_fields.output.yaml
tests/helm/terraform/static/collector_fields.output.yaml
tests/helm/terraform/static/conditional_sources.output.yaml
tests/helm/terraform/static/custom.output.yaml
tests/helm/terraform/static/default.output.yaml
tests/helm/terraform/static/disable_default_metrics.output.yaml
tests/helm/terraform/static/disabled_dashboards.output.yaml
tests/helm/terraform/static/disabled_monitors.output.yaml
tests/helm/terraform/static/monitors_with_email_notifications.output.yaml
tests/helm/terraform/static/monitors_with_single_email.output.yaml
tests/helm/terraform/static/strip_extrapolation.output.yaml
tests/helm/terraform/static/traces.output.yaml

chore: upgrade sumologic terraform provider to 2.16
Upgrade due to security isues
---

chore: upgrade sumologic terraform provider to 2.18

---

deploy/docs/SideBySidePrometheus.md
deploy/docs/existingPrometheusDoc.md
deploy/docs/standAlonePrometheus.md

A change of a dead link. A section of the documentation has been moved into another place and therefore the link has died.
Formerly: https://web.archive.org/web/20220121113033/https://help.sumologic.com/Observability_Solution/Kubernetes_Solution/Navigate_your_Kubernetes_environment
Currently: https://help.sumologic.com/Observability_Solution/Kubernetes_Solution/02Monitoring_Using_Kubernetes#open%C2%A0explore

docs: fix "open explore" dead link

---

CHANGELOG.md
deploy/helm/sumologic/conf/events/otelcol/config.yaml
deploy/helm/sumologic/values.yaml
tests/helm/events_otc/static/basic.output.yaml
tests/helm/events_otc/static/options.output.yaml
tests/helm/events_otc/static/override.output.yaml
tests/helm/events_otc_statefulset/static/annotations_labels.output.yaml
tests/helm/events_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml
tests/integration/values/values_helm_default_ot_fips_metadata.yaml

upgrade otelcol for metadata and events to 0.56.0-sumo-0

chore: upgrade otelcol for metadata and events to 0.56.0-sumo-0

---

tests/integration/internal/ctxopts/context_opts.go
tests/integration/internal/stepfuncs/debug.go
tests/integration/internal/stepfuncs/helm.go
tests/integration/internal/stepfuncs/options.go
tests/integration/main_test.go

Add explicit teardown steps for resources created by integration tests.E2E framework's AfterEachTest actions are not actually called if the test errors out or panics, so we add explicit Finish actions for all of our resources.

test(integration): improve teardown

---

CHANGELOG.md
deploy/docs/opentelemetry_collector.md
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/logs/collector/otelcol/configmap.yaml
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/templates/logs/collector/otelcol/service.yaml
deploy/helm/sumologic/templates/logs/collector/otelcol/serviceaccount.yaml
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc/static/basic.input.yaml
tests/helm/logs_otc/static/options.input.yaml
tests/helm/logs_otc/static/options.output.yaml
tests/helm/logs_otc/static/override.input.yaml
tests/helm/logs_otc/static/override.output.yaml
tests/helm/logs_otc_daemonset/static/basic.input.yaml
tests/helm/logs_otc_daemonset/static/complex.input.yaml
tests/integration/values/values_helm_otelcol_logs.yaml

Change how log collection using OT is configured. The idea here is for the purely functional configuration to live under the `sumologic.logs` key and contain no application-specific configuration, and for the K8s specific and application specific (like raw OT configuration) configuration to be separate - currently I've left it under `otellogs`, but I'm open to alternatives.
TODO:
---

feat: refactor OT log collector configuration

---

deploy/README.md

This needs a test confirmation, but we should be able to claim support for:

docs: update support matrix

---

CHANGELOG.md
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/metrics/remote-write-proxy/configmap.yaml
deploy/helm/sumologic/templates/metrics/remote-write-proxy/deployment.yaml
deploy/helm/sumologic/templates/metrics/remote-write-proxy/service.yaml
deploy/helm/sumologic/values.yaml
tests/helm/remote_write_proxy/static/basic.output.yaml
tests/integration/values/values_common.yaml

Remote write proxy helps metrics metadata enrichment efficiency by a lot, especially for larger clusters. It comes at a slight additional operational cost of the nginx Deployment, and a minimal resource cost. We've been running it in production for the past 6 months and never had any issue, so I believe we should enable it by default.
This isn't a breaking change, but it enables a new component, so I'm tagging it for v3.
---

feat: enable remote write proxy by default

---

CHANGELOG.md
deploy/helm/sumologic/conf/metrics/remote-write-proxy/remote-write-proxy.conf
deploy/helm/sumologic/templates/metrics/remote-write-proxy/deployment.yaml
deploy/helm/sumologic/templates/metrics/remote-write-proxy/service.yaml
deploy/helm/sumologic/values.yaml
tests/helm/remote_write_proxy/static/basic.output.yaml
tests/helm/remote_write_proxy/static/full_config.input.yaml

ref: 
- https://github.com/nginxinc/docker-nginx-unprivileged
- https://hub.docker.com/r/nginxinc/nginx-unprivileged
NGINX Unprivileged Docker Image is owned and maintained by NGINX on both GitHub and Docker Hub, see https://github.com/nginxinc/docker-nginx-unprivileged/issues/19#issuecomment-479536708 
Some details about Nginx on OpenShift can be found here: https://torstenwalter.de/openshift/nginx/2017/08/04/nginx-on-openshift.html
With `public.ecr.aws/nginx/nginx:1.21-alpine` image following issue occurs on OpenShift 4.10:
```
% kubectl logs -n sumologic collection-sumologic-remote-write-proxy-5bb47649df-wv2dv  -p
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/ …
```

fix(openshift): fix remote write proxy - use unprivileged NGINX

---

CHANGELOG.md
tests/integration/helm_otelcol_traces_test.go
tests/integration/internal/constants.go
tests/integration/internal/receivermock/receiver_mock.go
tests/integration/internal/stepfuncs/assess_funcs.go
tests/integration/internal/stepfuncs/traces.go
tests/integration/internal/tracesgenerator/tracesgenerator.go
tests/integration/values/values_helm_otelcol_traces.yaml
tests/integration/yamls/receiver-mock.yaml

This PR adds integration tests for otlp tracing.
The traces are generated using [customer-trace-tester](https://github.com/SumoLogic/sumologic-kubernetes-tools#customer-trace-tester) and then tested in a similar way to how logs are tested.

feat(tests/integration): add integration tests for otlp traces

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/remote_write_proxy/static/basic.output.yaml

Upgrade nginx to the most recent stable version. 1.21 has some vulnerabilities in the alpine image.
---

chore: upgrade nginx to 1.23

---

tests/integration/yamls/cluster.yaml

Etcd apparently does a lot of I/O on its storage, and this can be an issue in environments with slow disks, like CI runners. Put the storage in-memory instead.
This didn't really improve performance in testing, but I've recently seen some CI jobs fail due to etcd timing out, and I have hope that this will help.
See also: https://github.com/kubernetes-sigs/kind/issues/845

test(integration): run etcd in memory for kind

---

CHANGELOG.md
deploy/docs/additional_prometheus_configuration.md

Update documentation around additionalRemoteWrite for kube-prometheus-stack

docs: update documentation for additionalRemoteWrite

---

deploy/docs/Terraform.md

The existing links went to a `Page Not Found`, but didn't return a 404, which is why the link checker missed it.

docs: fix Terraform provider links

---

.github/workflows/pull_requests.yml

We want to make integration tests a required check, but this is annoying to do given their number. Add a job that only reports their aggregate success for this purpose.

ci: add PR job for reporting integration test status

---

CHANGELOG.md
deploy/helm/sumologic/templates/setup/secret.yaml

A recent change moved setup credentials to a temporary Secret, but failed to make this Secret conditional on setup being enabled. As a result, it's necessary to provide credentials even if setup is disabled, which is incorrect.
This PR doesn't include a test because our Helm template test framework doesn't allow not setting credentials in tests. I'll look into adding a test using Terratest instead in a separate PR.
---

fix(setup): allow credentials to not be set if setup is disabled

---

CHANGELOG.md

Changelog now has got entries related to releases older than `v2.1.5`.
Note: it's not possible to get the actual release notes through Github API, but it's possible to generate them and this is what has been done.
Version `v2.1.2-rc0` has been skipped.
Fixes #1771

feat(changelog): add historical releases

---

CHANGELOG.md
deploy/README.md

ref: https://cloud.google.com/kubernetes-engine/docs/release-notes-nochannel#October_05_2022
---

chore: remove support for GKE 1.20

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

It doesn't seem to be needed for anything.
Fixes #2404 
Migration: https://github.com/SumoLogic/sumologic-kubernetes-tools/pull/333

feat(metrics)!: disable thanos by default

---

CHANGELOG.md
deploy/README.md

chore: remove support for kOps 1.20

---

CHANGELOG.md
deploy/helm/sumologic/conf/cleanup/cleanup.sh

Fix cleanup job
```
2022-10-31T13:42:38.999556351Z stderr F ╷
2022-10-31T13:42:38.999587967Z stderr F │ Error: Failed to load "." as a plan file
2022-10-31T13:42:38.999599464Z stderr F │ 
2022-10-31T13:42:38.999604853Z stderr F │ The specified path is a directory, not a plan file. You can use the global
2022-10-31T13:42:38.999611347Z stderr F │ -chdir flag to use this directory as the configuration root.
2022-10-31T13:42:38.999616627Z stderr F ╵
```
---

fix(cleanup): fix cleanup job

---

deploy/docs/Troubleshoot_Collection.md
deploy/docs/additional_prometheus_configuration.md

docs: add information about creation of additional Prometheus instance
docs: add section about OOM failures for Prometheus Pod to troubleshooting collection doc
manual backport of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2609

docs: add information about creation of additional Prometheus instance

---

docs/v3-migration-doc.md

docs: fix migration commands to update CRDs
without --force-conflicts flag following issue was observed:
```
error: Apply failed with 2 conflicts: conflicts with "helm" using apiextensions.k8s.io/v1:
- .metadata.annotations.controller-gen.kubebuilder.io/version
- .spec.versions
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
manifest to remove references to the fields that should keep their
current managers.
* You may co-own fields by updating your manifest to match the existing
value; in this case, you'll become the manager if the other …
```

docs: fix migration commands to update CRDs

---

CHANGELOG.md
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/chart-configmap.yaml
deploy/helm/sumologic/values.yaml
docs/v3-migration-doc.md
tests/helm/events_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml
tests/helm/tracing-otelcol/static/collection-monitoring-false.output.yaml
tests/helm/tracing-otelcol/static/simple.output.yaml
tests/integration/helm_traces_enabled_test.go
tests/integration/values/values_helm_fluentd_metadata.yaml
tests/integration/values/values_helm_traces_enabled.yaml

- Service name change and switching the metrics default to otelcol
---

feat(metrics): service name change and switching the metrics default to otelcol

---

tests/integration/helm_otc_metadata_installation_test.go
tests/integration/yamls/receiver-mock.yaml

Resolving https://jira.kumoroku.com/jira/browse/SUMO-194814
The tests check that systemd and kubelet logs have source fields set to something different than `undefined`.

tests/integration: verify that _sourceHost and _sourceName are not `undefined`

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/events/static/apiServerUrl.input.yaml
tests/helm/events/static/apiServerUrl_null.input.yaml
tests/helm/events/static/customSourceCategory.input.yaml
tests/helm/events/static/default.input.yaml
tests/helm/events/static/watchResourceEventsOverrides.input.yaml
tests/helm/events/static/watchResourceEventsOverrides_apiServerUrl.input.yaml
tests/integration/helm_otc_fips_metadata_installation_test.go
tests/integration/helm_otc_metadata_installation_test.go
tests/integration/values/values_common.yaml
tests/integration/values/values_helm_fluentbit_fluentd.yaml

The migration apparently already exists: https://github.com/SumoLogic/sumologic-kubernetes-tools/tree/v2.14.0/src/go/cmd/update-collection-v3/migrations/events.

feat(events)!: switch from Fluentd to Otelcol as default events collector

---

.github/workflows/pull_requests.yml
Makefile
deploy/helm/sumologic/templates/chart-configmap.yaml
deploy/helm/sumologic/templates/events/common/service-headless.yaml
deploy/helm/sumologic/templates/logs/common/pdb.yaml
deploy/helm/sumologic/templates/logs/common/service-headless.yaml
deploy/helm/sumologic/templates/metrics/common/pdb.yaml
deploy/helm/sumologic/templates/metrics/common/service-headless.yaml
deploy/helm/sumologic/templates/priorityclass.yaml
tests/helm/common_test.go
tests/helm/const.go
tests/helm/template_test.go
tests/helm/testdata/everything-enabled.yaml

Add a test for basic builtin labels that covers all manifests generated by the chart. This isn't too exciting by itself, but it shows how you can write a test like this, which we can leverage to greater effect in the future.
The test caught a couple resources with missing labels, added those.
A decent amount of effort in this test is spent filtering out resources from subcharts, which don't and shouldn't have the labels. I'm not sure if what I've done is the best way of achieving this, would appreciate feedback.

test(helm): add builtin label test

---

deploy/helm/sumologic/conf/instrumentation/otelcol.instrumentation.conf.yaml
deploy/helm/sumologic/conf/instrumentation/traces.gateway.conf.yaml
deploy/helm/sumologic/conf/opentelemetry-operator/instrumentation.cr.yaml
deploy/helm/sumologic/templates/instrumentation/traces-gateway/configmap.yaml
deploy/helm/sumologic/templates/opentelemetry-operator/configmap-instrumentation-cr.yaml
tests/helm/common_test.go
tests/helm/go.mod
tests/helm/go.sum
tests/helm/opentelemetry_operator_instrumentation_cr_configmap/static/instrumentation.output.yaml
tests/helm/otelcol-instrumentation-config/static/traces-gateway-disabled.output.yaml
tests/helm/otelcol-instrumentation-config/static/traces-gateway-enabled.output.yaml
tests/helm/template_test.go
tests/helm/traces-gateway-loadbalancing/static/traces-gateway-true.output.yaml
tests/helm/utils.go

Refactor the template tests to stop relying on `config.sh` files from the old test framework. These used to be necessary to know which template we are testing, but we can instead just render all the objects and then pick the one we want based on its name and kind. This will allow us to reorganize the template test files easily.
I also fixed some newline issues with tracing configmaps.

test(helm): refactor template tests

---

docs/best-practices.md
docs/non-helm-installation.md
docs/v3-migration-doc.md

This is needed after kube-prometheus-stack was upgraded from v39 to v42 in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2651.

docs: bump Prometheus CRD versions

---

tests/integration/create-image-archive.sh

In MacOS' antiquated userspace, `xargs` doesn't have a `-a` argument, and it requires an explicit argument limit for `-x` to work. I've set the limit to 50 arbitrarily, doubt we'll ever have that many images in there.

test(integration): fix image archive creation on MacOS

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

The image for v1.6.10 has vulnerabilities that we'd rather not care about fixing.
Let's upgrade to the latest and see how it works.

chore: upgrade Fluent Bit to v2.0.6

---

CHANGELOG.md

It was put under the first beta release by mistake.

chore: move changelog entry to the right release

---

tests/integration/helm_ot_fluentbit_logs_test.go
tests/integration/values/values_common.yaml
tests/integration/values/values_helm_ot_fluentbit_logs.yaml

We were missing this configuration in tests, and we do support it.

test(integration): add otel and fluent bit logs test

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

Fluent Bit v2.0.6 (introduced in #2694) is not passing our e2e tests.
Changes in v1.6.10-sumo-3 vs. v1.6.10-sumo-2:
- remove vulnerabilities by upgrading base Docker image to latest Debian 11 https://github.com/SumoLogic/fluent-bit-docker-image/pull/5

chore: downgrade Fluent Bit to v1.6.10-sumo-3

---

.github/workflows/pull_requests.yml

Run only the PR checks relevant to the files being changed. Unfortunately, due to Github Actions deficiencies, this is very awkward.
The problems preventing this from being nice are:
* There is no way to skip a required check, so jobs for required checks always have to run
* You can only skip a whole job based on files changed, not a step
* There is no way to exit out of a job early without putting conditionals in subsequent steps
As a result of these, we need to do the checks in separate jobs, and then use the results of those as conditions for each step. We can skip some jobs that aren't required, like integration test setup, but for most we need to repeat the annoying boilerplate.
In a future PR, I'd also like to use this to only run the link check on files which actually changed, as …

ci: run PR checks only when files change

---

.github/workflows/dev_builds.yml
.github/workflows/pull_requests.yml
ci/markdown_link_check.sh

In PRs, only check links in modified Markdown files. We still check all of them on pushes to main in case a link expires.

ci: only check links in changed md files in PRs

---

CHANGELOG.md
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/templates/scc.yaml
deploy/helm/sumologic/values.yaml
docs/existing-prometheus-doc.md
docs/installation-with-helm.md
docs/non-helm-installation.md
docs/side-by-side-prometheus.md
docs/standalone-prometheus.md
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/logs_otc_daemonset/static/complex.input.yaml
tests/helm/logs_otc_daemonset/static/complex.output.yaml

Fixes following errors:
```
kubectl describe  -n sumologic daemonset.apps/collection-sumologic-otelcol-logs-collector 
....
Warning  FailedCreate  65s                daemonset-controller  Error creating: pods "collection1-sumologic-otelcol-logs-collector-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider "collection-sumologic-setup-scc": Forbidden: not usable by user or serviceaccount, provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{0}: 0 is not an allowed group, spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[3]: …
```

fix(openshift): add missing privileges for otelcol-logs-collector

---

CHANGELOG.md
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/events/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/instrumentation/traces-gateway/deployment.yaml
deploy/helm/sumologic/templates/instrumentation/traces-sampler/deployment.yaml
deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/setup/job.yaml
tests/helm/events_otc_statefulset/static/annotations_labels.output.yaml
tests/helm/events_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml
tests/helm/setup/basic.output.yaml

Otelcol instances sending data to Sumo weren't using the global proxy settings. Fix this by adding the right environment variables, as per https://opentelemetry.io/docs/collector/configuration/#proxy-support.

fix: obey proxy settings in otelcol

---

.github/workflows/dev_builds.yml

#2714 broke the dev builds by adding an incorrect configuration to the workflow. This fixes it.

ci: fix markdown link check in dev builds

---

CHANGELOG.md
deploy/helm/sumologic/Chart.yaml
deploy/helm/sumologic/values.yaml

Upgrade Fluent Bit to v1.6.10-sumo-3 (backport)
- remove vulnerabilities by upgrading base Docker image to latest Debian 11 https://github.com/SumoLogic/fluent-bit-docker-image/pull/5
- Also, updated the repository of the metrics-server based on the change to the bitnami/charts `index.yaml` retention policy 
- https://github.com/bitnami/charts/issues/10539#issue-1257888825
---

chore: upgrade Fluent Bit to v1.6.10-sumo-3 (backport)

---

docs/best-practices.md

Updated to reflect the current default setings of the chart:
- removed Fluent Bit,
- updated the list of pods that are now installed by default.

docs(best-practices): update section on `fullnameOverride`

---

CHANGELOG.md
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/events/otelcol/statefulset.yaml
deploy/helm/sumologic/values.yaml
tests/helm/events_otc_statefulset/static/annotations_labels.output.yaml
tests/helm/events_otc_statefulset/static/basic.output.yaml
tests/helm/kube-prometheus-stack/servicemonitors/basic-sumo.output.yaml
tests/helm/prometheus_test.go

Ensure the otelcol event collector Service and Pods have the right labels, and add a ServiceMonitor to collect metrics from the Pod.
This resolves #1549

feat: collect metrics from otelcol event collector

---

docs/README.md
docs/collecting-container-logs.md

Add a document explaining collecting container logs. Fixes #2415.
I'm not sure this needs to be separate from systemd, as a lot of settings overlap.

docs: collecting container logs

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/metadata_logs_otc/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml

Backports the change from https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2771.

fix(logs): make `excludeHostRegex` consistent between Otelcol and Fluentd

---

ci/markdown_link_check.sh

The script was not doing anything, because apparently the `ALL_FILES` variable was empty, because it was read-only and couldn't be modified.
```console
$ ./ci/markdown_link_check.sh
./ci/markdown_link_check.sh: line 10: ALL_FILES: readonly variable
$ echo $?
0
```
It's interesting that:
1. The script was returning 0, no error
2. Shellcheck was not highlighting this issue
3. We don't use this script in CI, only locally

chore: fix local markdown link check script

---

deploy/docs/additional_prometheus_configuration.md
docs/fluent/best-practices.md

We don't have any docs on removing metrics in Prometheus.
This non-existent link managed to get through the markdown-link-check because we now only check modified files,
so when a file is deleted or renamed,
links to it in other files are not checked.

docs: remove non-existent link

---

vagrant/README.md

While using freshly installed `brew`, I got the following message after using suggested commands for vagrant instalation:
```
Error: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.
```
Technically, for me it worked to just use it without the flag, eg. `brew install virtualbox`, but let's follow the suggestion and use `brew install --cask virtualbox`.

chore(docs): update brew commands for vagrant instalation

---

docs/prometheus.md

I'm going to rewrite installation to externally point to this document. Until that I would like to left old documentation as well

docs: gather all prometheus installation scenarios in one document

---

CHANGELOG.md
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/metadata_logs_otc/static/otel.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml

Parse JSON logs bodies into OTLP data structures. As a result, Sumo renders the JSON correctly. Without this change, JSON log bodies are just escaped strings.
This change is somewhat dangerous, and I'm wondering if we shouldn't make it possible to disable. The problem is that currently, if the JSON parsing returns an error, it'll result in a 500 returned to the collector, and potentially block the whole batch from being processed indefinitely. Discussion is ongoing in [otel upstream](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16519
) about how the errors should be handled, but right now there doesn't seem to be a way to just ignore parse errors.
I've switched to logstransform processor, and this actually lets the malformed data through while logging an error. …

feat(logs): parse JSON logs

---

docs/v3-migration-doc.md

I split the manual steps by signal type and made it clearer when the user needs to care about a specific step. To that end, I added a daisy chain of links they can use to go straight to the end if the steps don't apply to their usecase.
I'm planning to add more sections for other changes than may require user action or attention, this mostly sets up the new structure.

docs: refactor the v3 upgrade guide

---

ci/_build_functions.sh

See if this prevents intermittent git push problems in GitHub Actions.
Most recent failure on 2023-01-09:
https://github.com/SumoLogic/sumologic-kubernetes-collection/actions/runs/3871703022/jobs/6599746510#step:3:276

ci: add `git config user.email`

---

CHANGELOG.md
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
tests/helm/logs_otc/static/basic.output.yaml

fix(logs): correctly handle newlines

---

docs/README.md

EKS release calendar: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

chore: drop EKS 1.20 support (EOL since Nov 2022)

---

CHANGELOG.md

I did not realize that missing changelog does not block automerging.

fix(docs): add missing changelog entry for EKS 1.20 support removal

---

.github/workflows/pull_requests.yml
tests/integration/kind_images.json
tests/integration/yamls/cluster.yaml

1.19 and 1.20 are no longer supported, so they have been removed from tests. 
1.23 and 1.24 are now supported, so they have been added to the tests.

chore(tests/integration): update supported k8s versions

---

.github/workflows/pull_requests.yml
ci/shellcheck.sh
vagrant/Makefile
vagrant/provision.sh
vagrant/scripts/yq/avalanche-remote-write.yaml
vagrant/scripts/yq/update_remote_write_for_avalanche.yaml

There are some instructions in the documentation that still use `yq` version 3, but those also explicitly say to install that version, so they're not blocking this change.

chore: upgrade yq to 4.30.8

---

CHANGELOG.md
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc_daemonset/static/complex.input.yaml
tests/helm/logs_otc_daemonset/static/complex.output.yaml

feat(logs): allow setting daemonset labels and annotations

---

README.md

/deploy/README.md does not exist in release-v3 branch, it's /docs/README.md instead.

docs(readme): fix link to v3.0

---

docs/collecting-kubernetes-events.md

Fluentd was mentioned as the default events provider, which is incorrect.
Also changed the ordering to put the default (Otelcol) first.
I also believe the docs from /docs/opentelemetry-collector.md#kubernetes-events should be moved to /docs/collecting-kubernetes-events.md, but this should probably be a separate PR.

docs(events): fix default events provider

---

.github/workflows/pull_requests.yml
Makefile
tests/helm/events_test.go
tests/helm/goldenfile_test.go

Split the Makefile into sections for:
* linters
* formatters
* tests
* utilities
* vagrant
Make the make target names consistent and add aggregate targets for each section.
Finally, add linting template tests to PR checks.

chore: reorganize root Makefile

---

docs/README.md

I skip changelog on purpose because:
* I don't think we should release a patch release for this
* I don't want to add the "unreleased" section in the v3.0 docs
* I don't want to change the changelog for the already released version

chore: backport support for EKS and GKE 1.24 to v3.0

---

CHANGELOG.md
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/metadata_logs_otc/static/otel.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml

Fixes #2862
The `containerName` metadata extraction gives incorrect results for pods with more than one containers.
We don't need this extraction anyway, because container logs already have the `k8s.container.name` attribute from log file name.

fix(logs): fix metadata for pods with more than one container

---

.changelog/2863.fixed.txt
.changelog/2866.fixed.txt
.changelog/changelog_template.jinja
.github/pull_request_template.md
.github/workflows/changelog.yaml
CHANGELOG.md
Makefile
ci/add-changelog-entry.sh
docs/dev.md
docs/release.md
towncrier.toml

Use [Towncrier](https://towncrier.readthedocs.io/en/latest/index.html) for automatic changelog generation from entry files kept in `.changelog`. The specifics are described in the documentation updates.
For the current changelog, this is the block added to CHANGELOG.md after running `make update-changelog VERSION=3.1.0`:
```markdown
- chore: add support for EKS 1.24 [#2831]
- chore: add support for GKE 1.24 [#2832]
- feat(otelcol): add max size in batch processors [#2839]
- chore: add support for GKE 1.25 [#2848]
- chore: remove support for KOPS 1.21 [#2848]
- chore: add support for AKS 1.25 [#2848]
- chore: add support for Openshift 4.11 [#2848]
- chore: add support for KOPS 1.25 [#2848]
[#2831]: https://github.com/SumoLogic/sumologic-kubernetes-collection/pulls/2831
[#2832]: …
```

chore: use Towncrier for changelog generation

---

.github/workflows/changelog.yaml

Fixing an issue with #2850. Towncrier actually uses a proper diff for the check, so we need history between the PR branch and `main`. I've set the depth to 50 to avoid cloning the entire thing.
Also fixed the check for the PR number.

ci(changelog): fix changelog check

---

.changelog/2870.changed.txt
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/otelcol/config.yaml
tests/helm/logs_otc/static/basic.output.yaml
tests/helm/logs_otc/static/options.output.yaml
tests/helm/metadata_logs_otc/static/otel.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml
tests/helm/metadata_metrics_otc/static/additional_endpoints.output.yaml
tests/helm/metadata_metrics_otc/static/basic.output.yaml

With on_rebound compaction enabled, this isn't necessary anymore, and it causes long startup times when the queue is large.

feat: disable otel storage compaction on start

---

.changelog/2873.changed.txt
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/otelcol/config.yaml
deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml
tests/helm/metadata_logs_otc/static/otel.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc/static/additional_endpoints.output.yaml
tests/helm/metadata_metrics_otc/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

It's now possible to put the compaction directory on a different filesystem. Do this for metadata file storage extensions. This required manually adding `emptyDir` volumes at `/tmp`, as distroless containers don't have it by default.

feat: use /tmp for otel storage compaction

---

ci/_build_functions.sh
ci/push-helm-chart.sh

Prune dev Helm Chart releases older than 1 month. We don't really need the older ones, and our index was growing excessively large.

ci: prune dev Helm Chart releases

---

.changelog/2875.fixed.txt
CHANGELOG.md
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/instrumentation/otelcol-instrumentation/service-otelagent.yaml

PR adds scrape labels to service related to `otelcol-instrumentation`. Label value changed from `traces` -> `instrumentation`.

feat(instrumentation): scrape label added and updated

---

.changelog/2893.fixed.txt
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc_daemonset/static/additional.output.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/logs_otc_daemonset/static/complex.output.yaml
tests/integration/yamls/multiline-logs-generator.yaml

PR changes the tag from `latest` to specific version for busybox img.
PR fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/2763

fix(busybox): do not use latest tag img

---

.changelog/2896.fixed.txt
ci/add-changelog-entry.sh
deploy/helm/sumologic/values.yaml
tests/integration/internal/constants.go
tests/integration/values/values_common.yaml
tests/integration/yamls/cluster.yaml

Some of the kube-scheduler metrics we've been collecting have been removed in Kubernetes 1.23. Collect the replacement metric as well. I've also re-added checking scheduler metrics in integration tests.
Also fixed an issue with the changelog entry script.
This also fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/2079

fix: collect the right kube-scheduler metrics

---

.changelog/2898.changed.txt
ci/add-changelog-entry.sh
deploy/helm/sumologic/values.yaml
tests/integration/internal/constants.go

`apiserver_request_latencies_*` metrics were deprecated in 1.14 and disabled in 1.17. The current replacement are `apiserver_request_duration_*`. Enable checking these in integration tests.
Fix another small issue in the changelog generation script as well.

chore(metrics): remove deprecated apiserver metrics

---

.github/dependabot.yml

chore: automatically add skip-changelog to dependabot PRs

---

.changelog/2899.changed.txt
deploy/helm/sumologic/values.yaml
tests/integration/internal/constants.go

Final part of the control plane metrics cleanup. We now don't try to collect any deprecated metrics, and check everything we collect in integration tests.

chore(metrics): remove deprecated coredns and etcd metrics

---

docs/best-practices.md
docs/collecting-application-metrics.md
docs/collecting-container-logs.md
tests/helm/testdata/opentelemetry-metrics-extra-processors.yaml

The uppercase properties cause OTC crash in v0.71.0 and higher.

docs: change OTC properties to lowercase

---

.changelog/2918.fixed.txt
deploy/helm/sumologic/values.yaml

Cadvisor container metrics are emitted for all cgroups, even ones not actually related to containers run by the kubelet. For some of these, the only label is the id containing the cgroup path:
```bash
$ kubectl get --raw "/api/v1/nodes/sumologic-control-plane/proxy/metrics/cadvisor" | grep container_cpu_usage_seconds_total
container_cpu_usage_seconds_total{container="",cpu="total",id="/",image="",name="",namespace="",pod=""} 676.209622261 1678268968878
container_cpu_usage_seconds_total{container="",cpu="total",id="/docker/bc61f8197b2e99d91a3e3da589e9c13dbfd2756a4e7f9903a2b76c4e6b0b5fda/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod3d6b3bf5_5b1c_407c_8842_04565a00d150.slice/cri-containerd-3ac92040b58042a3828de42432948019484832e0f20e03d …
```

fix(metrics): drop cadvisor container metrics without metadata

---

.changelog/2923.fixed.txt
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/logs_otc/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc/options.output.yaml

By default, the sending queue has a size of 5000 for otlp exporter. This is way too much for us with our batches of 1000 records. I've set it to 10, which is roughly in line with the 5 MB limit we have set for Fluent Bit.

fix(logs): reduce the queue size of the logs collector

---

docs/collecting-kubernetes-metrics.md
docs/fluent/troubleshoot-collection.md
docs/troubleshoot-collection.md

"Gathering" is an uncommon word in this context.
We usually talk about "collecting" logs/metrics/traces.
I've checked the [sumologic-documentation](https://github.com/SumoLogic/sumologic-documentation/) repo and did not find any references.

docs: change "gathering" to "collecting"

---

docs/README.md

Can you imagine it was not included in the README? :exploding_head:

docs: add v3 migration doc to TOC

---

docs/README.md

This change reorders the upgrade docs in reverse-chronological order. I believe it makes much more sense to put most recent upgrades at the top. Other examples of reverse-chronological order for upgrade docs:
- https://kubernetes.io/docs/reference/using-api/deprecation-guide/
- https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
- https://guides.rubyonrails.org/upgrading_ruby_on_rails.html
Builds upon #2929.

docs: reorder upgrade docs to put most recent and the top

---

CHANGELOG.md
deploy/README.md
deploy/docs/v2-18-migration.md

Upgrading to this release with the OpenTelemetry Operator enabled breaks unless you upgrade the operator's CRDs. This needs to be documented.
Ports change from #2931 to `release-v2.19` branch.

docs(upgrading): add upgrade guide for v2.18.0

---

CHANGELOG.md
docs/README.md

Ports change from #2931 from `release-v2` branch.
Also adds missing releases to Changelog and cleans it up from duplicate entries :unamused:

docs: add link to upgrade guide for v2.18

---

docs/fluent/best-practices.md

This is to align with the docs on the HTTP Source
https://help.sumologic.com/docs/send-data/hosted-collectors/http-source/logs-metrics/
> We recommend that the data payload of a POST request have a size, before compression, of 100KB to 1MB.

docs(fluent): change max request size to 1 MB

---

deploy/docs/Best_Practices.md

Backports #2944
This is to align with the docs on the HTTP Source
https://help.sumologic.com/docs/send-data/hosted-collectors/http-source/logs-metrics/
> We recommend that the data payload of a POST request have a size, before compression, of 100KB to 1MB.

docs(fluentd): change max request size to 1 MB

---

.github/workflows/pull_requests.yml

Passing TEST_NAME to the integration test runner just passes that value verbatim to go test. The value in go test is a regular expression though , so if we have a test whose name is a prefix of another test, both will be run.
We were running the FIPS test alongside the default test every time because of this.

ci: don't run unnecessary integration tests

---

tests/integration/helm_ot_default_test.go
tests/integration/helm_otc_fips_metadata_installation_test.go
tests/integration/internal/constants.go

We are checking for tracing-specific otelcol metrics in all tests. This worked because we don't have a metrics test where tracing isn't enabled, but I wanted to add one in #2949 and ran into this problem.

test(integration): only check tracing metrics if tracing is enabled

---

deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/events/fluentd/statefulset.yaml
deploy/helm/sumologic/templates/events/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/instrumentation/traces-gateway/deployment.yaml
deploy/helm/sumologic/templates/instrumentation/traces-sampler/deployment.yaml
deploy/helm/sumologic/templates/logs/fluentd/statefulset.yaml
deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/metrics/fluentd/statefulset.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml

The caller should always handle indentation, not helpers themselves.
This change will help with the Prometheus migration.

refactor: remove indentation from helpers

---

.changelog/2968.changed.txt
deploy/helm/sumologic/Chart.yaml

No breaking changes observed. The upstream was mostly increasing default image

chore: upgrade fluent-bit chart to 0.25.0

---

.changelog/2969.changed.txt
deploy/helm/sumologic/templates/logs/common/hpa.yaml
deploy/helm/sumologic/templates/logs/fluentd/hpa.yaml
deploy/helm/sumologic/templates/metrics/common/hpa.yaml
deploy/helm/sumologic/templates/metrics/fluentd/hpa.yaml
docs/README.md
tests/integration/kind_images.json

chore: add support for KOPS 1.26, EKS 1.25; remove support for GKE 1.21, EKS 1.21
Start supporting 1.26

chore: update support matrix

---

.changelog/3001.fixed.txt
deploy/helm/sumologic/conf/logs/otelcol/config.yaml

Quick fix, I won't be able to write e2e for the pr
Removing unrelated conditions for the processors. They are being used outside of systemd flow

fix: fix logs pipeline if systemd is disabled

---

.github/workflows/backport_bot.yaml
.github/workflows/dev_builds.yml
.github/workflows/pr_labeler.yaml
.github/workflows/pull_requests.yml
.github/workflows/release_builds.yml
tests/integration/kind_images.json
tests/integration/yamls/cluster.yaml

The actual fix is the removal of the cgroupdriver workaround we added for MacOS in #2901 and the upgrade to ubuntu 22.04 for some unknown reason. I've also upgraded kind images in the process.
This is probably still broken on MacOS, but it's more important to unblock the CI right now.

ci: fix integration tests

---

ci/_build_functions.sh
ci/push-helm-chart.sh

We want to prune our dev releases to only keep the ones from the past month, but we also don't want to prune the most recent dev release, as E2E tests still run on it.
Fix the above by pruning for each major version separately. As a result, v2 dev releases will only be pruned when a new v2 dev release is added, ensuring there will always be one.

ci: prune old dev releases separately for each major version

---

ci/_build_functions.sh

There was an error in the pattern being matched.

ci: fix dev Helm Chart pruning

---

.changelog/3039.changed.txt
deploy/helm/sumologic/values.yaml
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

Instructs Sumo Logic to use `timestamp` key if it exists. It will ensure that the `timestamp` extraction is consistent. Auto-detection is fallback, so no behavior change is expected in case `timestamp` is not added to the log

feat: use timestamp as message time if exists

---

.changelog/3043.changed.0.txt
.changelog/3043.changed.1.txt
docs/README.md

OpenShift 4.8 and 4.9 are no longer supported: https://access.redhat.com/support/policy/updates/openshift#dates
GKE 1.22 is also no longer supported: https://cloud.google.com/kubernetes-engine/docs/release-schedule

chore: drop support for EOLd platforms

---

.changelog/3042.fixed.txt
deploy/helm/sumologic/conf/logs/otelcol/config.yaml

When using Fluent Bit as the log collector and otel for metadata enrichment, systemd logs would arrive empty in Sumo. The reason for this is that Fluent Bit actually puts the systemd attributes in the equivalent of record attributes, while the otel log collector puts them in the body. The pipelines were the same, which caused the issue.
I've removed the unnecessary processors from the Fluent Bit pipeline.

fix(logs): systemd logs with otel and Fluent Bit

---

.changelog/3047.added.0.txt
.changelog/3047.added.1.txt
docs/README.md

E2E tests now pass for these versions.

chore: add support for EKS 1.26 and GKE 1.26

---

.changelog/3054.fixed.txt
deploy/helm/sumologic/templates/NOTES.txt
tests/helm/common_test.go
tests/helm/const.go
tests/helm/testdata/everything-enabled.yaml

fix: warn about release name length

---

.changelog/3059.added.txt
deploy/helm/sumologic/conf/logs/collector/otelcloudwatch/config.yaml
docs/fargate.md

Add multiline support to EKS Fargate
https://stagdata.long.sumologic.net/ui/#/search/create?id=HS2q7MasCkcxQkWvkMdVFUEfYJ3Ku7DYbByPc4XL

feat(EKS Fargate): Add multiline support to EKS Fargate

---

.changelog/3063.fixed.txt
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/otel.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/templates.output.yaml

Use transform processor for JSON log parsing instead of the logstransform processor. The former is more stable and better supported, while the latter is slated for removal once OTTL has all the necessary features.

chore(logs): use transform processor for json parsing

---

.changelog/3050.added.txt
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/otel.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/templates.output.yaml

The [json_merge](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v3.6/docs/collecting-container-logs.md#json_merge-log-format) log configuration has problems if log bodies are only _sometimes_ JSON. Some of our pods output JSON logs, others don't, and we got lots of these errors:
```
2023-05-11T19:41:15.418Z	error	logstransformprocessor@v0.76.3/processor.go:203	processor encountered an issue with next consumer	{"kind": "processor", "name": "logstransform/containers_parse_json", "pipeline": "logs/otlp/containers", "error": "failed to execute statement: merge_maps(attributes, body, \"insert\"), expected pcommon.Map but got string"}
```
We should check whether a log line seems like JSON, and don't attempt to `merge_maps` if not.

fix: json_merge where message bodies are only sometimes json

---

.changelog/3070.fixed.txt
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
tests/helm/const.go
tests/helm/goldenfile_test.go
tests/helm/logs_test.go

Only use the longer file fingerprint for log file identification on K8s versions which still have docker-shim. This is not necessary with containerd.
Fixes #2916

fix(logs): use longer fingerprint only on K8s <1.24

---

README.md

This is quite tricky as 2.19 is going to be supported to `2023-07-20` only because it is the latest v2 version. Not sure how to handle it clear

chore: update support for v2

---

.changelog/3078.changed.txt
deploy/helm/sumologic/templates/logs/common/hpa.yaml
deploy/helm/sumologic/templates/logs/fluentd/hpa.yaml
deploy/helm/sumologic/templates/metrics/common/hpa.yaml
deploy/helm/sumologic/templates/metrics/fluentd/hpa.yaml

This addresses an issue when using ArgoCD (and maybe other GitOps operators) where Kubernetes reorders the objects under the spec.metrics key thus causing Sync issues with ArgoCD.
Originally reported to the ArgoCD project here:
https://github.com/argoproj/argo-cd/issues/1079
Originally reported to the Kubernetes project here: https://github.com/kubernetes/kubernetes/issues/74099
Other projects and companies have also addressed this by simply reordering the metrics section:
* https://github.com/kubernetes/ingress-nginx/pull/10043
* https://github.com/nginxinc/kubernetes-ingress/pull/3773
* https://github.com/grafana/helm-charts/pull/758
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/103
* https://github.com/Nextdoor/k8s-charts/pull/102

Reordering HPA spec.metrics to match HPA ordering

---

.changelog/3081.changed.txt
docs/README.md
tests/helm/const.go
tests/integration/kind_images.json
tests/integration/values/values_common.yaml
vagrant/provision.sh

EKS 1.22 is out of support since 04.06.2023 as per https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar. This was the last 1.22 version we supported, alongside KOPS.

chore: drop support for k8s 1.22

---

deploy/helm/sumologic/conf/events/otelcol/config.yaml
deploy/helm/sumologic/conf/logs/collector/otelcloudwatch/config.yaml
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/otelcol/exporters.yaml
deploy/helm/sumologic/conf/metrics/otelcol/processors.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

The references are a holdover from when the whole configuration was exposed to the user. We don't need them anymore, and updating them is annoying, see #3087 .

chore: remove reference comments from otel config

---

ci/_build_functions.sh

- Fixing retry logic for pushing dev build
- Pull latest changes from remote before pushing dev build

Fixing issues for pushing dev build

---

.github/workflows/dev_builds.yml

Dev builds would incorrectly specify tests running in a given matrix configuration by not anchoring the test regex.

ci: fix test names for dev builds

---

.changelog/3094.added.txt
deploy/helm/sumologic/values.yaml
docs/otlp-source.md
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml
tests/helm/testdata/goldenfile/traces-gateway-deployment/basic.output.yaml
tests/helm/testdata/goldenfile/traces-sampler-deployment/basic.output.yaml
tests/integration/helm_opentelemetry_operator_enabled_test.go
tests/integration/helm_ot_default_namespaceoverride_test.go
tests/integration/helm_ot_default_test.go
tests/integration/helm_otc_fips_metadata_installation_test.go
tests/integration/helm_otlp_test.go
tests/integration/values/values_common.yaml
tests/integration/values/values_helm_otlp.yaml

#3093 but for traces. As tracing otel config is embedded in values.yaml, the user has to manually change the exporter endpoint to enable otlp source.

feat(traces): add ability to use OTLP source

---

.changelog/3103.changed.txt
deploy/helm/sumologic/values.yaml

Move relabeling from remoteWrite to serviceMonitor in order to use common remoteWrite

feat(helm): move relabelling in prometheus from remoteWrites to serviceMonitors

---

.changelog/3098.changed.txt
CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

This pull request fixes  v3.9.1 release which was create from main branch https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/f6e9329b54adc0865b51bd9bfe7bae1cfe75c75f
Necessary changes are already on branch: https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/63061a1bd6abff815079eb3dd9200c4fb313b7cb

chore: prepare release v3.9.1

---

.changelog/3122.changed.txt
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/otelcol/pipeline.yaml
deploy/helm/sumologic/templates/metrics/collector/otelcol/opentelemetrycollector.yaml
deploy/helm/sumologic/templates/metrics/common/service-headless.yaml
deploy/helm/sumologic/templates/metrics/common/service.yaml
deploy/helm/sumologic/templates/metrics/otelcol/configmap.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/additional_endpoints.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc_statefulset/basic.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc_statefulset/custom.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/helm/testdata/goldenfile/services_with_service_monitor_labels/services_with_service_monitor_labels/default.output.yaml
tests/integration/features.go
tests/integration/helm_ot_metrics_test.go

Make the otel metrics collector strictly replace Prometheus, and keep the metadata StatefulSet separate. Originally I'd wanted to simplify the architecture by merging these two components, but this ended up making the migration more complicated and difficult to understand. We can do the architectural changes separately, in a future release.

feat(metrics): split metadata extraction from otel collector

---

deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/integration/features.go
tests/integration/helm_fluentbit_fluentd_test.go
tests/integration/internal/receivermock/labels.go

In metrics integration tests, check the expected labels strictly. Until now, we've only been checking if the expected attributes exist - now we also check if there are any extras, and fail the test in that case.
I've also dropped some attributes for metrics collected by the metrics collector.

test(integration): check metric labels strictly

---

.changelog/3131.changed.txt
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

By default, Prometheus receiver emits scrape metrics for each target, similar to Prometheus' `up`. We don't have these for Prometheus, so we should drop them by default for backwards compatibility.

fix(metrics/collector): drop scrape_* metrics

---

.changelog/3133.added.txt
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

Make sure we explicitly have an empty scrape configs array if both kubelet and cAdvisor metrics are disabled for the Otel collector. Opentelemetry-operator errors if this isn't the case.

fix(metrics/collector): disabling kubelet and cAdvisor metrics

---

.changelog/3099.fixed.txt
deploy/helm/sumologic/templates/_helpers/_logs.tpl
deploy/helm/sumologic/templates/logs/collector/otelcol-cloudwatch/statefulset.yaml
docs/fargate.md
tests/helm/testdata/goldenfile/logs_otc_cloudwatch/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc_cloudwatch/custom.output.yaml

- Fixing PVC name for the cloudwatch logs collector - to not hardcode the release name
- Correct the name of the EFS access points

Otel cloudwatch logs collector fixes

---

.changelog/3141.fixed.txt
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/integration/features.go
tests/integration/internal/stepfuncs/assess_funcs.go

Prometheus receiver adds some attributes based on Prometheus' meta labels. This cannot be turned off explicitly or prevented by deleting the labels in relabel configs, because the labels are extracted from the context.
Drop these labels in a processor, as we don't need them, and their presence makes the pipeline more difficult to understand.
I've also added a test specifically for metadata of kube-state-metrics, which have specific requirements. For example, Prometheus incorrectly assigns Pod metadata to them, and the test checks whether we remove it.

fix(metrics/collector): drop k8s labels

---

.changelog/3156.changed.txt
deploy/helm/sumologic/conf/logs/collector/otelcloudwatch/config.yaml
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
deploy/helm/sumologic/values.yaml
docs/best-practices.md
tests/helm/testdata/goldenfile/logs_otc/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc/options.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/helm/testdata/goldenfile/otelcol-instrumentation-config/traces-gateway-disabled.output.yaml
tests/helm/testdata/goldenfile/otelcol-instrumentation-config/traces-gateway-enabled.output.yaml

We transfer a bunch of data between components via OTLP. The default compression is gzip for the exporter, but the receiver supports ztsd since 0.81.0, which is a lot more efficient.

chore: use zstd compression for internal otlp data

---

.changelog/3155.fixed.txt
deploy/helm/sumologic/templates/logs/common/hpa.yaml
deploy/helm/sumologic/templates/logs/fluentd/hpa.yaml
deploy/helm/sumologic/templates/metrics/common/hpa.yaml
deploy/helm/sumologic/templates/metrics/fluentd/hpa.yaml

Change the minimum version for using autoscaling/v2 api to 1.23

---

.changelog/3157.changed.txt
deploy/helm/sumologic/values.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/additional_endpoints.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/basic.output.yaml

Merge most of the default remote writes into a single one that does (almost) no data transformations. We filter by job name instead of metric name.
* Node metrics still have their own, due to difficulty handling recording rule metrics.
* Collection internal metrics need some additional work before they can be handled this way.
* We need to manually drop Prometheus' scrape metrics.
This doesn't affect users who modified these, as that requires overriding the whole array, and this is therefore not a breaking change.

feat(metrics): do not filter in default remote write definitions

---

.changelog/3162.added.txt
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/integration/helm_ot_metrics_test.go
tests/integration/internal/constants.go
tests/integration/yamls/receiver-mock.yaml

We collect metrics from Pods with standard Prometheus annotations - `prometheus.io/scrape`, and so on - when using Prometheus. This PR implements this for otel. This is basically done by copying the additional scrape config we have for Prometheus into the prometheus receiver configuration.
The tests are very messy and I intend to add better ones in a separate PR when I implement metric filtering for Sumo Apps. This is just a quick and dirty way to show the functionality works, by using receiver-mock itself as the target.
Note that for this specific source of metrics, we actually forward Prometheus `scrape_*` metrics as well. I made the metrics collector behave the same way for the sake of consistency.

feat(metrics/collector): collect metrics from annotated Pods

---

.changelog/3170.fixed.txt
deploy/helm/sumologic/conf/metrics/otelcol/processors.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/additional_endpoints.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/basic.output.yaml

Until the change is released, the following configuration may be use:
```
metadata:
metrics:
config:
merge:
processors:
source:
exclude:
k8s.namespace.name: sumologic
```

fix(helm/metrics): exclude namespace if collectionMonitoring is disabled

---

.changelog/3171.fixed.txt
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/otelcol/processors.yaml
deploy/helm/sumologic/values.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/additional_endpoints.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/integration/features.go
tests/integration/helm_fluentbit_fluentd_test.go
tests/integration/helm_ot_default_test.go
tests/integration/helm_ot_metrics_test.go
tests/integration/internal/constants.go
tests/integration/internal/k8s/pods.go
tests/integration/internal/stepfuncs/assess_funcs.go
tests/integration/values/values_common.yaml
tests/integration/values/values_helm_default_ot.yaml
tests/integration/values/values_helm_fluentbit_fluentd.yaml
tests/integration/values/values_helm_ot_metrics.yaml
tests/integration/yamls/nginx.yaml

Don't forward App metrics if they originate from a Pod scraped due to annotations. We tell customers to do this for these metrics (https://help.sumologic.com/docs/integrations/web-servers/nginx/#configure-metrics-collection), but we have separate remote writes for these cases, and so they are forwarded twice, and with different labels.
I ended up making a bunch of additional changes:
* I've added a integration test for nginx metrics using Telegraf operator
* Refactored some receiver-mock related code in integration tests
* Added a utility function to assert metrics are present for a given filter
* Fixed some minor issues

fix(metrics): don't forward duplicate metrics from annotated Pods

---

deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
deploy/helm/sumologic/values.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

Remove some unnecessary relabel actions from both the otel metrics collector and our Pod annotation scrape config for Prometheus. These simply never exist for the kubernetes service discovery role they use, and are therefore noops. They mostly exist because we uncritically copied them from configurations emitted by prometheus-operator for ServiceMonitors.

chore(metrics): remove unnecessary relabellings

---

.changelog/3185.fixed.txt
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml

fix configuration for filelog/container to use default settings for `fingerprint_size` on k8s >=1.24
Problem with previous form of condition was observed on EKS 1.24 (I see [tests](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/fcac957b08d96c6cc867dd4ae482e378374f4f1f/tests/helm/logs_test.go#L399-L433) for this condition so it looks like there is different form of `.Capabilities.KubeVersion.Minor` on EKS) - this pull request uses `kubernetes.minor` function which is used in other places in our Helm Chart
When fingerprint_size is set to 1kb (default value) the issue with duplicated logs is not observed, https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22936

fix(otellogs): fix configuration for filelog/container to use default settings for fingerprint_size on k8s >=1.24

---

README.md

Since v2 is no longer supported, this commit removes all v2 version except the latest one from the list of unsupported versions, similar to how it looks for v0 and v1.

docs: remove unsupported v2 versions from the list

---

deploy/helm/sumologic/templates/metrics/collector/otelcol/opentelemetrycollector.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/integration/helm_ot_metrics_test.go
tests/integration/internal/constants.go
tests/integration/yamls/receiver-mock.yaml

Receiver-mock metrics were originally used for testing scraping from annotated Pods. This is now better accomplished with a dedicated test added in #3171. Therefore, I'm removing it.
I've also explicitly disabled the `prometheus.io/scrape` annotation, as the operator adds it by default.

test(integration): don't check receiver-mock metrics

---

.changelog/3193.fixed.txt
deploy/helm/sumologic/values.yaml
tests/integration/features.go
tests/integration/helm_fluentbit_fluentd_test.go
tests/integration/helm_ot_default_test.go
tests/integration/helm_ot_metrics_test.go
tests/integration/internal/constants.go

By default, Telegraf operator adds an `internal` input which collects Telegraf's own metrics. In addition, the Prometheus output exposes process and gocollector metrics. We don't want either of these enabled by default.
Unfortunately this behaviour of Telegraf operator can only be disabled via a flag passed on the command line, and the Helm Chart doesn't allow changing these. So instead we drop the metrics in the output.

fix(metrics): don't collect internal Telegraf metrics

---

.changelog/3195.fixed.txt
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

When all the scrape configs were disabled, we'd generate invalid yaml for the Otel configuration.

fix(metrics/collector): scrape configs disabled

---

.changelog/3197.fixed.txt
deploy/helm/sumologic/conf/logs/collector/otelcloudwatch/config.yaml
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
deploy/helm/sumologic/values.yaml
docs/best-practices.md
tests/helm/testdata/goldenfile/logs_otc/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc/options.output.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/multiple_multiline.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/helm/testdata/goldenfile/otelcol-instrumentation-config/traces-gateway-disabled.output.yaml
tests/helm/testdata/goldenfile/otelcol-instrumentation-config/traces-gateway-enabled.output.yaml

This reverts commit c18580380e4c680b1351fca46c113f847cf8c4c5. See: https://github.com/open-telemetry/opentelemetry-collector/issues/8216.
I'm going to backport this fix to 3.12 and 3.11, as it's quite disruptive.

Revert "chore: use zstd compression for internal otlp data"

---

.changelog/3197.fixed.txt
deploy/helm/sumologic/conf/logs/collector/otelcloudwatch/config.yaml
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
deploy/helm/sumologic/values.yaml
docs/best-practices.md
tests/helm/testdata/goldenfile/logs_otc/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc/options.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/helm/testdata/goldenfile/otelcol-instrumentation-config/traces-gateway-disabled.output.yaml
tests/helm/testdata/goldenfile/otelcol-instrumentation-config/traces-gateway-enabled.output.yaml

Backport https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/1461346704acb8a296b5cfaff13ee0ee614fbc1a from https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3197.

[Backport release-v3.11] Revert "chore: use zstd compression for internal otlp data"

---

.changelog/3197.fixed.txt
CHANGELOG.md

We also drop the changelog entry for #3197, as it's already in 3.12.1.

docs: add 3.11.1 and 3.12.1 to changelog

---

.changelog/3208.changed.txt
deploy/helm/sumologic/templates/metrics/collector/otelcol/opentelemetrycollector.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

This change makes us drop scrape configs which are filtered out by relabelling rules in the target allocator, so they're not given to collectors at all. By default, each collector does this on its own.

feat(metrics/collector): filter scrape configs in target allocator

---

.changelog/3209.changed.txt
docs/README.md

AKS doesn't allow creation of new clusters with 1.24, making it impossible to test.

chore: drop support for AKS 1.24

---

.changelog/3221.added.txt
deploy/helm/sumologic/conf/metrics/remote-write-proxy/remote-write-proxy.conf
deploy/helm/sumologic/templates/metrics/collector/otelcol/opentelemetrycollector.yaml
deploy/helm/sumologic/templates/metrics/remote-write-proxy/deployment.yaml
deploy/helm/sumologic/templates/metrics/remote-write-proxy/service.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/helm/testdata/goldenfile/remote_write_proxy/basic.output.yaml
tests/helm/testdata/goldenfile/remote_write_proxy/full_config.output.yaml
tests/helm/testdata/goldenfile/remote_write_proxy/full_configmap.output.yaml
tests/integration/internal/constants.go
tests/integration/values/values_helm_ot_metrics.yaml

The remote write proxy was originally disabled for the otel metrics collector. Until we've added the ability to disable persistent connections in the upstream collector, it's still useful for load balancing.

feat(metrics/collector): support remote write proxy

---

.changelog/3212.fixed.txt
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/logs_test.go

For OTLP sources, the text format is implemented by removing all record attributes. However, we were adding the timestamp attribute afterwards, causing the logs to be rendered as json. Fix this by moving the timestamp processor before the attribute removal.

fix(logs): fix text format for otlp source

---

.changelog/3225.fixed.txt
deploy/helm/sumologic/templates/metrics/collector/otelcol/opentelemetrycollector.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

If we only set the image as the operator's default, it doesn't upgrade existing OTC resources automatically.

fix(metrics/collector): explicitly set OT image

---

.changelog/3229.added.txt
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

Batching is more useful for splitting batches than aggregating them. In particular, kube-state-metrics in large clusters can produce very large batches that we want to split.

feat(metrics/collector): add batching

---

docs/README.md

Somehow these documents were not linked in the main README file.

docs: add links to metrics configuration

---

deploy/helm/sumologic/values.yaml
docs/fluent/best-practices.md
examples/multiline_logs/values_containerd.yaml
examples/multiline_logs/values_containerd_new_parser.yaml
tests/integration/values/values_helm_fluentbit_containerd_multiline_logs.yaml

Fix links to documentation in `values.yaml` after moving part of it to `fluentd` subdirectory

chore: fix doc links in yaml files

---

.changelog/3231.fixed.txt
deploy/helm/sumologic/templates/logs/common/pdb.yaml

This change updates the logs pdb.yaml to either use maxUnavailable, if defined, or minAvailable as a default.
The current behavior is to always include minAvailable since it's specified as a default in values.yaml file. There's no way in helm to unset this. With this change it will use maxUnavailable if defined and if not it will fall back to minAvailable.

Use either minAvailable or maxUnavailable for logs pdb

---

.changelog/3227.fixed.txt
deploy/helm/sumologic/values.yaml

Ref: https://github.com/fluent/fluent-bit/pull/3087
A customer reported this. Without setting this, the time attribute is empty.

fix(fluent-bit): set Time_Keep to On in containerd parser

---

docs/best-practices.md

This is feature our customer would like to use. WDYT about adding it to regular configuration as the following?
```
sumologic:
logs:
systemd:
removeAttributes:
- PRIORITY
```

docs: add instruction to remove unwanted attributes from systemd logs

---

tests/helm/const.go
tests/helm/testdata/goldenfile/logs_otc/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/multiple_multiline.output.yaml

Bumping to 1.26, because we don't support 1.27 on Kops yet.

chore(helm/tests): bump defaultK8sVersion to 1.26

---

docs/README.md

Reverts SumoLogic/sumologic-kubernetes-collection#3263
My bad, that PR was only meant for `release-v3` branch and not `main`.

Revert "docs: add link to "Switching from Prometheus" to main README"

---

.changelog/3267.fixed.txt
deploy/helm/sumologic/conf/logs/collector/otelcloudwatch/config.yaml
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/logs_otc/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc/options.output.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/multiple_multiline.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

Disable HTTP keep-alives for network traffic from collectors to metadata enrichment. This should make the Kubernetes iptables-based load balancing work better at the cost of increased network traffic.

fix: disable keep-alives for internal traffic

---

.changelog/3267.fixed.txt
deploy/helm/sumologic/conf/logs/collector/otelcloudwatch/config.yaml
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/logs_otc/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc/options.output.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/multiple_multiline.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

Replaces #3268, backporter bot can't handle multiple commits.

[Backport release-v3] fix: disable keep-alives for internal traffic

---

docs/opentelemetry-collector/metrics.md
tests/integration/values/values_helm_ot_metrics.yaml

After disabling keep-alives, remote write proxy isn't necessary anymore.

docs: disable remote write proxy for otel metrics collector

---

.changelog/3281.fixed.txt
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/templates.output.yaml

It's easier for users to write processors if they can assume the log body is a string, as opposed to having to work with arbitrary structured data.

fix(logs)!: move JSON parsing after user-defined processors

---

.changelog/3289.fixed.txt
deploy/helm/sumologic/conf/metrics/otelcol/exporters.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/additional_endpoints.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/custom.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/filtered_app_metrics.output.yaml

Sumo doesn't support OTLP Histograms natively yet. Enable decomposing these histograms into Gauge metrics in the exporter.

fix(metrics): decompose OTLP histograms

---

.changelog/3295.fixed.txt
deploy/helm/sumologic/conf/metrics/otelcol/processors.yaml
docs/v4-migration-doc.md
tests/helm/testdata/goldenfile/metadata_metrics_otc/additional_endpoints.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/custom.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/filtered_app_metrics.output.yaml
tests/integration/features.go

Use the `node` attribute instead. This was only part of the metrics metadata by mistake.

fix(metrics)!: drop k8s.node.name attribute

---

deploy/helm/sumologic/conf/metrics/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/otelcol/pipeline.yaml
deploy/helm/sumologic/conf/metrics/otelcol/processors.yaml
tests/helm/metrics_test.go
tests/helm/testdata/goldenfile/metadata_metrics_otc/additional_endpoints.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/custom.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/filtered_app_metrics.output.yaml

We can do this after having consolidated our remote writes.
I've decided to just send the `cloudprovider_*` metrics to the kubelet source if it's reported by the kubelet. Never really made sense that we sent it to the controller-manager source. In any case, OTLP source is going to be the default in v4, so this routing setup will only matter for users who manually switch back to the HTTP source.

chore(metrics): route based on job attributes

---

docs/v4-migration-doc.md

Make it clear we're removing Fluent Bit and Fluentd, and link to the v3 migration doc.

docs: update v4 migration doc

---

deploy/docs/release.md

The existing link was pointing to the same branch it's on :arrows_counterclockwise:

docs(release): update release guide link

---

.changelog/3318.fixed.txt
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

Prometheus and prometheus receiver emit staleness markers in the form of samples with a `NaN` value whenever a target disappears. These markers aren't that useful when a target is moved between collector Pods, and Sumo currently doesn't handle them correctly.
Drop them in the collector instead.

fix(metrics): drop stale datapoints

---

.changelog/3323.fixed.txt
deploy/helm/sumologic/values.yaml
tests/integration/features.go

We always drop `container` and `pod` attributes from kube state metrics if their value is the kube-state-metrics pod/container itself. This is usually wrong, as the attributes are added by the ServiceMonitor configuration to metrics which aren't about pods to begin with, like `kube_deployment_status_replicas`, for example.
However, this means we incorrectly drop these attributes from pod metrics about the `kube-state-metrics` pod itself, like `kube_pod_status_phase`.
This PR fixes this bug by checking for the `uid` attribute, which kube-state-metrics adds to all metrics about pods.

fix(metrics): kube-state-metrics pod metadata

---

.changelog/3281.fixed.txt
.changelog/3286.added.txt
.changelog/3289.fixed.txt
.changelog/3292.added.txt
.changelog/3314.added.txt
.changelog/3318.fixed.txt
.changelog/3320.changed.txt
.changelog/3321.fixed.txt
.changelog/3323.fixed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release 3.16.0

---

.changelog/3332.added.txt
docs/README.md

Wait with merging: PR that adds automatic test runs on this version has not been merged yet.

chore: add support for k8s 1.27 with KOPS

---

vagrant/scripts/README.md
vagrant/scripts/diff_values.py

Add script to diff customer values with default ones:
example usage:
```
./vagrant/scripts/diff_values.py --version v3.0.0 vagrant/values.local.yaml
```

feat(vagrant): add script to diff customer values with default ones

---

.changelog/3342.changed.txt
.changelog/3348.fixed.txt
.changelog/3367.fixed.txt
.changelog/3373.fixed.txt
.changelog/3374.added.txt
.changelog/3375.changed.txt
CHANGELOG.md
README.md

chore: prepare v3.17.0 release

---

.gitignore
Makefile
ci/check_dependencies/.gitignore
ci/check_dependencies/README.md
ci/check_dependencies/aks.py
ci/check_dependencies/common.py
ci/check_dependencies/eks.py
ci/check_dependencies/gke.py
ci/check_dependencies/helm_charts.py
ci/check_dependencies/kops.py
ci/check_dependencies/kubernetes_collection.py
ci/check_dependencies/main.py
ci/check_dependencies/openshift.py
ci/check_dependencies/requirements.txt
shell.nix

Add a dependency checker tool that can provide a summary of dependencies which need to be updated. This includes platform support.
Right now this can just be run locally, but the intent is to have it run on a schedule in CI and create issues about dependencies needing updates.
Credit goes to @kkujawa-sumo and https://github.com/kkujawa-sumo/gardener-helper, of which this is a copy with some minor bug fixes.

ci: add dependency-checker command

---

.github/workflows/workflow-integration-tests.yaml
tests/integration/kind_images.json

Run integration tests on k8s 1.28. It was necessary to upgrade kind to do this, and I've also bumped all the images as per https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0.

test(integration): support k8s 1.28

---

.github/workflows/pull_requests.yml
shell.nix

Update local tools. I wanted to use a more recent revision, but ran into some issues with towncrier, so I used the earliest one that has kind 0.20.0.

chore: update tools

---

ci/check_dependencies/helm_charts.py

Our kube-prometheus-stack version is mostly determined by OpenShift CRD compatibility, so there isn't much value in dependency_checker complaining about it.

chore(dependency_checker): ignore kube-prometheus-stack

---

.changelog/3394.changed.txt
deploy/helm/sumologic/Chart.yaml
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

I've also removed explicit configuration for prometheus receiver to use the target allocator, as the operator now injects this on its own.

deps: update opentelemetry-operator to 0.42.0

---

.changelog/3387.changed.2.txt
docs/README.md

This was removed by mistake.
This reverts commit 23f7b3425f54f226a0023cbbb6c6e18c03f5b5d6.

Revert "chore: drop support for GKE 1.24"

---

.changelog/3411.fixed.txt
deploy/helm/sumologic/templates/metrics/collector/otelcol/opentelemetrycollector.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

It was an oversight that these weren't configurable. I've set them to be identical to the collector for now, we'll see if more fine grained control over them is necessary.

fix(metrics): set nodeSelector and tolerations for target allocator

---

.changelog/3423.added.txt
deploy/helm/sumologic/conf/setup/resources.tf
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

Add description for collector. We are adding it to track coverage of helm chart versions. It won't work if setup job is disabled

feat: add description including helm version to collector

---

.github/workflows/pull_requests.yml

Integration tests run as an optional reusable workflow. We want to require that they pass for each PR, but only if they weren't skipped. This PR achieves this by adding a job that deals with the possible results correctly.

ci: add integration test success job

---

.changelog/3434.fixed.txt
deploy/helm/sumologic/conf/events/otelcol/config.yaml
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/testdata/goldenfile/events_otc/basic.output.yaml
tests/helm/testdata/goldenfile/events_otc/options.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/otel.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/templates.output.yaml

get current timestamp in case log timestamp is empty
Covers this piece of code: https://github.com/SumoLogic/sumologic-otel-collector/blob/a42dba41373bd03f81cc0204fb915c1997dc20dd/pkg/exporter/sumologicexporter/sender.go#L396-L398

fix: fix add_timestamp behavior

---

.changelog/3447.fixed.txt
deploy/helm/sumologic/templates/metrics/collector/otelcol/opentelemetrycollector.yaml
deploy/helm/sumologic/templates/metrics/collector/otelcol/targetallocator-serviceaccount.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

There's currently a bug in otel operator (https://github.com/open-telemetry/opentelemetry-operator/issues/2443) which causes it to create a ServiceAccount for the Target Allocator even if we provide our own. In practice, we used the same name as the operator, so it only changed some labels. As a work around for this bug, we just let the operator handle this.

fix(metrics): use targetallocator serviceaccount created by the operator

---

docs/troubleshoot-collection.md
vagrant/Makefile
vagrant/k8s/argo.yaml

docs: add troubleshoot for missing metrics for Argo installation

---

.changelog/3491.added.txt
deploy/helm/sumologic/templates/clusterrole.yaml
tests/helm/testdata/goldenfile/common/clusterrole.output.yaml

Add permission to get/list/watch EndpointSlice resources. We're planning to use these instead of Endpoints to track Pod to Service relationships in our Kubernetes metadata Otel processor.

feat: add endpointslices RBAC permission

---

.changelog/3507.changed.0.txt
.changelog/3507.changed.1.txt
.changelog/3507.changed.2.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md
tests/helm/testdata/goldenfile/metrics-server/basic.output.yaml

Falco: 3.8.6 -> 3.8.7
Metrics Server: 6.6.5 -> 6.8.0 (still warm!)
OpenTelemetry Operator: 0.44.2 -> 0.46.0

deps: update Falco and Metrics Server

---

.changelog/3514.fixed.txt
deploy/helm/sumologic/templates/_helpers/_api_versions.tpl

fix: fix capabilities check for PodDisrutionBudget

---

.changelog/3538.changed.txt
deploy/helm/sumologic/conf/instrumentation/otelcol.instrumentation.conf.yaml
tests/helm/testdata/goldenfile/otelcol-instrumentation-config/traces-gateway-disabled.output.yaml
tests/integration/features.go
tests/integration/helm_traces_gateway_disabled_test.go
tests/integration/values/values_helm_traces_gateway_disabled.yaml

Use `loadbalancingexporter` when `traces-gateway` is disabled to ensure that traces are sent to proper `traces-sampler` instance.

chore(otelcolInstrumentation):  use loadbalancing exporter when traces-gateway is disabled

---

.changelog/3539.fixed.txt
deploy/helm/sumologic/templates/metrics/collector/otelcol/opentelemetrycollector.yaml
deploy/helm/sumologic/templates/metrics/collector/otelcol/serviceaccount-targetallocator.yaml
deploy/helm/sumologic/templates/metrics/collector/otelcol/serviceaccount.yaml
tests/helm/common_test.go
tests/helm/testdata/everything-enabled.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/debug.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/kubelet.output.yaml

Ensure globally defined pull secrets are added to metrics collector ServiceAccounts. I've also added a test that checks all ServiceAccounts to ensure we catch this problem more easily in the future.
Fixes #3530

fix(metrics): image pull secrets for metrics collector

---

ci/check_dependencies/aks.py
ci/check_dependencies/eks.py
ci/check_dependencies/kops.py

Include preview releases in checks for platform support. We want this to be closely aligned with testability - if it's possible to provision a new cluster with a given version, and it's not explicitly out-of-support, then we want to keep supporting it.
It also turned out that our EKS checker used the wrong branch - the repo it was referencing made the switch from `master` to `main` recently.
With these changes, I get the following output:
```
Gardener helper
#####################################################################
Kops officially supported versions
['1.25', '1.26', '1.27', '1.28', '1.29']
Currently supported Kops versions for Sumologic Kubernetes Collection Helm Chart
['1.24', '1.25', '1.26', '1.27', '1.28', '1.29']
Please remove support to following Kops versions:
['1.24'] …
```

ci: include preview releases in platform support checks

---

.changelog/3574.changed.txt
deploy/helm/sumologic/conf/events/otelcol/config.yaml
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/testdata/goldenfile/events_otc/basic.output.yaml
tests/helm/testdata/goldenfile/events_otc/options.output.yaml
tests/helm/testdata/goldenfile/events_otc/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/debug.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/debug_with_sumologic_mock.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/otel.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/templates.output.yaml

chore: remove clear_logs_timestamp from otelcol configuration
related pull request: https://github.com/SumoLogic/sumologic-otel-collector/pull/1455
I'll update otelcol in the next pull request.

chore: remove clear_logs_timestamp from otelcol configuration

---

.changelog/3586.changed.txt
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/additional-complex.input.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/additional-complex.output.yaml

It may be useful to create daemonsets for windows. It will still require more configuration options, but I believe now it will be more predictable for customer. It is more customizable

feat(otellogs): allow to override all properties within additionalDaemonsets

---

.changelog/3592.changed.txt
deploy/helm/sumologic/conf/setup/main.tf
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

Fixes vulnerabilities reported in v2.27.0 and v2.28.0.

chore: update Sumo Logic Terraform Provider to 2.28.3

---

.changelog/3604.fixed.txt
deploy/helm/sumologic/templates/_helpers/_metrics.tpl
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/debug.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/kubelet.output.yaml

This is to avoid conflict with the operator's default. After the change, we can freely switch between the two without worrying about ownership conflicts. Helm errors if we tell it to manage a resource which already exists and is managed by the operator.
In #3515 we let the operator manage the target allocator's ServiceAccount. Then in #3539, we went back to managing it ourselves, because we needed to attach our own pull secrets to it. This results in an error when upgrading, because Helm refuses to manage a resource which is already managed by the operator, based on standard labels. Changing the name fixes this problem.
Fixes #3588. I'm also going to backport this change to v4.5 and release v4.5.2, as it currently blocks the upgrade for any user with Otel metrics enabled.

fix(metrics): change targetallocator ServiceAccount name

---

.github/pr-title-checker-config.json

The PR title checker currently disallows pr title prefixes used by the backporter bot. Fix this.

ci: allow backport prefix in PR names

---

tests/helm/goldenfile_test.go

This reverts changes in template tests from https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/f6e9329b54adc0865b51bd9bfe7bae1cfe75c75f
regular expression could replace random characters
what seems to happen in https://github.com/SumoLogic/sumologic-kubernetes-collection/actions/runs/8479476276/job/23233572027
```
Diff:
--- Expected
+++ Actual
@@ -27,3 +27,3 @@
(string) (len=11) "annotations": (map[string]interface {}) (len=2) {
-      (string) (len=15) "checksum/config": (string) (len=17) "%CONFIG_CHECKSUM%",
+      (string) (len=15) "checksum/config": (string) (len=82) "cbd6863a1bb9610%CURRENT_CHART_VERSION%0a88dd6a9b21781a5cbbe4c9076848d3d521f672b50a",
```

fix(test): get rid of unsafe regular expression for chart version replacing

---

.changelog/3618.fixed.txt
CHANGELOG.md
deploy/README.md
deploy/helm/sumologic/Chart.yaml
docs/README.md
tests/helm/goldenfile_test.go

- chore: prepare 4.6.1 release
- fix docs: change headers `Deployment Guide for unreleased version` to `Deployment Guide for v4.6`
- backport of #3626

chore: prepare 4.6.1 release

---

.changelog/3633.changed.0.txt
.changelog/3633.changed.1.txt
docs/README.md

chore: drop support for GKE 1.25 and AKS 1.25, 1.26

---

docs/filtering.md

Fixing the surrounding quotes in the documented example of filtering metrics using a k8s namespace.
The current usage of starting the string with backticks instead of single quotes is invalid YAML.

docs(filtering): Fix Documentation for Metrics Filtering

---

.changelog/3641.changed.0.txt
.changelog/3641.changed.1.txt
deploy/helm/sumologic/Chart.yaml
tests/helm/testdata/goldenfile/metrics-server/basic.output.yaml

Worth mentioning: metrics-server and falco can be upgraded to a new major version; opentelemetry-operator has some troubles when upgrading to v0.50.0 that will be solved later

chore: update metrics-server to 6.13.1 and telegraf-operator to 1.4.0

---

ci/check_dependencies/helm_charts.py
deploy/helm/sumologic/Chart.yaml

The dependency checker can't deal with non-pinned versions, so I pinned prometheus-windows-exporter. There isn't any reason not to keep it pinned like the rest of our dependencies, as far as I'm aware.
I've also added Falco to the ignore list, as we can only upgrade it in v5.

ci: fix dependency checker

---

ci/check_dependencies/helm_charts.py

Instead of ignoring upgrades to Falco and metrics-server, only check minor upgrades.

ci: check for minor chart upgrades

---

.changelog/3633.changed.1.txt
.changelog/3653.changed.txt
docs/README.md

#3633 erroneously dropped support for AKS 1.25. As per #3648, I'm restoring it, as it has platform support until June 2024.

chore: restore support for AKS 1.25

---

.github/dependabot.yml

Make dependabot submit K8s package updates in one PR. I've also changed the update cadence to weekly.

chore: make dependabot group k8s package updates

---

.changelog/3671.changed.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md

Can't upgrade any further for now due to https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1065.
Resolves #3655, at least for now.

deps: bump otel-operator to 0.49.0

---

docs/README.md

fluent-bit and fluentd were removed starting with v4.

Remove reference to fluent-bit in the docs

---

.changelog/3715.changed.0.txt
deploy/helm/sumologic/Chart.yaml

v0.46.7 of the fluent-bit helm chart addresses CVE-2024-4323

Upgrade fluent-bit helm chart

---

CHANGELOG.md
README.md

chore: Backport changes from 3.19.1

---

.changelog/3719.changed.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md

chore: upgrade tailing sidecar

chore: upgrade tailing sidecar

---

.changelog/3725.changed.txt
CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

chore: Prepare release v4.7.1

---

CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

(cherry picked from commit 1d42a8bd80ca92a5025a3aff880a1ba027bbf57c)
[Backport main] release v4.7.1 (#3726)

chore: Backport release v4.7.1 (#3726)

---

.changelog/3729.changed.txt
CHANGELOG.md

chore: prepare release v3.19.3

---

.changelog/3738.changed.txt
CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

Prepare v3.19.4 with upgraded otel collector. This is primarily so we can have a v3 release that includes the fix for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32170, which appears to be affecting several customers.

chore: prepare release v3.19.4

---

tests/integration/helm_opentelemetry_operator_enabled_test.go
tests/integration/helm_opentelemetry_operator_instr_test.go
tests/integration/internal/k8s/pods.go
tests/integration/internal/stepfuncs/assess_funcs.go
tests/integration/values/values_helm_opentelemetry_operator_enabled.yaml
tests/integration/values/values_opentelemetry_operator_instrumentation.yaml

Use different namespaces for different instrumentation tests. This makes conflicts less likely when running the tests in the same cluster.

test(integration): use different namespaces for instrumentation tests

---

tests/integration/features.go
tests/integration/internal/stepfuncs/kubectl.go
tests/integration/main_test.go

Namespace deletion can be slow in K8s due to finalizers. This can be a problem for fixed namespaces which are the same for each test that uses them. This change tries to improve this by explicitly disabling finalizers before deleting the namespace.

test(integration): force delete fixed namespaces

---

tests/integration/helm_ot_default_namespaceoverride_test.go

Fix a bug in integration tests where the test for overriding the namespace would register pre-feature handlers that would affect the rest of the tests. The reason this doesn't affect the CI is that it runs each test in a separate cluster. We now check the values.yaml before changing the namespace.

fix(test/integration): only override namespace if needed

---

tests/integration/Makefile
tests/integration/features.go
tests/integration/internal/ctxopts/context_opts.go
tests/integration/main_test.go

We currently create a new cluster for each test by default. This approach becomes a lot more annoying in e2e_framework 0.3.0, which I'd like to upgrade to here: #3741. Instead, use one cluster to run all the tests. Note that this doesn't affect E2E tests - those run each test in a separate job, which also means a separate cluster.
To make running all the tests in a single cluster less flaky, I've also moved log generator namespace creation and deletion to environment setup. Creating and deleting this namespace per-test is annoying, as namespace deletion can take some time in K8s. When running multiple tests in sequence in the same cluster, you sometimes get conflicts from trying to
create the log generator namespace while it's still being deleted.

feat(test/integration): use a single cluster

---

tests/integration/internal/ctxopts/context_opts.go
tests/integration/internal/stepfuncs/helm.go
tests/integration/main_test.go

Instead of storing helm options in the context, we can simply recalculate them from existing context properties. This makes the test setup more explicit.
This will make the upgrade in #3741 easier to do.

test(integration): don't store helm options in context

---

tests/integration/features.go
tests/integration/helm_opentelemetry_operator_enabled_test.go
tests/integration/helm_opentelemetry_operator_instr_test.go
tests/integration/internal/ctxopts/context_opts.go
tests/integration/internal/stepfuncs/assess_funcs.go
tests/integration/internal/stepfuncs/autoscaler.go
tests/integration/internal/stepfuncs/helm.go
tests/integration/internal/stepfuncs/options.go
tests/integration/internal/stepfuncs/traces.go
tests/integration/internal/strings/strings.go
tests/integration/internal/tracesgenerator/tracesgenerator.go

Instead of storing Helm release in context, we calculate it on demand based on the test name. Similar to #3748. Will make #3741 easier.
Calculating the release name requires the test object, and it wasn't passed everywhere it needed to be, so I had to modify some interfaces.

test(integration): don't store helm release in context

---

tests/go.mod
tests/go.sum
tests/integration/internal/ctxopts/context_opts.go
tests/integration/internal/stepfuncs/helm.go
tests/integration/internal/stepfuncs/kubectl.go
tests/integration/main_test.go

Update to [e2e_framework 0.3.0](https://github.com/kubernetes-sigs/e2e-framework/releases/tag/v0.3.0). Changes:
* creating the kind cluster is now a bit different, as it's part of a broader framework of cluster providers
* context is not actually passed between pre-test actions, so all changes need to be made in the final action
I plan to do some more cleanups of the context handling in a follow-up.

deps(test): upgrade e2e-framework to 0.3.0

---

tests/integration/features.go
tests/integration/helm_ot_default_namespaceoverride_test.go
tests/integration/internal/ctxopts/context_opts.go
tests/integration/internal/k8s/pods.go
tests/integration/internal/k8s/tunnel.go
tests/integration/internal/stepfuncs/assess_funcs.go
tests/integration/internal/stepfuncs/autoscaler.go
tests/integration/internal/stepfuncs/debug.go
tests/integration/internal/stepfuncs/helm.go
tests/integration/internal/stepfuncs/kubectl.go
tests/integration/internal/sumologicmock/receiver_mock.go
tests/integration/main_test.go

Instead just create the struct on the fly based on the environment and context. This lets us get rid of a bunch of custom test code, and also makes it easier to run the tests in parallel if need be.

test(integration): don't store kubectl options in context

---

tests/integration/internal/constants.go

I've reviewed all the metrics we test for and marked the ones used in Sumo Apps. Might also be useful to review the application metrics we don't test for, but that can happen in a separate change.

test(integration): mark metrics used by Apps

---

tests/integration/helm_ot_routing_additional_partially_test.go
tests/integration/helm_ot_routing_partial_test.go
tests/integration/helm_ot_routing_test.go

It's not necessary to run these in all K8s versions.

test(integration): only run routing tests on latest K8s

---

deploy/helm/sumologic/conf/cleanup/cleanup.sh
deploy/helm/sumologic/conf/setup/setup.sh
deploy/helm/sumologic/conf/setup/variables.tf
deploy/helm/sumologic/templates/_helpers/_setup.tpl
deploy/helm/sumologic/templates/cleanup/job.yaml
deploy/helm/sumologic/templates/setup/job.yaml
tests/helm/testdata/goldenfile/cleanup/basic.output.yaml
tests/helm/testdata/goldenfile/cleanup/sumologic-mock-no-secret.output.yaml
tests/helm/testdata/goldenfile/cleanup/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/setup/basic.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock-no-secret.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

Collector name was determined slightly differently in the setup/cleanup bash scripts and the Terraform manifests. This PR makes it consistently the same.
I've also moved collector name determination to the Job template. This is part of an effort to eventually do no templating in bash scripts and Terraform manifests. For Terraform, I removed defaults from the variable, and it's now set via a `TF_VAR_` environment variable.

chore(setup): use consistent collector name

---

deploy/helm/sumologic/conf/cleanup/cleanup.sh
deploy/helm/sumologic/conf/setup/fields.tf
deploy/helm/sumologic/conf/setup/resources.tf
deploy/helm/sumologic/conf/setup/setup.sh
deploy/helm/sumologic/conf/setup/terraform.tfvars.json
deploy/helm/sumologic/conf/setup/variables.tf
deploy/helm/sumologic/templates/_helpers/_common.tpl
deploy/helm/sumologic/templates/_helpers/_setup.tpl
deploy/helm/sumologic/templates/cleanup/job.yaml
deploy/helm/sumologic/templates/setup/job.yaml
tests/helm/testdata/goldenfile/cleanup/basic.output.yaml
tests/helm/testdata/goldenfile/cleanup/sumologic-mock-no-secret.output.yaml
tests/helm/testdata/goldenfile/cleanup/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/setup/basic.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock-no-secret.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

Pass these as Terraform variables. Define the values in a `terraform.tfvars.json` file, which Terraform loads automatically.
Collector fields require that we know the Helm Chart version, so pass that in as an environment variable.

chore(setup): pass log fields and collector fields via Terraform variables

---

deploy/helm/sumologic/conf/cleanup/cleanup.sh
deploy/helm/sumologic/conf/setup/resources.tf
deploy/helm/sumologic/conf/setup/setup.sh
deploy/helm/sumologic/conf/setup/variables.tf
deploy/helm/sumologic/templates/_helpers/_setup.tpl
deploy/helm/sumologic/templates/cleanup/job.yaml
deploy/helm/sumologic/templates/setup/job.yaml
tests/helm/testdata/goldenfile/cleanup/basic.output.yaml
tests/helm/testdata/goldenfile/cleanup/sumologic-mock-no-secret.output.yaml
tests/helm/testdata/goldenfile/cleanup/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/setup/basic.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock-no-secret.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

Pass secret name and namespace as variables instead of templating. Namespace we get from downward API, and secret name from a template.

chore(setup): pass secret name and namespace as TF variables

---

deploy/helm/sumologic/conf/cleanup/cleanup.sh
deploy/helm/sumologic/conf/setup/resources.tf
deploy/helm/sumologic/conf/setup/setup.sh
deploy/helm/sumologic/templates/cleanup/configmap.yaml
deploy/helm/sumologic/templates/cleanup/job.yaml
tests/helm/testdata/goldenfile/cleanup/basic.output.yaml
tests/helm/testdata/goldenfile/cleanup/sumologic-mock-no-secret.output.yaml
tests/helm/testdata/goldenfile/cleanup/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

Import using the json file as a reference instead of templating in the bash script. This is the final part of #3761.
Also fixed a bug in cleanup, which was using the wrong Secret name. 
Finally, set an attribute on the generated Secret to align more with Kubernetes defaults.

chore(setup): don't use templating for Terraform imports

---

deploy/helm/sumologic/conf/setup/monitors.sh
deploy/helm/sumologic/conf/setup/setup.sh
deploy/helm/sumologic/templates/cleanup/configmap.yaml
deploy/helm/sumologic/templates/setup/configmap.yaml
deploy/helm/sumologic/templates/setup/job.yaml
tests/helm/testdata/goldenfile/setup/basic.output.yaml
tests/helm/testdata/goldenfile/setup/monitors_with_email_notifications.input.yaml
tests/helm/testdata/goldenfile/setup/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/setup/monitors_with_single_email.input.yaml
tests/helm/testdata/goldenfile/setup/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock-no-secret.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

Remove remaining Helm templates from setup scripts. This mostly involves moving the values to environment variables defined on the Pod template. In the case of notification emails, this required a bit more effort.
The monitors.sh script requires literal double curly braces in a string, so I ended up just disabling templating altogether for *.sh and *.tf files.

chore(setup): remove Helm templates from setup scripts

---

ci/shellcheck.sh
deploy/helm/sumologic/conf/setup/monitors.sh
deploy/helm/sumologic/conf/setup/setup.sh
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

After removing Helm templating from setup and cleanup scripts in #3769, we can run shellcheck on them directly. This PR also fixes all the warnings.

ci: run shellcheck directly on scripts

---

.github/workflows/sync-repositories.yaml

Disable auto sync, as we got some complains from docker team about it

chore: disable auto-sync for repositories

---

.github/workflows/sync-repository.yaml
ci/sync-repository.sh

Add workflow to sync single repository. The load on docker will be less, and also I am going to use it to perform more optimisation if needed (without running the job for all repos)

feat: add workflow to sync single repository

---

deploy/helm/sumologic/conf/setup/setup.sh
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

Bash arrays are hard. #3770 introduced a bug where an array wasn't parsed correctly.

fix(setup): importing log fields

---

.changelog/3777.changed.txt
deploy/helm/sumologic/Chart.yaml
deploy/helm/sumologic/values.yaml
docs/README.md

This is the last version before changes to CRD handling that will require changes on our end as well.

deps: upgrade opentelemetry-operator Chart to 0.56.1

---

.changelog/3784.fixed.txt
deploy/helm/sumologic/conf/logs/collector/common/filelog_receiver.yaml
deploy/helm/sumologic/conf/logs/collector/otelcloudwatch/config.yaml
tests/helm/testdata/goldenfile/logs_otc/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc/debug.output.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/multiple_multiline.output.yaml
tests/helm/testdata/goldenfile/logs_otc_windows/configmap/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc_windows/configmap/debug.output.yaml
tests/helm/testdata/goldenfile/logs_otc_windows/daemonset/multiple_multiline.output.yaml

We are using `is_last_entry` and `max_unmatched_batch_size=1` which means we are sending all lines separately until `is_last_entry` matches. If we have multipart log on the beginning of file we will send every part separately.
Here is minimal reproduction:
log file:
```
2021-02-16T09:21:15.518430714Z stdout P a
2021-02-16T09:21:15.518430714Z stdout P b
2021-02-16T09:21:15.518430714Z stdout F c
```
config.yaml
```
exporters:
debug:
verbosity: detailed
receivers:
filelog/containers:
include:
- logs/0.log
start_at: beginning
include_file_name: false
include_file_path: true
operators:
- id: parser-containerd
output: merge-cri-lines
parse_to: body
regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*)( |)(?P<log>.*)$
timestamp:
layout: "%Y-%m-%dT%H:%M:%S.%LZ"
parse_from: …
```

fix: join multiparts on file beginning

---

tests/helm/goldenfile_test.go

This change finds a new method using regex for updating the helm chart version without affecting any other version that matches it
Find the [Ticket](https://sumologic.atlassian.net/browse/OSC-665)

fix: Better method to detect helm chart version in template tests

---

.changelog/3803.changed.txt
deploy/helm/sumologic/templates/logs/collector/common/serviceaccount.yaml
deploy/helm/sumologic/templates/metrics/collector/otelcol/serviceaccount-targetallocator.yaml
deploy/helm/sumologic/templates/metrics/collector/otelcol/serviceaccount.yaml
tests/helm/common_test.go
tests/helm/const.go
tests/helm/testdata/custom-global-config-attributes.yaml

- github issue: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/2699
- added annotations test SPECIFICALLY for service account in global configs
1 more to go:
```
sumologic.pullSecrets
```

test(integration): Added custom service account annotations test

---

.changelog/3804.changed.1.txt
.changelog/3804.changed.2.txt
.changelog/3804.changed.3.txt
.changelog/3804.changed.4.txt
.changelog/3804.changed.5.txt
docs/README.md

github issue: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/3799
jira: https://sumologic.atlassian.net/browse/OSC-828

feat: Add support for kubernetes 1.30 EKS, KOPS, GKE, AKS and 4.16 OpenShift

---

.changelog/3808.changed.txt
deploy/helm/sumologic/values.yaml
docs/working-with-container-registries.md
tests/helm/common_test.go
tests/helm/const.go
tests/helm/testdata/custom-global-config-attributes.yaml

- github issue: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/2699
- added image pull secrets test

test(integration): Added custom image pull secrets test

---

deploy/helm/sumologic/templates/_helpers/_common.tpl
deploy/helm/sumologic/templates/setup/job.yaml
tests/helm/testdata/goldenfile/setup/basic.output.yaml
tests/helm/testdata/goldenfile/setup/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/setup/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock-no-secret.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock.output.yaml

[OSC-832] Add labels to setup Pods for easy logs collection
[OSC-832]: https://sumologic.atlassian.net/browse/OSC-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add labels to setup Pods for easy logs collection

---

.changelog/3804.changed.2.txt
docs/README.md

- Removed KOPs 1.30, not supported yet
- not adding new changelog, just removed old one
- merging this once e2e pr merged

chore: Removed KOPs 1.30, not supported yet

---

.changelog/3856.changed.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md

chore: upgrade tailing-sidecar to v0.16.0

chore: upgrade tailing-sidecar to v0.16.0

---

CHANGELOG.md
deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc_statefulset/basic.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc_statefulset/custom.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc_statefulset/basic.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc_statefulset/custom.output.yaml

Add the `whenDeleted` option to the PVC retention policy. This addition is to ensure consistency. When the policy is enabled both options must be configured or none. This change ensures that is the case and is not a breaking change.
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention

feat: Add the whenDeleted option to the PVC retention policy

---

.changelog/3913.changed.txt
deploy/helm/sumologic/templates/metrics/collector/otelcol/targetallocator-clusterrole.yaml

Allow the target allocator access to probes and scrapeconfigs in the coreos apiGroups

fix(TA): Allow the target allocator access to probes and scrapeconfigs in the coreos apiGroups

---

.changelog/3927.fixed.txt
deploy/helm/sumologic/templates/metrics/collector/otelcol/opentelemetrycollector.yaml
deploy/helm/sumologic/values.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/debug.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/kubelet.output.yaml

Add the default release label for serviceMonitorSelectors and PodMonitorSelectors

fix: Add the default release label for serviceMonitorSelectors and PodMonitorSelectors

---

.changelog/3930.fixed.txt
deploy/helm/sumologic/conf/cleanup/cleanup.sh

cleanup.sh can complain that `SUMOLOGIC_BASE_URL` is unbound. It attempts to modify the URL so that it does not contain a v1.
This seems like some sort of hack that should have been cleaned up. I don't think we should be doing this, so I am removing references to `SUMOLOGIC_BASE_URL` in this script.
Closes #3867

fix: do not modify SUMOLOGIC_BASE_URL in cleanup.sh

---

.markdown_link_check.json

Fix the link linter by not following Stack Overflow links. Stack Overflow is issuing 403 to crawlers and seems to consider Github Actions as one of them.

chore: fix link linter

---

.changelog/3985.fixed.txt
.github/workflows/pull_requests.yml
.github/workflows/workflow-integration-tests.yaml
.prettierignore
.yamllint.yaml
deploy/helm/sumologic/Chart.yaml
deploy/helm/sumologic/crds/crd-opentelemetry.io_targetallocators.yaml

This PR upgrades opentelemetry-operator to v0.93.0. This resolves an incompatibility with helm versions > 3.18.4.
The TargetAllocator type has been moved into its own CRD, so it has been added as well.
As a result of upgrading to opentelemetry-operator v0.93.0, we can revert the workaround we had to add in CI that downgrades helm.

chore: upgrade opentelemetry-operator

---

.changelog/3997.changed.txt
.gitignore
docs/README.md

Update the k8s version support matrix.
**Jenkins tests**
EKS:1.33.0 - https://ct-jenkins.kumoroku.com/view/All%20Dev%20Jobs/job/dev-sumo-platform-test-k8s-collection/2533/
EKS Fargate:1.32.0 - https://ct-jenkins.kumoroku.com/view/All%20Dev%20Jobs/job/dev-sumo-platform-test-k8s-collection/2530/
EKS Fargate:1.33.0 - https://ct-jenkins.kumoroku.com/view/All%20Dev%20Jobs/job/dev-sumo-platform-test-k8s-collection/2531/
AKS:1.32.0 - https://ct-jenkins.kumoroku.com/view/All%20Dev%20Jobs/job/dev-sumo-platform-test-k8s-collection/2529/
AKS:1.33.0 - https://ct-jenkins.kumoroku.com/view/All%20Dev%20Jobs/job/dev-sumo-platform-test-k8s-collection/2527/
GKE: 1.33.0 - https://ct-jenkins.kumoroku.com/view/All%20Dev%20Jobs/job/dev-sumo-platform-test-k8s-collection/2526/
Updated older version based on …

chore: Update the K8s version support matrix
