SumoLogic/sumologic-kubernetes-collection

ci/markdown_links_lint.sh

test: fix links linter

---

deploy/helm/sumologic/Chart.yaml

Prepare v2.1.1

---

deploy/README.md
deploy/docs/Security_Best_Practices.md

Add Security Best Practices doc
Closes #1470 
---

Add Security Best Practices doc

---

deploy/docs/SideBySidePrometheus.md
deploy/docs/existingPrometheusDoc.md
deploy/docs/standAlonePrometheus.md

mention `prometheusInstanceNamespace`s in documentation for openshift

docs: mention prometheusInstanceNamespaces in documentation

---

deploy/docs/Best_Practices.md
deploy/helm/sumologic/README.md
deploy/helm/sumologic/values.yaml
tests/upgrade_v2_script/static/metrics_server.input.yaml

docs: fix links to helm subcharts

---

deploy/docs/Troubleshoot_Collection.md

add missing header for gzip compression issue
---

docs: add missing header for gzip compression issue

---

deploy/docs/Troubleshoot_Collection.md

fix documentation for gzip compression issue
---

fix documentation for gzip compression issue

---

vagrant/Makefile
vagrant/dashboards/performance.json
vagrant/scripts/generate-local-config.sh

fix generate-local-config to env agnostic 
vagrant: fix grafana dashboard
---

Minor vagrant improvements

---

deploy/docs/Best_Practices.md

docs: add section about getting logs not available on stdout

---

deploy/README.md

Manual backport of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1610
---

SUMO-165923 Updating the versions of kubernetes clusters (#1610)

---

deploy/helm/sumologic/README.md
deploy/helm/sumologic/templates/setup/setup-serviceaccount.yaml
deploy/helm/sumologic/values.yaml

Add pullSecrets to setup job (#1616)

---

deploy/helm/sumologic/Chart.yaml

Prepare v2.1.2-rc.0

---

vagrant/Makefile
vagrant/k8s/logs-generator.yaml

Add logs generator to vagrant

---

.yamllint.yaml
deploy/helm/sumologic/values.yaml

ci: enforce yamllint checks

---

deploy/helm/sumologic/values.yaml

Fix regex typo from https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1632/files
---

fix: regex typo

---

.github/CODEOWNERS

Use @SumoLogic/open-source-collection-team for CODEOWNERS
---

fix(github): fix CODEOWNERS

---

deploy/helm/sumologic/Chart.yaml

Prepare v2.1.2-rc.1

---

deploy/helm/sumologic/Chart.yaml

Prepare v2.1.2

---

.github/workflows/check_pr_labels.yaml
.github/workflows/pr_milestone_check.yaml

* use https://github.com/siimon/milestone-check-action for milestone checks
* https://github.com/mheap/github-action-required-labels for labels checks
---

feat(ci): tweak do not hold label checker and add pr milestone checker

---

deploy/docs/Installation_with_Helm.md

docs: replace information about DockerHub with information about Amazon Public ECR

---

deploy/README.md

doc: add links for different documentation versions to doc starting page

---

deploy/helm/sumologic/Chart.yaml

chore: bump version and appVersion in Chart.yaml

---

deploy/README.md

[Backport release-v1.3] doc: add links for different documentation versions to doc starting page

---

deploy/README.md

[Backport release-v0.17] doc: add links for different documentation versions to doc starting page

---

deploy/README.md

docs: add container log parsing doc to main readme

---

.github/labeler.yml
.github/workflows/pr_labeler.yaml

Add https://github.com/actions/labeler

feat(ci): add pr labeler

---

deploy/helm/sumologic/Chart.yaml

changes:
- Container image for kube-rbac-proxy configurable in Helm Chart
---

chore: upgrade Tailing Sidecar Operator to v0.3.1

---

deploy/helm/sumologic/Chart.yaml

Changes: https://github.com/SumoLogic/sumologic-kubernetes-collection/compare/v2.1.2...release-v2.1
---

Prepare v2.1.3-rc.0

---

deploy/helm/sumologic/Chart.yaml

Changes: https://github.com/SumoLogic/sumologic-kubernetes-collection/compare/v2.1.2...v2.1.3-rc.0
---

Prepare v2.1.3

---

deploy/helm/sumologic/values.yaml

Cherry-pick nginx plus change 574fcb5dd9d912393ef148b208b5bbce65b1ce5d

feat: add nginx plus to prometheus remote write (#1656)

---

deploy/helm/sumologic/Chart.yaml

Prepare v2.1.4

---

README.md

feat: end support for 1.3

---

deploy/helm/sumologic/Chart.yaml

Changes since `2.1.4` https://github.com/SumoLogic/sumologic-kubernetes-collection/compare/v2.1.4...release-v2.1?expand=1

Prepare v2.1.5-rc.0

---

deploy/helm/sumologic/Chart.yaml

Prepare v2.1.5

---

deploy/helm/sumologic/values.yaml

doc: remove comment about telegraf-operator being experimental

---

deploy/docs/Additional_Fluentd_Plugins.md
deploy/docs/Best_Practices.md

docs: Describe using Alpine-based Fluentd image

---

deploy/helm/sumologic/README.md
deploy/helm/sumologic/templates/cleanup/cleanup-serviceaccount.yaml
deploy/helm/sumologic/templates/serviceaccount.yaml
deploy/helm/sumologic/templates/setup/setup-serviceaccount.yaml
deploy/helm/sumologic/values.yaml

feat(helm): add sumologic.serviceAccount.annotations so custom annotation cen be added

---

deploy/docs/Terraform.md
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/values.yaml
tests/terraform/static/all_fields.output.yaml
tests/terraform/static/collector_fields.output.yaml
tests/terraform/static/default.output.yaml
tests/terraform/static/disable_default_metrics.output.yaml
tests/terraform/static/strip_extrapolation.output.yaml

Reverts SumoLogic/sumologic-kubernetes-collection#1371

Revert "Remove duplicated collector source category from configuration"

---

deploy/README.md

docs: update k8s support matrix

---

deploy/README.md

chore(docs): update helm version

---

deploy/helm/sumologic/values.yaml

- fix links to documentation
- adjust to changes in configuration for Source Processor
---

chore: Upgrade sumologic-otel-collector from 0.0.18 to 0.0.23-beta.0

---

deploy/helm/sumologic/values.yaml

feat(otelcol): enable sending queue and improve overall metrics performance due to e2e test
---

feat(otelcol): enable sending queue and improve overall metrics performance due to e2e test

---

deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/values.yaml

Set of fixes based on e2e tests findings 

---

deploy/docs/Installation_with_Helm.md
deploy/docs/Non_Helm_Installation.md

improve documentation for installation on OpenShift
---

docs: improve documentation for installation on OpenShift

---

deploy/helm/sumologic/values.yaml

fix(deploy,otelcol): fix labels and annotation configuration

---

.markdownlint.jsonc
CHANGELOG.md
Makefile

Add a changelog so that we can use notes added there whenever we release.
Based on https://keepachangelog.com/en/1.0.0/

doc: add changelog

---

deploy/docs/opentelemetry_collector.md

docs: init opentelemetry documentation

---

deploy/helm/sumologic/values.yaml

fix(otelcol/logs): avoid sending metadata attributes in json body

---

deploy/docs/fluentd_otc_comparison.md

docs(fluentd_otc_comparison): init document which compares fluentd and otelcol

---

deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/traces/otelcol/deployment.yaml

feat(helm/otelcol): respect otelcol.metrics.enabled by logs and metrics

---

deploy/helm/sumologic/values.yaml

feat(deploy/ottelcol/logs): expose json_logs for json format

---

deploy/helm/sumologic/values.yaml

See change log at https://github.com/SumoLogic/sumologic-kubernetes-fluentd/releases.

fix(deps): upgrade Fluentd to 1.12.2-sumo-6

---

deploy/helm/sumologic/README.md
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/values.yaml

 feat: Add fullnameOverride chart parameter

---

deploy/helm/sumologic/Chart.yaml
tests/metadata_logs_otc/static/templates.output.yaml
tests/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/metadata_metrics_otc_statefulset/static/basic.output.yaml

Changes between v2.2.0-rc.0 and v2.2.0.rc.1: https://github.com/SumoLogic/sumologic-kubernetes-collection/compare/39cffc4a817179ed56e152e4f0ab88034f4a5bb2...310e4ea4df6c4735ebd518427595de7f44c48cd9
---

Prepare v2.2.0-rc.1

---

CHANGELOG.md
deploy/helm/sumologic/Chart.yaml
tests/metadata_logs_otc/static/templates.output.yaml
tests/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/metadata_metrics_otc_statefulset/static/basic.output.yaml

Changes: https://github.com/SumoLogic/sumologic-kubernetes-collection/compare/v2.1.7...v2.2.0-rc.1
---

Prepare v2.2.0

---

README.md

Update support links for v2.2

---

ci/push-helm-chart.sh

Change this to fix an incompatibility with e2e tests.
---

ci: increase hash length in dev version names

---

deploy/README.md
deploy/docs/Migration_Steps.md
deploy/docs/fluentd_otc_comparison.md

This is an attempt to make links to our docs more discoverable and more organized.

docs: reorder deploy readme

---

.github/workflows/dev_builds.yml

ci: allow silent dev builds on 'dev-build/' branches

---

.github/CODEOWNERS

ci(codeowners): use team name only

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

Rel: https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.0.42-beta.0

chore(deps): bump Sumo OT distro to 0.0.42-beta.0

---

.github/pull_request_template.md

I'm annoyed at always forgetting to update the changelog, so here's a small reminder. Ideally, we'd have tooling to check this in the CI, but this is easy to do and should help a fair bit.

Add changelog update item to PR checklist

---

deploy/README.md

update support matrix - add OpenShift 4.8

docs: update support matrix - add OpenShift 4.8

---

CHANGELOG.md

chore: changelog update with information about the API Server calls reduction

---

deploy/helm/sumologic/Chart.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

Prepare v2.3.0-rc.0

---

ci/_build_functions.sh

Bugfix for #1853 which caused #1898 to fail.
tl;dr let's make sure a loop cleans up after it's run
---

ci: bugfix for release builds not being published in helm repo

---

ci/_build_functions.sh

ci: bugfix for exit on empty stash

---

deploy/helm/sumologic/Chart.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

Prepare v2.3.0-rc.1

---

CHANGELOG.md
deploy/helm/sumologic/templates/_api_versions_helpers.tpl

See https://github.com/argoproj/argo-cd/issues/7291

fix: work around API versions issue when deploying with ArgoCD

---

deploy/helm/sumologic/values.yaml

Comment change in values.yaml - tracing is not experimental anymore
---

docs: comment change in values.yaml - tracing is not experimental anymore

---

CHANGELOG.md
README.md
deploy/README.md
deploy/helm/sumologic/Chart.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

Prepare release v2.3.0

---

CHANGELOG.md

docs: clean up changelog for v2.3 from the unreleased section

---

deploy/helm/sumologic/Chart.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

Prepare v2.4.0-alpha.1

---

deploy/docs/Troubleshoot_Collection.md

Related to https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1807.

docs: add troubleshooting Prometheus init containers

---

CHANGELOG.md

chore: enable all links checks in CHANGELOG

---

CHANGELOG.md
deploy/helm/sumologic/Chart.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

chore: prepare release v2.3.1

---

CHANGELOG.md

fix: broken link to PR in changelog for v2.3.1

---

CHANGELOG.md

Partial backport of 21a67f33ecc10220915a7e09270fa09bf126c15e from #1978

docs: add the v2.3.1 release to CHANGELOG

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

Related release: https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.0.43-beta.0

chore(deps): bump Sumo OT distro to 0.0.43-beta.0

---

CHANGELOG.md
deploy/helm/sumologic/templates/clusterrole.yaml

fix(helm): add job and cronjob to clusterrole's permission set

---

vagrant/provision.sh

chore(vagrant): add Go and Kind to vagrant environment

chore(vagrant): add Go and Kind to vagrant environment

---

deploy/helm/sumologic/values.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

Related release: https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.0.45-beta.0

chore(deps): bump Sumo OT distro to 0.0.45-beta.0

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

The new version only includes tool security updates: https://github.com/SumoLogic/sumologic-kubernetes-setup/releases/tag/v3.2.0.
---

chore: update setup image to 3.2.0

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

Related release: https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.0.46-beta.0

chore(deps): bump Sumo OT distro to 0.0.46-beta.0

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

related release: https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.0.47-beta.0

chore: bump sumo ot distro to 0.0.47-beta.0

---

CHANGELOG.md
README.md
deploy/README.md
deploy/helm/sumologic/Chart.yaml

Prepare v2.4.0

---

CHANGELOG.md

docs: update changelog for v2.4.0

---

README.md
deploy/README.md

[Backport release-v0.17] docs: keep versions information in one place

---

README.md
deploy/README.md

[Backport release-v2.3] docs: keep versions information in one place

---

README.md
deploy/README.md

[Backport release-v2.2] docs: keep versions information in one place

---

README.md
deploy/README.md

[Backport release-v2.1] docs: keep versions information in one place

---

README.md
deploy/README.md

[Backport release-v1.3] docs: keep versions information in one place

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

Related release: https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.0.48-beta.0

chore: bump sumo ot distro to 0.0.48-beta.0

---

vagrant/scripts/get-kubeconfig.sh

fix(vagrant): update ip for get-kubeconfig script

fix(vagrant): update ip for get-kubeconfig script

---

deploy/docs/Security_Best_Practices.md
deploy/helm/sumologic/values.yaml

Document what capabilities collection requires to function for each data type and how some of the default permissions may be restricted.
---

docs: document required capabilities

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

Manual backport of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2063

chore: bump setup image to 3.2.1

---

.gitignore
.vscode/snippets.code-snippets

I find this snippet useful for adding links to pull requests in Changelog.
What do you think, can we add the file to the repo?

style: add VS Code snippet for PR link

---

CHANGELOG.md
deploy/README.md

docs(readme): add support for AKS 1.22

---

CHANGELOG.md

changelog update for #2085 
---

docs(changelog): update

---

CHANGELOG.md
deploy/README.md

docs(readme): add support for KOPS 1.22

---

deploy/helm/sumologic/conf/setup/setup.sh
tests/helm/terraform/static/all_fields.output.yaml
tests/helm/terraform/static/collector_fields.output.yaml
tests/helm/terraform/static/conditional_sources.output.yaml
tests/helm/terraform/static/custom.output.yaml
tests/helm/terraform/static/default.output.yaml
tests/helm/terraform/static/disable_default_metrics.output.yaml
tests/helm/terraform/static/strip_extrapolation.output.yaml
tests/helm/terraform/static/traces.output.yaml

Exemplar logs that will be spewed out additionally to what's already printed:
```
2022-01-06T19:20:05.213Z [INFO]  provider: configuring client automatic mTLS
2022-01-06T19:20:05.223Z [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hashicorp/kubernetes/1.13.4/linux_amd64/terraform-provider-kubernetes_v1.13.4_x4 args=[.terraform/providers/registry.terraform.io/hashicorp/kubernetes/1.13.4/linux_amd64/terraform-provider-kubernetes_v1.13.4_x4]
2022-01-06T19:20:05.223Z [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/hashicorp/kubernetes/1.13.4/linux_amd64/terraform-provider-kubernetes_v1.13.4_x4 pid=1296
2022-01-06T19:20:05.223Z [DEBUG] provider: waiting for RPC address: …
```

chore: enable debug logs for terraform providers in setup job

---

deploy/docs/Installation_with_Helm.md
deploy/docs/Non_Helm_Installation.md
deploy/docs/SideBySidePrometheus.md
deploy/docs/existingPrometheusDoc.md
deploy/docs/standAlonePrometheus.md

New version of Markdownlint introduced new checks.
https://github.com/igorshubovych/markdownlint-cli/releases/tag/v0.31.0

chore: fix Markdownlint issues

---

deploy/docs/Best_Practices.md
deploy/docs/monitoring-lag.md

docs: small addition around fluentd vs hpa vs data ingestion delay

---

CHANGELOG.md

related PR: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2127

docs(changelog): add entry about bump sumo ot distro to 0.0.50-beta.0

---

deploy/docs/Best_Practices.md
deploy/docs/fluentd_otc_comparison.md

Compile queue and batching knowledge into short section in Best Practices
---

docs(best_practices): add otc queueing and batching

---

deploy/docs/Best_Practices.md

docs(best_practices): add queueing to ToC

---

deploy/helm/sumologic/values.yaml

Supplement for commit f3e06e4c from PR #2113

fix: add couchbase to Telegraf configuration for OTC

---

deploy/docs/Best_Practices.md

add any dimension exclusion for fluentd
---

docs(best_practices): add dimension exclusion for fluentd

---

vagrant/values.yaml

fix(vagrant): fix indentation for fluent-bit config
---

fix(vagrant): fix indentation for fluent-bit config

---

CHANGELOG.md
deploy/docs/Best_Practices.md

Remove unnecessary attribute
---

docs(best_practices): remove k8s_uid for /var/log/pods

---

deploy/helm/sumologic/values.yaml

docs(values): fix comments format

---

deploy/helm/sumologic/Chart.yaml

chore: prepare release 2.6.0-rc.0

---

deploy/docs/Best_Practices.md

docs(best_practices): fix ToC

---

tests/integration/README.md
tests/integration/helm_fluentbit_containerd_multiline_logs_test.go
tests/integration/internal/constants.go
tests/integration/values/values_helm_fluentbit_containerd_multiline_logs.yaml
tests/integration/yamls/multiline-logs-generator.yaml

test(integration): add test for multiline logs in containerd log format
---
- run `make test TEST_NAME="Test_Helm_FluentBit_Containerd_Multiline_Logs"`

test(integration): add test for multiline logs in containerd log format

---

.github/pull_request_template.md

chore(pr_template): comment info for pr author

---

deploy/docs/Troubleshoot_Collection.md

Add prometheus config verification step

docs(troubleshooting): add prometheus config verification step

---

CHANGELOG.md
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc/static/basic.output.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

The performance cost of this extension is negligible, and it really helps with live profiling and debugging.
---

feat: add pprof extension for otelcol

---

deploy/README.md

fix: add release version to the documentation title

---

CHANGELOG.md

https://help.sumologic.com/Traces/Getting_Started_with_Transaction_Tracing/What_if_I_don't_want_to_send_all_the_tracing_data_to_Sumo_Logic%3F seems to redirect to https://help.sumologic.com/Traces/03Advanced_Configuration/What_if_I_don't_want_to_send_all_the_tracing_data_to_Sumo_Logic%3F anyway and it's causing issues when checking link for validity.

chore(docs): fix changelog link

---

CHANGELOG.md
deploy/docs/Best_Practices.md
deploy/docs/fluentd_otc_comparison.md
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

Bump otelcol to https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.47.0-sumo-0

chore: bump otelcol-sumo to the officially supported version v0.47.0-sumo-0

---

vagrant/README.md

Unsufficient VirtualBox priviledges
---

docs: Update README.md

---

CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare v2.7.0 release

---

CHANGELOG.md
deploy/docs/Best_Practices.md
deploy/docs/FluentdPersistence.md

Make it clear that the FluentD buffer size needs to be increased alongside the volume size.
---

docs: FluentD buffer size configuration

---

Makefile

add vagrant targets to main Makefile
---

chore(makefile): add vagrant related commands to makefile

---

deploy/README.md

docs(README): fix deploy title

---

.github/workflows/pull_requests.yml
ci/shellcheck.sh
deploy/helm/sumologic/conf/setup/setup.sh
tests/helm/terraform/static/all_fields.output.yaml
tests/helm/terraform/static/collector_fields.output.yaml
tests/helm/terraform/static/conditional_sources.output.yaml
tests/helm/terraform/static/custom.input.yaml
tests/helm/terraform/static/custom.output.yaml
tests/helm/terraform/static/default.output.yaml
tests/helm/terraform/static/disable_default_metrics.output.yaml
tests/helm/terraform/static/strip_extrapolation.output.yaml
tests/helm/terraform/static/traces.output.yaml
tests/helm/terraform_custom/static/custom.input.yaml
tests/helm/terraform_custom/static/custom.output.yaml

Run shellcheck against rendered `setup.sh` and `custom_setup.sh`
Fixes: #2248
---

chore(shellcheck): validate generated setup shell files

---

CHANGELOG.md
deploy/helm/sumologic/templates/cleanup/job.yaml
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/values.yaml
examples/multiline_logs/pod_multiline_long_lines.yaml
examples/multiline_logs/pod_multiline_single_long_line.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml
tests/integration/yamls/multiline-logs-generator.yaml

We should use the ECR image to avoid Dockerhub rate limiting.
---

fix: switch to ECR for the busybox image

---

deploy/docs/opentelemetry_collector.md

Add documentation how to use Opentelemetry Collector in order to scrape container logs
---

docs(otellogs): document how to use otellogs

---

deploy/docs/Best_Practices.md

Add `Modifying logs in Fluentd` which describes how to redact logs and kubernetes metadata
---

docs(best_practices): add instruction how to redact sensitive data

---

deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/logs/collector/otelcol/configmap.yaml
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/templates/logs/collector/otelcol/service.yaml
deploy/helm/sumologic/templates/logs/collector/otelcol/serviceaccount.yaml
deploy/helm/sumologic/templates/logs/common/service.yaml
deploy/helm/sumologic/templates/metrics/common/service.yaml
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc_daemonset/static/basic.output.yaml

- feat: do not expose fluentd metric port for otelcol
- refactor(otellogs): adjust names to internal convention
- feat(otellogs): scrape metrics from otellogs
---

feat(otellogs): scrape metrics from otellogs

---

deploy/helm/sumologic/Chart.yaml

chore(release): prepare 2.8.0-rc.0

---

CHANGELOG.md
deploy/helm/sumologic/templates/metrics/remote-write-proxy/deployment.yaml
deploy/helm/sumologic/templates/traces/otel-agent/daemonset.yaml
deploy/helm/sumologic/templates/traces/otel-gateway/deployment.yaml
deploy/helm/sumologic/templates/traces/otelcol/deployment.yaml
tests/helm/remote_write_proxy/static/full_config.input.yaml
tests/helm/remote_write_proxy/static/full_config.output.yaml

fix(templates): fix templates indentation

---

CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release v2.8.0

---

deploy/docs/Troubleshoot_Collection.md

mitigate logs duplication in fluentd
---

docs: mitigate logs duplication in fluentd

---

CHANGELOG.md

I accidentally added the changelog entry for #2287 to v2.8.0 instead of the unreleased section.

docs(changelog): fix invalid entry for #2287

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

[Backport release-v2.3] chore(deps): upgrade fluentd to 1.14.6-sumo-3

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

[Backport release-v2.6]chore(deps): upgrade fluentd to 1.14.6-sumo-3

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

[Backport release-v2.7] chore(deps): upgrade fluentd to 1.14.6-sumo-3

---

deploy/docs/Best_Practices.md
deploy/docs/Troubleshoot_Collection.md

Add split big chunks to best practices
---

docs(best_practices): add info about splitting big chunks

---

deploy/helm/sumologic/Chart.yaml

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v2.8/CHANGELOG.md#v282

chore: prepare release v2.8.2

---

deploy/helm/sumologic/Chart.yaml

Changelog: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v2.7/CHANGELOG.md#v273

chore: prepare release v2.7.3

---

deploy/helm/sumologic/Chart.yaml

Changelog: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v2.5/CHANGELOG.md#v254

chore: prepare release v2.5.4

---

deploy/helm/sumologic/Chart.yaml

Changelog: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v2.4/CHANGELOG.md#v243

chore: prepare release v2.4.3

---

deploy/helm/sumologic/Chart.yaml

Changelog: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/release-v2.2/CHANGELOG.md#v222---2022-06-02

chore: prepare release v2.2.2

---

README.md

docs: remove support for v2.2

---

deploy/docs/Best_Practices.md
deploy/docs/Troubleshoot_Collection.md
deploy/helm/sumologic/values.yaml

Start multiline log detection section in troubleshoot_collection
---

docs(troubleshoot_collection): add text format multiline log detection issue

---

deploy/docs/support.md

Add customer issues playbook to this repo
---

docs: add support document

---

deploy/helm/sumologic/templates/opentelemetry-operator/instrumentation-cr.yaml
tests/helm/opentelemetry_operator_instrumentation_cr/static/instrumentation.output.yaml

Remove xray propagator - missing in the instrumentation img
---

Remove xray propagator - missing in the instrumentation img

---

tests/integration/helm_otc_fips_metadata_installation_test.go
tests/integration/values/values_helm_default_ot_fips_metadata.yaml

the same tests as in `Test_Helm_Default_OT_Metadata`

test(integration): add tests for otelcol FIPS images

---

CHANGELOG.md
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc_daemonset/static/complex.input.yaml
tests/helm/logs_otc_daemonset/static/complex.output.yaml

This is set of changes required in order to test https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2364
---

feat(otellogs): add additional volumes and env configs

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

feat(metadata): upgrade otelcol to v0.54.0-sumo-0
---

feat(metadata): upgrade otelcol to v0.54.0-sumo-0

---

deploy/helm/sumologic/templates/traces/otel-gateway/deployment.yaml
deploy/helm/sumologic/values.yaml

PR adds possibility to configure number of OTelGateway replicas.
---

chore(otelgw): add possibility to configure replicas

---

CHANGELOG.md

docs(changelog): fix

---

deploy/docs/v3_migration_doc.md

docs: bootstrap migration document
---

docs: bootstrap migration document

---

CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

prepared release according to: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/docs/release.md

feat: prepare release v2.13.0

---

CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

Prepare v2.14.0

---

CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

backport of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2459

chore: update Tailing Sidecar Operator subchart to 0.3.3

---

CHANGELOG.md
ci/_build_functions.sh
deploy/docs/Kube-Prometheus.md
deploy/docs/Non_Helm_Installation.md
deploy/docs/additional_prometheus_configuration.md
deploy/docs/standAlonePrometheus.md
deploy/docs/v2_migration_doc.md
tests/helm/functions.sh
tests/integration/internal/constants.go
tests/integration/yamls/receiver-mock.yaml
vagrant/k8s/istio-receiver-mock.yaml
vagrant/k8s/logs-generator.yaml
vagrant/k8s/receiver-mock.yaml

This PR bumps the version of kubernetes-tools to v2.12.0
---

chore: update kubernetes-tools to 2.12.0

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/logs_otc/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/basic.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml

feat: enable compaction for OT storage

---

tests/integration/internal/receivermock/receiver_mock.go

Ref: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/698143e963a5c828c5b7c4a08d2a0fc209fab438/tests/integration/internal/receivermock/receiver_mock.go#L136-L142

refactor(tests/integration): extract function for parsing url

---

CHANGELOG.md
README.md
deploy/docs/release.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release v2.15.0

---

CHANGELOG.md

Add unreleased section to changelog 
---

chore(changelog): update

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

fix(logs): prevent Fluent Bit from doing metadata enrichment

---

.github/workflows/dev_builds.yml
.github/workflows/pull_requests.yml
deploy/docs/release.md

chore: enable actions on release-vx branches

---

CHANGELOG.md
ci/jsonnet-mixin.tmpl
deploy/docs/Best_Practices.md
deploy/docs/Kube-Prometheus.md
deploy/docs/Performance.md
deploy/docs/additional_prometheus_configuration.md
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/values.yaml
examples/kube_prometheus_stack/values-prometheus.yaml
tests/helm/logs_otc/static/basic.output.yaml
tests/helm/logs_otc/static/options.output.yaml
tests/helm/logs_otc/static/override.output.yaml
vagrant/scripts/perf-test.sh
vagrant/scripts/yq/update_remote_write_for_avalanche.yaml

Backport #2502 to release-v2
---

backport: feat: add dot suffix to internal dns addresses

---

deploy/docs/Non_Helm_Installation.md

docs(openshift): add missing parameter for non-helm installation

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml
tests/helm/metadata_logs_otc_statefulset/static/basic.output.yaml
tests/helm/metadata_metrics_otc_statefulset/static/basic.output.yaml

feat(metadata): upgrade otelcol to v0.57.2-sumo-1

---

CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release v2.17.0

---

CHANGELOG.md

chore(changelog): add release v2.17.0

---

deploy/docs/Best_Practices.md

docs: parsing json content by fluentd

---

tests/integration/internal/k8s/pods.go
tests/integration/internal/stepfuncs/helm.go

Hopefully this will help random integration test failures.

test(integration): add more debug info for Helm install failures

---

CHANGELOG.md
deploy/helm/sumologic/conf/metrics/remote-write-proxy/remote-write-proxy.conf
deploy/helm/sumologic/templates/metrics/remote-write-proxy/deployment.yaml
deploy/helm/sumologic/templates/metrics/remote-write-proxy/service.yaml
deploy/helm/sumologic/values.yaml
tests/helm/remote_write_proxy/static/basic.output.yaml
tests/helm/remote_write_proxy/static/full_config.input.yaml

Backport of #2554 and #2510 to v2.
---

[Backport release-v2] chore: upgrade nginx to v1.23.1

---

CHANGELOG.md
deploy/helm/sumologic/templates/setup/secret.yaml

[Backport release-v2] fix(setup):allow credentials to not be set if setup is disabled

---

README.md

Change description of v2.6 to be unsupported since it is past the date in the README

Update 2.6 to unsupported based on date

---

CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

Prepare v2.18.1

---

CHANGELOG.md
deploy/README.md

chore: remove support for OpenShift 4.6 and OpenShift 4.7

---

CHANGELOG.md
deploy/README.md

chore: remove support for EKS 1.19

---

README.md

chore: remove support for sumologic-kubernetes-collection v2.6

---

CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

Backport of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2597

chore(telegraf-operator): update Telegraf Operator Helm Chart to 1.3.10

---

CHANGELOG.md
deploy/helm/sumologic/templates/_helpers.tpl
deploy/helm/sumologic/templates/cleanup/role.yaml
deploy/helm/sumologic/templates/cleanup/rolebinding.yaml
deploy/helm/sumologic/templates/setup/role.yaml
deploy/helm/sumologic/templates/setup/rolebinding.yaml

restrict permissions for setup and cleanup jobs
Fixes: #2593

feat(chart): restrict permissions for setup and cleanup jobs

---

README.md
deploy/docs/roadmap.md

docs: roadmap

---

deploy/docs/Installation_with_Helm.md

docs(installation): fix typo

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
deploy/docs/Additional_Fluentd_Plugins.md
deploy/docs/Best_Practices.md
deploy/docs/ContainerLogs.md
deploy/docs/FluentdPersistence.md
deploy/docs/Installation_with_Helm.md
deploy/docs/Non_Helm_Installation.md
deploy/docs/SideBySidePrometheus.md
deploy/docs/Terraform.md
deploy/docs/Troubleshoot_Collection.md
deploy/docs/Working_with_container_registries.md
deploy/docs/additional_prometheus_configuration.md
deploy/docs/existingPrometheusDoc.md
deploy/docs/opentelemetry_collector.md
deploy/docs/standAlonePrometheus.md
deploy/docs/v1_conf_examples.md
deploy/docs/v1_migration_doc.md
deploy/docs/v2_migration_doc.md

Fixes #2109
Please, in particular, check if changes in examples are ok.
I did not change anything in the scripts, but it would probably be right to do so.
---

docs: rename user-provided config from values.yaml to user-values.yaml

---

CHANGELOG.md
deploy/README.md
deploy/helm/sumologic/Chart.yaml
deploy/helm/sumologic/templates/setup/secret.yaml

Update branch `release-2.18`
---

Update branch release v2.18

---

CHANGELOG.md

docs(readme): preapre release 2.18.2

---

README.md

Updates list of supported releases.
---

docs(readme): update supported releases matrix

---

docs/release.md

Fix links in docs/release.md
---

docs: fix release.md links

---

README.md

Replace mentions of Fluent Bit and Fluentd with OpenTelemetry.

docs: update summary

---

deploy/docs/v1_conf_examples.md
deploy/docs/v1_migration_doc.md
deploy/docs/v2_migration_doc.md
docs/README.md
docs/best-practices.md
docs/existing-prometheus-doc.md
docs/non-helm-installation.md
docs/side-by-side-prometheus.md
docs/standalone-prometheus.md
docs/troubleshoot-collection.md

#2654  and #2655 removed some docs files, which led to breaking the CI because of dead links. The dead link have been removed.

docs: remove dead links to v1 and v2 docs

---

CHANGELOG.md
deploy/helm/sumologic/values.yaml

fix: fix configuration for metrics-server

---

Makefile

feat: add docs to markdownlint

---

docs/security-best-practices.md

docs: add otelcol FIPS images documentation

---

deploy/helm/sumologic/values.yaml

chore: fix values.yaml comments

---

.github/workflows/pull_requests.yml
Makefile
ci/check_configuration_keys.py
vagrant/provision.sh

chore: add check for configuration coverage in README.md 

---

ci/check_configuration_keys.py

chore: add checking default values for values.yaml and README.md

---

CHANGELOG.md
deploy/docs/release.md
deploy/helm/sumologic/Chart.yaml

Updating the changelog and chart for the upcoming patch release
Signed-off-by: Raj Nishtala [rnishtala@sumologic.com](rnishtala@sumologic.com)
---

chore: prepare release v2.19.1

---

.github/workflows/pull_requests.yml
CHANGELOG.md
deploy/docs/Non_Helm_Installation.md
deploy/docs/Security_Best_Practices.md
deploy/docs/release.md
deploy/helm/sumologic/Chart.yaml
deploy/helm/sumologic/values.yaml
tests/integration/helm_otelcol_events_test.go

chore: backport release 2.19.1 to release 2.19

chore: backport release 2.19.1 to release 2.19

---

vagrant/provision.sh

- install pip
- print out summary at the end of installation

chore(vagrant): fix provision

---

ci/check_configuration_keys.py

I think we can make this check obligatory

chore(configuration-check): fail in case of any issue

---

docs/troubleshoot-collection.md

docs(troubleshooting): add advanced prometheus investigation

---

docs/README.md

Falco support for arm64 is there:
* https://github.com/falcosecurity/falco/issues/1589
* https://github.com/falcosecurity/falco/issues/1813
* https://github.com/falcosecurity/falco/pull/1990

docs: falco supports arm64 🎉

---

docs/v3-migration-doc.md

Add a brief description on how to use the configuration migration tool.
I also moved the full list of changes to the end of the document, as it's not that useful for someone starting the migration. I'd like to restructure it a bit more to make it clear for users what they need to care about based on their configuration.
Instead, the start has a short `Important Changes` section that provides context for the rest of the upgrade steps.

docs: add configuration migration to the migration guide

---

CHANGELOG.md
deploy/helm/sumologic/Chart.yaml
docs/release.md

I've also removed an unnecessary step from the release guide.

chore: prepare release v3.0.0-rc.0

---

deploy/docs/support.md

Backport the following PR:
* #2781

docs: backport #2781 to branch release-v2

---

docs/troubleshoot-collection.md

Add step to figure out the prometheus name

docs(troublehooting): minor changes to prometheus snippets

---

docs/installation.md
docs/troubleshoot-collection.md

Move troubleshooting sections strictly related to installation to `/docs/installation.md#troubleshooting-installation`

docs(troubleshooting): move installation troubleshooting to installation document

---

CHANGELOG.md
docs/README.md

chore: add support for EKS 1.24

---

docs/v3-migration-doc.md

docs(v3-migration): upgrade migration tool to v2.18.0

---

docs/v3-migration-doc.md

Describe better changes for tracing/instrumentation.
Fixes: https://github.com/SumoLogic/sumologic-kubernetes-tools/issues/445

feat(tracing): bold information about changes

---

docs/v3-migration-doc.md

add instruction for logs collector migration without data loss

docs(v3-migration-doc): add instruction for logs collector migration without data loss

---

docs/security-best-practices.md
docs/troubleshoot-collection.md

docs(troubleshoot): add solution for dns issue in otellogs

---

deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/metadata_logs_otc/static/otel.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml

This change should resolve https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/2843

fix(logs): use less greedy json regexp

---

ci/push-helm-chart.sh

Fixing an error that crept into #2846

fix(build): Helm Chart push script

---

ci/markdown_links_lint.sh

fix(ci): update markdown_links_lint.sh

---

.github/workflows/pull_requests.yml
Makefile
tests/helm/Makefile
tests/integration/Makefile

chore: upgrade golangci-lint to v1.51.0

---

CHANGELOG.md
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/metadata_logs_otc/static/otel.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml

fix(logs): fix excluding logs by container, namespace, node, pod regex

---

CHANGELOG.md
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/metadata_logs_otc/static/otel.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml

fix(logs): fix excluding logs by container, namespace, node, pod

---

CHANGELOG.md
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
tests/helm/metadata_logs_otc/static/otel.output.yaml
tests/helm/metadata_logs_otc/static/templates.output.yaml

fix(logs): fix metadata for pods with more than one container

---

ci/_build_functions.sh

Make the push function retry a defined number of times before failing. This should prevent any infinite loops from permanent errors.
Remove the loop completely from the pruning function. We don't need pruning to actually succeed on every execution - if there are concurrent builds, the other execution is enough.

ci: fix dev Helm Chart release pruning

---

docs/README.md
docs/opentelemetry-collector.md

docs: remove remaining mentions of otel beta

---

docs/README.md
docs/opentelemetry-collector.md

 [Backport release-v3.0] docs: remove remaining mentions of otel beta

---

docs/support.md

docs(support): remove tools template example

---

vagrant/provision.sh
vagrant/scripts/sumo-make-completion.sh

fix(vagrant): fix provision.sh and completion script

---

docs/troubleshoot-collection.md
docs/v3-migration-doc.md

docs: add migration and troubleshooting for remoteWrites

---

docs/troubleshoot-collection.md
docs/v3-migration-doc.md

docs(troubleshoot-collection.md): fix additionalEndpoints example

---

tests/helm/Makefile
tests/integration/Makefile
tests/integration/README.md
tests/integration/kind_images.json
tests/integration/values/values_helm_default_ot_fips_metadata.yaml

Running the integration tests for k8s 1.25.2

---

.github/workflows/dev_builds.yml
.github/workflows/pull_requests.yml
vagrant/provision.sh

chore: upgrade kind to 0.17.0

---

docs/installation.md

Add info about sumologic.setupEnable parameter in CreateContainerConfigError  troubleshooting part

docs: update troubleshooting guide

---

docs/README.md

Backport:
* https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2929

docs: add v2 to v3 migration doc link to main docs README

---

.changelog/2899.changed.txt
.changelog/2918.fixed.txt
.changelog/2923.fixed.txt
.changelog/2924.added.txt
.changelog/2927.changed.txt
.changelog/2932.fixed.txt
.changelog/2950.changed.txt
.changelog/2952.fixed.txt
.changelog/2953.fixed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare v3.4.0

---

.changelog/2962.fixed.txt
deploy/helm/sumologic/templates/pvc-cleaner/serviceaccount.yaml

fix(pvcCleaner): don't create resources when pvcCleaner is disabled

---

docs/fargate.md
examples/fargate/install-metrics.sh

docs(fargate.md): init

---

.changelog/2971.changed.txt
deploy/helm/sumologic/Chart.yaml

Upgrade tailing sidecar image to the latest version

chore: upgrade tailing-sidecar to 0.7.0

---

examples/kube_prometheus_stack/values-prometheus.yaml

Remove thanos from documentation as we do not need to use it at all

docs(example) remove thanos

---

CONTRIBUTING.md
Makefile
ci/update-otc.sh

This is needed for https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2976.

chore: add make target for updating OTC version

---

ci/update-otc.sh
deploy/helm/sumologic/conf/events/otelcol/config.yaml
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/otelcol/exporters.yaml
deploy/helm/sumologic/conf/metrics/otelcol/pipeline.yaml
deploy/helm/sumologic/conf/metrics/otelcol/processors.yaml

Refs: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/2975

refactor: sort OTC config file contents alphabetically

---

.changelog/2958.fixed.txt
.changelog/2962.fixed.txt
.changelog/2968.changed.txt
.changelog/2970.changed.txt
.changelog/2971.changed.txt
.changelog/2973.changed.txt
.changelog/2983.changed.txt
.changelog/2984.fixed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare v3.5.0

---

docs/performance.md

docs: add otc performance doc for reference

---

docs/fargate.md

docs(fargate): mark fargate support as experimental

---

docs/best-practices.md

docs(best-practices): fix snippet for scraping additional logs from node

---

ci/_build_functions.sh

fix(ci): fail workflow when pushing helm chart fails

---

docs/README.md

In #2977 there was added script for updating this, but this was not up to date in the first place.

docs(support matrix): update otelcol version to 0.73.0

---

docs/fargate.md

Fargate documentation updates
- Setting up persistence for logs metrics and events
- Document restructuring

docs(fargate): Documenting persistence for logs and events

---

.changelog/2969.changed.txt
.changelog/2982.added.txt
.changelog/3000.changed.txt
.changelog/3001.fixed.txt
.changelog/3008.changed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release v3.6.0

---

.changelog/3022.fixed.txt
CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release v3.6.1

---

docs/installation.md

docs: update fields list in installation.md

---

.changelog/3039.changed.txt
.changelog/3041.changed.txt
.changelog/3042.fixed.txt
.changelog/3043.changed.0.txt
.changelog/3043.changed.1.txt
.changelog/3047.added.0.txt
.changelog/3047.added.1.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: release v3.7.0

---

docs/best-practices.md

Add snippet to keep sourceCategory for metrics

docs: add instruction how to keep sourceCategory for metrics

---

tests/integration/values/values_helm_default_ot_fips_metadata.yaml

It wasn't upgraded with the rest in #3041

test(integration): update fips image

---

docs/fargate.md

Added the following aws policies that are needed as part of cloudwatch logs collection
- A policy that provides permissions to EKS fargate to create cloudwatch log groups
- A policy that authenticates and allows reading the cloudwatch log streams

feat(fargate-docs): Adding aws policies needed as part of cloudwatch logs collection

---

tests/integration/features.go
tests/integration/helm_ot_metrics_test.go
tests/integration/internal/constants.go
tests/integration/internal/stepfuncs/assess_funcs.go

Check for recording rule metrics in integration tests. I've also found we're missing 3 of these, and commented them out for now.
I've also improved logging for the metrics test.

test(integration): check for recording rule metrics

---

.changelog/3050.added.txt
.changelog/3063.fixed.txt
.changelog/3068.changed.txt
.changelog/3070.fixed.txt
.changelog/3071.breaking.txt
.changelog/3075.changed.txt
.changelog/3076.changed.txt
.changelog/3078.changed.txt
.changelog/3081.changed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml
tests/helm/testdata/goldenfile/setup/setup/basic.output.yaml

chore: prepare 3.9.0 release

---

.changelog/3085.changed.txt
deploy/helm/sumologic/templates/_helpers/_common.tpl
deploy/helm/sumologic/templates/events/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/instrumentation/otelcol-instrumentation/statefulset.yaml
deploy/helm/sumologic/templates/logs/fluentd/statefulset.yaml
deploy/helm/sumologic/templates/logs/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/metrics/fluentd/statefulset.yaml
deploy/helm/sumologic/templates/metrics/otelcol/statefulset.yaml
tests/helm/testdata/goldenfile/events_otc_statefulset/annotations_labels.output.yaml
tests/helm/testdata/goldenfile/events_otc_statefulset/basic.output.yaml
tests/helm/testdata/goldenfile/events_otc_statefulset/proxy.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc_statefulset/basic.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc_statefulset/custom.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc_statefulset/basic.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc_statefulset/custom.output.yaml
tests/helm/testdata/goldenfile/otelcol-instrumentation-statefulset/basic.output.yaml
tests/helm/testdata/goldenfile/otelcol-instrumentation-statefulset/custom.output.yaml

feat: unify anti-affinity configuration

---

tests/integration/kind_images.json

chore: update default k8s version to 1.27 in integration tests

---

.changelog/3104.added.0.txt
.changelog/3104.added.1.txt
docs/README.md

Add support for OpenShift 4.13 and EKS 1.27

---

.changelog/3110.changed.txt
deploy/helm/sumologic/Chart.yaml
tests/helm/testdata/goldenfile/metric-server/basic.output.yaml

chore: update metrics-server to 6.3.1

---

.changelog/3111.changed.txt
deploy/helm/sumologic/Chart.yaml

chore: update Telegraf Operator to v1.3.11

---

.changelog/3098.changed.txt
CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release v3.9.1

---

docs/README.md

docs: update version in README.md

---

.changelog/3117.changed.txt
deploy/helm/sumologic/Chart.yaml

chore: update Fluent Bit Helm Chart to v0.31.0

---

.changelog/3125.changed.txt
deploy/helm/sumologic/Chart.yaml
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
deploy/helm/sumologic/conf/opentelemetry-operator/instrumentation.cr.yaml
deploy/helm/sumologic/values.yaml
docs/README.md
tests/helm/goldenfile_test.go
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/helm/testdata/goldenfile/opentelemetry_operator_instrumentation_cr_configmap/instrumentation.output.yaml

chore: upgrade opentelemetry-operator chart to 0.33.0

---

docs/best-practices.md

docs: add instruction for using newer Kube Prometheus Stack

---

.changelog/3136.changed.txt
docs/README.md

chore: add support for EKS (fargate) 1.27

---

.changelog/3148.changed.txt
docs/README.md

chore: add support for GKE 1.27

---

docs/best-practices.md
docs/monitoring-lag.md

docs: add example configuration to change sending_queue

---

.changelog/3140.added.txt
docs/prometheus.md
docs/troubleshoot-collection.md

Added a section on prometheus sharding

docs(prometheus): Added a section on prometheus sharding

---

README.md

chore: stop supporting helm v2

---

.changelog/3146.changed.txt
deploy/helm/sumologic/Chart.yaml
tests/helm/testdata/goldenfile/metric-server/basic.output.yaml

chore(chart): update metrics-server chart to 6.4.3

---

.changelog/3172.fixed.txt
deploy/helm/sumologic/conf/logs/collector/otelcloudwatch/config.yaml
tests/helm/testdata/goldenfile/logs_otc_cloudwatch/custom.input.yaml
tests/helm/testdata/goldenfile/logs_otc_cloudwatch/custom.output.yaml

fix(helm): fix cloudwatch collector configuration for disabled persistence

---

.changelog/3136.changed.txt
.changelog/3139.changed.txt
.changelog/3140.added.txt
.changelog/3141.fixed.txt
.changelog/3142.changed.txt
.changelog/3143.changed.txt
.changelog/3145.changed.txt
.changelog/3146.changed.txt
.changelog/3148.changed.txt
.changelog/3149.changed.txt
.changelog/3155.fixed.txt
.changelog/3156.changed.txt
.changelog/3157.changed.txt
.changelog/3159.changed.txt
.changelog/3160.changed.txt
.changelog/3161.changed.txt
.changelog/3162.added.txt
.changelog/3165.changed.txt
.changelog/3166.changed.txt
.changelog/3170.fixed.txt
.changelog/3171.fixed.txt
.changelog/3172.fixed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release 3.11.0

---

.github/workflows/dev_builds.yml

chore(ci): fix typo

---

.changelog/3194.fixed.txt
deploy/helm/sumologic/templates/logs/fluentd/hpa.yaml
tests/helm/testdata/goldenfile/logs_fluentd_hpa/basic.input.yaml
tests/helm/testdata/goldenfile/logs_fluentd_hpa/basic.output.yaml
tests/helm/testdata/goldenfile/logs_fluentd_hpa/withmem.input.yaml
tests/helm/testdata/goldenfile/logs_fluentd_hpa/withmem.output.yaml

PR fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/3151

feat: fix fluentd hpa template generation

---

.changelog/3197.fixed.txt
CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release 3.11.1

---

docs/v4-migration-doc.md

docs: add skeleton for v4 migration doc

---

docs/opentelemetry-collector/README.md
docs/opentelemetry-collector/metrics.md

docs: add otel metrics collector documentation

---

deploy/docs/opentelemetry_collector.md
docs/collecting-kubernetes-events.md
docs/fluentbit-otc-comparison.md
docs/otlp-source.md

Fix the remaining links broken by #3216 .

docs: fix broken links

---

.changelog/3192.added.txt
.changelog/3193.fixed.txt
.changelog/3194.fixed.txt
.changelog/3195.fixed.txt
.changelog/3203.added.txt
.changelog/3203.changed.txt
.changelog/3204.added.txt
.changelog/3207.changed.txt
.changelog/3208.changed.txt
.changelog/3209.changed.txt
.changelog/3212.fixed.txt
.changelog/3214.added.txt
.changelog/3215.changed.txt
.changelog/3219.changed.txt
.changelog/3221.added.txt
.changelog/3223.changed.txt
.changelog/3225.fixed.txt
.changelog/3226.added.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare 3.13.0 release

---

README.md
deploy/docs/v1_migration_doc.md
tests/integration/README.md

This is for the `release-v2` branch.

docs: mark v2.19 as unsupported

---

tests/integration/internal/constants.go

test(integration): ignore flaky metric

---

README.md

ref: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3254#pullrequestreview-1616916514

docs: add EOL dates for unsupported versions

---

docs/opentelemetry-collector/metrics.md

docs: consider the otel metrics collector stable

---

docs/collecting-application-metrics.md
docs/collecting-kubernetes-metrics.md
docs/prometheus.md
docs/troubleshoot-collection.md

After #3232, we only have one trivial remote write, which simplifies some of our documentation around custom metrics.

docs: update remote write usage

---

.changelog/3308.fixed.txt
deploy/helm/sumologic/templates/scc.yaml

fix: fix scc definition

---

docs/v4-migration-doc.md

docs: fix v4 migration doc formatting

---

.changelog/3309.fixed.txt
deploy/helm/sumologic/templates/scc.yaml

fix(openshift): fix SecurityContextConstraints for OpenTelemetry Collector

---

.changelog/3310.fixed.txt
deploy/helm/sumologic/templates/scc.yaml

fix(openshift): fix SecurityContextConstraints for OpenTelemetry Collector Operator

---

docs/best-practices.md

I feel that I might be missing something, so I'm pushing this for review now.

docs: add information about lowering ingest

---

deploy/helm/sumologic/values.yaml
docs/scraped-metrics.md
docs/v4-migration-doc.md

Document how to reproduce metrics from recording rules via Sumo queries. Remove a couple that didn't work at all or were duplicates of others.

docs: recreating recording rules via Sumo queries

---

.changelog/3322.added.txt
deploy/helm/sumologic/values.yaml
docs/scraped-metrics.md
docs/v4-migration-doc.md
tests/integration/internal/constants.go

This metric is used by the new K8s App.

feat(metrics): collect node_memory_MemAvailable_bytes

---

.changelog/3318.fixed.txt
deploy/helm/sumologic/conf/metrics/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

(cherry picked from commit 70af83f69e2b856d4173fdfd3e11739de47b8a43)

[Backport release-v3] fix(metrics): drop stale datapoints

---

docs/v4-migration-doc.md

Document how to upgrade to the new Kubernetes App version. Document how to configure v3 to use the new App as well.

docs: upgrading the Kubernetes app for v4

---

.changelog/3334.changed.txt
CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

I plan to merge this pull request on 2023-10-20.

chore: prepare release 3.16.1

---

.changelog/3334.changed.txt
CHANGELOG.md

chore: update changelog

---

.changelog/3322.added.txt
.changelog/3329.breaking.txt
.changelog/3332.added.txt
.changelog/3340.changed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare 4.0.0 release

---

deploy/helm/sumologic/README.md

docs: fix dead link to Falco docs

---

docs/prometheus.md

fix(docs): fix snippets for crd update

---

deploy/docs/Best_Practices.md
deploy/docs/Dev.md
deploy/docs/Installation_with_Helm.md
deploy/docs/Installing_Behind_Proxy.md
deploy/docs/Kube-Prometheus.md
deploy/docs/Migration_Steps.md
deploy/docs/Non_Helm_Installation.md
deploy/docs/Performance.md
deploy/docs/Security_Best_Practices.md
deploy/docs/SideBySidePrometheus.md
deploy/docs/Terraform.md
deploy/docs/Troubleshoot_Collection.md
deploy/docs/Working_with_container_registries.md
deploy/docs/additional_prometheus_configuration.md
deploy/docs/collecting-kubernetes-events.md
deploy/docs/existingPrometheusDoc.md
deploy/docs/monitoring-lag.md
deploy/docs/opentelemetry_collector.md
deploy/docs/release.md
deploy/docs/scraped_metrics.md
deploy/docs/standAlonePrometheus.md
deploy/docs/support.md
deploy/docs/v3_migration_doc.md

chore(docs)!: remove deploy/docs directory

---

deploy/helm/sumologic/Chart.yaml

chore: prepare release v4.0.1

---

.changelog/3352.fixed.txt
CHANGELOG.md

chore: update changelog for v3.16.2

---

vagrant/README.md

docs: remove remaining references to vagrant-disksize

---

.changelog/3315.fixed.txt
.changelog/3366.fixed.txt
deploy/helm/sumologic/templates/_helpers/_api_versions.tpl
deploy/helm/sumologic/templates/instrumentation/otelcol-instrumentation/hpa.yaml
deploy/helm/sumologic/templates/instrumentation/traces-gateway/hpa.yaml
deploy/helm/sumologic/templates/logs/common/hpa.yaml
deploy/helm/sumologic/templates/metrics/common/hpa.yaml

Adoption of @montmanu https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3315

fix: rely on api rather than on k8s version

---

docs/README.md

docs: fix malformed html tag in support matrix

---

.changelog/3374.added.txt
deploy/helm/sumologic/templates/_helpers/_logs.tpl
deploy/helm/sumologic/templates/logs/collector/otelcol-cloudwatch/serviceaccount.yaml
deploy/helm/sumologic/templates/logs/collector/otelcol-cloudwatch/statefulset.yaml

Add new service account for the otel cloudwatch collector statefulset
E2E test: https://ct-jenkins.kumoroku.com/view/All%20Dev%20Jobs/job/dev-sumo-platform-test-k8s-collection/2085/console

Add new service account for the otel cloudwatch collector statefulset

---

.changelog/3391.changed.txt
deploy/helm/sumologic/Chart.yaml

deps: update tailing-sidecar to 0.9.0

---

.changelog/3392.changed.txt
deploy/helm/sumologic/Chart.yaml
tests/helm/testdata/goldenfile/metric-server/basic.output.yaml

deps: update metrics-server to 6.6.0

---

.changelog/3393.changed.txt
deploy/helm/sumologic/Chart.yaml

deps: update falco to 3.8.4

---

Makefile
ci/check_dependencies/aks.py
ci/check_dependencies/common.py
ci/check_dependencies/eks.py
ci/check_dependencies/gke.py
ci/check_dependencies/helm_charts.py
ci/check_dependencies/kops.py
ci/check_dependencies/main.py
ci/check_dependencies/openshift.py

The idea is for the checker to output nothing if there's nothing to change. This makes running it in CI much easier.

chore: add quiet mode to dependency_checker

---

.github/workflows/check_dependencies.yaml

ci: create a JIRA issue for dependency updates

---

.changelog/3412.fixed.txt
deploy/helm/sumologic/templates/metrics/collector/otelcol/opentelemetrycollector.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml

fix(metrics): set affinity for target allocator

---

.changelog/3417.changed.txt
deploy/helm/sumologic/Chart.yaml

As per https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/3384

deps: update telegraf operator to v1.3.12

---

.changelog/3368.breaking.txt
.changelog/3387.changed.0.txt
.changelog/3387.changed.1.txt
.changelog/3387.changed.3.txt
.changelog/3387.changed.4.txt
.changelog/3387.changed.5.txt
.changelog/3387.changed.6.txt
.changelog/3387.changed.7.txt
.changelog/3387.changed.8.txt
.changelog/3391.changed.txt
.changelog/3392.changed.txt
.changelog/3393.changed.txt
.changelog/3394.changed.txt
.changelog/3400.added.txt
.changelog/3403.added.txt
.changelog/3404.changed.txt
.changelog/3405.changed.txt
.changelog/3411.fixed.txt
.changelog/3412.fixed.txt
.changelog/3414.changed.txt
.changelog/3415.changed.txt
.changelog/3416.changed.txt
.changelog/3417.changed.txt
.changelog/3418.changed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare 4.2.0 release

---

README.md

Add link from main readme to installation docs

---

deploy/helm/sumologic/README.md

docs: add link to telegraf operator config docs

---

.changelog/3441.changed.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md

chore: update OpenTelemetry Operator to v0.44.0

---

.changelog/3423.added.txt
.changelog/3427.added.txt
.changelog/3428.fixed.txt
.changelog/3434.fixed.txt
.changelog/3438.changed.txt
.changelog/3441.changed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release v4.3.0

---

.changelog/3408.changed.1.txt
.changelog/3408.changed.2.txt
.changelog/3408.changed.3.txt
.changelog/3408.changed.4.txt
.changelog/3408.changed.5.txt
.changelog/3408.changed.txt
.changelog/3425.added.txt
.changelog/3436.fixed.txt
.changelog/3439.changed.txt
.changelog/3443.changed.txt
.changelog/3444.changed.txt
.changelog/3445.changed.txt
CHANGELOG.md
README.md

chore: prepare release v3.18.0

---

.changelog/3455.changed.txt
deploy/helm/sumologic/Chart.yaml

As per https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/3384
Changes in Falco Helm Chart: https://github.com/falcosecurity/charts/compare/falco-3.8.5...falco-3.8.6

deps: update falco to 3.8.6

---

.changelog/3456.changed.txt
deploy/helm/sumologic/Chart.yaml
tests/helm/testdata/goldenfile/metrics-server/basic.output.yaml

As per https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/3384
List of changes in metrics server helm chart: https://github.com/bitnami/charts/commits/main/bitnami/metrics-server

deps: update metrics server to 6.6.5

---

.changelog/3457.changed.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md

As per https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/3384
List of changes in opentelemetry operator: https://github.com/open-telemetry/opentelemetry-helm-charts/compare/opentelemetry-operator-0.44.0...opentelemetry-operator-0.44.2

deps: update opentelemetry operator to 0.44.2

---

.changelog/3460.changed.txt
.changelog/3461.changed.txt
deploy/helm/sumologic/conf/events/otelcol/config.yaml
deploy/helm/sumologic/conf/logs/otelcol/config.yaml
deploy/helm/sumologic/conf/metrics/otelcol/exporters.yaml
deploy/helm/sumologic/values.yaml
tests/helm/testdata/goldenfile/events_otc/basic.output.yaml
tests/helm/testdata/goldenfile/events_otc/options.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/otel.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/templates.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/additional_endpoints.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/custom.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/filtered_app_metrics.output.yaml
tests/helm/testdata/goldenfile/otelcol-instrumentation-config/traces-gateway-disabled.output.yaml
tests/helm/testdata/goldenfile/otelcol-instrumentation-config/traces-gateway-enabled.output.yaml

Send k8s version with every request to Sumo Logic

feat(opentelemetry): send information about k8s version

---

vagrant/values.yaml

chore(vagrant): remove fluent related configuration

---

docs/best-practices.md
docs/collecting-application-metrics.md
docs/collecting-container-logs.md
docs/collecting-systemd-logs.md
docs/filtering.md

I checked for remaining mentions to filtering in other docs.
Also - removed configs for `filterprocessor` were outdated, just saying.

docs: add more detailed information about filtering ingested data

---

docs/best-practices.md

docs: add information about global config options

---

docs/README.md

docs: add missing link to  migration doc to v4

---

docs/troubleshoot-collection.md

docs: add troubleshooting for metrics with Open Telemetry Operator

---

docs/troubleshoot-collection.md

docs(troubleshooting): add section about printing metrics on stdout

---

docs/security-best-practices.md

docs: Update security-best-practices.md

---

.changelog/3447.fixed.txt
.changelog/3455.changed.txt
.changelog/3456.changed.txt
.changelog/3457.changed.txt
.changelog/3459.added.txt
.changelog/3460.changed.txt
.changelog/3462.added.txt
.changelog/3469.fixed.txt
.changelog/3478.changed.0.txt
.changelog/3478.changed.1.txt
.changelog/3490.added.txt
.changelog/3491.added.txt
.changelog/3505.changed.txt
.changelog/3507.changed.0.txt
.changelog/3507.changed.1.txt
.changelog/3510.changed.txt
.changelog/3515.changed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: Prepare release 4.4.0

---

README.md

chore: drop support for v3.9 and v3.10

---

deploy/helm/sumologic/values.yaml
docs/README.md
docs/collecting-kubernetes-events.md

https://help.sumologic.com/docs/send-data/kubernetes/collecting-kubernetes-event returns 404

docs: fix link to events

---

.changelog/3535.fixed.txt
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
deploy/helm/sumologic/templates/_helpers/_logs.tpl
deploy/helm/sumologic/templates/_helpers/_metrics.tpl
tests/helm/testdata/goldenfile/logs_otc/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc/debug.output.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/multiple_multiline.output.yaml

Fix exclusions regexes in logs-collector

fix(debug): fix exclusion of logs scraping

---

.changelog/3536.changed.txt
deploy/helm/sumologic/templates/_helpers/_sumologic_mock.tpl
tests/helm/testdata/goldenfile/logs_otc/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc/debug.output.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/multiple_multiline.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/debug_with_sumologic_mock.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/debug_with_sumologic_mock_http.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/debug_with_sumologic_mock.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/debug_with_sumologic_mock_http.output.yaml
tests/helm/testdata/goldenfile/sumologic-mock/basic.output.yaml
tests/helm/testdata/goldenfile/sumologic-mock/complex.output.yaml

feat: rename sumologic-mock to mock in kubernetes object names

---

.changelog/3541.changed.txt
deploy/helm/sumologic/templates/_helpers/_sumologic_mock.tpl
deploy/helm/sumologic/templates/sumologic-mock/deployment.yaml
deploy/helm/sumologic/templates/sumologic-mock/service.yaml
tests/helm/testdata/goldenfile/sumologic-mock/basic.output.yaml
tests/helm/testdata/goldenfile/sumologic-mock/complex.output.yaml

Labels are useful for easier getting logs or exposing service. It will simplify documentation about Sumo Logic Mock

feat(sumologic-mock): add sumologic.com/app label

---

.changelog/3542.fixed.txt
deploy/helm/sumologic/templates/metrics/collector/otelcol/opentelemetrycollector.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/custom.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/debug.output.yaml
tests/helm/testdata/goldenfile/metrics_collector_otc/kubelet.output.yaml

fix: fix opentelemetry object for metrics collector

---

.changelog/3547.changed.1.txt
.changelog/3547.changed.2.txt
.changelog/3547.changed.txt
docs/README.md

feat: add support for kubernetes 1.29 for EKS, KOPS and AKS

---

README.md

chore: fix EOL dates

---

deploy/helm/sumologic/conf/instrumentation/traces.sampler.conf.yaml
vagrant/opentelemetry-collector.yaml

Fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/3503

docs: replace Logging exporter with Debug exporter

---

.changelog/3555.changed.txt
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/additional.input.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/additional.output.yaml

fix(logs): do not require resources for additionalDaemonset

---

.changelog/3556.changed.txt
deploy/helm/sumologic/Chart.yaml

deps: update tailing-sidecar to 0.10.0

deps: update tailing-sidecar to 0.10.0

---

.changelog/3557.changed.txt
deploy/helm/sumologic/Chart.yaml

deps: update opentelemetry-operator to 0.47.0

deps: update opentelemetry-operator to 0.47.0

---

.github/workflows/check_dependencies.yaml
ci/check_dependencies/issue_header.md

See: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/3559

ci: add date to dependencies issue title

---

.changelog/3560.changed.1.txt
.changelog/3560.changed.txt
docs/README.md

chore: Platform support updates

chore: Platform support updates

---

.changelog/3564.fixed.txt
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/templates/sumologic-mock/deployment.yaml
tests/helm/testdata/goldenfile/sumologic-mock/complex.output.yaml

fix(sumologic-mock): fix nodeSelector

---

.changelog/3565.changed.txt
deploy/helm/sumologic/templates/_helpers/_events.tpl
deploy/helm/sumologic/templates/events/otelcol/statefulset.yaml
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
tests/helm/testdata/goldenfile/events_otc_statefulset/common.input.yaml
tests/helm/testdata/goldenfile/events_otc_statefulset/common.output.yaml

feat(events): support global nodeSelector, tolerations and affinity

---

.changelog/3571.changed.txt
deploy/helm/sumologic/templates/_helpers/_traces.tpl
deploy/helm/sumologic/templates/instrumentation/otelcol-instrumentation/service-deprecated-otelcol.yaml

Reverts SumoLogic/sumologic-kubernetes-collection#3571 until v5.

Revert "chore(instrumentation): remove deprecated otelcol service"

---

.changelog/3585.changed.txt
deploy/helm/sumologic/templates/_helpers/_sumologic_mock.tpl
tests/helm/testdata/goldenfile/cleanup/sumologic-mock-no-secret.output.yaml
tests/helm/testdata/goldenfile/cleanup/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/events_otc/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/debug_with_sumologic_mock.output.yaml
tests/helm/testdata/goldenfile/metadata_logs_otc/debug_with_sumologic_mock_http.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/debug_with_sumologic_mock.output.yaml
tests/helm/testdata/goldenfile/metadata_metrics_otc/debug_with_sumologic_mock_http.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock-no-secret.output.yaml
tests/helm/testdata/goldenfile/setup/sumologic-mock.output.yaml
tests/helm/testdata/goldenfile/sumologic-mock/basic.output.yaml
tests/helm/testdata/goldenfile/sumologic-mock/complex.output.yaml
tests/helm/testdata/goldenfile/traces-sampler/sumologic-mock.output.yaml

Short hostname name is not recognized by windows DNS

feat(sumologicmock): use full hostname

---

.changelog/3583.changed.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md

Update opentelemetry-operator subchart to 0.47.1

deps: Update opentelemetry-operator subchart to 0.47.1

---

.changelog/3596.added.txt
deploy/helm/sumologic/templates/logs/collector/otelcol/daemonset.yaml
deploy/helm/sumologic/values.yaml
tests/helm/logs_test.go

feat(logs): make logs-collector's update strategy configurable

---

vagrant/scripts/get-kubeconfig.sh

chore(vagrant): set default namespace to sumologic when using cluster locally

---

deploy/helm/sumologic/templates/sumologic-mock/serviceaccount.yaml

chore: do not create sumologic mock serviceaccount by default

---

.changelog/3603.changed.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md

chore: update Tailing Sidecar to 0.11.0

---

.changelog/3564.fixed.txt
.changelog/3565.changed.txt
.changelog/3567.changed.txt
.changelog/3569.added.txt
.changelog/3570.changed.txt
.changelog/3573.fixed.txt
.changelog/3574.changed.txt
.changelog/3581.changed.txt
.changelog/3582.fixed.txt
.changelog/3583.changed.txt
.changelog/3584.changed.txt
.changelog/3585.changed.txt
.changelog/3586.changed.txt
.changelog/3592.changed.txt
.changelog/3594.changed.txt
.changelog/3596.added.txt
.changelog/3603.changed.txt
.changelog/3604.fixed.txt
.changelog/3608.changed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare 4.6.0 release

---

.github/workflows/changelog.yaml
.github/workflows/workflow-integration-tests.yaml
Makefile
shell.nix

Upgrate tools to whatever is in nixpkgs unstable today. Tested all the make targets.

chore: upgrade tools

---

.changelog/3618.fixed.txt
deploy/helm/sumologic/templates/metrics/prometheus/servicemonitors.yaml
tests/helm/testdata/goldenfile/metrics_additional_service_monitors/basic.input.yaml
tests/helm/testdata/goldenfile/metrics_additional_service_monitors/basic.output.yaml
tests/helm/testdata/goldenfile/metrics_additional_service_monitors/custom.input.yaml
tests/helm/testdata/goldenfile/metrics_additional_service_monitors/custom.output.yaml

fix(metrics): use namespaceSelector from configuration for additionalServiceMonitors

---

README.md

docs: fix link to v4.6 docs

---

README.md

docs: update supported versions

---

.changelog/3654.changed.txt
docs/README.md

E2E tests pass. Partially addresses #3648.

chore: add support for OpenShift 4.15

---

docs/filtering.md

doc(metrics): Filtering Prometheus metrics

docs: Filtering Prometheus metrics

---

.github/workflows/sync-repositories.yaml

chore: simplify sync repositories workflow

---

.github/workflows/sync-repositories.yaml
.github/workflows/workflow-sync-repositories.yaml
ci/sync-repository.sh
shell.nix

Depends on #3675
Example run: https://github.com/SumoLogic/sumologic-kubernetes-collection/actions/runs/8802897795/job/24159743854

chore: add remaining repositories for syncing 

---

examples/instrumentation/custom-values-cascading-filter.yaml
examples/instrumentation/multiple-cascading-filter-sampler-instances.yaml

PR adds examples for instrumentation traces-sampler.

chore: add instrumentation examples

---

.changelog/3591.added.txt
.changelog/3630.changed.0.txt
.changelog/3630.changed.1.txt
.changelog/3633.changed.0.txt
.changelog/3633.changed.1.txt
.changelog/3641.changed.0.txt
.changelog/3641.changed.1.txt
.changelog/3643.added.txt
.changelog/3653.changed.txt
.changelog/3654.changed.txt
.changelog/3656.changed.txt
.changelog/3664.changed.txt
.changelog/3665.changed.txt
.changelog/3666.changed.txt
.changelog/3667.changed.txt
.changelog/3671.changed.txt
.changelog/3674.added.txt
.changelog/3677.changed.txt
.changelog/3682.changed.txt
.changelog/3684.added.txt
.changelog/3688.changed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release v4.7

---

.changelog/3695.changed.0.txt
.changelog/3695.changed.1.txt
.changelog/3695.changed.2.txt
.changelog/3695.changed.3.txt
.changelog/3695.changed.4.txt
.changelog/3695.changed.5.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md
tests/helm/testdata/goldenfile/metrics-server/basic.output.yaml

Update subcharts up to what is currently in v4.

[v3] deps: update subcharts

---

CHANGELOG.md
README.md

docs: add v3.19 release

---

.github/workflows/close-jira-task.yaml

Automatically close jira issue, when github issue is closed

chore: close jira issue automatically

---

.github/workflows/pull_requests.yml
Makefile
ci/check_unused_templates.sh
deploy/helm/sumologic/templates/_helpers/_common.tpl
deploy/helm/sumologic/templates/_helpers/_logs.tpl
deploy/helm/sumologic/templates/_helpers/_metrics.tpl
deploy/helm/sumologic/templates/_helpers/_setup.tpl
deploy/helm/sumologic/templates/_helpers/_sumologic_mock.tpl
deploy/helm/sumologic/templates/_helpers/_traces.tpl

chore: cleanup unused templates

---

.github/workflows/close-jira-task.yaml

feat: fix bash syntax

---

.changelog/3715.changed.0.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release 3.19.1

---

tests/integration/internal/stepfuncs/kubectl.go
tests/integration/main_test.go

Some integration tests need namespaces created before the Helm Chart is installed. Examples include namespaces where we create default Instrumentation resources, or the override namespace. Creating these for each test is annoying, because we also need to delete them for each test, and namespace deletion tends to be slow in Kubernetes.
Instead, only create these when the per-test values.yaml requires it.
Resolves #2199.

test(integration): create fixed namespaces only when needed

---

.changelog/3720.changed.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md

(cherry picked from commit 19bc5d88e0e10215c3a0d85bb07b7dc2e63433d1)
chore: upgrade tailing sidecar (#3719)

chore: upgrade tailing sidecar (#3719)

---

.changelog/3719.changed.txt
CHANGELOG.md

chore: Prepare release v3.19.2

chore: Prepare release v3.19.2

---

deploy/helm/sumologic/Chart.yaml

chore: upgrade chart version

---

.changelog/3725.changed.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md

chore: Upgrading tailing-sidecar

chore: Upgrading tailing-sidecar

---

deploy/helm/sumologic/Chart.yaml

chore: release v3.19.3

---

CHANGELOG.md

chore: add release v3.19.3

---

.changelog/3691.added.txt
CONTRIBUTING.md
vagrant/README.md

Adds additional instructions for setting up a development environment on Macs with Apple Silicon processors.

chore: apple silicon instructions for CONTRIBUTING.md & vagrant/README.md

---

.changelog/3753.changed.txt
deploy/helm/sumologic/Chart.yaml
docs/README.md

chore: Upgrade tailing-sidecar to v0.14.0

---

.changelog/3691.added.txt
.changelog/3697.changed.txt
.changelog/3711.changed.txt
.changelog/3720.changed.txt
.changelog/3728.changed.txt
.changelog/3737.changed.txt
.changelog/3753.changed.txt
.changelog/3755.changed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: prepare release v4.8.0

---

deploy/helm/sumologic/conf/setup/fields.tf
deploy/helm/sumologic/conf/setup/resources.tf
deploy/helm/sumologic/conf/setup/variables.tf
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

Format the Terraform manifests. I thought of setting up tflint as well, but this is changed so rarely that it's probably not worth it.

chore(setup): run terraform fmt on manifests

---

.changelog/3787.fixed.txt
deploy/helm/sumologic/conf/logs/collector/otelcloudwatch/config.yaml
deploy/helm/sumologic/conf/logs/collector/otelcol/config.yaml
tests/helm/testdata/goldenfile/logs_otc/basic.output.yaml
tests/helm/testdata/goldenfile/logs_otc_daemonset/multiple_multiline.output.yaml

fix: join multiparts on file beginning

---

.changelog/3791.changed.txt
deploy/helm/sumologic/conf/setup/main.tf
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

chore: upgrade terraform providers versions in setup

---

.github/workflows/sync-repository.yaml
ci/sync-repository.sh

chore: fix typo

---

docs/filtering.md
docs/scraped-metrics.md

Updates to the doc around allowing histogram metrics

docs(histogram-metrics): Documentation updates for allowing histogram metrics (dropped by default)

---

.changelog/3795.changed.txt
.changelog/3796.fixed.txt
.changelog/3802.changed.txt
.changelog/3803.changed.txt
.changelog/3804.changed.1.txt
.changelog/3804.changed.3.txt
.changelog/3804.changed.4.txt
.changelog/3804.changed.5.txt
.changelog/3808.changed.txt
.changelog/3818.changed.txt
.changelog/3821.added.txt
.changelog/3829.changed.txt
.changelog/3832.fixed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: Prepare release 4.10.0

---

CHANGELOG.md
deploy/helm/sumologic/conf/setup/monitors.sh
deploy/helm/sumologic/conf/setup/setup.sh
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

Add support for the Korea region of the Sumologic deployment

feat: Add support for the Korea region of the Sumologic deployment

---

.changelog/3853.fixed.txt
Vagrantfile
deploy/helm/sumologic/values.yaml
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

fix(timestamp): Fix the timestamp locator for log sources

fix(timestamp): Fix the timestamp locator for log sources

---

.changelog/3852.changed.txt
deploy/helm/sumologic/conf/setup/main.tf
tests/helm/testdata/goldenfile/terraform/all_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/collector_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/conditional_sources.output.yaml
tests/helm/testdata/goldenfile/terraform/custom.output.yaml
tests/helm/testdata/goldenfile/terraform/default.output.yaml
tests/helm/testdata/goldenfile/terraform/disable_default_metrics.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_dashboards.output.yaml
tests/helm/testdata/goldenfile/terraform/disabled_monitors.output.yaml
tests/helm/testdata/goldenfile/terraform/logs_fields.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_email_notifications.output.yaml
tests/helm/testdata/goldenfile/terraform/monitors_with_single_email.output.yaml
tests/helm/testdata/goldenfile/terraform/strip_extrapolation.output.yaml
tests/helm/testdata/goldenfile/terraform/traces.output.yaml
tests/helm/testdata/goldenfile/terraform/tracing-metrics-disabled.output.yaml

chore: upgrade terraform provider

chore: upgrade terraform provider

---

.changelog/3865.fixed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

Release 4.7.0 has now moved outside of the support window.

chore: prepare release 4.11.1

---

.changelog/3886.changed.txt
docs/README.md

Update the k8s version support matrix
Jenkins tests
[EKS] https://ct-jenkins.kumoroku.com/view/All%20Dev%20Jobs/job/dev-sumo-platform-test-k8s-collection/2306/
[AKS] https://ct-jenkins.kumoroku.com/view/All%20Dev%20Jobs/job/dev-sumo-platform-test-k8s-collection/2312/
[GKE] https://ct-jenkins.kumoroku.com/view/All%20Dev%20Jobs/job/dev-sumo-platform-test-k8s-collection/2307/
[EKS Fargate] https://ct-jenkins.kumoroku.com/view/All%20Dev%20Jobs/job/dev-sumo-platform-test-k8s-collection/2314

chore: Update the k8s version support matrix

---

.changelog/3877.changed.txt
.changelog/3881.changed.txt
.changelog/3882.changed.txt
.changelog/3884.added.txt
.changelog/3885.added.txt
.changelog/3886.changed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml

chore: Prepare release 4.12.0

---

docs/README.md

Update title for the deployment guide

docs: Update title for the deployment guide

---

docs/windows.md

More detail on whats needed to support pods on Windows nodes

docs: More detail on whats needed to support pods on Windows nodes

---

.changelog/3901.added.txt
.changelog/3902.added.txt
CHANGELOG.md
deploy/helm/sumologic/Chart.yaml

chore: Prepare release 4.12.1

---

.changelog/3898.changed.txt
.changelog/3911.added.txt
.changelog/3912.added.txt
.changelog/3913.changed.txt
.changelog/3914.added.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml
docs/README.md

chore: Prepare release 4.13.0

---

.changelog/3925.changed.txt
.changelog/3927.fixed.txt
.changelog/3930.fixed.txt
.changelog/3938.changed.txt
CHANGELOG.md
README.md
deploy/helm/sumologic/Chart.yaml
docs/README.md

chore: Prepare release v4.14.0

---

tests/integration/features.go

Issue with the routing logs test

fix: Issue with the routing logs test

---

tests/integration/features.go

fix: Reduce flakiness in the logs test

fix: Remove flakiness in the logs test

---

docs/README.md

docs: Update helm and otel operator versions

docs: Update helm and otel operator versions

---

artifacthub-repo.yml

Claim ownership of this repository on artifacthub - https://artifacthub.io/docs/topics/repositories/#ownership-claim

chore: Claim ownership of this repository on artifacthub
