.travis.yml, ci/build.sh
add travis support for
- UT
- docker build
- docker push
=> add travis ci support

fluent-plugin-datapoint/README.md, fluent-plugin-datapoint/lib/fluent/plugin/out_datapoint.rb, fluent-plugin-datapoint/test/plugin/test_out_datapoint.rb, fluent-plugin-datapoint/test/resources/multiple.json, fluent-plugin-datapoint/test/resources/multiple.missing_value.json, fluent-plugin-datapoint/test/resources/multiple.nan_value.json, fluent-plugin-datapoint/test/resources/multiple.output_part.json, fluent-plugin-datapoint/test/resources/single.json, fluent-plugin-datapoint/test/resources/single.missing_value.json, fluent-plugin-datapoint/test/resources/single.nan_value.json, fluent-plugin-datapoint/test/resources/single.output.json, fluent-plugin-datapoint/test/resources/timeseries.json
fluentd output plugin for breaking time series record into data points (see README for details)
**Reviewers:**
@samjsong @lei-sumo
FYI:
@rvmiller89 @maimaisie @yuting-liu
=> datapoint plugin

ci/build.sh, deploy/docker/Dockerfile, deploy/docker/fluent.conf, deploy/kubernetes/deployment-fluentd.yaml, deploy/kubernetes/secret-sumologic.yaml, deploy/test/test_docker.rb, fluent-plugin-protobuf/lib/fluent/plugin/parser_protobuf.rb, fluent-plugin-protobuf/test/plugin/test_parser_protobuf.rb
Deploy update on both docker image and Kubernetes `.yaml` include:
- Dockerfile update and unit test (make sure Docker image is built and runnable)
- Routing metrics pipeline in `fluent.conf` with current 3 plugins 
- Placeholder of events/logs pipeline
- Rename `ProtobufParse` to `ProtobufParser` otherwise fluentd will fail to find it
Need an end-to-end test with Prometheus cluster
FYI - @maimaisie @yuting-liu @frankreno
=> Byi deploy metrics

deploy/helm/overrides.yaml, deploy/kubernetes/fluentd-sumologic.yaml
- add Prometheus rule metrics
- add up metrics
- remove go_* metrics
metrics generated by rule will go into the default source
@samjsong @frankreno 
FYI - @lei-sumo @ggarg2906sumo
=> Byi tweak remote write

deploy/kubernetes/fluentd-sumologic.yaml
relabel pod to pod_name, container to container_name
https://jira.kumoroku.com/jira/browse/SUMO-109075
FYI - @frankreno @lei-sumo
=> rename from pod_name/container_name to pod/container

deploy/README.md, deploy/kubernetes/fluentd-sumologic.yaml, deploy/kubernetes/setup.sh
add a bash script for creating source deploy fluent
with following change:
- remove prometheus-operator and cAdvisor since we no longer have metrics with these jobs
- document update for process/script usage/relabel/patch Prometheus service, etc.
FYI - @lei-sumo @ggarg2906sumo
=> Byi setup script

deploy/helm/overrides.yaml
We want to collect:
```
etcd_helper_cache_hit_count
etcd_helper_cache_miss_count
node_memory_Cached_bytes
node_memory_Free_bytes
```
cc @ggarg2906sumo @lei-sumo
=> Collect additional metrics

deploy/helm/overrides.yaml
Add in StatefulSet metrics that Prom Scraper previously pulled.
=> add stateful set metrics

deploy/README.md, deploy/kubernetes/fluentd-sumologic.yaml, deploy/kubernetes/setup.sh
- rename the secret from `sumologic` to `metric-endpoints` (so we can use different secret for log/metric)
- if secret exists, abort the setup script
- readme update
=> script fixing

deploy/README.md
Fixes some wording in the README file
=> Update wording in deploy README file

deploy/docker/Dockerfile, deploy/docker/fluent.conf, fluent-plugin-enhance-k8s-metadata/fluent-plugin-enhance-k8s-metadata.gemspec, fluent-plugin-enhance-k8s-metadata/test/plugin/test_filter_enhance_k8s_metadata.rb
- add plugin and dependencies into docker image
=> add into docker image

deploy/README.md
Forgot to update bits of the README on the last PR.
=> Fix README

deploy/kubernetes/setup.sh
=> Include namespace parameter in help usage

fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb, fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_service_monitor.rb
=> Disable service metadata for now

deploy/README.md
Fix ServiceMonitor docs for missing label and add note about using `--force` with `helm upgrade.`
=> Fix ServiceMonitor docs for missing label and add note about using `--force` with `helm upgrade.`

README.md
=> Add Docker pulls badge to README

ci/build.sh
FYI: @frankreno @lei-sumo @maimaisie
=> Don't build/push docker image with latest tag

README.md
Realized we don't explicitly mention anywhere that this solution is still in development - figured we should add a disclaimer to the README. Wasn't sure about the wording, any feedback would be appreciated.
=> add development disclaimer

deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> Use v1 (non-beta) API for ClusterRole, ClusterRoleBinding

deploy/README.md, deploy/kubernetes/setup.sh
Add is an alpha flag to set alpha fluentD image
=> Add param for alpha docker images

deploy/README.md
- Auto-generated TOC from the VS Code plugin "Auto Markdown TOC".
- Fixes some formatting and spelling errors
- Adds section on troubleshooting log/metric collection by looking at FluentBit/FluentD metrics
=> Improve troubleshooting section of deployment README

deploy/README.md
Add link to Helm docs on securing Helm.
=> Add link to Helm docs on securing Helm.

deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Bumps the yaml version now that we've released 0.1.0
=> Bump yaml version to 0.1.0

deploy/README.md, deploy/helm/falco-gke-overrides.yaml, deploy/helm/falco-overrides.yaml
Added- overrides.yaml for Falco and Falco GKE. Updated Read me for Falco.
=> Added Falco specific changes.

deploy/helm/sumologic/conf/logs/logs.source.containers.conf, deploy/helm/sumologic/templates/clusterrole.yaml, deploy/helm/sumologic/templates/clusterrolebinding.yaml, deploy/helm/sumologic/templates/deployment.yaml, deploy/helm/sumologic/templates/events-deployment.yaml, deploy/helm/sumologic/templates/service.yaml, deploy/helm/sumologic/values.yaml
Sync helm chart before adding automation for generating yaml file from helm
=> Sync helm chart yaml and fix service selector

deploy/README.md
Update doc with steps to extend fluentD image with custom plugins.
=> Update doc with steps to extend fluentD image with custom plugins.

deploy/README.md, deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> Cut release 0.2.0

deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> SUMO-117653: Change docker image pull policy to IfNotPresent

deploy/helm/README.md
=> Add sed for prometheus namespaceSelector

deploy/README.md
=> Update README HelpDoc link

deploy/README.md
=> Update docs for release 0.6.0

deploy/README.md
Add the necessary fields to be added in the Sumo UI to the deploy README
=> Add necessary fields list to README

deploy/README.md
=> Update instruction for cluster name

deploy/README.md
=> Add prerequisite on endpoint and access key

deploy/README.md
fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/207
=> Fix curl command in README

deploy/README.md
=> Update docs for 0.7.0

ci/build.sh
For non-Travis code authors, verify they have not changed any of the generated files.
This fixes the bug where you couldn't commit subsequent changes after Travis had generated some files in your PR.
FYI: @maimaisie @frankreno
=> Fix CI Yaml validation for subsequent commits

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
README updates will follow after the release is made.
=> Cut release 0.9.0

deploy/README.md
Merge after the release is built.
=> README changes for 0.9.0 release

deploy/README.md
Adding docs for migration from old to new setup.
=> Migration docs

deploy/helm/sumologic/values.yaml
Fix described here: https://github.com/helm/charts/issues/9793#issuecomment-449393278
Tested it and it seems to work fine.
FYI: @lei-sumo @maimaisie
=> Fix grafana from starting via Helm deployment

deploy/README.md
To be merged after we cut the release.
=> Update README with v0.10.0 release

ci/build.sh
Needed based on errors in https://travis-ci.org/SumoLogic/sumologic-kubernetes-collection/builds/606114390
=> Add helm repo update

ci/build.sh
=> Fix helm package to also update dependencies

deploy/kubernetes/setup-sumologic.yaml.tmpl
This file is needed to be checked in for testing yaml generation in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/278
=> Add empty setup job yaml in preparation for yaml generation

deploy/docs/Installation_with_Helm.md
Fixing links to other readme files
=> Fix links to other readme files

deploy/docs/Installation_with_Helm.md
=> Update SUMO_ENDPOINT refs to SUMO_API_ENDPOINT

deploy/helm/sumologic/templates/setup/setup-clusterrole.yaml, deploy/helm/sumologic/templates/setup/setup-clusterrolebinding.yaml, deploy/helm/sumologic/templates/setup/setup-configmap.yaml, deploy/helm/sumologic/templates/setup/setup-job.yaml, deploy/helm/sumologic/templates/setup/setup-serviceaccount.yaml, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Revert pre-upgrade hook for now for further testing

deploy/docs/Non_Helm_Installation.md, deploy/docs/existingPrometheusDoc.md
Updates the README for the new release
=> Update README for v0.11.0 release

.travis.yml
=> Fix branch/tag regex validation

deploy/helm/sumologic/templates/setup/setup-configmap.yaml
=> Missed indentation in this file

deploy/docs/Non_Helm_Installation.md, deploy/helm/sumologic/requirements.yaml
=> Bump Chart Versions

deploy/helm/sumologic/templates/setup/setup-job.yaml
Fix an issue i found with my changes from yesterday
=> fix missing secret ref

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
README updates will follow after the release is made.
=> Cut release 0.12.0

deploy/README.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/existingPrometheusDoc.md, deploy/helm/sumologic/templates/events-configmap.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> README changes for 0.12.0 release

deploy/docs/Non_Helm_Installation.md
=> Fix README typo

deploy/docker/Dockerfile
Reverts SumoLogic/sumologic-kubernetes-collection#356
=> Revert "Bump fluentd image version to fix fluentd buffer bug"

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> cut release 0.13.0

deploy/docs/Non_Helm_Installation.md, deploy/docs/existingPrometheusDoc.md
=> readme changes for v0.13.0

deploy/README.md, deploy/docs/Best_Practices.md
add best practices doc
This is a modified version of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/329/ which contains changes wrt to upcoming major release.
=> Add best practices/Advanced config doc for v.0.13.0

deploy/docs/Best_Practices.md
Fix heading format in Best Practices doc
=> use proper heading format

deploy/helm/sumologic/requirements.yaml
=> Bump falco helm chart dep to 1.1.1

deploy/README.md, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> change dependency matrix

deploy/README.md
=> fix support matrix

deploy/docs/Best_Practices.md
add documentation for docker_mode
=> add documentation for docker_mode

README.md, deploy/README.md, deploy/docs/Helm3.md, deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/existingPrometheusDoc.md, deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Cut release 0.14.0

deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/conf/metrics/metrics.conf, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
=> Revert 116 metrics with filter

README.md, deploy/docs/Helm3.md, deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/Upgrading_with_Helm.md, deploy/docs/existingPrometheusDoc.md, deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Cut release 0.15.0

deploy/helm/sumologic/values.yaml, deploy/kubernetes/setup-sumologic.yaml.tmpl
Reverts SumoLogic/sumologic-kubernetes-collection#357
=> [1.0.0] Revert "Revert "[breaking change] Add pre-upgrade hook for setup""

deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/conf/metrics/metrics.conf, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
Reverts SumoLogic/sumologic-kubernetes-collection#432
=> Revert "Revert 116 metrics with filter"

deploy/helm/sumologic/templates/events-statefulset.yaml, deploy/helm/sumologic/templates/otelcol-deployment.yaml, deploy/helm/sumologic/templates/statefulset.yaml, deploy/helm/sumologic/values.yaml
=> move the statefulsets and deployment configs under root level keys

deploy/helm/sumologic/values.yaml
=> Fix typo in tag name

ci/build.sh
Do not release alpha version with every commit to master
Use git describe for master branch development build tags
Extract duplicated code into functions
=> Semver ci adjustments

deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/values.yaml
Clarify params in `values.yaml` for better understanding and usability.
=> Clarify params in values.yaml

ci/build.sh
=> Remove letter v from tags for developmend builds

.travis.yml
=> Allow for alpha and beta builds on Travis

ci/build.sh
=> Fix gem prerelease builds for dev and pre-release

ci/build.sh
=> ci kick: enclose  in {}

deploy/docs/Installation_with_Helm.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md
=> add doc changes for v0.16.0

README.md, deploy/docs/Helm3.md, deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/Upgrading_with_Helm.md, deploy/docs/existingPrometheusDoc.md
=> Bump version in the docs to v0.16.0

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Set the 0.16.0-rc.1 image for the future rc.1 release tests

README.md, deploy/docs/Helm3.md, deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/Upgrading_with_Helm.md, deploy/docs/existingPrometheusDoc.md, deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prerelease docs and version bump

deploy/README.md, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Update the support matrix to include missing versions
=> Update the support matrix

README.md
=> Remove white characters from the line ends

deploy/docs/Non_Helm_Installation.md, deploy/docs/Upgrading_with_Helm.md
=> Use Helm 2 docs and not the latest

deploy/helm/sumologic/templates/chart-configmap.yaml, deploy/helm/sumologic/templates/events-statefulset.yaml, deploy/helm/sumologic/templates/statefulset.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> [1.0.0] add fluentd to name of both logs and events fluentd statefulsets

deploy/docs/Installation_with_Helm.md, deploy/docs/Troubleshoot_Collection.md, deploy/docs/Upgrading_with_Helm.md, deploy/docs/existingPrometheusDoc.md
=> Release v0.16 backports

README.md
=> Release v0.17 backports

README.md, deploy/docs/Helm3.md, deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/Upgrading_with_Helm.md, deploy/docs/existingPrometheusDoc.md
=> release-v0.17 - change GH documentation links from tag to the release branch

README.md, deploy/docs/Helm3.md, deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/Upgrading_with_Helm.md, deploy/docs/existingPrometheusDoc.md
=> release-v0.16 - change GH documentation links from tag to the release branch

deploy/docs/Non_Helm_Installation.md
=> add sed command to replace cluster name for non-helm users

README.md
=> Use short release version names for documentation

deploy/docs/standAlonePrometheus.md
=> Put more detail for installing with standalone Prometheus

deploy/docs/additional_prometheus_configuration.md
During adding new metric to prometheus I had some issues and I wanted to update this document to avoid similar confusions in the future.
Especially using `prometheus-override.yaml` was very unclear for me.
Please check if this update makes sense and I would be grateful for spell-checking 😸 🇬🇧
=> Update additional metrics instruction

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare for 1.0.0-beta.0 build

deploy/docs/Troubleshoot_Collection.md
=> Add helm RBAC error and solution

deploy/helm/sumologic/templates/deployment.yaml, deploy/helm/sumologic/values.yaml, fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb
=> Revert the _sourceHost changes

deploy/docs/existingPrometheusDoc.md
Reformatted command line interface examples for better readability
=> Reformatted CLI examples to more easily readable

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare version v0.17.1-rc.0

.travis.yml
=> Allow for release branches PRs builds

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v0.17.1

ci/build.sh
=> Allow dev builds on release branches

deploy/docs/Best_Practices.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/Troubleshoot_Collection.md, deploy/docs/additional_prometheus_configuration.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md
=> backport docs

deploy/docs/Best_Practices.md
=> add steps for additional buffer & flush parameters

deploy/helm/sumologic/upgrade-1.0.0.sh
This is a very good style guide to use:
https://google.github.io/styleguide/shellguide.html#loops
I propose that we should use it :)
=> Keep consistent style with loops and ifs

deploy/helm/sumologic/upgrade-1.0.0.sh
Add support for prometheus regexes
=> Add support for rewriting prometheus regexes

deploy/docs/Non_Helm_Installation.md
=> Set namepace and cluster name when deploying fluentd

deploy/docs/standAlonePrometheus.md
=> change tag to release branch

deploy/helm/sumologic/upgrade-1.0.0.sh
Bash script that takes existing values.yaml file and spits out new.yaml, compatible with 1.0.0
This is a reopen of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/443
Thank you everyone for your contributions!!
**TODO** add link to Migration Doc once that is ready
=> [1.0.0] Upgrade script to convert values.yaml to 1.0.0

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.0.0-beta.1

deploy/docs/Installation_with_Helm.md
It looks like installations to PROD require the endpoint - BUG https://jira.kumoroku.com/jira/browse/SUMO-131403
=> Added endpoint into helm CLI until the bug fix

deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Since we don't want to expose sourceHost any longer, removing it from the values.yaml file
=> remove sourceHost from values.yaml

deploy/helm/sumologic/values.yaml
V0.17 backport of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/560
=> Clean up tag names

deploy/helm/sumologic/conf/traces/traces.conf, deploy/helm/sumologic/values.yaml
Fix buffers in tracing configuration
=> Fix buffers according to 1.0.0

deploy/README.md, deploy/helm/sumologic/requirements.yaml
=> Bump Falco chart to 1.1.6

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare 1.0.0-beta.2

deploy/helm/sumologic/templates/hpa.yaml
=> Fix HPA for fluentd after changing it into statefulset

deploy/helm/sumologic/templates/service-headless.yaml
=> Add Zipkin write port to the Fluentd's headless service

deploy/helm/sumologic/values.yaml
Add etcd to control plane metrics
=> Add etcd to control plane metrics

deploy/docs/Best_Practices.md
Added a table of Contents, corrected cases for headers, renamed headers
=> ToC fo Best Practices

deploy/docs/Upgrading_with_Helm.md
Added a note asking customers to do a helm repo update before they run a helm upgrade on their clusters.
=> fix(Update_with_helm): Added helm repo update note

deploy/helm/sumologic/upgrade-1.0.0.sh
Update upgrade script to be suit with #588 changes
=> Update upgrade script to fix prometheus config

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare 1.0.0-rc.0

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v0.17.2

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v0.17.3

deploy/helm/sumologic/templates/events-configmap.yaml, deploy/helm/sumologic/templates/events-service-headless.yaml, deploy/helm/sumologic/templates/events-service.yaml, deploy/helm/sumologic/templates/events-statefulset.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> Adjust events naming to the new fluentd- schema

deploy/helm/sumologic/upgrade-1.0.0.sh
=> Fix the unbound variable 1 error in the upgrade script

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.0.0-rc.2

deploy/docs/v1_migration_doc.md
=> add migration doc - final

deploy/docs/v1_migration_doc.md
=> Upgrade docs fixes after review for #630

deploy/helm/sumologic/upgrade-1.0.0.sh, tests/upgrade_script/static/fluent_bit_casts.input.yaml, tests/upgrade_script/static/fluent_bit_casts.log, tests/upgrade_script/static/fluent_bit_casts.output.yaml, tests/upgrade_script/static/hooks.input.yaml, tests/upgrade_script/static/hooks.log, tests/upgrade_script/static/hooks.output.yaml
Re-cast to string for particular keys
Solves #633 #634
=> Re-cast to string for particular keys

deploy/docs/v1_migration_doc.md
Add rollback section to helm installation
=> Add rollback section to helm installation

deploy/helm/sumologic/upgrade-1.0.0.sh
=> Add upgrade doc link to the upgrade script

deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/values.yaml
=> add baseImage for thanos

tests/upgrade_script/run.sh
Replace grep in favor of sed for upgrade script tests
=> Replace grep in favor of sed for upgrade script tests

deploy/docs/v1_migration_doc.md
=> [fix] broken doc link

deploy/helm/sumologic/conf/logs/logs.source.containers.conf, deploy/helm/sumologic/conf/logs/logs.source.default.conf, deploy/helm/sumologic/conf/logs/logs.source.systemd.conf
=> [fix] FluentD's overrideOuputConf needs some indenting

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v0.17.4

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.0.0-rc.3

deploy/README.md
=> Add upgrade doc link to the main docs page

README.md, deploy/docs/Helm3.md, deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/Upgrading_with_Helm.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md, deploy/docs/v1_migration_doc.md
=> Docs update before the 1.0 release

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
This PR prepares the code for the 1.0 release 🎉
=> Prepare the v1.0.0 release

deploy/docs/v1_migration_doc.md
Add troubleshooting section to upgrade doc.
=> Add troubleshooting section to upgrade doc.

deploy/docs/v1_migration_doc.md
=> Add troubleshooting section to upgrade doc. (#673)

deploy/helm/sumologic/requirements.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> Update falco helm chart

deploy/helm/sumologic/requirements.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> Update fluent-bit helm chart

deploy/helm/sumologic/requirements.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> Update metrics server helm chart

deploy/helm/sumologic/conf/buffer.output.conf, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Change default retry_timeout to 1h
=> Change default retry_timeout to 1h

deploy/helm/sumologic/conf/setup/setup.sh, deploy/helm/sumologic/conf/setup/sumo-k8s.tf, deploy/kubernetes/setup-sumologic.yaml.tmpl
* Fix importing terraform objects
* Fix generating additional fields (flat structure)
=> Fix terraform import and additional fields

deploy/helm/sumologic/conf/setup/setup.sh, deploy/kubernetes/setup-sumologic.yaml.tmpl
Handle Collector name with spaces
=> Handle Collector name with spaces

deploy/helm/sumologic/templates/statefulset.yaml
=> fix indentation

deploy/helm/sumologic/conf/setup/sumo-k8s.tf, deploy/helm/sumologic/templates/_helpers.tpl, deploy/helm/sumologic/values.yaml, tests/terraform/run.sh, tests/terraform/static/all_fields.input.yaml, tests/terraform/static/all_fields.output.yaml, tests/terraform/static/collector_fields.input.yaml, tests/terraform/static/collector_fields.output.yaml, tests/terraform/static/default.output.yaml, vagrant/provision.sh
Dynamic generation of terraform properties
=> Dynamic generation of terraform properties

tests/terraform/run.sh, tests/terraform/static/all_fields.output.yaml, tests/terraform/static/collector_fields.output.yaml, tests/terraform/static/default.output.yaml, tests/upgrade_script/run.sh
=> Fix terraform tests

deploy/helm/fluent-bit-overrides.yaml, deploy/helm/sumologic/values.yaml
=> add db for systemd

deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml, deploy/helm/sumologic/values.yaml, tests/tracing/run.sh, tests/tracing/static/collection-monitoring-false.input.yaml, tests/tracing/static/collection-monitoring-false.output.yaml, tests/tracing/static/simple.input.yaml, tests/tracing/static/simple.output.yaml
Adds a maximum batch size limit and leverages new tag structure
=> Otelcol config update with batch size and source processor

deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/values.yaml
Enabled on Long for Zaidan, had over 50% memory reduction in Prometheus
=> enable wal compression by default

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.1.0-beta.0

deploy/docs/Installation_with_Helm.md, deploy/docs/Terraform.md
=> Add terraform documentation

deploy/docs/additional_prometheus_configuration.md, deploy/docs/v1_conf_examples.md, deploy/helm/fluent-bit-overrides.yaml, deploy/helm/metrics-server-overrides.yaml, deploy/helm/prometheus-overrides.yaml
Update documentation for additional sources. Waiting for adding logs and events, because it can change configuration structure
=> Update documentation for additional sources

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.1.0-beta.2

deploy/docs/Best_Practices.md
=> Port missing docs from old repo

deploy/helm/sumologic/values.yaml
=> Remove unused grafana.enabled key

deploy/docs/Best_Practices.md
=> Update docs to show how to filter messages by content.

deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> increase fluentd evets sts resource limits

deploy/helm/sumologic/templates/events-statefulset.yaml, deploy/helm/sumologic/values.yaml
Addition to https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/681
=> Add extra volumes for events

deploy/helm/fluent-bit-overrides.yaml, deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/values.yaml
=> Fix comment for the prometheus-operator.enabled key

deploy/docs/v1_migration_doc.md
The namespace and secret do not need to be deleted.
=> update non-helm migration steps to only what is needed

deploy/README.md
=> Bump supported k8s versions

deploy/README.md
=> Update used charts versions in the documentation

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.1.0-rc.0

deploy/helm/sumologic/values.yaml
=> Update ref to falco in values.yaml

deploy/README.md
=> Bump supported AKS versions

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.1.0-rc.1

deploy/docs/Installing_Behind_Proxy.md
Add doc for installation behind a proxy.
=> Add doc for installation behind a proxy.

deploy/docs/Non_Helm_Installation.md
=> Use the kubernetes-tools 1.0 release version in docs

README.md, deploy/docs/Upgrading_with_Helm.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md, deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.1.0

deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/SideBySidePrometheus.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md
=> doc update misses (#812) for release-v1.1

deploy/docs/Terraform.md, deploy/helm/sumologic/values.yaml
Add docs on creating processing rules with setup job.
=> Add docs on creating processing rules with setup job.

deploy/docs/Non_Helm_Installation.md
Make upgrade steps a bit more clear and perscriptive.
=> Improve non-helm upgrade docs

deploy/docs/Non_Helm_Installation.md, deploy/docs/Terraform.md, deploy/helm/sumologic/values.yaml
=> backport docs 1.1

deploy/docs/additional_prometheus_configuration.md
=> Fixing a typo in additional Prometheus configuration

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> prepare v.1.2.0-beta.0

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.2.0-beta.1

deploy/docs/v1_conf_examples.md
=> Clarify docs for custom logs conf

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.2.0-beta.2

deploy/docs/HelmChartConfiguration.md
This updates helm chart configuration doc with changes introduced in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/822 and https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/819
=> Update helm chart configuration doc with podLabels and podAnnotations changes

deploy/docs/existingPrometheusDoc.md
Helm chart configuration moved to helm chart dir
Additional change for b377afe
=> Fix for link in the Prometheus doc

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.2.0

deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml, deploy/helm/sumologic/templates/configmap.yaml
Revert removal of traces config
=> Revert removal of traces config

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.2.1

deploy/docs/Best_Practices.md
=> Update file buffer documentation

deploy/docs/Best_Practices.md
=> Add steps for disabling logs, metrics, or falco

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.2.2-rc.0

.travis.yml, ci/build.sh, deploy/helm/fluent-bit-overrides.yaml, deploy/helm/metrics-server-overrides.yaml, deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/upgrade-1.0.0.sh, tests/terraform/run.sh, tests/terraform/static/all_fields.output.yaml, tests/terraform/static/collector_fields.output.yaml, tests/terraform/static/conditional_sources.output.yaml, tests/terraform/static/default.output.yaml, tests/terraform/static/strip_extrapolation.output.yaml, tests/terraform/static/traces.output.yaml, tests/tracing/run.sh, tests/tracing/static/collection-monitoring-false.output.yaml, tests/tracing/static/simple.output.yaml, tests/upgrade_script/run.sh
=> Add Tests into Travis CI

tests/terraform/run.sh, tests/terraform/static/all_fields.output.yaml, tests/terraform/static/collector_fields.output.yaml, tests/terraform/static/conditional_sources.output.yaml, tests/terraform/static/default.output.yaml, tests/terraform/static/strip_extrapolation.output.yaml, tests/terraform/static/traces.output.yaml, tests/tracing/run.sh, tests/tracing/static/collection-monitoring-false.output.yaml, tests/tracing/static/simple.output.yaml
=> Use non-hardcoded current chart version in CI tests

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.2.2

deploy/helm/sumologic/templates/logs-pdb.yaml, deploy/helm/sumologic/templates/metrics-pdb.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> add pdb for fluentd logs and metrics

deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
=> add container_cpu_cfs_throttled_seconds_total metric

ci/build.sh, deploy/helm/sumologic/requirements.yaml, deploy/helm/sumologic/values.yaml
=> change prometheus-operator repo

deploy/helm/sumologic/requirements.yaml
=> add alias for kube-prometheus-stack helm chart

deploy/helm/sumologic/templates/events-statefulset.yaml, deploy/helm/sumologic/templates/metrics-statefulset.yaml, deploy/helm/sumologic/templates/statefulset.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> Support all securityContext resources

deploy/README.md
=> Add EKS 1.17 support information to the docs

deploy/README.md
=> v1.2 backport - add EKS 1.17 support information to the docs

.travis.yml, ci/build.sh
=> Add simple permissive shellcheck for ci/build.sh script

deploy/helm/sumologic/requirements.yaml, deploy/helm/sumologic/values.yaml, vagrant/values.yaml
Add telegraf operator helm chart to the requirements
=> Add telegraf operator helm chart to the requirements

deploy/helm/sumologic/conf/setup/setup.sh, deploy/helm/sumologic/templates/setup/setup-job.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/setup-sumologic.yaml.tmpl, tests/terraform/static/all_fields.output.yaml, tests/terraform/static/collector_fields.output.yaml, tests/terraform/static/conditional_sources.output.yaml, tests/terraform/static/default.output.yaml, tests/terraform/static/strip_extrapolation.output.yaml, tests/terraform/static/traces.output.yaml
* Do not proxy kubernetes internal traffic
* Update terraform tests
=> Backport #920 - do not proxy kubernetes internal traffic

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.2.3

deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/SideBySidePrometheus.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md
=> Point to correction section in Fields doc for pre-req step

deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/Performance.md, deploy/docs/SideBySidePrometheus.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md
Based on Vaibhav's performance tests.
I wasn't sure where to link to this doc, just adding it for now. Anybody have any suggestions? :)
=> add performance doc

deploy/helm/sumologic/README.md
Add proxy options to the README.md
=> Add proxy options to the README.md

deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/SideBySidePrometheus.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md, deploy/helm/sumologic/README.md
Added steps to install in Openshift platform, both via helm and non-helm.
=> Openshift docs

vagrant/Makefile, vagrant/k8s/application_metrics/redis/bitnami/values.prometheus.yaml, vagrant/k8s/application_metrics/redis/bitnami/values.telegraf.yaml, vagrant/k8s/application_metrics/redis/docker/statefulset.yaml
Add redis to the vagrant environment
=> Add redis to the vagrant environment

vagrant/Makefile, vagrant/k8s/application_metrics/jmx/jmxexporter/docker/Dockerfile, vagrant/k8s/application_metrics/jmx/jmxexporter/docker/configmap.yaml, vagrant/k8s/application_metrics/jmx/jmxexporter/docker/statefulset.yaml, vagrant/k8s/application_metrics/jmx/jolokia/agent/Dockerfile, vagrant/k8s/application_metrics/jmx/jolokia/agent/entrypoint.sh, vagrant/k8s/application_metrics/jmx/jolokia/agent/statefulset.yaml, vagrant/k8s/application_metrics/jmx/jolokia/docker/Dockerfile, vagrant/k8s/application_metrics/jmx/jolokia/docker/statefulset.yaml
Add jmx application to the vagrant
=> Add jmx application to the vagrant

deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
Forward redis metrics to the sumologic
=> Forward redis metrics to the sumologic

deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/values.yaml
=> add resource limits for prometheus container

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.3.0-beta.0

vagrant/provision.sh, vagrant/scripts/get-dashboard-token.sh
=> Extract script for getting the dashboard token

deploy/helm/sumologic/templates/_helpers.tpl, deploy/helm/sumologic/templates/psp.yaml, deploy/helm/sumologic/templates/scc.yaml
=> refactor: use custom template names for scc and psp metadata and labels

deploy/docs/existingPrometheusDoc.md
=> Doc: use variable for prometheus operator chart name

deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> change cpu limits format

deploy/helm/sumologic/values.yaml, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> bugfix: setup job is faster when it's given more CPU

deploy/README.md, deploy/helm/sumologic/requirements.yaml
=> revert prom-operator version bump

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.3.0-beta.1

ci/build.sh, deploy/README.md, deploy/docs/existingPrometheusDoc.md, deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/README.md, deploy/helm/sumologic/requirements.yaml, deploy/helm/sumologic/values.yaml
=> Revert to using helm stable for Prometheus Operator chart

deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
Reverts SumoLogic/sumologic-kubernetes-collection#976
=> Revert "Revert the FluentD image version to 1.2.3"

deploy/helm/prometheus-overrides.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> add back all resource limits and turn off kubelet resource scraping

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> prep v1.3.0-beta2

README.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md, deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.3.0

deploy/helm/sumologic/templates/_helpers.tpl, deploy/helm/sumologic/templates/setup/setup-job.yaml, deploy/helm/sumologic/templates/setup/setup-scc.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Add scc for setup job

deploy/docs/Best_Practices.md
Fix link in best prcatices doc
=> Fix link in best practices doc

deploy/helm/sumologic/values.yaml
v1.3 series of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1012
=> Otc v0.12 on v1.3

deploy/helm/sumologic/templates/setup/setup-custom-configmap.yaml, deploy/kubernetes/setup-sumologic.yaml.tmpl, tests/terraform_custom/static/empty.output.yaml
Always create custom setup configmap
=> Always create custom setup configmap

Vagrantfile
=> Bump Vagrant VM to Ubuntu 20.04

deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> Enable FluentD file persistence by default

deploy/helm/sumologic/values.yaml
Updates OpenTelemetry Collector to v0.12.0, which includes numerous bug fixes, such as correctly handling Service Name in asynchronous span Jaeger workflow scenarios
=> Upgrade OpenTelemetry Collector to v0.12

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.3.1-rc.0

deploy/helm/sumologic/README.md, deploy/helm/sumologic/templates/otelcol-deployment.yaml, deploy/helm/sumologic/templates/otelcol-service.yaml, deploy/helm/sumologic/values.yaml
=> Rename OTC setting metrics_enabled into metrics.enabled

deploy/helm/sumologic/templates/scc.yaml
Add persistentVolumeClaim to scc
=> Add persistentVolumeClaim to scc

deploy/helm/sumologic/values.yaml
=> add comment for using maxUnavailable parameter in pdb

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.3.1

deploy/helm/sumologic/templates/_helpers.tpl, deploy/helm/sumologic/templates/metrics-pdb.yaml
=> Add metrics pdb template

deploy/helm/sumologic/templates/otelcol-deployment.yaml, deploy/helm/sumologic/values.yaml
=> Add extraEnvVars to the otelcol

deploy/helm/sumologic/templates/otelcol-deployment.yaml, deploy/helm/sumologic/values.yaml
Add extraVolumeMounts and extraVolumes to the otelcol
=> Add extraVolumeMounts and extraVolumes to the otelcol

deploy/helm/sumologic/values.yaml, vagrant/values.yaml
Add falco rules to whitelist Sumo Logic collection known exceptions to prevent falco complaining about them.
=> Add falco rules based on images

deploy/README.md, deploy/docs/Alpha_Release_Guide.md, deploy/docs/Installation_with_Helm.md, deploy/docs/SideBySidePrometheus.md, deploy/docs/Troubleshoot_Collection.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md, deploy/docs/v1_migration_doc.md, deploy/helm/sumologic/requirements.yaml, vagrant/README.md, vagrant/provision.sh
=> Drop helm2 support

deploy/helm/sumologic/README.md, deploy/helm/sumologic/conf/events/events.conf, deploy/helm/sumologic/conf/logs/logs.output.conf, deploy/helm/sumologic/conf/metrics/metrics.output.conf, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Enable compression in fluentd output plugin by default
=> Enable compression in fluentd output plugin by default

deploy/docker/Dockerfile
This will be used in e.g. https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1064
=> Add curl and jq to docker image

deploy/docs/Installation_with_Helm.md
Make markdown lint happy, update TOC and make markdown more readable by splitting lines.
=> Update helm installation docs

deploy/helm/sumologic/requirements.yaml
=> Use new Helm stable repo URL

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.3.2-rc.0

deploy/helm/sumologic/requirements.yaml
=> Use new Helm stable repo URL for metrics-server

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.3.2-rc.1

deploy/helm/sumologic/templates/otelcol-deployment.yaml
=> Add OTLP HTTP port

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.3.2

ci/build.sh, deploy/docs/Kube-Prometheus.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/additional_prometheus_configuration.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md, tests/functions.sh, vagrant/k8s/receiver-mock.yaml
Bump sumologic/kubernetes-tools to 2.0.0
=> Bump sumologic/kubernetes-tools to 2.0.0

deploy/docs/v1_migration_doc.md
=> Adds Kubernetes App update info after succesfull migration

deploy/docs/v1_migration_doc.md
Adds Kubernetes App update info after successful migration
It's a backport for the commit 72e7a28e7d9967e8064717dfad64b974f2f9fdb9
PR https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/856
=> Adds Kubernetes App update info after successful migration (backport of #856)

deploy/docs/Installation_with_Helm.md, deploy/docs/Migration_Steps.md, deploy/docs/existingPrometheusDoc.md
Markdown docs cleanup and fixing some markdownlint issues.
=> Markdown docs cleanup

deploy/helm/sumologic/conf/setup/custom.sh, deploy/helm/sumologic/conf/setup/setup.sh, tests/terraform/static/all_fields.output.yaml, tests/terraform/static/collector_fields.output.yaml, tests/terraform/static/conditional_sources.output.yaml, tests/terraform/static/custom.output.yaml, tests/terraform/static/default.output.yaml, tests/terraform/static/disable_default_metrics.output.yaml, tests/terraform/static/strip_extrapolation.output.yaml, tests/terraform/static/traces.output.yaml
Exit from setup job in case of fail
=> Exit from setup job in case of fail

deploy/README.md, deploy/docs/Authenticating_with_docker_registry.md, deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/helm/sumologic/values.yaml
Update docs regarding pullSecrets
=> Update docs regarding pullSecrets

deploy/docker/Dockerfile, deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/Terraform.md, deploy/helm/sumologic/conf/cleanup/cleanup.sh, deploy/helm/sumologic/conf/logs/logs.source.containers.conf, deploy/helm/sumologic/conf/setup/setup.sh, deploy/helm/sumologic/conf/setup/variables.tf, deploy/helm/sumologic/templates/_helpers.tpl, deploy/helm/sumologic/values.yaml, fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb, tests/terraform/static/all_fields.output.yaml, tests/terraform/static/collector_fields.output.yaml, tests/terraform/static/conditional_sources.output.yaml, tests/terraform/static/custom.output.yaml, tests/terraform/static/default.output.yaml, tests/terraform/static/disable_default_metrics.output.yaml, tests/terraform/static/strip_extrapolation.output.yaml, tests/terraform/static/traces.output.yaml
=> Docs cleanup - capitalize proper names like Kubernetes or Terraform

deploy/docs/Dev.md
Add documentation for dev helm charts.
=> Add documentation for dev helm charts

deploy/helm/sumologic/requirements.yaml, deploy/helm/sumologic/values.yaml
Migrate to new fluent-bit helm chart. Due to the changes required to migrate, this will be considered a breaking change.
=> Migrate to new fluent-bit helm chart.

deploy/helm/sumologic/requirements.yaml
=> Update Falco to 1.5.4

deploy/docs/v1_conf_examples.md, deploy/docs/v1_migration_doc.md
=> v1 migration docs refactor

deploy/docs/Best_Practices.md
=> Refactor best practices doc

ci/build.sh
=> Add pushing of dev helm charts into dev directory

ci/build.sh
Reverts SumoLogic/sumologic-kubernetes-collection#1117
Due to [errors](https://travis-ci.com/github/SumoLogic/sumologic-kubernetes-collection/jobs/442540187#L1529) I need to revert it now.
=> Revert "Add pushing of dev helm charts into dev directory"

ci/build.sh
=> Add missing space in helm merge command

.github/CODEOWNERS
=> Add github CODEOWNERS

artifacthub-repo.yml
Add repositoryID to metadata file, required to receive label named [Verified Publisher](https://github.com/artifacthub/hub/blob/master/docs/repositories.md#verified-publisher).
=> Add repositoryID to metadata file

deploy/helm/sumologic/conf/logs/logs.source.systemd.conf
=> Fix fluentd systemd logs dropping (typo)

.travis.yml, README.md, ci/build.sh, deploy/docs/v1_conf_examples.md, deploy/docs/v1_migration_doc.md, deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml
=> Migrate the default git branch from master to main

deploy/helm/sumologic/Chart.yaml
=> Add tracing to the helm chart description

deploy/docs/Kube-Prometheus.md, deploy/docs/Performance.md, deploy/docs/SideBySidePrometheus.md, deploy/docs/Troubleshoot_Collection.md, deploy/docs/additional_prometheus_configuration.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md
=> Update docs from prometheus-operator to kube-prometheus-stack

deploy/docs/Installation_with_Helm.md
=> Add cleanup docs

deploy/helm/sumologic/conf/logs/logs.source.systemd.conf, deploy/kubernetes/fluentd-sumologic.yaml.tmpl
=> Drop kubelet/systemd logs if they are disabled

deploy/helm/falco-overrides.yaml, deploy/helm/fluent-bit-overrides.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Migrate off of the Docker Hub images into GitHub packages

.github/workflows/main.yml, Makefile, ci/build.sh, ci/shellcheck.sh, ci/tests.sh, vagrant/Makefile
Start using Github Actions for CI.
For now it works for PRs but further work is required to handle github environment variables for pushing docker images purposes.
=> Use Github Actions for CI

.github/ISSUE_TEMPLATE/bug_report.md
Template is generated through repository settings.
=> Update issue templates - bug report

.github/ISSUE_TEMPLATE/feature_request.md
Template is generated through repository settings.
=> Update issue template for feature request

.github/workflows/dev_builds.yml, .github/workflows/pull_requests.yml, .github/workflows/release_builds.yml, Makefile, ci/_build_functions.sh, ci/_test_functions.sh, ci/build.sh, ci/push.sh, ci/tests.sh
This introduces pushing helm chart and docker image for `main` branch, `release` branches and for tags.
There are 3 separate workflows:
- `PRs checks` - checks for PRs for `main` branch
- `Dev builds` - for `main` and release branches; building docker images, pushing it to docker hub and pushing helm chart to dev repo
- `Release builds` - for release tags; building docker images, pushing it to docker hub and pushing helm chart to main primary repo
=> Add Github Actions build and push actions

.github/workflows/pull_requests.yml, .yamllint.yaml, Makefile, deploy/helm/sumologic/values.yaml, vagrant/Makefile, vagrant/provision.sh
=> Add yamllint to CI

.github/workflows/pull_requests.yml
Run checks on release branches on Github Actions
=> Run checks on release branches on Github Actions

vagrant/Makefile
=> Improve vagrant's Makefile

ci/_build_functions.sh
=> Fix pushing helm charts

_layouts/default.html
Add favicon to Helm Chart page
=> Add favicon to Helm Chart page

_layouts/default.html
=> Add type to favicon

deploy/helm/sumologic/Chart.yaml
=> Upgrade Kube Prometheus Stack to 12.3.0

deploy/helm/sumologic/Chart.yaml
=> Upgrade Fluent Bit to 0.7.10 and Falco to 1.5.5

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml
=> Prepare v1.3.3-rc.0

ci/_build_functions.sh
=> Backport CI fix

deploy/docs/Troubleshoot_Collection.md
Update missing kube scheduler and controller manager metrics doc
=> Update missing kube scheduler and controller manager metrics doc

deploy/helm/sumologic/values.yaml
=> Update scheduler metrics

.travis.yml, ci/build_travis.sh
=> Add travis for overrides

.github/workflows/pull_requests.yml, ci/build_travis.sh, deploy/helm/falco-overrides.yaml, deploy/helm/fluent-bit-overrides.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
Replace ghcr.io with public AWS ECR: https://gallery.ecr.aws/u5z5f8z6/kubernetes-fluentd
=> Replace ghcr.io with public AWS ECR

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.3.3-rc.1

deploy/helm/sumologic/Chart.yaml
=> Upgrade Fluent Bit to 0.7.12 and Kube Prometheus Stack to 12.7.0

deploy/helm/sumologic/Chart.yaml
=> Upgrade Fluent Bit to 0.7.13

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml
=> Prepare v2.0.0-beta.0

deploy/docker/setup/Makefile, deploy/helm/sumologic/values.yaml
=> Use sumologic alias for ECR

deploy/helm/sumologic/Chart.yaml
=> Upgrade Kube Prometheus Stack to 12.8.0 and Falco to 1.5.6

ci/_build_functions.sh, deploy/docs/Kube-Prometheus.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/additional_prometheus_configuration.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md, tests/functions.sh
=> Bump kubernetes-tools to 2.1.0

deploy/helm/sumologic/Chart.yaml
=> Upgrade Falco to 1.5.7

ci/build_travis.sh
=> Unblock 1.3 CI

ci/_build_functions.sh, deploy/docs/Kube-Prometheus.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/additional_prometheus_configuration.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md, tests/functions.sh, vagrant/k8s/receiver-mock.yaml
=> Bump kubernetes-tools to 2.2.0

deploy/helm/sumologic/upgrade-2.0.0.sh
Since `yq` `4.0.0` is out with a breaking API https://github.com/mikefarah/yq/releases/tag/4.0.0 we need to limit supported `yq` versions in upgrade script to  be less than `4.0.0`
=> Don't support yq version 4.0 and above in migration script v2

.github/workflows/pull_requests.yml, vagrant/provision.sh
https://github.com/helm/helm/releases/tag/v2.17.0
=> Bump Helm 2 from 2.16.11 to 2.17.0 in CI

deploy/helm/sumologic/README.md
=> Fix typo in README

deploy/docs/Installation_with_Helm.md
=> Update docs to contain information about setup job creating fields

deploy/docs/Installation_with_Helm.md, deploy/helm/sumologic/templates/checks.txt
Related PR: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1240
=> Document kubernetes version check when installing with helm

deploy/helm/sumologic/values.yaml
rel: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/releases/tag/v2.0.0-beta.1
=> Update sumologic/kubernetes-fluentd image to 2.0.0-beta.1

deploy/helm/sumologic/templates/scc.yaml, deploy/helm/sumologic/templates/setup/setup-scc.yaml
=> Use minimal scc permissions

deploy/helm/sumologic/Chart.yaml
=> Upgrade Kube Prometheus Stack to 12.8.1

.github/workflows/release_builds.yml, ci/_build_functions.sh
Add pushing container images to https://gallery.ecr.aws/sumologic/kubernetes-fluentd when publishing 1.3 releases.
=> Add ECR push to 1.3 branch

.github/pull_request_template.md
=> Remove ci/build.sh from pull request template

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.3.5-rc.0

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/values.yaml, deploy/kubernetes/fluentd-sumologic.yaml.tmpl, deploy/kubernetes/setup-sumologic.yaml.tmpl
=> Prepare v1.3.5

deploy/docker/Dockerfile
=> Bump Fluentd from 1.11.1 to 1.11.5

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/README.md, deploy/helm/sumologic/values.yaml
Prepare chart for the v2.0.0-rc.0 release
---
=> Prepare v2.0.0-rc.0

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/README.md, deploy/helm/sumologic/values.yaml
=> Prepare v2.0.0-rc.1

deploy/helm/sumologic/Chart.yaml
=> Upgrade Kube Prometheus Stack to 12.10.6

deploy/docs/v2_migration_doc.md
=> Add output yaml flag to helm get values

deploy/docs/v2_migration_doc.md
Update v2 migration docs about base upgrade version
---
=> Update v2 migration docs about base upgrade version

deploy/helm/sumologic/upgrade-2.0.0.sh, tests/upgrade_v2_script/static/fluent_bit.input.yaml, tests/upgrade_v2_script/static/fluent_bit.log, tests/upgrade_v2_script/static/fluent_bit.output.yaml, tests/upgrade_v2_script/static/fluentd_persistence_true.log, tests/upgrade_v2_script/static/image_rename.log, tests/upgrade_v2_script/static/metrics_server.log, tests/upgrade_v2_script/static/otelcol_image_name.log, tests/upgrade_v2_script/static/prometheus_operator_valid.log, tests/upgrade_v2_script/static/prometheus_remote_write_regexes.log, tests/upgrade_v2_script/static/prometheus_remote_write_regexes_changed_values.log, tests/upgrade_v2_script/static/prometheus_remote_write_timeout.log, tests/upgrade_v2_script/static/prometheus_service_monitors.log, tests/upgrade_v2_script/static/prometheus_whole_config.log, tests/upgrade_v2_script/static/sumologic_collector_fields.log, tests/upgrade_v2_script/static/sumologic_sources.log
=> Add v2 migration logic for fluent-bit section

deploy/helm/sumologic/templates/otel-agent-daemonset.yaml, deploy/helm/sumologic/templates/otel-agent-service.yaml, deploy/helm/sumologic/templates/otelcol-deployment.yaml, deploy/helm/sumologic/templates/otelcol-service.yaml, deploy/helm/sumologic/values.yaml, tests/tracing/static/collection-monitoring-false.output.yaml, tests/tracing/static/simple.output.yaml
=> Upgrade OTC to 0.16.0-sumo

deploy/helm/sumologic/README.md, deploy/helm/sumologic/upgrade-2.0.0.sh, deploy/helm/sumologic/values.yaml, tests/upgrade_v2_script/static/fluent_bit.log, tests/upgrade_v2_script/static/fluent_bit.output.yaml
Rename the variable so it's more clear what should go there
---
=> Rename CHART variable into FLUENTD_LOGS_SVC

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/README.md, deploy/helm/sumologic/values.yaml
=> Prepare v2.0.0-rc.2

deploy/docs/v2_migration_doc.md
Add information about warning when resource managed by helm is modified
---
=> Add information about warning when resource managed by helm is modified

deploy/helm/sumologic/upgrade-2.0.0.sh, tests/upgrade_v2_script/static/fluent_bit.log, tests/upgrade_v2_script/static/fluentd_persistence_false.log, tests/upgrade_v2_script/static/fluentd_persistence_true.log, tests/upgrade_v2_script/static/image_rename.log, tests/upgrade_v2_script/static/metrics_server.log, tests/upgrade_v2_script/static/otelcol_image_name.log, tests/upgrade_v2_script/static/prometheus_operator_valid.log, tests/upgrade_v2_script/static/prometheus_remote_write_regexes.log, tests/upgrade_v2_script/static/prometheus_remote_write_regexes_changed_values.log, tests/upgrade_v2_script/static/prometheus_remote_write_timeout.log, tests/upgrade_v2_script/static/prometheus_service_monitors.log, tests/upgrade_v2_script/static/prometheus_whole_config.log, tests/upgrade_v2_script/static/sumologic_collector_fields.log, tests/upgrade_v2_script/static/sumologic_sources.log
Update v2 migration script logs
---
=> Update v2 migration script logs

deploy/helm/sumologic/upgrade-2.0.0.sh, tests/upgrade_v2_script/static/fluent_bit.log
=> v2 migration script - change wording when unexpected fluent-bit section encountered

deploy/docs/SideBySidePrometheus.md, deploy/docs/existingPrometheusDoc.md
Add prom oper compatibility note to side by side doc
---
=> Add prom oper compatibility note to side by side doc

deploy/docs/v2_migration_doc.md
Add migration instruction for non-helm users
---
=> Add migration instruction for non-helm users

deploy/docs/v2_migration_doc.md
Update v2 migration docs with migration script in container usage
---
=> Update v2 migration docs with migration script in container usage

deploy/docs/v2_migration_doc.md
v2 migration docs touch ups.
---
=> v2 migration docs touch up

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/README.md, deploy/helm/sumologic/values.yaml
=> Prepare v2.0.0-rc.3

README.md, deploy/README.md, deploy/helm/sumologic/upgrade-2.0.0.sh
=> Update documentation for the v2.0.0 release

deploy/README.md
=> Upgrade the subcharts versions

deploy/docs/Installation_with_Helm.md, deploy/helm/sumologic/README.md, deploy/helm/sumologic/templates/cleanup/cleanup-configmap.yaml, deploy/helm/sumologic/templates/cleanup/cleanup-job.yaml, deploy/helm/sumologic/values.yaml, tests/upgrade_v2_script/static/image_rename.input.yaml, tests/upgrade_v2_script/static/image_rename.output.yaml, tests/upgrade_v2_script/static/sumologic_collector_fields.input.yaml, tests/upgrade_v2_script/static/sumologic_collector_fields.output.yaml, vagrant/values.yaml
=> Rename cleanUpEnabled to cleanupEnabled

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/README.md, deploy/helm/sumologic/values.yaml
=> Prepare 2.0.0

deploy/README.md
=> Add missing migration doc link

.github/workflows/backport_bot.yaml
Add backport bot: https://github.com/tibdex/backport so that we can use labels on PRs in order to backport them to other branches.
---
=> Add backport bot workflow

.github/workflows/backport_bot.yaml
=> Make bot the author of backport commits

deploy/docs/v2_migration_doc.md
=> Update v2 doc links to release-v2.0

deploy/docs/v2_migration_doc.md
=> Bump kubernetes-tools to 2.3.1 in v2 migration doc

.github/workflows/pull_requests.yml, Makefile
=> Add helm lint to CI

deploy/helm/sumologic/templates/otel-agent-daemonset.yaml
=> Fix ECR image repository name after migration for agent

deploy/helm/sumologic/Chart.yaml
=> Prepare 2.0.1

deploy/README.md
=> Add OpenShift 3.11 support info

deploy/docs/Best_Practices.md, deploy/helm/sumologic/upgrade-2.0.0.sh, deploy/helm/sumologic/values.yaml, tests/upgrade_v2_script/static/fluentd_persistence_false.log, tests/upgrade_v2_script/static/fluentd_whole_config.input.yaml
Update links in configuration files, values.yaml and its parts
to redirect user to documentation related to 2.0 release
---
=> Update links in configuration files, values.yaml and its parts

deploy/helm/sumologic/values.yaml
Change links to configuration files in values.yaml, replace `main` with `release-v1.3`.
---
=> Change links to configuration files in values.yaml

deploy/docs/v1_migration_doc.md
Manual backport of #1372 into release-v1.3
---
=> [Manual backport] Fix links to Prometheus and FluenBit deploy instuctions

deploy/docs/Best_Practices.md
Removed inaccurate/outdated information, added up-to-date information, cleaned up.
=> docs: Fix docs for annotations

deploy/helm/sumologic/Chart.yaml
Upgrade fluent-bit to 1.6.10
---
=> Upgrade fluent-bit to 1.6.10

README.md
=> Add deprecation date to the v1.3 release

deploy/README.md
=> Add additional Prometheus configuration doc link into main readme

deploy/docs/Best_Practices.md
=> doc: reword message into log

deploy/helm/sumologic/values.yaml
Changes:
- Use numeric Fluentd user ID in Dockerfile https://github.com/SumoLogic/sumologic-kubernetes-fluentd/pull/118
=> Upgrade Fluentd from 1.12.0-sumo-1.rc0 to rc.1

deploy/docs/Terraform.md
Remove traces from Terraform docs mentioned twice
=> Remove traces from Terraform docs mentioned twice

deploy/helm/sumologic/values.yaml
There are no changes from 1.12.0-sumo-1-rc.1.
=> Upgrade Fluentd to 1.12.0-sumo-1

deploy/helm/sumologic/Chart.yaml
=> Prepare v2.0.2-rc.0

deploy/helm/sumologic/Chart.yaml
=> Prepare v2.0.2

deploy/docs/additional_prometheus_configuration.md
=> docs: update sources in additional prometheus metrics

deploy/helm/sumologic/values.yaml
=> Use the ECR repository for dependencies: Fluent Bit, Telegraf and Falco

CONTRIBUTING.md
=> Add information about Vagrant environment

deploy/helm/sumologic/Chart.yaml
Diff since `v2.0.3-rc.0`:
* 3d6ffe31 Prepare v2.0.3-rc.1
* dd2a6163 Add information for Docker, CRI-O, containerd log parsing Add containerd Fluent Bit Parser Remove quetes for crio Parser to remove time parsing errors
=> Prepare v2.0.3-rc.1

deploy/docs/additional_prometheus_configuration.md
=> docs: update additional metrics due to fluentd errors

.github/workflows/backport_bot.yaml
=> Use backport app

.github/workflows/backport_bot.yaml
This reverts commit 0a7be6d6d34fe46cbf6b53fce25b0da1f0d19138 from https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1465
---
=> Revert "Use backport app"

.github/workflows/backport_bot.yaml
Backport 1b46da3983a78db73dd037d82e91f9240d2c10ca from #1471
=> [Backport release-v2.0] Change backport bot token

deploy/helm/sumologic/templates/_helpers.tpl, deploy/helm/sumologic/templates/logs-pdb.yaml, deploy/helm/sumologic/templates/metrics-pdb.yaml
Backport ca90142cf73890762b57813a3ce47200d209f63a from #1469
=> [Backport release-v2.0] Make pdb definitions and usage consistent

deploy/helm/sumologic/upgrade-2.0.0.sh, tests/upgrade_v2_script/static/prometheus_remote_write_regexes.output.yaml, tests/upgrade_v2_script/static/prometheus_remote_write_regexes_changed_values.output.yaml, tests/upgrade_v2_script/static/prometheus_remote_write_timeout_unspecified.input.yaml, tests/upgrade_v2_script/static/prometheus_remote_write_timeout_unspecified.log, tests/upgrade_v2_script/static/prometheus_remote_write_timeout_unspecified.output.yaml, tests/upgrade_v2_script/static/prometheus_whole_config.output.yaml
Fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1412
=> Fix v2.0.0 migration script not migrating remoteTimeout

deploy/helm/sumologic/upgrade-2.0.0.sh, tests/upgrade_v2_script/static/prometheus_remote_write_regexes.output.yaml, tests/upgrade_v2_script/static/prometheus_remote_write_regexes_changed_values.output.yaml, tests/upgrade_v2_script/static/prometheus_remote_write_timeout_unspecified.input.yaml, tests/upgrade_v2_script/static/prometheus_remote_write_timeout_unspecified.log, tests/upgrade_v2_script/static/prometheus_remote_write_timeout_unspecified.output.yaml, tests/upgrade_v2_script/static/prometheus_whole_config.output.yaml
Backport 81b5b949bffcc7899f4cf5305c3e4643f89dc150 from #1467
=> [Backport release-v2.0] Fix v2.0.0 migration script not migrating remoteTimeout

.github/workflows/pull_requests.yml, Makefile, ci/markdown_links_lint.sh, vagrant/Makefile
=> Add linter for markdown links

vagrant/provision.sh
=> Add k9s to the Vagrant box

deploy/helm/sumologic/values.yaml
Fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1461
=> Bump fluentd image to 1.12.0-sumo-2

deploy/helm/sumologic/Chart.yaml
=> Prepare v2.0.4-rc.1

deploy/helm/sumologic/Chart.yaml
=> Prepare v2.0.4

deploy/docs/Installation_with_Helm.md
Refactor the docs and specify `2.0.0` as an exemplar version to install instead of `1.0.0`.
=> Refactor helm installation docs

deploy/helm/sumologic/values.yaml
fluent-bit: disable keepalive to improve load balancing
---
=> fluent-bit: disable keepalive

deploy/helm/sumologic/Chart.yaml, deploy/helm/sumologic/README.md, deploy/helm/sumologic/values.yaml
Add Tailing Sidecar Operator as Helm Chart dependency
---
=> Add Tailing Sidecar Operator as Helm Chart dependency

deploy/helm/sumologic/values.yaml
Use https://github.com/SumoLogic/sumologic-kubernetes-fluentd/releases/tag/v1.12.0-sumo-4
=> Bump fluentd image to 1.12.0-sumo-4

deploy/helm/sumologic/Chart.yaml
=> Prepare v2.0.5-rc.0

deploy/docs/Troubleshoot_Collection.md
=> Add troubleshooting section about not running Prometheus pod

deploy/README.md, deploy/helm/sumologic/Chart.yaml
Fluent Bit to 0.15.0
Falco to 1.7.10
Metrics Server to 5.8.0
Tailing Sidecar Operator to 0.3.0
Upgrade correspoding documentation
---
=> Upgrade subcharts

deploy/helm/sumologic/Chart.yaml
=> Prepare v2.1.0-rc.2

deploy/helm/sumologic/values.yaml
=> Upgrade Fluentd to 1.12.0-sumo-0

deploy/helm/sumologic/Chart.yaml
=> Prepare v2.1.0

deploy/helm/sumologic/README.md, deploy/helm/sumologic/values.yaml, tests/upgrade_v2_script/static/fluentd_whole_config.input.yaml, tests/upgrade_v2_script/static/fluentd_whole_config.output.yaml, tests/upgrade_v2_script/static/otelcol_image_name.input.yaml, tests/upgrade_v2_script/static/otelcol_image_name.output.yaml
=> fix: Remove Helm warning for tolerations

deploy/helm/sumologic/Chart.yaml
=> Prepare v2.0.6

deploy/helm/sumologic/values.yaml
Changes:
- feat: Add per-container pod annotations (https://github.com/SumoLogic/sumologic-kubernetes-fluentd/pull/177)
=> chore: Upgrade Fluentd from 1.12.1-sumo-0 to 1.12.1-sumo-1

deploy/docs/Troubleshoot_Collection.md
=> Add troubleshooting section for the stuck PVCs

deploy/README.md, deploy/helm/sumologic/Chart.yaml
=> chore: upgrade metrics server to 5.8.4

deploy/helm/sumologic/Chart.yaml
=> Prepare v2.1.1-rc.0

deploy/docs/Best_Practices.md, deploy/helm/sumologic/README.md, deploy/helm/sumologic/values.yaml, tests/upgrade_v2_script/static/metrics_server.input.yaml
=> docs: fix links to helm charts

.github/workflows/pull_requests.yml, .markdown_link_check.json, README.md, deploy/docs/Alpha_Release_Guide.md, deploy/docs/Installation_with_Helm.md, deploy/docs/Non_Helm_Installation.md, deploy/docs/SideBySidePrometheus.md, deploy/docs/additional_prometheus_configuration.md, deploy/docs/existingPrometheusDoc.md, deploy/docs/standAlonePrometheus.md, deploy/helm/sumologic/README.md
Add markdown-link-check ([action](https://github.com/gaurav-nelson/github-action-markdown-link-check) & [tool](https://github.com/tcort/markdown-link-check)) in order to check for dead links.
---
=> Add markdown-link-check

README.md
=> doc: add v2.1 info into main readme

deploy/README.md
=> docs: fix tests matrix

deploy/helm/sumologic/Chart.yaml
=> Prepare v2.1.1-rc.1
