- .gitignore
- fluent-plugin-protobuf/README.md
- fluent-plugin-protobuf/lib/fluent/plugin/parse_protobuf.rb
- fluent-plugin-protobuf/test/plugin/test_parse_protobuf.rb
- fluent-plugin-protobuf/test/resources/multiple.json
- fluent-plugin-protobuf/test/resources/multiple.missing_value.json
- fluent-plugin-protobuf/test/resources/multiple.nan_value.json
- fluent-plugin-protobuf/test/resources/single.json
- fluent-plugin-protobuf/test/resources/single.missing_value.json
- fluent-plugin-protobuf/test/resources/single.nan_value.json
- fluent-plugin-protobuf/test/resources/timeseries.json
Fluentd parser plugin, input is from Prometheus, and output is timeseries event of the format expected by the datapoint output plugin.
I manually tested in my Kubernetes cluster running Prometheus and Fluentd, with this parser plugin and the datapoint output plugin. The messages are of the expected form:
```json
{"@metric":"container_cpu_schedstat_runqueue_seconds_total","endpoint":"http-metrics","id":"/system.slice/systemd-random-seed.service","instance":"172.20.91.206:10255","job":"kubelet","node":"ip-172-20-91-206.us-west-1.compute.internal","prometheus":"monitoring/prometheus-operator-prometheus","prometheus_replica":"prometheus-prometheus-operator-prometheus-0","service":"prometheus-operator-kubelet","@timestamp":1554246017731,"@value":0.0}
```
FYI @lei-sumo @maimaisie @yuting-liu
> protobuf parser plugin

- fluent-plugin-carbon-v2/README.md
- fluent-plugin-carbon-v2/lib/fluent/plugin/filter_carbon_v2.rb
- fluent-plugin-carbon-v2/test/plugin/test_filter_carbon_v2.rb
- fluent-plugin-carbon-v2/test/resources/datapoint.nested.spaces.json
- fluent-plugin-carbon-v2/test/resources/output.datapoint.nested.spaces.relabel.json
Since the space is not allowed in carbon V2 tags (name or value), add a parameter `space_as` to handle this case with replace all spaces in tags to a given string (by default use `_`)
> space_as parameter

- deploy/helm/overrides.yaml
- deploy/kubernetes/fluentd-sumologic.yaml
filter the metrics from write api config following https://docs.google.com/document/d/1z0KFYygDMahOXsXrAYPOwmSkTmSDTOhUdVwOwxXusv0
@frankreno @samjsong @lei-sumo 
FYI - @rvmiller89 @ggarg2906sumo
> select metrics

- deploy/docker/Dockerfile
- deploy/kubernetes/fluentd-sumologic.yaml
We want to split metrics to multiple HTTP sources to prevent blacklisting. Synced with Frank about the more common jobs we'd want to separate out, which included:
```
apiserver
cadvisor
kubelet
kube-controller-manager
kube-scheduler
kube-state*
node-exporter
prometheus-operator-*
```
We still include a catchall http source for those metrics not belonging to any of the above jobs.
@frankreno @bin3377 @lei-sumo 
FYI - @rvmiller89 @ggarg2906sumo
> Split metrics to multiple http sources

- fluent-plugin-carbon-v2/lib/fluent/plugin/filter_carbon_v2.rb
- fluent-plugin-datapoint/lib/fluent/plugin/out_datapoint.rb
- fluent-plugin-datapoint/test/plugin/test_out_datapoint.rb
- fluent-plugin-protobuf/lib/fluent/plugin/parser_protobuf.rb
- fluent-plugin-protobuf/test/plugin/test_parser_protobuf.rb
Fix the problem: only one point goes into pipeline in one HTTP request.
The problems are:
1. parse plug-ins need to implement `parse(text)` with `yield` return with time and record (e.g. hash)
refer to:
https://docs.fluentd.org/v0.12/articles/plugin-development#parser-plugins
https://github.com/fluent/fluentd/tree/master/lib/fluent/plugin
2. since single HTTP request may contains a list of TimeSeries not one, add a wrapper to make it a hash and also change datapoint plugin to handle it
update unit test make sure the time stamp and records are correctly bring in.
verified with private docker image on stag. the timeseries now giving points in fixed interval
> Byi fix timeseries

- deploy/helm/overrides.yaml
- deploy/kubernetes/fluentd-sumologic.yaml
update yaml files for:
- fix the changed name/job in metrics
- add cluster label
- remove cadvisor source since it's combined into kubelet
> Byi override yaml update

- deploy/kubernetes/fluentd-sumologic.yaml
We are switching to using the prometheus format plugin for metrics.
cc @ggarg2906sumo @MariePMcGarry @frankreno @lei-sumo
> Use prometheus format for metrics

- deploy/helm/overrides.yaml
- deploy/kubernetes/fluentd-sumologic.yaml
Fix two issues:
- remove any metrics with `container=POD` in cAdvisor container_*
- disable cookies support on all output plugins since it's useless and generating batch of "Unknown key: MAX-AGE = 604800" in fluentd log
FYI @frankreno @lei-sumo
> Byi remove container eq pod

- deploy/helm/overrides.yaml
- deploy/kubernetes/fluentd-sumologic.yaml
Tuning fluentd resource to fix [Context canceled issue](https://jira.kumoroku.com/jira/browse/SUMO-109456)
- Use `3` replica rather than `1`
- Reduce Memory from `2Gi` to `256Mi` (each container)
- Reduce CPU from `200m` to `100m` (each container)
Monitoring for couple of hours and looks like no more `context canceled` error in Prometheus log now
FYI - [definition of Kubernetes resource limitation](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/)
@frankreno @ggarg2906sumo
> Byi more replicas

- deploy/README.md
- deploy/kubernetes/setup.sh
Refine on the deployment script:
- add `jq` requirement in doc
- better error message when fail to create collector/source
> refine deployment script

- fluent-plugin-enhance-k8s-metadata/Gemfile
- fluent-plugin-enhance-k8s-metadata/README.md
- fluent-plugin-enhance-k8s-metadata/Rakefile
- fluent-plugin-enhance-k8s-metadata/fluent-plugin-enhance-k8s-metadata.gemspec
- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/test/helper.rb
- fluent-plugin-enhance-k8s-metadata/test/plugin/test_filter_enhance_k8s_metadata.rb
- add scaffold for new plugin, for build pass, not functional
> plugin scaffold

- deploy/helm/overrides.yaml
Hey Sumo,
Added in a regex match for `working_set_bytes` so that we can keep that metric and send it along to Sumo as well. `working_set_bytes` is used to track the working memory and is what the Kubernetes system uses to trigger OOMkills and restarts against the limits.
> Added in the working_set_bytes metric

- deploy/README.md
- deploy/kubernetes/fluentd-sumologic.yaml
- deploy/kubernetes/setup.sh
1. We update the setup script to include a source for logs and events, and attach `-metrics` suffix to metrics sources
2. We rename the secret to `sumologic` and include all endpoints in this single secret
3. We include an optional `cluster` field to the collector upon creation to keep it consistent with metrics
FYI - @ggarg2906sumo @yuting-liu @lei-sumo
> Update setup script for logs and events

- deploy/kubernetes/fluentd-sumologic.yaml
Based on the metrics I collected on CPU and Memory usage, I feel these are reasonable numbers for request and limit. This is sufficient for collecting up to 5MB/sec = 432GB/day rates. For greater loads, we can either increase the number of Fluentd replicas, or increase the CPU limits. Memory usage seems to be relatively stable even with higher loads.
FYI @ggarg2906sumo @lei-sumo @maimaisie @yuting-liu @frankreno
> Increase the resource limits on CPU and memory for fluentd deployment

- deploy/kubernetes/fluentd-sumologic.yaml
The current regex includes the full file path (which you get as part of the tag on tail plugin) in the pod_name.  This removes that.
> fix-pod-name-including-filepath

- deploy/helm/overrides.yaml
Adding container_spec_cpu_quota and container_spec_cpu_period so that we can actually calculate CPU %.
https://github.com/google/cadvisor/issues/2026#issuecomment-486134079
> CPU % extra metrics

- deploy/helm/overrides.yaml
* Sending all remote write related Prometheus metrics to Sumo
* This will allow us to monitor and manage Prometheus better on customer accounts by showing us the delays, replays, and instability in using Prometheus as a collector.
> Forwarding all Remote Write Metrics

- fluent-plugin-events/lib/fluent/plugin/in_events.rb
- fluent-plugin-events/lib/sumologic/kubernetes/connector.rb
After discovering the issue with k8s watch and list API regarding the resource version parameter, we redesigned the plugin flow. Now, the main thread acts as a monitor that loops forever (until the plugin is told to shut down) to update configmap and preemptively recreate the watch thread periodically. In more detail, it mainly does these things:
1. Pull latest resource version from the `List` API and store in configmap every `configmap_update_interval_seconds` (10s by default).
2. Check if the watch thread is running. If it's not, create the watcher thread using the resource version from the the configmap to resume from an earlier point in time if 
1. this is the first iteration (when the plugin just started and the watch thread does not exist)
2. the watcher thread somehow died (thread …
> Fix events plugin

- fluent-plugin-events/lib/fluent/plugin/in_events.rb
This PR adds a fluentd config param for specifying a list of event types to ingest. An error will be thrown if (1) the list is empty; (2) the list size exceeds three; (3) each element in the list is not one of ADDED, MODIFIED or DELETED (uses **case-insensitive** string compare, Ruby's `casecmp` is case insensitive and returns 0 if two strings are the same ignoring case, ie, `"ADDED".casecmp("addED") == 0`)
User can then have something like this:
```
<source>
@type events
type_selector ["ADDED", "deleted"]
</source>
```
> Add configurable event type filter

- deploy/helm/overrides.yaml
During testing we found the following metrics were missing:
- `cloudprovider_.*_api_request_duration_seconds.*`
- this was due to the job changing from `kube-controller-manager` to `kubelet`
- `container_memory_swap`
- this was due to a bug in the regex
- `container_spec_.*`
- this was due to trying to add multiple regex matchers in the same writeRelabelConfigs section, which I believe is piped and therefore the metrics were being dropped
- `node_memory_Free_bytes`
- this metric was renamed to `node_memory_MemFree_bytes` and `node_memory_SwapFree_bytes`
cc @ggarg2906sumo
> Fix missing metrics

- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- fluent-plugin-events/lib/fluent/plugin/in_events.rb
- fluent-plugin-events/lib/sumologic/kubernetes/connector.rb
Introduce new config param `resource_name` to take in a resource name to watch, defaulted to `events`. Use the same config map to store per-resource RV using key in the `resource-version-<resource-name>` format.
Minor change: rename `apiVersion` to `api_version` to follow the convention of other config param naming.
FYI @rvmiller89 @lei-sumo
> Parameterize resource name to support watching other resources in events plugin

- deploy/docker/Dockerfile
- deploy/docker/fluent.conf
- deploy/kubernetes/fluentd-sumologic.yaml
- fluent-plugin-enhance-k8s-metadata/fluent-plugin-enhance-k8s-metadata.gemspec
- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/connector.rb
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/service_monitor.rb
- fluent-plugin-enhance-k8s-metadata/test/helper.rb
- fluent-plugin-enhance-k8s-metadata/test/resources/endpoints_events.json
- fluent-plugin-enhance-k8s-metadata/test/resources/endpoints_list.json
- fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_service_monitor.rb
Decided this was a really stupidly large PR (mostly UT's and JSON I promise). Really the only big addition is just `service_monitor.rb`.
I used much of the watch thread logic from the Events plugin, but we don't need to persist state on restart since we don't care about data duplication.
Next step is to actually read from this hash and attach as metadata to the record. Decided to put that on hold until we make the changes in SUMO-112136 which will make this part easier.
If anything doesn't make sense or it looks inefficient or messy please let me know and I will fix 🙂 For an idea of what input and output looks like, feel free to look at the test JSONs and UT's.
> Add service metadata monitoring

- deploy/kubernetes/setup.sh
Adding support to ensure sourceCategory has a sensible default. By default it will be CLUSTER_NAME/SOURCE_NAME uless overridden via HTP header.  This is useful for merics and events.
> enable logical default source category for all http sources

- deploy/helm/overrides.yaml
Grafana and AlertManager are not needed and add resource consumption.  This will disable them by default, users can always adjust the values if they want them.
> disable Alertmanager and Grafana by default.

- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/service_monitor.rb
- fluent-plugin-events/lib/fluent/plugin/in_events.rb
It is found that having the `while` loop in the main thread blocks fluentd from running multiple input sources simultaneously. @samjsong found the `timer_execute` helper function from `timer` helper being used in the tail input source, which works with multiple tail sources. 
The `while` loops in events and service monitor are replaced by `timer_execute`. The sleep for the timer is determined by the sleep used in the `while` loops before (which is different from how often watcher recreates)
> Use fluentd helper function

- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/reader.rb
- fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_cache_strategy.rb
- fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_reader.rb
- fluent-plugin-prometheus-format/lib/fluent/plugin/filter_prometheus_format.rb
- fluent-plugin-prometheus-format/test/plugin/test_filter_prometheus_format.rb
- fluent-plugin-prometheus-format/test/resources/output.datapoint.nested.escape.json
- fluent-plugin-prometheus-format/test/resources/output.datapoint.nested.json
1) We remove the `kubernetes` prefix from all of the enhanced metadata attached by the `enhance_k8s_metadata` filter plugin, including `pod.labels.foo`
2) We rename `service` metadata to `prometheus_service` to avoid collision with the future attached `service` metadata.
Example metric output:
```
up {cluster="ssong-k8s-stag-9", _collector="kubernetes-1561673833", _collectorId="00000000061841EB", _contentType="Prometheus", _origin="kubernetes", _source="(default-metrics)", _sourceCategory="Http Input", _sourceId="00000000062EEE26", _sourceName="Http Input", deployment.name="kube-dns", endpoint="http-metrics", instance="100.115.226.65:9153", job="coredns", namespace="kube-system", pod.labels.k8s-app="kube-dns", pod.labels.pod-template-hash="2609061007", …
```
> Update default label behaviour for metadata enhancement plugin

- fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_cache_strategy.rb
- fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_reader.rb
The correct order for `assert_equal` should be `assert_equal expected, actual`.
The order is incorrect for some test files.
> Fix order of assert_equal in test files

- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Currently we are using the same label in the events deployment and the logs/metrics deployment. The `Service` we defined in the yaml uses this label as selector and opens two ports (one for prometheus and one for fluent-bit) for all pods that have this label, but it is not needed by the events collection. @abhi-sumo reported it caused some issue to a customer, so we will use a different label for events.
> Use different label in events deployment

- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_service_monitor.rb
We attach the service metadata to the record in the `enhance_k8s_metadata` filter plugin. In the off chance that a pod maps to more than one service, we merge the service names with an underscore after sorting alphabetically.
For example (screenshot from Sumo UI):
These pods started with just service `fluentd`, after which I attached another service `ssong-2nd`, then attached another service `middle-test`.
(also noticed one of the `service_monitor` UT's was missing an assert statement so I added that)
cc @Gourav2906 @abhi-sumo @frankreno
> Attach service metadata

- deploy/docker/Dockerfile
Switch default log_format to fields to ensure log metadata is delivered as expected.
> use-fields-log-format

- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Until we start tagging our `sumologic/kubernetes-fluentd` releases, we should be explicit about the `Always` imagePullPolicy and `0.0.0` tag.
Once we start tagging, we can change this to:
```
image: sumologic/kubernetes-fluentd:v1.blah
imagePullPolicy: IfNotPresent
```
> Make imagePullPolicy and latest tag explicit for now

- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Noticed on my kubernetes deployment with RBAC enabled, I was getting an error from `fluentd-events` pod with 403 error trying to "patch" the config map:
```ruby
2019-07-17 20:53:07 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:events_monitor error_class=Kubeclient::HttpError error="HTTP status code 403, configmaps \"fluentd-config-resource-version\" is forbidden: User \"system:serviceaccount:sumologic:fluentd\" cannot patch configmaps in the namespace \"sumologic\" for PATCH https://100.64.0.1/api/v1/namespaces/sumologic/configmaps/fluentd-config-resource-version"
2019-07-17 20:53:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/kubeclient-4.4.0/lib/kubeclient/common.rb:129:in `rescue in handle_exception'
```
Adding "patch" verb to configmaps capability fixed the …
> Add "patch" configmaps capability for fluentd

- deploy/helm/prometheus-overrides.yaml
Fix regex expression to collect remote_storage metrics from https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/42
> Fix remote storage regex prometheus override

- .travis.yml
- ci/build.sh
- deploy/test/test_docker.rb
When docker password env variable is present, and we are pushing to master (merging a PR), this will push a new docker image with auto-incrementing patch number.
It will use the latest non-alpha version to determine the next patch number to use and append `-alpha` to the version.
Example output:
```
Most recent release version: 0.0.0, most recent alpha: 0.0.0-alpha
Pushing alpha docker image with version 0.0.1-alpha
```
> Push alpha docker image on merge push CI

- deploy/docker/Dockerfile
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- Raise number of threads per output plugin to 4 threads to alleviate http bottleneck
- Apply same buffer configuration settings to both logs and metrics output plugins
- Specify `gzip` compression for fluentd to use internally when buffering to maximize amount of buffering we can do
- Parameterize chunk_limit_size (http payload size) with 100KB max, and total_limit_size (amount of memory used per plugin) with 128MB max
Tested bringing up Fluentd pods and ensured log and metric collection is working.
> Parameterize buffer settings for Fluentd Logs/Metrics

- deploy/kubernetes/setup.sh
Fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/98
- `kubectl get` doesn't have the same issue with substring matches that `kubectl describe` has:
```
k8s $ kubectl get namespace sumol
Error from server (NotFound): namespaces "sumol" not found
k8s $ echo $?
1
k8s $ kubectl get namespace sumologic
NAME        STATUS   AGE
sumologic   Active   12d
k8s $ echo $?
0
```
Fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/97
> Fix setup.sh bash script issues

- ci/build.sh
Automatically tag pushes to master with the same version we use to push the docker image. From these tags we can create releases in Github, and also perform diffs between tags/master.
> Auto-tag alpha images in Git that we can generate full releases from

- ci/build.sh
```
Tagging git with v0.0.5-alpha...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/SumoLogic/sumologic-kubernetes-collection.git/'
The command "bash ci/build.sh" exited with 128.
```
This adds authentication from a Github token env variable I added to Travis settings.
> Use Github token to push tags

- deploy/docker/Dockerfile
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
We currently have an issue where customers can use the latest yaml file from master branch (e.g. from setup.sh script) but it can reference environment variables in newer docker images so they won't get the default value.
To avoid drift, we would like to centralize this configuration in the yaml file itself.
> Move Dockerfile env variables to yaml file to avoid drift

- fluent-plugin-events/lib/fluent/plugin/in_events.rb
- fluent-plugin-events/test/helper.rb
- fluent-plugin-events/test/plugin/test_in_events.rb
Since we are using `timer_execute` for `start_monitor`, any exceptions thrown from the method will cause the timer detached.
We are going to add exceptions handling for all methods that have kubeclient calls in events plugin, including following methods:
```
start_watcher_thread
create_config_map
patch_config_map
initialize_resource_version
pull_resource_version
```
We will only rescue possible errors and then log the error so that we can know errors from which method they throw. For all other methods except for `start_watch_thread`, we don't want errors from kubeclient blocks the thread of watching, so we just log the error and ignore it. For `start_watcher_thread`, we need `timer_execute` continues working so exceptions will be swallowed and timer won't be detached in this case.
> SUMO-115364 Handle exceptions thrwon from kubeclient calls

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/prometheus-overrides.yaml
This PR enables Fluent-Bit metrics, creates a serviceMonitor with the appropriate label so Prometheus discovers, and then adds the appropriate remote write configuration.
> enable fluent-bit metrics collection

- deploy/docker/Dockerfile
- deploy/helm/prometheus-overrides.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- fluent-plugin-protobuf/lib/fluent/plugin/parser_protobuf.rb
Exposes Prometheus metrics (currently just output plugin metrics) for fluentd and fluentd-events deployments.
> Add monitoring for FluentD plugins

- deploy/docker/Dockerfile
This is required to get the changes that allow enhanced metadata for logs when using `LOG_FORMAT = fields` (for the new logs metadata feature).
cc @Gourav2906
> bump fluentd-kubernetes-sumologic v2.4.2

- deploy/helm/fluent-bit-overrides.yaml
Fixes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/84
Tested only by redeploying fluentbit operator with these overrides and ensuring log collection works.
> Tolerate any NoScheule taint regardless of key

- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/connector.rb
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/service_monitor.rb
We had this running on 15 Fluentd replicas over the last ~3.5 days and none of the replicas have yet to get stuck.
Ryan concurrently ran a test with calling `get_endpoints` in a tight loop over the weekend, and found this time that none of the replicas got stuck. We're not sure what changed, but it seems like `get_endpoints` may be working now? 🤞
> Fix service monitor

- deploy/docker/Dockerfile
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/reader.rb
- fluent-plugin-events/lib/fluent/plugin/in_events.rb
Noticed several of our fluentd plugin gems are out of date, and one is not being used.
Testing performed:
- ci/build.sh
- Redeploy fluentd and fluentd-events pods
- Confirm events logs and normal logs and metrics are still coming in
FYI: @lei-sumo @frankreno
> Bump versions of plugins used in Dockerfile

- deploy/README.md
- deploy/kubernetes/setup.sh
This PR adds two new flags to the setup script: 
- `-d` for deploying (running `kubectl apply`); default to true and 
- `-y` for downloading yaml; default to true
Two reasons for these changes:
1. When working with @drduke1 on the docs we realize for users who wants to customize the configuration, they currently run setup.sh which deploys everything with default settings, then they'll make changes to the downloaded yaml, and then redeploy. With this change, they can set `-d false` and it will only download the yaml file so they can make changes locally and run `kubectl apply` on their own.
2. Before we add pre-installation hook to our Helm chart that sets up the collector and sources as part of `helm install`, Helm users will need to run the setup script with `-d false -y false` before …
> Optionally deploy and download yaml in setup.sh

- deploy/docker/Dockerfile
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
The [fluentd-kubernetes](https://github.com/fluent/fluentd-kubernetes-daemonset) daemonset has deprecated using Alpine as their base image, and also says
> The following repository expose images based on Alpine Linux and Debian. For production environments we strongly suggest to use Debian images.
This PR changes our fluentd Docker image to be based on Debian.
Testing performed:
- ci/build.sh
- Redeploy fluentd and fluentd-events pods
- Confirm events logs and normal logs and metrics are still coming in
> Switch to Debian fluentd Dockerfile

- deploy/helm/sumologic/.helmignore
- deploy/helm/sumologic/Chart.yaml
- deploy/helm/sumologic/conf/buffer.output.conf
- deploy/helm/sumologic/conf/common.conf
- deploy/helm/sumologic/conf/events/events.conf
- deploy/helm/sumologic/conf/logs/logs.conf
- deploy/helm/sumologic/conf/logs/logs.output.conf
- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/conf/logs/logs.source.systemd.conf
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/conf/metrics/metrics.output.conf
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/clusterrole.yaml
- deploy/helm/sumologic/templates/clusterrolebinding.yaml
- deploy/helm/sumologic/templates/configmap.yaml
- deploy/helm/sumologic/templates/deployment.yaml
- deploy/helm/sumologic/templates/events-configmap.yaml
- deploy/helm/sumologic/templates/events-deployment.yaml
- deploy/helm/sumologic/templates/events-service.yaml
- deploy/helm/sumologic/templates/service.yaml
- deploy/helm/sumologic/templates/serviceaccount.yaml
- deploy/helm/sumologic/values.yaml
Create the Helm chart. Dependencies and automation of yaml generation will be in separate PRs.
Output of `helm install`:
```
$ helm install helm/sumologic
NAME:   giggly-pike
LAST DEPLOYED: Fri Aug  2 11:24:49 2019
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1/ConfigMap
NAME                                 DATA  AGE
giggly-pike-sumologic-config         9     1s
giggly-pike-sumologic-events-config  2     1s
==> v1/Deployment
NAME                          READY  UP-TO-DATE  AVAILABLE  AGE
giggly-pike-sumologic         0/3    3           0          0s
giggly-pike-sumologic-events  0/1    1           0          0s
==> v1/Pod(related)
NAME                                           READY  STATUS             RESTARTS  AGE
giggly-pike-sumologic-d5dc9d85d-9ptld          0/1    Pending …
```
> Helm Chart initial commit

- deploy/docker/Dockerfile
This switches to multi-stage Docker build so that we can ship an image with only the dependencies needed to run our FluentD setup.
This should help with the image size increase after switching to Debian in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/125.
> SUMO-114676: Use multi-stage Docker build to reduce image size

- deploy/README.md
For now, just updating docs, but we should think through a better solution. Update README with note on remote write API changes needed when deploying Prometheus to a different namespace or using an existing Prometheus running in a different namespace.
> Note On Possible Remote Write Update Changes

- deploy/helm/fluent-bit-overrides.yaml
Since the OOB fluent-bit helm chart does not expose configs for `Refresh_Interval` and `Rotate_Wait`, we decided to expose the `[INPUT]` config for fluent-bit explicitly in the overrides yaml file.
For reference, this was the helm chart's `[INPUT]` [config](https://github.com/helm/charts/blob/master/stable/fluent-bit/templates/config.yaml). We need to keep `.Values.input.systemd.enabled` and `.Values. trackOffsets` in our overrides since they are used [here](https://github.com/helm/charts/blob/master/stable/fluent-bit/templates/daemonset.yaml).
> Move fluent-bit INPUT config to overrides yaml

- ci/build.sh
Should not check for changes in yaml.tmpl for master builds. cc @rvmiller89
> Fix failing master builds

- ci/build.sh
- deploy/helm/sumologic/values.yaml
After adding dependencies into our helm chart, `helm template` will render not only our own yaml templates but also the yaml templates from all of the dependent charts. To render only our templates, we use the `-x` option for each .yaml file under `sumologic/templates` folder in the `helm template` command.
> Only pass in our own yamls to helm template cmd

- ci/build.sh
When a new tag is created, `setup.sh` should create a new docker release as well as a new helm chart release and pushes the packaged helm chart with the new version to Github Pages.
We need to do some refactoring work on the setup script as it becomes longer and has more repeated code. But we can do it at once after Yuting merges the overrides auto generation.
> Automate helm chart release in setup.sh

- deploy/README.md
- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
Health check metrics are broken because the values.yaml contains the old labels "k8s-app=fluentd-sumologic". If we change it, we also need to update the README to instruct users to download versioned overrides yamls. I don't think manually updating the version in the URLs is scalable but I also don't know if just telling users to change the URL with the latest version is sufficient?
> Fix labels for k8s health check metrics and use versioned overrides yaml files

- ci/build.sh
Fix for broken Travis build on new release https://travis-ci.org/SumoLogic/sumologic-kubernetes-collection/builds/578495759#L1778
`git checkout -- .` should throw away the gemspec changes.
> Get rid of unstaged changes before switching to gh-pages branch

- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
Sumo backend can't accept fields with empty values, so we drop those pod labels with empty values here
> Drop labels with empty values

- deploy/fluent-bit/overrides.yaml
- deploy/helm/overrides.yaml
We previously added these symlinks for old versions of the setup script that downloaded the resources directly, but since Github doesn't actually resolve the symlink (they would only get the filename as the contents of the symlink), we might as well clean these up.
> Remove symlinks to legacy helm override files

- .gitignore
Same as `gh-pages` branch but for `master` branch.
> Git ignore Helm chart deps

- deploy/docker/Dockerfile
- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-kubernetes-sumologic/Gemfile
- fluent-plugin-kubernetes-sumologic/README.md
- fluent-plugin-kubernetes-sumologic/Rakefile
- fluent-plugin-kubernetes-sumologic/fluent-plugin-kubernetes-sumologic.gemspec
- fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb
- fluent-plugin-kubernetes-sumologic/test/helper.rb
- fluent-plugin-kubernetes-sumologic/test/plugin/test_filter_kubernetes_sumologic.rb
This moves the `kubernetes_sumologic` filter plugin from the old repo to this repo, and builds locally rather than pulling the gem.
We also duplicate the `host` metadata and attach as a new field `node` since that makes more sense in the kubernetes context.
> Migrate kubernetes_sumologic filter plugin

- ci/build.sh
Recommend using "Hide whitespace changes" since most of this is just indent change.
Rather than using  `TRAVIS_COMMIT_RANGE` which is empty on initial commit, we can `git diff master...$TRAVIS_BRANCH` to detect manual changes to the yaml files.
Rather than checking for changes made to `values.yaml`, we can always generate the new files and commit them if there is a difference.
> SUMO-117261: Skip using TRAVIS_COMMIT_RANGE for yaml detection

- deploy/helm/README.md
After #159 user also needs to replace all occurrences of `collection` for the override values if they use a different release name.
> Update helm readme

- ci/build.sh
- deploy/README.md
- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Fixes both Helm and YAML-based deployment by standardizing on `collection-sumologic` app labels (removing "fluentd" all together).
Also removes spurious `release: collection` in prometheus overrides, which was causing problems with YAML-based prometheus operator deployment.
> Fix Helm template naming in yaml files

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
I saw this other property is evaluated in some templates, and setting both to `false` seems to prevent deploying Grafana when using Helm collection chart.
`helm install sumologic/sumologic --name collection --namespace sumologic --no-crd-hook -f prometheus-overrides.yaml`
> SUMO-117711: Prevent Grafana from deploying with Helm collection chart

- deploy/helm/sumologic/requirements.yaml
We want to pin the stable versions that have been tested, including the patch version.
> Pin patch version of helm dependencies

- ci/build.sh
- deploy/helm/sumologic/templates/setup/setup-clusterrole.yaml
- deploy/helm/sumologic/templates/setup/setup-clusterrolebinding.yaml
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/templates/setup/setup-serviceaccount.yaml
Fix RBAC error for pre-install hook
> RBAC for pre-install hook

- deploy/helm/sumologic/templates/setup/setup-clusterrole.yaml
- deploy/helm/sumologic/templates/setup/setup-clusterrolebinding.yaml
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/templates/setup/setup-serviceaccount.yaml
According to docs:
> Tiller sorts hooks by weight (assigning a weight of 0 by default) and by name for those hooks with the same weight in ascending order. Tiller then loads the hook with the lowest weight first (negative to positive)
So the service account should be assigned the lowest weight to get loaded first, and the job should be assigned the highest to get loaded last.
> Assign weight to pre-install hooks

- deploy/README.md
readme had outdated curl url for setup.sh
> fix setup curl command url

- deploy/helm/sumologic/Chart.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Cut 0.5.0 release. The URL changes in README will be in a separate PR after CI builds the 0.5.0 image and helm chart. (Otherwise customers will get 404 not found if we change it before the actual release is made. I'll update the release process doc as well)
> Cut 0.5.0 release

- deploy/helm/sumologic/values.yaml
helm upgrade collection sumologic/sumologic -f values.yaml is failing.  The helm file [setup-job.yaml ](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/templates/setup/setup-job.yaml#L33)is looking for accessKey, but the [values.yaml](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/values.yaml#L38) is set to accesskey.
> accesskey should be accessKey

- deploy/README.md
> Add setup job troubleshooting steps

- ci/build.sh
I saw that https://travis-ci.org/SumoLogic/sumologic-kubernetes-collection/builds/589711994 failed due to trying to check `git log` for a Tag build.  We can skip the generated yaml check all together for Tag builds, so that it doesn't fail when we cut a new release.
> Skip generated yaml check for TRAVIS_TAG builds

- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Ensure container metrics get routed to Kubelet source and not to default-metrics.
> Fix Container Metrics Routing

- deploy/docker/Dockerfile
- fluent-plugin-enhance-k8s-metadata/fluent-plugin-enhance-k8s-metadata.gemspec
Root issue for the problem:
```
ERROR:  Could not find a valid gem 'kubeclient' (~> 4.4.0) (required by 'fluent-plugin-enhance-k8s-metadata' (>= 0)) in any repository
```
was that in our metadata plugin we were defining required version as `~>4.4.0` which only applies to `>= 4.4.0` and `< 4.5`.  Overnight `kubeclient` released a `4.5.0` version which now fails the required version check.
This PR fixes that issue, and also pins our external gem dependency versions to avoid surprises since otherwise our CI could randomly start failing at any time as projects release new major versions.
> Pin gem dependency versions; Fix metadata version string

- deploy/helm/sumologic/conf/common.conf
- deploy/helm/sumologic/conf/events/events.conf
- deploy/helm/sumologic/conf/logs/logs.conf
- deploy/helm/sumologic/conf/metrics/metrics.conf
The first issue is we were incorrectly accessing `fluentdLogLevel` in the templates, we should be using `.Values.sumologic.fluentdLogLevel` instead of `.Values.fluentdLogLevel`. The second issue that Sam noticed was fluentd could not start if the `<system>` block is defined twice. The fix for that is to have `<system>` block defined once in the logs and metrics config map (in common.conf) and once in the events config map.
> Fix fluentd log level parameter

- deploy/README.md
> Add instructions on deploying second prometheus in the same cluster

- deploy/helm/sumologic/requirements.yaml
Bump falco chart version to 1.0.8 for EKS fix
> Bump falco chart version to 1.0.8 for EKS fix

- deploy/docker/setup/setup.sh
`kubectl describe secret sumologic` will return results if you have any secret whose name starts with `sumologic`
so if you have any secret named `sumologic.*`, the setup script will fail. On the other hand, `kubectl describe secret/sumologic` will only return results for an exact match on a secret named `sumologic`.
> check exact secret name in setup script

- deploy/docker/Dockerfile
The `fluent-plugin-prometheus` gem has a dependency on `prometheus-client` which recently introduced a breaking change in their latest release, describe in https://github.com/fluent/fluent-plugin-prometheus/issues/119. `fluent-plugin-prometheus` made a new release 1.6.1 to use a version lower than the latest. To unblock our release we should try this new version and verify it doesn't create other issues.
> Bump fluent-plugin-prometheus version to fix breaking change from prometheus-client

- deploy/docs/monitoring-lag.md
> Scaling Fluentd

- deploy/docker/Dockerfile
We should have the Kubernetes collection start using this version of the output plugin: https://github.com/SumoLogic/fluentd-output-sumologic/releases/tag/1.6.0
> Bump version of Fluentd Output plugin to support fields

- deploy/docker/Dockerfile
Dockerfile changes to install Terraform dependencies.
This needs to be merged and docker image built with a new Helm chart release before we can merge https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/249
> Dockerfile changes for Terraform support

- deploy/docker/Dockerfile
`wget` dependency was removed in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/248 but we still need this while we have the `setup.sh` script since it depends on it.
FYI: @maimaisie
> Re-add wget dependency for setup.sh script

- deploy/docker/Dockerfile
To fix issue with missing deployment + other enhanced metadata: https://github.com/SumoLogic/fluentd-output-sumologic/pull/55
> bump output plugin version to 1.6.1

- deploy/helm/sumologic/templates/deployment.yaml
- deploy/helm/sumologic/templates/events-deployment.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Adds `nodeSelector` and `tolerations` to both deployments, from https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/255
> Add NodeSelector and Tolerations to both deployments

- deploy/helm/sumologic/Chart.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
In preparation for cutting release 0.10.0
FYI: @maimaisie @lei-sumo @frankreno
> Cut release 0.10.0

- .travis.yml
- ci/build.sh
1. Only pushing to master (merging a PR) will run CI with `push` event type
2. Otherwise, all PRs will run CI with `pull_request` event type. In this case we look at `TRAVIS_PULL_REQUEST_BRANCH` in order to detect changes made to generated files, or changes that need to be committed for generated files.
FYI: @maimaisie
> Update Travis CI to support PR push

- deploy/helm/sumologic/templates/_helpers.tpl
In case we can't get https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/266 to work
> Fix helper template variables

- deploy/helm/sumologic/templates/setup/setup-clusterrole.yaml
- deploy/helm/sumologic/templates/setup/setup-configmap.yaml
- deploy/helm/sumologic/templates/setup/setup-job.yaml
Adds Terraform-based setup for Sumo collector and HTTP sources, as well as Kubernetes namespace and secret.
Requires https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/248 to be merged, and a Helm chart release (minor version, non-alpha) so that the docker image contains the required dependencies.
~~Do not merge until we have a Helm chart release with the updated Dockerfile~~
Dockerfile changes are in Helm chart release 0.10.0
> Update setup.sh to use Terraform

- ci/build.sh
This will start generating alpha helm chart releases in our Github Pages-hosted chart: https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/gh-pages
Will need to merge to test this on Travis CI
> Start pushing alpha helm chart releases with every alpha build

- deploy/README.md
Added the clusterName overrides to the base command so that its easier to get right the first time around.
> ClusterName override in Base

- ci/build.sh
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Updates the CI `build.sh` script to generate a new template yaml file `setup-sumologic.yaml.tmpl` that contains all of the setup Helm templates needed to run a job on Kubernetes to setup the Sumo Logic collector and HTTP sources, namespace and secret.
In order to use the job yaml, you must first create the `sumologic` namespace:
```sh
kubectl create namespace sumologic
```
And then update these parameters in the yaml template:
1. $NAMESPACE
2. $SUMOLOGIC_ACCESSID
3. $SUMOLOGIC_ACCESSKEY
4. $COLLECTOR_NAME
5. $CLUSTER_NAME
This can be added to our README in a future PR.  One thing I did notice is it leaves the setup pod as `0/1 Completed` but I think that's okay to leave:
```sh
k8s $ k get pods
NAME                               READY   STATUS      RESTARTS   AGE …
```
> Generate setup job yaml from helm template

- deploy/helm/sumologic/templates/setup/setup-clusterrole.yaml
- deploy/helm/sumologic/templates/setup/setup-clusterrolebinding.yaml
- deploy/helm/sumologic/templates/setup/setup-configmap.yaml
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/templates/setup/setup-serviceaccount.yaml
Adding setup job and RBAC resources as pre-upgrade hooks
> Add setup as pre-upgrade hook

- deploy/docker/Dockerfile
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
With the new TF provider, we no longer require specifying endpoint URL since it will try to follow the 301 redirection response to the correct deployment.
> Bump Dockerfile Sumo TF provider to 2.0.0

- deploy/helm/sumologic/values.yaml
As per request, we're updating the comment in the `values.yaml` file to help make it clearer that it is the API endpoint used here
> Add help doc link for API endpoint

- deploy/helm/sumologic/Chart.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- deploy/kubernetes/setup-sumologic.yaml.tmpl
> Cut release 0.11.0

- .travis.yml
Since we only build master branch now it's not building the "branch" created when making a release in Github.
This will start building any branches with the format v#.#.#
> Also build version branches

- ci/build.sh
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Unfortunately our CI still can't push to PRs from forked repos, so this PR is really just to get the CI to generate the yaml.
But at the same time, add a couple log lines I wanted to see yesterday.
> Add log lines; Force CI yaml generation

- deploy/docs/Installation_with_Helm.md
- deploy/docs/Non_Helm_Installation.md
- deploy/docs/SideBySidePrometheus.md
- deploy/docs/Troubleshoot_Collection.md
- deploy/docs/additional_prometheus_configuration.md
- deploy/docs/additonal_prometheus_configuration.md
- deploy/docs/existingPrometheusDoc.md
- deploy/docs/standAlonePrometheus.md
Improve non-helm install docs with more detailed steps and move filter/trim/relabel/custom metrics docs to standalone documentation.
> Improve Docs

- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/values.yaml
facilitate gitops better through sourced secrets in setup Chart
Change the source of the config for the setup job to a secret for better facilitating helm dependency in git
Not sure if these are 100% necessary as this is just a config change to the chart
> #293 facilitate gitops better through sourced secrets in setup Chart

- deploy/helm/sumologic/templates/NOTES.txt
Notes should use `collectorName` if supplied, if not use `clusterName` which has a default value of `kubernetes`.
> Update helm installation/upgrade notes on collector name

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Noticed while investigating an issue around high rate of CoreDNS resolution, we should include a trailing dot (".") to ensure we do fully-qualified DNS resolution. This reduces the total rate of DNS resolution by a factor of 5 on my test cluster.
Reference: https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-397404229
> Use fully-qualified name for fluent-bit DNS resolution

- deploy/helm/sumologic/templates/setup/setup-clusterrole.yaml
- deploy/helm/sumologic/templates/setup/setup-clusterrolebinding.yaml
- deploy/helm/sumologic/templates/setup/setup-configmap.yaml
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/templates/setup/setup-serviceaccount.yaml
- deploy/helm/sumologic/values.yaml
I think that the ability to customize the annotations for helm hooks is important enough to move it out into the values to make it override-able. I also fixed some of the formatting around setup in the values to make it expandable in the future.
> Customizable annotations for setup resources

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
A few fixes based on the failing automation tests:
1. New prometheus operator version introduced in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/299 seems to have added this admission webhook step that fails our helm installation. Since we're not using admission webhooks, we can disable this by setting `prometheus-operator.prometheusOperator.admissionWebhooks.enabled=false`.
2. Disables `tlsProxy` in the new prometheus operator version as well since this was failing to start prometheus when enabled.
3. Helm hook weights seem to expect string values, not numbers, so changing these back to strings after they were changed to numbers in https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/302
> Fix alpha helm chart installation

- deploy/README.md
- deploy/docs/Alpha_Release_Guide.md
Adds documentation on how to find and use an Alpha docker image and Alpha helm chart release, geared toward customers that want to run alpha builds, such as customers contributing PRs to our repo.
N/A
> Add Alpha Release Guide to Docs

- deploy/docs/Non_Helm_Installation.md
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Since we are deprecating the setup.sh and instead providing a YAML file to run a container that does all setup, we need to update our docs to reflect that.
> Update non-helm installation docs

- deploy/docs/Upgrading_with_Helm.md
Since this caused some confusion when trying to set a value and seeing my Helm chart actually be downgraded to the last release version.
> Add note about version flag for helm upgrade

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/values.yaml
From the CoreDNS investigation, we are using the default fluent-bit flush interval of 1s, which leads to DNS lookup per flush. We can increase the flush interval to lessen the DNS lookups, and also the number of network calls from fluent-bit to fluentd.
> Increase fluent-bit flush interval to lessen DNS load

- ci/build.sh
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
We decided to use empty string for the `endpoint` config param so by default it will do auto URL redirection unless the user overrides it. This will work for both helm and non-helm installations.
> Use empty endpoint URL by default for redirection

- deploy/README.md
Helm 3 was released recently and has become default version for homebrew for installs. Adding a note in the support matrix since there is currently some issues in our solution with Helm 3.
> Add a note for helm 3 support

- deploy/docs/Troubleshoot_Collection.md
Adds more details on troubleshooting FluentD from https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/202
> Update the instructions for FluentD configuration changes

- fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb
Unfortunately we found that if `kubernetes_meta` is set to `false` and `kubernetes_meta_reduce` is set to `true` at the same time, this plugin tries to delete keys from `record["kubernetes"]`, which has been deleted previously and is therefore nil.
At the very least this spams fluentd logs with the error, which is self collected and creates a nasty loop.
At worst, we believe this may have caused container logs to be dropped due to the unhandled error in this plugin. We should confirm that behavior, and in general handle errors more gracefully in all of our plugins to ensure this sort of issue does not occur again.
> fix filter plugin error with kubernetes_meta_reduce

- deploy/helm/sumologic/templates/events-configmap.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Include buffer.output.conf for events configmap
> Include buffer.output.conf for events configmap

- deploy/docs/Non_Helm_Installation.md
update prometheus version to 8.2.0 for non-helm docs
> update prometheus version to 8.2.0 for non-helm docs

- deploy/docs/Installation_with_Helm.md
> Fix ambiguity in helm install command

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
We discovered that there were duplicate container metrics ; one with container name and one without them. The metrics without the container name are the aggregate metrics. 
This PR  added the container name in the sourceLabels and modifies the regex accordingly.
> Clean Prometheus container metrics

- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Revert #288 since we have confirmed that upgrading from non-TF chart to TF chart with setup running in pre-upgrade will potentially create a new collector (breaking change). 
Will update CHANGELOG in #333.
> [breaking change] Add pre-upgrade hook for setup

- deploy/docs/Non_Helm_Installation.md
The non-helm documentation refers to incorrect prometheus pod name to check the status of prometheus-operator. This PR updates the doc with the correct pod name.
> Update promethues pod name in doc

- deploy/helm/sumologic/conf/common.conf
- deploy/helm/sumologic/conf/logs/logs.conf
- deploy/helm/sumologic/templates/deployment.yaml
- deploy/helm/sumologic/templates/events-deployment.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Add new liveness probe to fluentd deployment. 
```
httpGet:
path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
port: 9880
```
The rationale is that if Fluentd can accept log messages, it must be healthy.
The endpoint itself results in a new fluentd tag `fluentd.pod-healthcheck`
The query parameter in the URL defines a URL-encoded JSON object that looks like this:
{"log": "health check"}
> Improve fluentd liveness probe

- deploy/docs/Non_Helm_Installation.md
The old instruction `brew install kubernetes-helm` downloads helm 3 which is not currently supported by us.
> Update helm installation instructions in Non_Helm_Installation.md 

- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Following SEs and @frankreno's suggestion, change default fluentd log level to `error` to reduce verbose logging especially when customer is throttled.
> Change default fluentd log level to ERROR

- deploy/helm/sumologic/values.yaml
It's not clear how to use `envFromSecret` based on https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/352 so this PR adds a comment explaining the two env variables we require to be added to the secret used.
> Clarify usage of envFromSecret to specify env variables needed

- deploy/helm/sumologic/templates/events-deployment.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Reverting the readiness probe for events deployment.
> revert readiness probe for events deployment

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
In #345 , we had made a change to drop the duplicate metrics which did not have the container name. Few metrics eg.
`container_network_receive_bytes_total`
`container_network_transmit_bytes_total`
`container_network_receive_errors_total`
`container_network_transmit_errors_total`
`container_network_receive_packets_dropped_total`
`container_network_transmit_packets_dropped_total`
The above metrics are cumulative container metrics and do not have the container name. 
This PR adds a new remote write section with these metrics.
> fix missing aggregate container metrics

- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Reverts SumoLogic/sumologic-kubernetes-collection#335
Need to revert since we want to make a minor release
> Revert "[breaking change] Add pre-upgrade hook for setup"

- deploy/helm/sumologic/values.yaml
This PR disabled the `metrics-server` helm chart dependency by default. 
`metrics-server` is only required for the `fluentd` HPA , which is disabled by default, so we are also defaulting this dependency to `false`.
It is primarily done to cover the scenario, where the user already has `metrics-server` installed in the k8s cluster, then our helm install command would fail with the error : 
```Error: release collection failed: apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io" already exists```
Now, if the user wants to enable autoscaling for fluentd they will have to do the following steps:
1. Enable `metrics-server` dependency 
Note: if `metrics-server` is already installed , this step is not required
2.Enable autoscaling for fluentd
> disable metrics-server dependency by default

- deploy/helm/sumologic/conf/events/events.conf
- deploy/helm/sumologic/templates/events-deployment.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
This PR adds the http source to `events.conf` and changes the readiness/liveness probes for the events deployment.
> Change events deployment readiness probe

- deploy/helm/sumologic/templates/setup/setup-configmap.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
The terraform script currently specifies the source category for each source to be `{cluster-name}/{source-name}` during source creation, however we did not used to specify source category when using the bash script. 
This change creates confusion to users running queries directly from UI by clicking the query icon next to the source category since it returns no results. The reason is because output plugin sends different source category through HTTP header and that takes precedence over the static source category.
> Remove source categories from source creation in terraform script

- deploy/docker/Dockerfile
Bump fluentd image version to fix fluentd buffer bug https://github.com/fluent/fluentd/issues/2619. Also bumping version of `fluent-plugin-kubernetes_metadata_filter` since the older version has a conflict with 1.8.1 fluentd image.
> Bump fluentd image version to fix fluentd buffer bug

- deploy/helm/tiller-rbac.yaml
Noticed that our jenkins jobs actually downloads this file, and without it I believe the helm installation fails.
I don't think this is enough to fix the jenkins job for helm since it's been failing for a few days, we'll have to keep investigating once this is merged
> Re-add tiller-rbac.yaml

- fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb
- fluent-plugin-kubernetes-sumologic/test/plugin/test_filter_kubernetes_sumologic.rb
as a short term workaround, we attach logs metadata as fields regardless of the log format (fields, json, text, json_merge)
this will enable the use of text format with metadata, but multiline detection will be broken, as it was for the old kubernetes collection solution.
> SUMO-124885 attach logs metadata as fields for all log formats

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
Relabel metrics metadata "container_name" to "container" for k8s 1.16
> Prometheus fix for k8s 1.16 

- deploy/README.md
- deploy/docs/Helm3.md
- deploy/docs/Installation_with_Helm.md
This PR adds documentation on installation with Helm3.
> freno-helm3

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
**Deprecated apiserver metrics:**
`apiserver_request_count` -> `apiserver_request_total`
`apiserver_request_latencies_summary` -> `apiserver_request_duration_seconds`
`etcd_request_cache_get_latencies_summary` -> `etcd_request_cache_get_duration_seconds`
`etcd_request_cache_add_latencies_summary` -> `etcd_request_cache_add_duration_seconds`
`etcd_helper_cache_hit_count` -> `etcd_helper_cache_hit_total`
`etcd_helper_cache_miss_count` -> `etcd_helper_cache_miss_total`
(Verified the apiserver metrics are coming in 1.16, but the etcd ones are not, I think all of these 4 etcd metrics got removed in 1.17 but not sure why they are not showing up in 1.16 either)
**Deprecated kubelet metrics:**
`kubelet_runtime_operations_latency_microseconds` -> `kubelet_runtime_operations_duration_seconds` …
> Modify regexes to match both deprecated and new metrics in 1.16

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/values.yaml
Modify the default multiline regex to be more flexible to be more flexible with datetime format. 
This regex matches the first line of a multiline log starting with a date of the format :  `"2019-11-17 07:14:12"` or `"2019-11-17T07:14:12"`
> Modify the default multiline regex to be more flexible

- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Expose cache params for enhance_k8s_metadata plugin and change default cache size to 10000
> expose cache params for enhance_k8s_metadata plugin

- deploy/docs/Helm3.md
- deploy/docs/Installation_with_Helm.md
- deploy/docs/existingPrometheusDoc.md
Update the documentation to remove the `sumologic.endpoint` argument as it is now deteremined automatically based on accessID and key.
> Remove sumologic.endpoint from installation commands.

- deploy/helm/sumologic/templates/setup/setup-configmap.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Since the events data doesn't go through metadata enrichment plugin currently, the source category for events source is just the default `http` after we removed static source category for all sources in #349. 
This PR adds it back just for events source and expose it in values.yaml file. Since after Sam's breaking change, [all events configuration fields](https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/330/files#diff-1afd7b203a6373f36b3fdb4d68d7ddb5R273) go under `events` I am adding it here in case this goes out in a minor release before the major one to avoid one more rename that customer needs to do when we do make the major release.
> Add back and expose source category for events source

- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
fix discrepancy in metadata cache ENV name
> fix discrepancy in metadata cache ENV name

- deploy/docs/Installation_with_Helm.md
- deploy/docs/Non_Helm_Installation.md
- deploy/docs/Troubleshoot_Collection.md
- deploy/docs/additional_prometheus_configuration.md
Replaces absolute links with relative links so that historical docs will be preserved with working links when new releases are made (new tags).
> Convert more absolute URLs to Relative URLs in Docs

- deploy/helm/sumologic/templates/setup/setup-configmap.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
TF complains about missing double quotes in rendered source category for events source.
> Add missing double quotes

- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
Rename `statefulset` and `eventsStatefulset` back to `deployment` and `eventsDeployment` to avoid breaking change in the minor release. Will revert this PR for major release.
> Rename statefulset configs to avoid breaking change

- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Frank pointed out we are using ordered podManagementPolicy (default) and it results in very slow replica creation. Changing to parallel should speed up replica creation.
> Change podManagementPolicy to Parallel for statefulsets

- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
This PR uses the fluentd timer helper plugin to asynchronously refresh the cache entries at a configurable interval. 
(I tried to put the timer logic inside `cache_strategy.rb` together with all the existing caching logic but since it is a module that does not extend fluentd, I couldn't import the fluentd timer there.)
> Add async cache and expose refresh interval in values.yaml

- deploy/helm/sumologic/conf/buffer.output.conf
- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
This PR adds the new buffer parameter: `queued_chunks_limit_size` which limits the number of queued chunks. Its default value is the number of threads which is `flush_thread_count` . This value is set to be 128 so that at max we would have 128 chunks of 1 MB each,  in the queue whose size  `total_limit_size` is 128MB.
Also, changing the default chunk size `chunk_limit_size` to 1MB from 100k.
> change buffer params

- deploy/docs/Helm3.md
- deploy/docs/Installation_with_Helm.md
- deploy/docs/Non_Helm_Installation.md
- deploy/docs/existingPrometheusDoc.md
Since our changes to these files could be breaking changes, we want to ensure our docs point to the correct versioned urls. In addition, once we cut a major release, this will make it easy for customers who are on older versions to realize they can change the version in the url to the version they are running.
> Use versioned URLs for docs

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
Reverts SumoLogic/sumologic-kubernetes-collection#372 since this we have another minor release to make before the major release
> Revert "Modify regexes to match both deprecated and new metrics in 1.16"

- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
Changing to 30 from 10min default cache refresh interval to reduce apiserver load.
> Change cache refresh interval to 30 min

- deploy/docs/Installation_with_Helm.md
GKE requires using the values.yaml override file to enable ebpf. This is noted in the non-helm installation instructions but not in the helm installation.
Please feel free to edit this PR to the instructions or reject the PR and submit something different.  But it is believed to be required and needs to be added to the helm installation doc.
> Add ebpf enable to helm_installation for GKE

- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Increase the default number of output threads to  8
> Increase the default number of output threads to  8

- deploy/docs/SideBySidePrometheus.md
We found that multiple prometheus operators cannot be deployed on the same cluster. This doc change is to reflect that finding.
> Clarify Prometheus side-by-side docs

- deploy/helm/sumologic/conf/logs/logs.conf
- deploy/helm/sumologic/conf/logs/logs.source.generic.conf
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Currently we only collect the container logs in the fluentd pipeline. This PR adds a generic fluentd pipeline to catch all logs. User would need to configure a new Input in the Fluent-bit config to send it to fluentd.
> add generic fluentd pipeline to catch all logs

- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Tried reproducing missing metadata locally, when I ran `kubectl describe configmap collection-sumologic` I noticed there was no config in the `enhance_k8s_metadata` plugin section
> Fix typo in container logs pipeline

- deploy/docs/Troubleshoot_Collection.md
Updating outdated troubleshooting docs for Helm world
> Update Troubleshooting docs for Helm

- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
For the multiline to work, we added the first step of the fluentd pipeline to be a record transformer to process the stiched multiline logs in the correct format. 
This transformation relies on the fact that the `log` value is a JSON object based on the default multiline parser regex.
If the user changes the parser to say, `docker` parser, then the `log` is no longer a JSON and it fails. 
This PR adds error handling for the same. In case the `log` value is not JSON, we will pass the content as is.
> add error handling on JSON parsing for the multiline fix

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
This PR removes cluster label from prometheus config in `values.yaml` and adds it in the fluentd metrics pipeline.
This will avoid the hassle of specifying the cluster name in the `helm install` command twice.
> remove cluster label from prometheus config in values.yaml

- deploy/helm/sumologic/conf/traces/traces.conf
- deploy/helm/sumologic/templates/configmap.yaml
- deploy/helm/sumologic/templates/service.yaml
- deploy/helm/sumologic/values.yaml
Helm configuration for zipkin plugin
> Update configuration for helm

- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
We noticed that the default record transformer filter might drop data if the input is JSON and it does not contain nested `log` key-value pair. 
For eg: 
```{"log":"{\"source_host\":\"sagepay-gateway-1-6bd89fbc6f-fv9pt\",\"method\":\"completeAuthorisation\",\"level\":\"INFO\",\"message\":\"avs response :DATA NOT CHECKED\",\"ndc\":\"EC4D3DE1-E41B-548C-0D5D-65BFBD8B2619\",\"mdc\":{\"Request-Tracker\":\"229D7DAC-D5C6-461A-A74F-A359614FD9E6\"},\"@timestamp\":\"2020-02-12T10:10:15.518Z\",\"file\":\"StandardAuthorisationStrategy.java\",\"line_number\":\"92\",\"thread_name\":\"http-apr-8080-exec-9\",\"@version\":1,\"logger_name\":\"com.protx.vsp.services.authorisationStrategy.StandardAuthorisationStrategy\",\"class\":\"com.protx.vsp.services.authorisationStrategy.StandardAuthorisationStrategy\"}\ …
```
> add check for multiline in the multiline record transformer

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml
- deploy/helm/sumologic/templates/otelcol-configmap.yaml
- deploy/helm/sumologic/templates/otelcol-deployment.yaml
- deploy/helm/sumologic/templates/otelcol-service.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
> Adds the opentelemetry collector

- deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml
- fluent-plugin-zipkin/lib/fluent/plugin/parser_zipkin_protobuf.rb
- fluent-plugin-zipkin/test/plugin/test_parser_zipkin_protobuf.rb
FIx fluent json parsing
Fix zipkin receiver port exposition
> Fix fluentd zipkin json parsing

- deploy/README.md
The prometheus operator requires Helm version 2.12+ now, so we need to update the docs to reflect this
> Update Helm requirement to 2.12+

- deploy/docs/Upgrading_with_Helm.md
This PR adds a clarifying statement to use the latest`values.yaml` before running the helm upgrade command.
> add clarifying doc for helm upgrades

- ci/build.sh
Skips check for touching generated files when the branch name starts with "revert-" to allow PR reverts through Github.
Will need to test by opening a revert after this is merged (e.g. https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/439)
> Allow PR reverts in CI build script

- deploy/docs/Installation_with_Helm.md
- deploy/docs/existingPrometheusDoc.md
- deploy/docs/standAlonePrometheus.md
With the new feature of installing the helm chart with a custom release name and a namespace, the prometheus remote write urls are dynamic. One of the variables used in these urls is sourced from a configmap and exposed via thanos in prometheus-operator.
If the user has existing prometheus/prometheus-operator, they will need to modify the urls. 
**Case 1 : Customer has existing prometheus operator in a different namespace.** 
- Post installation of the sumologic helm chart, copy the `sumologic-configmap` to the namespace where prometheus-operator is installed.
**Case 2: Standalone Prometheus**
- In this case the user will have to manually modify the remote write urls to point to the right location.
**Case 3: Side-by-side prometheus along with exisiting prometheus server in different …
> Update docs for prometheus dynamic remote write urls

- deploy/docker/Dockerfile
Bringing back this change (originally introduced in #356) for major release. This version of fluentd image contains fix for a gzip compression bug in fluentd buffer.
> [1.0.0] Bump fluentd image version to fix fluentd buffer bug

- deploy/helm/sumologic/conf/traces/traces.conf
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
This is mid-PR for integration with terraform (#445). It ensures that it's possible to send traces to proper endpoint before terraform release
> Use endpoint for tracing from values.yaml

- fluent-plugin-zipkin/lib/fluent/plugin/out_zipkin.rb
- fluent-plugin-zipkin/test/plugin/test_out_zipkin.rb
Strip empty fields from sending via fluentd plugin:
* trace_id
* parent_id
* ipv4
* ipv6
> Strip empty fields from sending

- deploy/helm/sumologic/conf/common.conf
- deploy/helm/sumologic/conf/events/events.conf
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
We do not want to ingest the demo log which we use for fluentd liveness probe to be ingested in Sumo. This PR prevents fluentd from handling records containing its own logs.
> Prevent fluentd from handling records containing its own logs.

- deploy/helm/sumologic/values.yaml
> Bump otelcol and remove unused tags

- fluent-plugin-zipkin/lib/fluent/plugin/in_zipkin.rb
- fluent-plugin-zipkin/lib/fluent/plugin/out_zipkin.rb
- fluent-plugin-zipkin/test/plugin/test_out_zipkin.rb
* Re-route unsuccessfully sent traces back to the fluentd
* Add information about first trace passing the pipeline
> Improve zipkin plugins

- deploy/helm/sumologic/conf/traces/traces.conf
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/values.yaml
- fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb
- fluent-plugin-kubernetes-sumologic/test/plugin/test_filter_kubernetes_sumologic.rb
I have a PR under discussion. We have requirement for traces to tag `sourceHost` and `sourceCategory`. There is few possible way to solve this. This PR represents moreless set of changes/differences between traces and logs/metrics.
I see few possible solutions for this issue:
1. Separate filter plugin
2. Extract common part to another plugin (and logs related to another one
3. Filter which behaves little bit different depending on source (like in this PR)
@rvmiller89 @samjsong @vsinghal13 @perk-sumo @pmaciolek 
I would like to know your thoughs
> Support tracing in filter plugin

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
This PR exposes setting resource constraints for fluentbit, prometheus, prometheus-operator.
> Expose setting resource constraints for helm dependencies

- deploy/helm/sumologic/values.yaml
Not all endpoints list on `0.0.0.0` by default. Some of them do on `localhost`. This enables them to listen on `0.0.0.0` and also bumps OpenTelemetry Collector version used
Manual tests with settings applied
> Make Otelcol listen on 0.0.0.0 rather than localhost

- fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb
Do not drop record in filter if it's 'broken'
> Do not drop record in filter if it's 'broken'

- deploy/helm/sumologic/Chart.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- deploy/kubernetes/setup-sumologic.yaml.tmpl
This is a minor release for the opentelemetry collector related changes (disabled by default).
> Set new release 0.16.0

- deploy/helm/sumologic/values.yaml
Updates otelcol config (as the title says) and bumps collector version
> [WIP] Use memory_limiter and better batch settings

- README.md
- deploy/docs/Helm3.md
- deploy/docs/Installation_with_Helm.md
- deploy/docs/Non_Helm_Installation.md
- deploy/docs/Upgrading_with_Helm.md
- deploy/docs/existingPrometheusDoc.md
Let's take the docs for now and reintroduce them when the release is really ready.
> Revert "Bump version in the docs to v0.16.0"

- deploy/helm/sumologic/conf/traces/traces.conf
- deploy/helm/sumologic/values.yaml
- fluent-plugin-zipkin/lib/fluent/plugin/out_zipkin.rb
Move spans per request to configuration for zipkin
> Move spans per request to configuration for zipkin plugin

- deploy/docs/additional_prometheus_configuration.md
Fix markdown typo in additional_prometheus_configuration
> Fix markdown for additional_prometheus_configuration

- deploy/helm/sumologic/conf/logs/logs.source.systemd.conf
This PR adds source_category_replace_dash to systemd log filters.
[The default setting is "/"](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb#L11) and we noticed that container logs were honoring our override, but systemd logs were not.
> Add missing source_category_replace_dash to systemd conf.

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/templates/chart-configmap.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
This PR changes the dynamic namespace env variable to be fluentd namespace for the prometheus remote write URL's.
> change the dynamic namespace env variable to be fluentd namespace

- deploy/helm/sumologic/templates/otelcol-deployment.yaml
- deploy/helm/sumologic/templates/otelcol-service.yaml
- deploy/helm/sumologic/values.yaml
Jaeger Client typically uses UDP `thrift-compact` protocol for sending spans. Lets expose it by default
> Expose otelcol UDP enpoints too

- README.md
- deploy/docs/Helm3.md
- deploy/docs/Installation_with_Helm.md
- deploy/docs/Non_Helm_Installation.md
- deploy/docs/Upgrading_with_Helm.md
- deploy/docs/existingPrometheusDoc.md
- deploy/helm/sumologic/Chart.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- deploy/kubernetes/setup-sumologic.yaml.tmpl
> Bump version to 0.17.0

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
Include OpenTelemetry Collector metrics (if present) when pushing them through fluentd
> Include otelcol metrics

- deploy/helm/sumologic/values.yaml
Updates Open Telemetry collector to a new version. It is based on more recent codebase of the parent project and includes a fix for tagging hostname when it's not set (then, pod name is taken, per https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields )
> Bump otelcol to newer version

- deploy/docs/existingPrometheusDoc.md
Starting version `0.17` we do not need the sed command in the case of existing Prometheus operator.
> change docs for existing prometheus operator to remove sed command

- deploy/helm/sumologic/values.yaml
We're seeing an issue our current policy of installing Falco, by default, as part of our Kubernetes collection solution. We've bundled Falco as part of K8s Collection in order to provide collection of security events. However, the installation of Falco triggers the following security alert if the customer has installed our solution in an EKS cluster that is already being monitored by GuardDuty.
“falco pod is connecting to Bitcoin mining server."
The reason Falco triggers this alert is that it is trying to detect nefarious bitcoin mining within the cluster. It does so by first connecting to well know bitcoin servers, and resolving those hostnames to IPs. It them other processes in the cluster that are connecting to those IP's. This is Falco doing its job, but Falco's activity appears to …
> disable falco by default

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/values.yaml
Fluent bit uses a DB to keep track of monitored files and offsets. This PR modifies the default DB path which is specified in the fluent-bit helm chart to avoid having `database error` in case a user already has fluent-bit installed in the cluster with the default DB path.
> [1.0.0] change default DB path for fluentbit

- deploy/docs/Non_Helm_Installation.md
Update non-helm documentation to add sed command to replace cluster name for non-helm users
> add sed command to replace cluster name for non-helm users

- deploy/docs/Best_Practices.md
> Added how to modify the log level for Falco

- deploy/helm/sumologic/conf/traces/traces.conf
- deploy/helm/sumologic/templates/deployment.yaml
- deploy/helm/sumologic/values.yaml
- fluent-plugin-kubernetes-sumologic/lib/fluent/plugin/filter_kubernetes_sumologic.rb
This does several things:
- uses `host` rather than `hostName` for the tag
- bumps OpenTelemetry Collector to more recent version (with config format changed)
- add default value to `_sourceHost` (being the... `host`)
- removes `start_time` tag
> Hostname and _sourceHost fix for v0.17

- deploy/docs/Non_Helm_Installation.md
We don't need to set the cluster in the prometheus-overrides.yaml since it's set up in fluentd already.
> Remove reference to setting cluster in Prometheus

- deploy/docker/Dockerfile
- deploy/docker/entrypoint.sh
- deploy/docs/Additional_Fluentd_Plugins.md
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Allow to install plugins basing on values.yaml
Solves #139 for simple plugins (which do not require additional libraries)
> Allow to install plugins in docker image

- deploy/helm/sumologic/templates/setup/setup-configmap.yaml
When a user specifies a custom `fluentd.events.sourceCategory`, the terraform template treats it as variable and results in an error, so we need to wrap it in quotes so that TF can treat it as a string.
We will need to backport this to `0.17` as well (except the config is `sumologic.events.sourceCategory` in `0.17`), since current customers are running into this bug.
> add quotes when specifying events sourceCategory

- deploy/docs/standAlonePrometheus.md
All other URL's seem to be already using the correct release branch.
> change tag to release branch

- deploy/helm/sumologic/templates/events-service-headless.yaml
- deploy/helm/sumologic/templates/events-service.yaml
- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/service-headless.yaml
- deploy/helm/sumologic/templates/service.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Found that our e2e tests were failing due to logs and metrics not being sent, while events were still working. I updated the service name to include `fluentd`, tested locally and it seems to be working again
> Add fluentd to service name to fix urls

- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/conf/logs/logs.source.systemd.conf
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
This is similar to the way that Fluent-bit exposes their config. They have the option to set configs, but also to override entire sections if needed.
Here are two of the use-cases we want to solve with this new `fluentd.logs.containers.overrideRawConfig`:
1. If the user wants to change config that requires some form of indentation. examples include adding a new label to split the pipeline based on metadata (metadata based ingest budgets?), or forking to S3 (need to use the `copy` plugin in the output)
2. If the user wants to add a new tag to enrich custom logs with metadata. In that case, they could update the tags in this pipeline from `<filter containers.**>` to `<filter containers.** custom.**>`, which will allow for the custom logs with the custom tag to also go through this pipeline. …
> [1.0.0] expose override raw conf for container log pipeline

- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
We have seen that the plugins are sending the `info` level logs. This PR adds the plugin-specific log level to avoid unnecessary logs.
> add plugin specific log level for metadata and output plugins

- deploy/helm/sumologic/values.yaml
This is a replacement for https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/521/files
- uses host rather than hostName for the tag
- bumps OpenTelemetry Collector to more recent version (with config format changed)
- removes start_time tag
This is v1.0 equivalent of #530
> Update OtelCol and clean up tags

- vagrant/provision.sh
Bump kubernetes version to 1.15 (microk8s with coreDNS)
> vagrant: Bump k8s to 1.15

- deploy/helm/sumologic/templates/configmap.yaml
- deploy/helm/sumologic/templates/events-service-headless.yaml
- deploy/helm/sumologic/templates/events-service.yaml
- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/hpa.yaml
- deploy/helm/sumologic/templates/service-headless.yaml
- deploy/helm/sumologic/templates/service.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
> Adjust fluentd names and app labels

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/setup/setup-configmap.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Add control plane metrics:
- coredns
- etcd
Also extract match section from the metrics configuration to the helm template function
> Control plane metrics

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
Fix url name for control plane metrics in prometheus config
> Fix control plane metrics url to be sync with fluentd

- deploy/docs/existingPrometheusDoc.md
- deploy/docs/standAlonePrometheus.md
Update docs with a note on support and handling for multiple Prometheus replicas.
> Add note on how to handle Prometheus replicas.

- deploy/helm/sumologic/conf/metrics/metrics.conf
Cast version which have suffixes to the base one before comparison: e.g. `15+` -> `15`
> Fix filtering metrics for old kubernetes versions

- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/conf/logs/logs.source.default.conf
- deploy/helm/sumologic/conf/logs/logs.source.systemd.conf
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
> expose fluentd output section for logs

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
Expose resource config for prometheus node-exporter and kube state metrics.
> Expose resource config for prometheus node-exporter and kube state metrics.

- tools/README.md
- tools/tools-usage
> Include serviceaccount in the usage description

- deploy/helm/sumologic/upgrade-1.0.0.sh
Small fixes due to 0.17 to 1.0 upgrade testing
> Small fixes due to 0.17 to 1.0 upgrade testing

- deploy/docker/Dockerfile
- deploy/helm/sumologic/conf/events/events.conf
- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/conf/logs/logs.source.default.conf
- deploy/helm/sumologic/conf/logs/logs.source.systemd.conf
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Bump sumologic fluentd output plugin and override sumo_client with helm version
> Bump sumologic fluentd output plugin and override sumo_client with helm version

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/upgrade-1.0.0.sh
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
Drop histogram metrics (with `_bucket` suffix)
> Do not pass histogram metrics to the fluentd

- deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml
> Fix fluentd url for tracing

- deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/otelcol-deployment.yaml
- deploy/helm/sumologic/templates/otelcol-service.yaml
- deploy/helm/sumologic/values.yaml
Use OpenTelemetry Collector @ Sumo v0.3 series, which includes sources processor (tagging `_sourceCategory` and `_sourceName`) and sends traces directly
> Use Otelcol v0.3 and send spans directly

- deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml
This fixes the issue with tracing endpoint not being set
> Do not set tracing URL if it is not available

- deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml
This reverts commit 24094ac267667d370414343b53d80a1f4189cfc6.
It's actually better for the container to fail early in case of the empty URL.
> Revert "Do not set tracing URL if it is not available"

- deploy/helm/sumologic/upgrade-1.0.0.sh
> Upgrade script fixes

- deploy/helm/sumologic/templates/setup/setup-configmap.yaml
Backport #549 as requested in #550
> Backport 'add quotes when specifying events sourceCategory' (#549)

- deploy/docs/v1_conf_examples.md
> v1 fluentd config examples

- deploy/helm/sumologic/values.yaml
> Add --force flag for pv

- deploy/docs/v1_migration_doc.md
It seems like `-o` flag only works with Helm3 and not with Helm2.
> remove -o flag

- deploy/helm/sumologic/upgrade-1.0.0.sh
- vagrant/provision.sh
Fixes #644
* fix for upgrade script doesn't work under GNU sed >= 4.4
* upgrade needs recent GNU Bash but doesn't check for that
* grep does not have to be modern
* allow for newer yq
> Upgrade script grep sed bash fixes

- deploy/docs/v1_migration_doc.md
Update migration doc due to 0.17.4 release
> Update migration doc due to 0.17.4 release

- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
ingest retry succeeded logs and expose param in values file to turn off the filter
Fixes #621
> ingest retry succeeded logs and expose param in values file 

- deploy/helm/sumologic/requirements.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
> Update prometheus operator helm chart

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
Add list of metrics which we forward to the sumologic
> List metrics forwarded to the sumologic

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/values.yaml
Fixes #596.
Set `Ignore_Older` to `24h` by default to prevent older logs from being ingested when collection is first installed.  Relative times are supported.  Tested using shorter time range (1m) and validated that the older logs are not ingested.
https://github.com/fluent/fluent-bit/issues/221
https://docs.fluentbit.io/manual/pipeline/inputs/tail#config
Note, this is not supported on `systemd` plugin so only updating `tail` plugin.
> Set `Ignore_Older` to `24h` by default to prevent older logs from being ingested on install.

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
This PR is intended to replace #581. 
This PR exposes the global prometheus scrape interval, as well as the per target of each serviceMonitor we scrape from.
> Expose Scrape Intervals in values.yaml to make it easier to adjust.

- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/conf/setup/sumo-k8s.tf
- deploy/helm/sumologic/templates/NOTES.txt
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/values.yaml
Description
Fixes #608. When spaces are found in `sumologicClusterName`, replace them with dashes and warn via NOTES.txt.
Testing performed
ci/build.sh
[ X ] Redeploy fluentd and fluentd-events pods
[ X ] Confirm events, logs, and metrics are coming in
> Ensure clusterName has no spaces to prevent issue with Explore rendering.

- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/chart-configmap.yaml
- deploy/helm/sumologic/templates/clusterrole.yaml
- deploy/helm/sumologic/templates/clusterrolebinding.yaml
- deploy/helm/sumologic/templates/configmap.yaml
- deploy/helm/sumologic/templates/events-configmap.yaml
- deploy/helm/sumologic/templates/events-service-headless.yaml
- deploy/helm/sumologic/templates/events-service.yaml
- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/hpa.yaml
- deploy/helm/sumologic/templates/metrics-configmap.yaml
- deploy/helm/sumologic/templates/metrics-hpa.yaml
- deploy/helm/sumologic/templates/metrics-service-headless.yaml
- deploy/helm/sumologic/templates/metrics-service.yaml
- deploy/helm/sumologic/templates/metrics-statefulset.yaml
- deploy/helm/sumologic/templates/otelcol-configmap.yaml
- deploy/helm/sumologic/templates/otelcol-deployment.yaml
- deploy/helm/sumologic/templates/otelcol-service.yaml
- deploy/helm/sumologic/templates/service-headless.yaml
- deploy/helm/sumologic/templates/service.yaml
- deploy/helm/sumologic/templates/serviceaccount.yaml
- deploy/helm/sumologic/templates/setup/setup-clusterrole.yaml
- deploy/helm/sumologic/templates/setup/setup-clusterrolebinding.yaml
- deploy/helm/sumologic/templates/setup/setup-configmap.yaml
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/templates/setup/setup-serviceaccount.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
The purpose is to not lost track of relations between kubernetes objects
> Generate labels and names using helm templates

- deploy/helm/sumologic/conf/logs/logs.kubernetes.sumologic.filter.conf
- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
> add collectionMonitoring logic

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
Rebased #676  (Use env for prometheus metrics namespace)
> Use env for prometheus metrics namespace

- deploy/helm/sumologic/templates/metrics-service-headless.yaml
- deploy/helm/sumologic/templates/service-headless.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Fix labels for headless services
> Fix labels for headless services

- ci/build.sh
- deploy/helm/sumologic/requirements.yaml
Replace Falco helm/stable with falcosecurity/charts.
Fixes #332 and #687
> Switch helm chart from helm/stable to falcosecurity/charts.

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/requirements.yaml
- deploy/helm/sumologic/templates/configmap.yaml
- deploy/helm/sumologic/templates/metrics-configmap.yaml
- deploy/helm/sumologic/templates/metrics-service-headless.yaml
- deploy/helm/sumologic/templates/metrics-service.yaml
- deploy/helm/sumologic/templates/metrics-statefulset.yaml
- deploy/helm/sumologic/templates/service-headless.yaml
- deploy/helm/sumologic/templates/service.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
> optional metrics resources

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/conf/events/events.conf
- deploy/helm/sumologic/conf/logs/logs.output.conf
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/conf/setup/setup.sh
- deploy/helm/sumologic/conf/setup/sumo-k8s.tf
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/metrics-statefulset.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Expose http sources in values.yaml
I decided to not expose logs and events so far
> Expose http sources for metrics in values.yaml

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
Restrict coredns and etcd  metrics
> Filter list of control-plane app metrics

- ci/build.sh
Fix Travis build due to default shallow git clone
https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth
> Fix Travis build due to default shallow git clone

- deploy/docker/Dockerfile
- deploy/helm/sumologic/conf/setup/sumo-k8s.tf
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/strip_extrapolation.input.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
* Bump providers versions
* Bump terraform client version due to bugs
* Update terraform scripts due to deprecation warnings
* Add one new test and update previous ones regarding aboves
> Bump terraform providers

- deploy/helm/sumologic/conf/events/events.conf
- deploy/helm/sumologic/conf/logs/logs.output.conf
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/conf/setup/setup.sh
- deploy/helm/sumologic/conf/setup/sumo-k8s.tf
- deploy/helm/sumologic/conf/traces/traces.conf
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/metrics-statefulset.yaml
- deploy/helm/sumologic/templates/otelcol-deployment.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- deploy/kubernetes/setup-sumologic.yaml.tmpl
- tests/terraform/static/all_fields.input.yaml
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/conditional_sources.input.yaml
- tests/terraform/static/conditional_sources.output.yaml
- tests/terraform/static/default.output.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
- tests/terraform/static/traces.input.yaml
- tests/terraform/static/traces.output.yaml
Auto-generate logs, events and traces endpoints in terraform
It doesn't add automatic usage of these sources in fluentd. It has to be done manually
This PR is made almost on the top of the #705
> Add generator for logs, events and traces sources

- deploy/helm/sumologic/conf/events/events.conf
- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/conf/logs/logs.source.default.conf
- deploy/helm/sumologic/conf/logs/logs.source.systemd.conf
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/conf/traces/traces.conf
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Adds `fluentd_input_status_num_records_total` and `fluentd_output_status_num_records_total` metrics
Fixes #717
> Add missing metrics to fluentd

- deploy/helm/sumologic/conf/setup/resources.tf
- deploy/kubernetes/setup-sumologic.yaml.tmpl
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/conditional_sources.output.yaml
- tests/terraform/static/default.output.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
- tests/terraform/static/traces.output.yaml
Fix potential tf race confition
Fixes #720
> Fix potential tf race confition

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/requirements.yaml
- deploy/helm/sumologic/values.yaml
Multiple conditions works as below:
1. If first value is specified, it decides if the requirement is installed or not
2. If it's not, the second is taken under consideration
due to point 1 we should change order of conditions and comment the `prometheus-operator.enabled`
so for prometheus:
If `prometheus-operator.enabled` is not set, the `metrics.enabled` decides if we enable prometheus or not, otherwise `prometheus-operator.enabled` is decisive
> Fix helm chart requirements conditions

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
I observed during review that we already use 'sumologic.com/' prefix in annotations so it would be better to stick that convention for internal labels
> Use sumologic.com as prefix for internal labels

- vagrant/forwarding/forward-dashboard.sh
- vagrant/forwarding/forward-prometheus.sh
- vagrant/provision.sh
> Bump k8s in vagrant to 1.18

- deploy/helm/sumologic/conf/setup/resources.tf
- deploy/helm/sumologic/conf/setup/setup.sh
Normally in helm the namespace is created automatically or beforehand, in most cases organizations will want to add metadata to their namespace for auditing and automating purposes. Sumologic's helm setup job makes this impossible as it recreates the namespace thus removing all the metadata added beforehand. This PR's intention is to remove this responsibility from sumologic's helm.
> Severity1 fix 741

- deploy/docs/Terraform.md
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Add Terraform variables section to terraform documentation
I didn't add information about `local`, as it is just alias for source name which is took from values.yaml
> Add Terraform variables section to terraform documentation

- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/metrics-statefulset.yaml
> Fix indents on FluentDs extraEnvVars and extraVolumes

- deploy/helm/sumologic/templates/_helpers.tpl
When enabled HPA throws the following error:
template "sumologic.metadata.name.metrics.hpa" not defined
template "sumologic.metadata.name.logs.hpa" not defined
> fix: HPA for FluentDs

- deploy/helm/sumologic/conf/buffer.output.conf
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Use retry_max_interval instead of retry_timeout for fluentd buffer
https://docs.fluentd.org/configuration/buffer-section#retries-parameters
```
retry_timeout [time]
Default: 72h
The maximum seconds to retry to flush while failing, until plugin discards buffer chunks
retry_forever [bool]
Default: false
If true, plugin will ignore retry_timeout and retry_max_times options and retry flushing forever
retry_max_interval [time]
Default: none
The maximum interval seconds for exponential backoff between retries while failing
```
> Use retry_max_interval instead of retry_timeout for fluentd buffer

- deploy/helm/sumologic/values.yaml
Use **SUMO_ENDPOINT_DEFAULT_TRACES_SOURCE** environment as default Zipkin exporter URL.
> Use SUMO_ENDPOINT_DEFAULT_TRACES_SOURCE env

- deploy/docs/Terraform.md
Add information about building the endpoint variable names
> Add information about building the endpoint variable names

- deploy/helm/sumologic/conf/traces/traces.otelcol.conf.yaml
- deploy/helm/sumologic/values.yaml
> Remove the unused sumologic.traces.endpoint key (clean up otelcol conf after the #778 merge)

- deploy/helm/sumologic/templates/NOTES.txt
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Enabled fluentd file persistence by default along with a warning message if the property `fluentd.persistence.enabled` is set to `false`
> Enable file persistence by default

- deploy/helm/sumologic/values.yaml
Otelcol is bumped to 0.6.1 and config updated accordingly
> Use Otelcol 0.6.1 and corresponding configuration

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/metrics-statefulset.yaml
- deploy/helm/sumologic/templates/otelcol-deployment.yaml
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
- Users will be able to add labels to all fluentd pods and setup job.
- There is a common property to apply to all fluentd pods together, as well as the ability to add to each individually.
- expose the ability to add labels on fluent-bit and Prometheus
Configs:
- `sumologic.podLabels` -> add labels to fluentd sts, setup job, otelcol deployment
- `fluentd.podLabels` -> add labels to all fluentd sts.
- `fluentd.logs.statefulset.podLabels` -> add labels only to logs fluentd sts.
- `fluentd.metrics.statefulset.podLabels` -> add labels only to metrics fluentd sts.
- `fluentd.events.statefulsetpodLabels` -> add labels only to events fluentd sts.
- `otelcol.deployment.podLabels` -> add labels only to otelcol deployment.
- `sumologic.setup.job.podLabels` -> add labels only to setup job.
> add custom labels to fluentd sts and setup job pods

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- Add custom labels for `kube-state-metrics`.
- Fixed the indentation for `prometheus-node-exporter` and `kube-state-metrics`
> Add customLabels for kube-state-metrics

- deploy/docs/Non_Helm_Installation.md
- deploy/docs/Terraform.md
- deploy/docs/additional_prometheus_configuration.md
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/metrics-statefulset.yaml
- deploy/helm/sumologic/templates/otelcol-deployment.yaml
- deploy/helm/sumologic/templates/setup/setup-clusterrole.yaml
- deploy/helm/sumologic/templates/setup/setup-clusterrolebinding.yaml
- deploy/helm/sumologic/templates/setup/setup-configmap.yaml
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/templates/setup/setup-serviceaccount.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/values.yaml
Allow custom pod annotations in helm chart
> Allow custom pod annotations in helm chart

- deploy/helm/sumologic/conf/logs/logs.conf
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Allows the user to specify additional forward plugin config in fluentd for TLS, security, etc.
> expose extra conf for fluentd in_forward

- deploy/docs/Best_Practices.md
- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/values.yaml
- Add documentation to configure `Ignore_Older` parameter
- Remove setting `Ignore_Older` by default in `values.yaml` file
> Add ignore_older documentation

- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/metrics-statefulset.yaml
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
- add labels to `template.metadata` for setup job
- remove labels from the `selector` for all the sts as `updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`
> fix podLabels

- deploy/docs/Best_Practices.md
- Update the docs to reflect the configuration for autoscaling the logs and metrics fluentd `statefulsets`.
> update autoscaling section in docs

- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
It seems that [previous PR](https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/843) managed to break setup-job by moving the helm.sh annotations to pod spec. This PR address that.
> Fix broken setup job helm.sh annotations

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
This PR adds possibility to add custom:
* annotations for `kube-state` pods (as described in https://github.com/helm/charts/tree/master/stable/kube-state-metrics#configuration) 
* annotations and labels for `prometheus` pods (as described in https://github.com/helm/charts/tree/master/stable/prometheus-operator#prometheus)
> Allow custom pod annotations for kube-state and prometheus

- deploy/docs/v1_conf_examples.md
- deploy/helm/sumologic/conf/buffer.output.conf
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Set text compress as default due to https://github.com/fluent/fluentd/issues/3110
> Set text compress as default

- deploy/docs/additional_prometheus_configuration.md
Use variables in documentation for additional prometheus metrics. The current service name used in the docs is out of date
> Use variables in documentation for additional prometheus metrics

- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
> disable fluentd persistence by default

- deploy/docs/Best_Practices.md
Add info to best practices doc about docker mode multiline in fluent-bit
> Add info to best practices doc about docker mode multiline in fluent-bit

- deploy/helm/sumologic/templates/NOTES.txt
> Provide FluentD file persistence setting key in the chart notes

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
> Drop container=pod label when scraping container network metrics

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
Relabel pod and service dimensions for non-pod metrics
> Relabel pod and service dimensions for non-pod metrics

- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/connector.rb
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/reader.rb
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/service_monitor.rb
- fluent-plugin-enhance-k8s-metadata/test/plugin/test_filter_enhance_k8s_metadata.rb
- fluent-plugin-events/lib/fluent/plugin/in_events.rb
- fluent-plugin-events/lib/sumologic/kubernetes/connector.rb
- fluent-plugin-events/test/plugin/test_in_events.rb
**Edit:** New proposal based on Dominik's comments is to retry for ~4 minutes (with exponential backoff) in the `configure` step. This should hopefully give enough leeway for transient issue, and throw an exception otherwise, causing the Fluentd worker process to die and restart (after having logged the exception). This will make it way easier to understand the issue than the previous `Got exception undefined method`.
Based on the issues that @frankreno mentioned some customers were facing with
```
Got exception undefined method _____ for #<String:0x00007ff19eaf4e60> ______
```
I found that this is because Ruby does a weird thing where if a method returns an exception, Ruby treats that exception as a String type. In this case, inside `connect_kubernetes` we call `create_client` which can …
> retry creating kubeclients when error

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
> Fix prometheus configuration

- deploy/helm/sumologic/templates/events-service-headless.yaml
- deploy/helm/sumologic/templates/metrics-service-headless.yaml
- deploy/helm/sumologic/templates/service-headless.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
This prevents prometheus double scraping fluentd pods by removing the annotations from headless services.
> Don't scrape from headless services

- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/reader.rb
- fluent-plugin-enhance-k8s-metadata/test/plugin/test_filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/test/resources/records.json
Attach node metadata to metrics when it is not already present.
> attach node metadata to metrics when not present

- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/metrics-statefulset.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
We're not using fluentd's [`tail` input plugin](https://docs.fluentd.org/input/tail) so don't define pos files volumes.
> Don't mount and don't define pos volumes for fluentd

- deploy/docs/additional_prometheus_configuration.md
- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
Scrap metrics from pods basing on annotations
rel: https://github.com/prometheus-operator/kube-prometheus/pull/16#issuecomment-424318647
rel: https://github.com/prometheus/prometheus/pull/4131
> Scrap metrics from pods basing on annotations

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
Solves #862 
Ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#thanosspec
> define resources for thanos sidecar

- deploy/helm/sumologic/requirements.yaml
Fixes #811 
Closes #904 
Tested with EKS
* k8s `v1.16`
* AMI `ami-016ce7a1ae8ecbc95`
* Sumo Logic chart version 1.2.2 (https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/ee84b7843551a20ffbf78c965c6516da45f39a0a)
Got a successful falco launch:
```
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to dkms install falco module
* Running dkms build failed, couldn't find /var/lib/dkms/falco/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/build/make.log
* Trying to load a system falco driver, if present
* Trying to find locally a prebuilt falco module for kernel 4.14.193-149.317.amzn2.x86_64, if present
* Trying to download prebuilt module from …
```
> Update Falco helm chart to 1.3.0

- vagrant/Makefile
- vagrant/README.md
- vagrant/provision.sh
Add build target to the vagrant's Makefile
> Add build target to the vagrant's Makefile

- deploy/helm/sumologic/templates/otelcol-service.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- tests/tracing/static/collection-monitoring-false.output.yaml
- tests/tracing/static/simple.output.yaml
> Add HTTP protocol for OTLP receiver

- vagrant/values.yaml
Fix grafana installation
```
Error: UPGRADE FAILED: template: sumologic/charts/prometheus-operator/charts/grafana/templates/deployment.yaml:46:10: executing "sumologic/charts/prometheus-operator/charts/grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: sumologic/charts/prometheus-operator/charts/grafana/templates/_pod.tpl:75:18: executing "grafana.pod" at <.Values.sidecar.image.sha>: can't evaluate field sha in type interface {}
```
> Fix grafana installation in vagrant

- ci/build.sh
We had a bug in our build script which was revealed when we double-quoted all the variables:
https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/911/files#diff-78b1794b72c7105dbabbe466019395d6R21
It was working previously because the `git checkout` command can work without the argument where it just takes the current branch.
But it can't work with an empty argument (see below):
```
$ git checkout
Your branch is up to date with 'origin/master'.
$ git checkout ""
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
$ git checkout "master"
Already on 'master'
Your branch is up to date with 'origin/master'.
```
The problem could not occur during the PR phase, it would only show itself on master (and release) branch build, hence the …
> Fix CI on master: always provide the branch name to checkout

- deploy/helm/sumologic/conf/setup/setup.sh
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/conditional_sources.output.yaml
- tests/terraform/static/default.output.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
- tests/terraform/static/traces.output.yaml
Do not proxy kubernetes internal traffic
> Do not proxy kubernetes internal traffic

- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
The cache TTL was increased as well because it always needs
to be greater than the refresh interval, to prevent a situation where
there is no cached value for a resource.
> Increase cache refresh interval to 1 hour

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
Using `values.yaml` from the repository without any scaling changes it seems that `thanos-sidecar` gets OOMKilled every ~~15min.
This PR addresses that by increasing the memory limit to `32Mi`.
With that it seems that memory usage stabilize at around `18Mi` for the "default" setup.
> Increase memory limits for thanos-sidecar to 32Mi to prevent restarts

- deploy/helm/sumologic/README.md
Add proxy options to the README.md
backport of #940
> Add proxy options to the README.md

- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/connector.rb
- fluent-plugin-enhance-k8s-metadata/test/helper.rb
Because of using arrays in configuration, e.g. here https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/bc3f0db72011c0b797edddc7f794d0ca58e9e37c/deploy/kubernetes/fluentd-sumologic.yaml.tmpl#L102
let's roll back `hash` to `array` and change code accordingly.
> Fix handling api versions in fluent-plugin-enhance-k8s-metadata

- vagrant/provision.sh
Using `snap` instead of `apt` as the version of `shellcheck` packaged by `snap` is a bit more up to date (`0.7.0` vs `0.4.6-1` as of now).
> Add shellcheck to vagrant

- vagrant/provision.sh
It seems that it isn't as easy as we might think:
`shellcheck`'s snap doesn't have access to all filesystems 
```
snap connections shellcheck
Interface        Plug                        Slot   Notes
home             shellcheck:home             :home  -
removable-media  shellcheck:removable-media  -      -
```
and it doesn't seem that it's easy to allow it to access (in our case) `/sumologic`
https://askubuntu.com/questions/1033344/how-to-give-snaps-access-to-somedir
> Install shellcheck with apt in vagrant

- ci/build.sh
> Extract bundle fluentd plugins function

- deploy/docker/Dockerfile
* aggregate `gem install`s into less invocations
* unify formatting (`&&` at the beginning of the line and equal indentation)
> Refactor build Dockerfile

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/values.yaml
The default `cri` parser defined in fluent-bit uses `message` as the key, instead of `log`. This PR defines a custom `crio` parser which uses the `log` key instead, so that the Sumo Logic apps do not break.
Example of `CRI`format log with `message` key attached.
> add crio parser to fluent-bit

- deploy/helm/sumologic/README.md
> change prometheus-operator docs to kube-prometheus-stack

- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/conf/logs/logs.enhance.k8s.metadata.filter.conf
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
This PR introduces a random variation in cache refresh interval for each pod, allowing the load on API server to be spread in time.
By default, there are multiple Fluentd pods running in a cluster, each of the pods maintaining its own version of pod metadata cache. The cache is being refreshed by each Fluentd pod independently in regular intervals specified by the `fluentd.metadata.cacheRefresh` configuration variable. Before this change, the cache refresh interval was equal for all pods, causing all of them to flood API server with queries in approximately the same time.
The introduction of `fluentd.metadata.cacheRefreshVariationRange` configuration variable makes it possible to spread the load on API server by changing the cache refresh interval by a different, randomly assigned value …
> Introduce cache refresh variation

- ci/build.sh
- vagrant/.gitignore
- vagrant/Makefile
- vagrant/scripts/generate-local-config.sh
- vagrant/scripts/generate-local-values-file.sh
This is a poor man's try at adding the following improvements:
- When building locally, push the built Docker image to local registry and use it when running locally.
- When building locally, use Docker cache.
Suggestions for improvements are welcome.
> Use local changes when building and running locally

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
- vagrant/k8s/application_metrics/jmx/jolokia/agent/statefulset.yaml
- vagrant/k8s/application_metrics/jmx/jolokia/docker/statefulset.yaml
> Add list of jmx metrics

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/kube-prometheus-sumo-logic-mixin.libsonnet
The `kube-state-metrics` helm chart  currently uses the `v1.9.7` image  which still uses `hpa` instead of `horizontalpodautoscaler`.
These will be renamed as part of `v2.0.0` of kube-state-metrics.
`v2.0.0 Alpha` release notes: https://github.com/kubernetes/kube-state-metrics/releases
Ref PR: https://github.com/kubernetes/kube-state-metrics/pull/1003
> rename hpa metrics

- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Splits the filter commonly assigned to Fluentd and OTC into two separate filters.
For OTC, select logs with warning or error level, as well as some of the other logs
from selected components. That way we e.g. skip logging exporter logs (which could
flood the ingest)
> Include OpenTelemetry Collector logs by default

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
Update info about adoptopenjdk-openj9 missing metrics
> Update info about adoptopenjdk-openj9 missing metrics

- deploy/helm/sumologic/values.yaml
Cleanup white chars from v1.2.0
> Cleanup white chars from v1.2.0

- deploy/helm/prometheus-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/setup-sumologic.yaml.tmpl
I propose to remove resources from Prometheus in `1.3` release and reintroduce it in `2.0`.
It has been added as a fix for https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/885
I see adding `resources` for Prometheus were wrong values can break the solution as a breaking change.
The same story with `setup job` and for `Thanos`.
> fix: remove adding new resources limits and requests from 1.3

- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- deploy/kubernetes/setup-sumologic.yaml.tmpl
> Revert the FluentD image version to 1.2.3

- ci/build.sh
- deploy/README.md
- deploy/docs/existingPrometheusDoc.md
- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/requirements.yaml
- deploy/helm/sumologic/values.yaml
This reverts commit 12916f9c93c61dec6ba4856a5c757e8f8af5e611.
> Revert "Revert to using helm stable for Prometheus Operator chart"

- deploy/helm/sumologic/README.md
Add flags related to Telegraf Operator to the chart's README
> Add flags related to Telegraf Operator to the chart's README

- deploy/helm/sumologic/README.md
Adds docs for OpenTelemetry Collector-related params
> Include description of otelcol Helm chart params

- deploy/README.md
> Remove unsupported AKS 1.15 and GKE 1.14 from the docs

- ci/build.sh
The command `helm repo index` is changing timestamps for already existing charts.
This seems to be intended: https://github.com/helm/helm/issues/7363
Helm stable repo tests use this workaround:
https://github.com/helm/charts/blob/c6e503ccfd9911dd06ea9ac389a40a3490637516/test/repo-sync.sh#L83-L90
This PR adds the mentioned workaround to our build.
It's a first step for #987
> Fix: do not change timestamps for already existing helm charts

- Vagrantfile
If user has `vagrant-disksize` plugin missing he'll get an error saying:
```
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:
Vagrant:
* Unknown configuration section 'disksize'.
```
This PR catches this explicitly and suggests how to install said plugin.
> Add check for vagrant disksize plugin in Vagrantfile

- deploy/helm/sumologic/templates/scc.yaml
Allow HostsPorts for openshift (required for node-exporter).
> Allow HostsPorts for openshift (required for  node-exporter)

- .travis.yml
- ci/build.sh
- ci/tests.sh
- deploy/docker/entrypoint.sh
- deploy/helm/sumologic/upgrade-1.0.0.sh
- tests/functions.sh
- tests/run.sh
- tests/upgrade_script/run.sh
- vagrant/Makefile
- vagrant/forwarding/forward-dashboard.sh
- vagrant/forwarding/forward-prometheus.sh
- vagrant/k8s/application_metrics/jmx/jmxexporter/docker/Dockerfile
- vagrant/k8s/application_metrics/jmx/jolokia/agent/Dockerfile
- vagrant/k8s/application_metrics/jmx/jolokia/docker/Dockerfile
- vagrant/provision.sh
- vagrant/scripts/sumo-make-completion.sh
Extract unit tests from build.sh
> Extract unit tests from build.sh and run as separate build stage

- deploy/docker/Dockerfile
Fixes #995 by upgrading the Fluent plugin that was causing the issue.
Link to the fix in the plugin: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/204
> Bump fluent-plugin-kubernetes_metadata_filter from 2.4.1 to 2.5.2

- deploy/helm/sumologic/requirements.yaml
- vagrant/values.yaml
* enable falco by default in vagrant
* add known k8s api callers to prevent unnecessary notice logs - https://github.com/falcosecurity/falco/blob/388de273985758afbfc2833885faa24ee5da5703/rules/falco_rules.yaml#L2422-L2436
* bump falco chart from `1.4.0` to `1.5.0` (this bumps falco from `0.25.0` to `0.26.1`)
> Add known k8s api callers to vagrant values.yaml and bump falco chart to 1.5.0

- deploy/helm/sumologic/conf/logs/logs.source.default.conf
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
> exclude fluentd warning message

- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/values.yaml
Add priorityClassName to events statefulset
> Add priorityClassName to events statefulset

- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/values.yaml
* Add priorityClassName to events statefulset
* Update options in README.md
> Add priorityClassName to events statefulset (#1006 backport)

- deploy/docker/Dockerfile
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Bump fluentd and enable gzip compression by default
> Bump fluentd and enable gzip compression by default

- deploy/helm/sumologic/requirements.yaml
Bump telegraf-operator to 1.1.6 ([official 1.1.5](https://github.com/influxdata/helm-charts/tree/master/charts/telegraf-operator) + helm2 support)
> Bump telegraf-operator to 1.1.6 (official 1.1.5 + helm2 support)

- deploy/helm/sumologic/requirements.yaml
Bump telegraf-operator to 1.1.6 (official 1.1.5 with helm2 support) #1008 Backport
> Bump telegraf-operator to 1.1.6 (official 1.1.5 with helm2 support)(#1008 Backport)

- deploy/docs/Best_Practices.md
Add information how to setup metrics-server in kops clusters
> Add information how to setup metrics-server in kops clusters

- deploy/helm/sumologic/conf/setup/main.tf
- deploy/kubernetes/setup-sumologic.yaml.tmpl
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/conditional_sources.output.yaml
- tests/terraform/static/default.output.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
- tests/terraform/static/traces.output.yaml
Bump to https://github.com/SumoLogic/terraform-provider-sumologic/releases/tag/v2.3.0
> Bump sumologic-terraform-provider to 2.3.0

- deploy/helm/sumologic/conf/setup/main.tf
- deploy/kubernetes/setup-sumologic.yaml.tmpl
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/conditional_sources.output.yaml
- tests/terraform/static/default.output.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
- tests/terraform/static/traces.output.yaml
Bump to https://github.com/SumoLogic/terraform-provider-sumologic/releases/tag/v2.3.3
> Bump sumologic-terraform-provider to 2.3.3

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/values.yaml
> override fluent bit image to 1.6.0 for helm chart version 1.3

- vagrant/values.yaml
* `prometheus` key was under `grafana` key which according to `helm show values prometheus-community/kube-prometheus-stack` doesn't exist (yet it exists under `prometheus-operator`'s root key)
* add somewhat relaxes limits to vagrant prometheus to prevent OOMs
> Fix vagrant values.yaml and add limits for prometheus

- deploy/docs/Installation_with_Helm.md
> fix typo in helm installation command

- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/templates/otelcol-deployment.yaml
- deploy/helm/sumologic/templates/otelcol-service.yaml
- deploy/helm/sumologic/values.yaml
**###### Description**
New variable `otelcol.metrics_enabled` gives possibility to disable or enable (false/true) metrics coming from OpenTelemetry Collector. Changes are touching otc-service configuration (ports), otc-deployment (additional argument in command), values.yaml (default value).
**Expected log when metrics are enabled:**
`{"level":"info","ts":1602188423.6246598,"caller":"service/service.go:256","msg":"Setting up own telemetry..."}
{"level":"info","ts":1602188423.6251273,"caller":"service/telemetry.go:100","msg":"Serving Prometheus metrics","address":":8888","legacy_metrics":false,"new_metrics":true,"level":3,"service.instance.id":"c8020a8f-9ccb-4d98-8619-b0ddf1f24331"}
{"level":"info","ts":1602188423.6261094,"caller":"service/service.go:293","msg":"Loading configuration..."}` …
> Add possibility to disable metrics coming from OTC

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/values.yaml
Override Fluent Bit image to 1.6.0
> Override Fluent Bit image to fluent/fluent-bit:1.6.0

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/values.yaml
Use `Docker_Mode_Parser` to support `Docker_Mode` and `Multiline` together.
> Change default Fluent Bit config: use Docker_Mode

- .travis.yml
* Add retries to `curl` when installing dependencies in CI.
* Update travis image to `bionic`
* Install `helm` from `tar.gz` not via `snap` (way faster)
> CI: add retries to curl, update image and install helm from tar.gz

- deploy/helm/sumologic/templates/metrics-pdb.yaml
Check if metrics are enabled when creating metrics pdb.
Closes https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1044
> Add condition when creating metrics pdb

- .travis.yml
`before_install` left files which provides to Ci error and prevents from publishing new helm chart
https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1055
> Add cleanup to travis

- vagrant/values.yaml
* filter `fluentd` k8s api calls by image repository not by proc names
* add falco and prometheus node exporter to `user_sensitive_mount_containers`
> Update falco rules in vagrant

- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/metrics-statefulset.yaml
- deploy/helm/sumologic/templates/otelcol-deployment.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
Add `checksum/config` annotations for `fluentd` and `otelcol` deployment/statefulset
fixes #1046
> Add checksum/config annotations for fluentd and otelcol

- ci/build.sh
helm-sync directory was created outside of helm -> docker scope what was causing no such file or directory error during merging indexes
> CI bugfix: use relative path for the helm sync dir

- tests/run.sh
Check if docker daemon is running before running tests
> Check if docker daemon is running before running tests

- deploy/helm/sumologic/requirements.yaml
The old stable charts bucket [will be shut down this month](https://github.com/helm/charts/issues/23742#issuecomment-702128318). Users will be unable to install or upgrade this chart, as the transitive dependency on fluent-bit will fail to resolve.
[There is a new URL that can be used to resolve stable charts](https://helm.sh/blog/new-location-stable-incubator-charts/). This takes advantage of that.
This should close #750, in a non-breaking way.
> Use new stable repo URL

- deploy/helm/sumologic/values.yaml
Set Prometheus data retention to 1 day
> Set Prometheus data retention to 1 day (#793)

- deploy/helm/sumologic/templates/otelcol-deployment.yaml
It's a https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1086 backport.
> Add OTLP HTTP port

- deploy/README.md
- vagrant/README.md
- Corrected formatting
- Added useful information to vagrant readme
> Changes in documentation

- deploy/helm/sumologic/templates/hpa.yaml
- deploy/helm/sumologic/templates/metrics-hpa.yaml
- deploy/helm/sumologic/values.yaml
Update autoscaling/v1 to autoscaling/v2beta2 in order to enable custom metrics autoscaling and autoscaling based on memory utilization.
This PR adds `targetMemoryUtilizationPercentage` key to enable autoscaling based on memory utilization.
ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics
> Update autoscaling/v1 to autoscaling/v2beta2

- index.yaml
Fix creation date for helm charts using [script](https://gist.github.com/kkujawa-sumo/b196d4106201c23d740ed2f051c989df), [report](https://gist.github.com/kkujawa-sumo/58d697ba69f74331e865daeb06eb4ede) generated by script
> Fix creation date for helm charts

- index.yaml
git tag does not exist for some of helm charts versions in such cases last modification date of the chart is used.
Previously used script to fix dates was updated and this pull request contains changes only for helm charts with missing git tag.
[script](https://gist.github.com/kkujawa-sumo/b196d4106201c23d740ed2f051c989df), [report](https://gist.github.com/kkujawa-sumo/58d697ba69f74331e865daeb06eb4ede) generated by script.
> Fix creation date for helm charts with missing tag

- deploy/docs/v1_migration_doc.md
> update non-helm migration steps to only what is needed

- .travis.yml
.travis.yml seems to be no longer needed, please see [this conversation](https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1093#issuecomment-727885480). It causes failed build result, see [example](https://travis-ci.com/github/SumoLogic/sumologic-kubernetes-collection/builds/201716813).
> Remove .travis.yml from gh-pages

- deploy/docs/Installation_with_Helm.md
- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/templates/serviceaccount.yaml
- deploy/helm/sumologic/values.yaml
This PR adds possibility to specify `pullSecrets` in order to authenticate with docker registry.
This can be done in order to e.g. overcome [hub.docker.com rate limiting](https://www.docker.com/increase-rate-limits)
Creating this secret is beyond the scope of our manuals and readme and user can refer to [Creating a Secret with a Docker config at kubernetes.io](https://kubernetes.io/docs/concepts/containers/images/#creating-a-secret-with-a-docker-config).
In order to use this secret for our dependencies, one can use the following customization in `values.yaml`:
* kube-prometheus-stack https://github.com/prometheus-community/helm-charts/blob/72a59c7bd3ff092cfd1bd2e654feaa62618a2b6f/charts/kube-prometheus-stack/values.yaml#L105-L109
* fluent-bit …
> Allow specifying pullSecrets

- deploy/helm/sumologic/values.yaml
In k8s 1.19 `kubelet_running_container_count` and `kubelet_running_pod_count` has been renamed.
https://github.com/kubernetes/kubernetes/blob/b3fc8888631a43c21df159c395e560adf967be1f/CHANGELOG/CHANGELOG-1.19.md
```
Kubelet: following metrics have been renamed: kubelet_running_container_count --> kubelet_running_containers kubelet_running_pod_count --> kubelet_running_pods (#92407, @RainbowMango) [SIG API Machinery, Cluster Lifecycle, Instrumentation and Node]
```
> Add forwarding kubelet_running containers and pods metrics

- ci/build.sh
There were missing these lines [line#115](https://github.com/SumoLogic/sumologic-kubernetes-collection/compare/kkujawa-pushing-chart-to-dir?expand=1#diff-0f42fd993ce699d1eaf4007157dd696e37a4ad3f424642cf0e504cfba2faa97eR115) and [line#113](https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1122/commits/3f631c51786d349ef219a575031ab272bd49c261#diff-0f42fd993ce699d1eaf4007157dd696e37a4ad3f424642cf0e504cfba2faa97eR113) in #1117.
> Push dev charts into dev directory

- deploy/helm/sumologic/values.yaml
When migrating to the new fluent-bit chart, I removed docker_mode support.  This adds it back in.
> Switch back to docker_mode

- artifacthub-repo.yml
Added artifacthub-repo.yaml required to [claim ownership](https://github.com/artifacthub/hub/blob/master/docs/repositories.md#ownership-claim).
> Add artifacthub-repo.yaml with owners

- artifacthub-repo.yml
> Extend helm charts owners

- deploy/helm/sumologic/conf/setup/setup.sh
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/conditional_sources.output.yaml
- tests/terraform/static/custom.output.yaml
- tests/terraform/static/default.output.yaml
- tests/terraform/static/disable_default_metrics.output.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
- tests/terraform/static/traces.output.yaml
Only import sources when collector exists.
This should cut down the time needed for setup job to complete.
> Only import sources when collector exists

- deploy/helm/sumologic/requirements.yaml
Bump metrics-server to 5.0.2
`5.0.0` dropped support for helm2 hence this is another change that doesn't support helm in our collection
ref: https://github.com/bitnami/charts/tree/master/bitnami/metrics-server#to-500
> Bump metrics-server to 5.0.2

- .github/CODEOWNERS
Add explicit list of active maintainers to CODEOWNERS
> Add explicit list of active maintainers to CODEOWNERS

- deploy/helm/sumologic/README.md
It's a backport of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1143
> Fix for chart documentation spelling of Fluent Bit and Kube Prometheus Stack

- deploy/helm/sumologic/upgrade-2.0.0.sh
- tests/upgrade_v2_script/run.sh
- tests/upgrade_v2_script/static/prometheus_operator_valid.input.yaml
- tests/upgrade_v2_script/static/prometheus_operator_valid.log
- tests/upgrade_v2_script/static/prometheus_operator_valid.output.yaml
Create v2 migration script:
* add migration of `prometheus-operator.prometheusOperator.tlsProxy` -> `kube-prometheus-stack.prometheusOperator.tls`
* rename `prometheus-operator` -> `kube-prometheus-stack`
* rename `prometheus-operator.prometheus.prometheusSpec.containers.(name==prometheus-config-reloader)` -> `config-reloader` as `prometheus-config-reloader` is not supported anymore in prometheus-operator `0.43` [ref](https://github.com/prometheus-operator/prometheus-operator/blob/release-0.43/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml#L1122-L1132)
> v2 migration script

- ci/build.sh
- deploy/docker/Dockerfile
- deploy/helm/sumologic/conf/cleanup/cleanup.sh
- deploy/helm/sumologic/conf/setup/main.tf
- deploy/helm/sumologic/conf/setup/setup.sh
- deploy/helm/sumologic/templates/cleanup/cleanup-job.yaml
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/conditional_sources.output.yaml
- tests/terraform/static/custom.output.yaml
- tests/terraform/static/default.output.yaml
- tests/terraform/static/disable_default_metrics.output.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
- tests/terraform/static/traces.output.yaml
* bump terraform from `0.12.26` to `0.12.29`
* relax `sumologic` terraform provider version constraint to update up to (excluding) `3.0.0` when possible (instead of `2.5.0`)
* use the same image - `.Values.image.repository` for cleanup job (instead of `hashicorp:terraform`
* bundle terraform providers (`kubernetes` and `sumologic`) in `sumologic:kubernetes-fluentd` image (in `/terraform/.terraform`)
> Bundle terraform providers in kubernetes-fluentd image

- .travis.yml
- ci/tests.sh
- deploy/docs/v2_migration_doc.md
- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/templates/cleanup/cleanup-job.yaml
- deploy/helm/sumologic/templates/events-statefulset.yaml
- deploy/helm/sumologic/templates/metrics-statefulset.yaml
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/templates/statefulset.yaml
- deploy/helm/sumologic/upgrade-1.0.0.sh
- deploy/helm/sumologic/upgrade-2.0.0.sh
- deploy/helm/sumologic/values.yaml
- tests/run.sh
- tests/upgrade_script/static/chart_envs.output.yaml
- tests/upgrade_script/static/key_mapping_one_to_multiple.output.yaml
- tests/upgrade_script/static/prometheus_remote_write.output.yaml
- tests/upgrade_script/static/prometheus_remote_write_modified.output.yaml
- tests/upgrade_script/static/prometheus_service_monitors.input.yaml
- tests/upgrade_script/static/prometheus_service_monitors.output.yaml
- tests/upgrade_v2_script/static/image_rename.input.yaml
- tests/upgrade_v2_script/static/image_rename.log
- tests/upgrade_v2_script/static/image_rename.output.yaml
- tests/upgrade_v2_script/static/prometheus_operator_valid.log
- vagrant/Makefile
- vagrant/provision.sh
* migrate `image` to `sumologic.setup.job.image` and to `fluentd.image` (for now use the same image but prepare a separate image for setup job in a different PR)
* add this to v2 migration script and add its tests to CI
* change tests
* adjust migration script (v1) tests as they used `yq` arguments which changed in 3.4.0 and now need to be provided differently - we might actually end up remove this script as it's only relevant to 1.x branches
* bump `yq` in vagrant and on CI to 3.4.1
> Migrate image to fluentd.image and sumologic.setup.job.image

- deploy/helm/sumologic/templates/otelcol-deployment.yaml
- deploy/helm/sumologic/upgrade-2.0.0.sh
- deploy/helm/sumologic/values.yaml
- tests/upgrade_v2_script/static/otelcol_image_name.input.yaml
- tests/upgrade_v2_script/static/otelcol_image_name.log
- tests/upgrade_v2_script/static/otelcol_image_name.output.yaml
Migrate `otelcol.deployment.image.name` -> `otelcol.deployment.image.repository`
> Migrate otelcol image name to otelcol image repository

- .travis.yml
- README.md
- ci/build.sh
- deploy/docs/v1_conf_examples.md
- deploy/docs/v1_migration_doc.md
- deploy/helm/sumologic/Chart.yaml
- deploy/helm/sumologic/values.yaml
It's a backport of e1b46abe3075e7c839dcafdc301cd8d27631d5d7
> Migrate the default git branch from master to main

- .github/CODEOWNERS
- .travis.yml
- README.md
- ci/build.sh
- deploy/docs/v1_conf_examples.md
- deploy/docs/v1_migration_doc.md
- deploy/helm/sumologic/Chart.yaml
- deploy/helm/sumologic/values.yaml
It's a backport of the following commits:
96c4ace6f224993c57d8ab3605759d2dabee7ac9
fb7376675ef2cb6c83140edaaeef904fd9169b8c
19a931712c417fb475a4cb8e8793c8ccf0f3ca15
> Backport CODEOWNERS from the main branch

- deploy/helm/sumologic/Chart.yaml
> Add tracing to the helm chart description (backport of #1153)

- deploy/helm/sumologic/requirements.yaml
> Use official repo for telegraf-operator

- vagrant/Makefile
- vagrant/README.md
Add targets to test logs and metrics from receiver-mock (requested in [PR#1084](https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1084#discussion_r522136049))
> Add targets to test logs and metrics from receiver-mock

- deploy/docs/Troubleshoot_Collection.md
Fix prometheus-operator service names in troubleshooting docs
> Fix prometheus-operator service names in troubleshooting docs

- vagrant/Makefile
- vagrant/provision.sh
Clean makefile and update vagrant due to new ruby package
> Clean makefile and update vagrant due to new ruby package

- deploy/helm/sumologic/values.yaml
Fixes #1187 
Changes according to current definition of fluent-bit service:
```
$ kubectl describe svc collection-fluent-bit
Name:              collection-fluent-bit
Namespace:         sumologic
Labels:            app.kubernetes.io/instance=collection
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=fluent-bit
app.kubernetes.io/version=1.6.3
helm.sh/chart=fluent-bit-0.7.4
Annotations:       meta.helm.sh/release-name: collection
meta.helm.sh/release-namespace: sumologic
Selector:          app.kubernetes.io/instance=collection,app.kubernetes.io/name=fluent-bit
Type:              ClusterIP
IP:                10.152.183.87
Port:              http  2020/TCP
TargetPort:        http/TCP
Endpoints:         10.1.57.18:2020
Session Affinity:  None
Events:            <none>
```
> Change ServiceMonitor for fluent-bit - port and matchLabels

- vagrant/Makefile
Fixes following error:
```
$sumo-make expose-prometheus
kubectl port-forward -n "sumologic" service/collection-prometheus-oper-prometheus --address=0.0.0.0 9090
Error from server (NotFound): services "collection-prometheus-oper-prometheus" not found
make: *** [/sumologic/vagrant/Makefile:122: expose-prometheus] Error 1
```
> Fix expose-prometheus target in Makefile

- deploy/helm/sumologic/values.yaml
- Removed the flag `kubeTargetVersionOverride: 1.13.0-0`
- following node rule metrics have been removed in from 1.14, so we have to add them to our values file.
| Metrics                                      	|
|----------------------------------------------	|
| :node_cpu_saturation_load1:                  	|
| :node_cpu_utilisation:avg1m                  	|
| :node_disk_saturation:avg_irate              	|
| :node_disk_utilisation:avg_irate             	|
| :node_memory_swap_io_bytes:sum_rate          	|
| :node_memory_utilisation:                    	|
| :node_net_saturation:sum_irate               	|
| :node_net_utilisation:sum_irate              	|
| node:cluster_cpu_utilisation:ratio           	|
| node:cluster_memory_utilisation:ratio        	|
| node:node_cpu_saturation_load1: …
> Migrate off of the legacy pre-1.14 recording rules

- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/events-service-headless.yaml
- deploy/helm/sumologic/templates/events-service.yaml
- deploy/helm/sumologic/templates/metrics-service-headless.yaml
- deploy/helm/sumologic/templates/metrics-service.yaml
- deploy/helm/sumologic/templates/otelcol-service.yaml
- deploy/helm/sumologic/templates/service-headless.yaml
- deploy/helm/sumologic/templates/service.yaml
- deploy/helm/sumologic/values.yaml
> Add a new label for scraping metrics

- deploy/docs/v2_migration_doc.md
- deploy/helm/sumologic/upgrade-2.0.0.sh
> Add v2 migrations steps

- ci/_build_functions.sh
Fix CI not pushing helm charts
> Fix CI not pushing helm charts

- deploy/docs/Best_Practices.md
- deploy/helm/sumologic/values.yaml
> Set prometheus remoteTimeout to 5s

- deploy/helm/sumologic/values.yaml
Update coredns metrics due to 1.7.0 release
ref: https://coredns.io/2020/06/15/coredns-1.7.0-release/#metric-changes
> Update coredns metrics due to 1.7.0 release

- deploy/docker/Dockerfile
Bump fluentd image to v1.11.5
Changelog: https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1115---20201106
> Bump fluentd image to v1.11.5

- vagrant/k8s/receiver-mock.yaml
Bump receiver-mock image in vagrant to kubernetes-tools:2.1.0
https://github.com/SumoLogic/sumologic-kubernetes-tools/releases/tag/v2.1.0
> Bump receiver-mock image in vagrant to kubernetes-tools:2.1.0

- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/reader.rb
- fluent-plugin-enhance-k8s-metadata/test/helper.rb
- fluent-plugin-enhance-k8s-metadata/test/resources/pod_with_nonexistent_owner.json
- fluent-plugin-enhance-k8s-metadata/test/sumologic/kubernetes/test_reader.rb
This PR fixes the "undefined local variable or method `type'" error coming from enhance_k8s_metadata Fluent plugin.
Here's a sample error log:
```
2020-12-02 01:13:43 +0000 [error]: #0 undefined local variable or method `type' for #<Fluent::Plugin::EnhanceK8sMetadataFilter:007fc915dc9138>
```
> Prevent "undefined local variable or method" error from enhance_k8s_metadata Fluent plugin

- .github/workflows/release_builds.yml
- ci/_build_functions.sh
> Add pushing images to ghcr.io for release builds

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- deploy/docker/setup/Dockerfile
- deploy/docker/setup/Makefile
- deploy/docker/setup/main.tf
> kubernetes-setup Dockerfile

- .github/workflows/release_builds.yml
This will allowing automatic `kubernetes-image` build and push procedure whenever a proper semver tag is pushed to repository.
Image tags are being trimmed of `v` prefix.
> Add release job for kubernetes-setup image

- .gitignore
- deploy/helm/sumologic/conf/metrics/metrics.conf
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/checks.txt
- deploy/helm/sumologic/values.yaml
> Check minimal k8s version before installation

- deploy/helm/sumologic/conf/setup/custom.sh
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/conditional_sources.output.yaml
- tests/terraform/static/custom.output.yaml
- tests/terraform/static/default.output.yaml
- tests/terraform/static/disable_default_metrics.output.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
- tests/terraform/static/traces.output.yaml
> Explicitly log that setup.sh is missing when using custom setup scripts

- deploy/helm/sumologic/upgrade-2.0.0.sh
- tests/upgrade_v2_script/static/prometheus_remote_write_timeout.input.yaml
- tests/upgrade_v2_script/static/prometheus_remote_write_timeout.log
- tests/upgrade_v2_script/static/prometheus_remote_write_timeout.output.yaml
> Migration script v2 set remoteWrite remoteTimeout to 5s

- deploy/helm/falco-overrides.yaml
- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/values.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Backporting https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/94161a5e31a759768765258c663870bee45cdc36 to `release-v1.3`
> Use sumologic alias for ECR

- deploy/docs/Best_Practices.md
Since we've enabled persistence by default in #1033 let's document it.
> Document change in fluentd persistence in 2.0

- .github/workflows/dev_builds.yml
- .github/workflows/release_builds.yml
After https://github.com/actions/virtual-environments/issues/2219 got closed and resolved we can drop installing the most recent version of `aws`.
> Don't install aws cli when already available in gh env with ecr-public command

- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/test/plugin/test_filter_enhance_k8s_metadata.rb
The `@pods_to_services` variable is being initialized in another thread: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/035dc054d0811d13fb14aafcb85e048f3191d6fc/fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/service_monitor.rb#L52 We need to make sure `@pods_to_services` is not accessed until it's properly initialized.
> Prevent access to uninitialized variable

- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/setup/setup-job.yaml
- deploy/helm/sumologic/templates/setup/setup-scc.yaml
- deploy/kubernetes/fluentd-sumologic.yaml.tmpl
- deploy/kubernetes/setup-sumologic.yaml.tmpl
Added changes required for OpenShift support
```
helm upgrade  collection deploy/helm/sumologic -f deploy/helm/sumologic/values.yaml,vagrant/values.yaml --set sumologic.scc.create=true --set fluent-bit.securityContext.privileged=true
```
Used files:
[deploy/helm/sumologic/values.yaml](https://gist.github.com/kkujawa-sumo/de7517931c4e90d333f1fb8fe9eb11e6)
[vagrant/values.yaml](https://gist.github.com/kkujawa-sumo/fde38282ba2b755c288afaa83c6e7652)
Tested on VM with OpenShift 3.11 from https://github.com/hector-vido/okd-3.11 with following [Vagrantfile](https://gist.github.com/kkujawa-sumo/14e51861cce40707f5b4ba29a8c8da75)
Checked that metrics and logs are comming to receiver-mock.
Checked that following metrics are available:
- etcd_helper_cache_hit_count
- etcd_helper_cache_miss_count
- …
> Add changes required for OpenShift support

- deploy/docs/v2_migration_doc.md
Some minor tweaks to v2 migration docs.
> Update v2 migration doc

- deploy/docs/v2_migration_doc.md
Add steps required for fluent-bit to upgrade collection.
- fluent-bit uses sqlite, [see](https://docs.fluentbit.io/manual/pipeline/inputs/tail)
- sqlite db can be copied to make a backup of data, [see](https://sqlite.org/tempfiles.html), which is used in initContainer for temporary instance of fluent-bit
- `kubectl apply -f (--force)` causes that fluent-bit receives SIGTERM signal
Content of files which where used in tests in attached at the end.
weak point: fluent-bit metrics not available twice 
```
kubectl get daemonset -l "app=fluent-bit,release=my-release" -o yaml | \
yq w - "items[*].spec.selector.matchLabels[app.kubernetes.io/name]" "fluent-bit" | \
yq w - "items[*].spec.selector.matchLabels[app.kubernetes.io/instance]" "my-release" | \
yq w - …
```
> Add steps required for fluent-bit to upgrade

- fluent-plugin-enhance-k8s-metadata/lib/fluent/plugin/filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/test/plugin/test_filter_enhance_k8s_metadata.rb
- fluent-plugin-enhance-k8s-metadata/test/resources/records.json
After attaching `node=nil` metadata to a metrics record, the other plugin `prometheus_format` fails with "undefined method `gsub' for nil:NilClass":
```console
long-collection-sumologic-fluentd-metrics-8 fluentd 2020-12-23 11:18:21 +0000 [warn]: #0 dump an error event: error_class=NoMethodError error="undefined method `gsub' for nil:NilClass" location="/usr/local/bundle/gems/fluent-plugin-prometheus-format-1.3.2/lib/fluent/plugin/filter_prometheus_format.rb:127:in `escape'" tag="prometheus.metrics.state" time=2020-12-23 11:18:14.000000000 +0000 record={"@metric"=>"kube_pod_container_resource_limits", "app"=>"collections", "container"=>"forge-metrics", "endpoint"=>"http", "instance"=>"10.3.71.116:8080", "job"=>"kube-state-metrics", "namespace"=>"long-distributed-systems", …
```
> Do not attach empty 'node' metadata

- deploy/helm/sumologic/upgrade-2.0.0.sh
- tests/upgrade_v2_script/static/image_rename.input.yaml
- tests/upgrade_v2_script/static/image_rename.log
- tests/upgrade_v2_script/static/image_rename.output.yaml
Fix upgrade v2 script image rename and add also renaming `repository` (both for `fluentd` and for `setup` images)
---
> Fix upgrade v2 script image rename

- deploy/helm/sumologic/requirements.yaml
This fixes an issue where older versions of falco (`0.25.0`) try to download modules from https://dl.bintray.com/falcosecurity/driver instead of https://download.falco.org/?prefix=driver/
Default behaviour (controlled by `DRIVERS_REPO` env variable) has been changed in  https://github.com/falcosecurity/falco/pull/1460
Additionally `falco:0.26.2` has been pushed to https://gallery.ecr.aws/sumologic/falco
---
> Bump falco dependency to 1.5.7

- deploy/helm/sumologic/upgrade-2.0.0.sh
- tests/upgrade_v2_script/static/metrics_server.input.yaml
- tests/upgrade_v2_script/static/metrics_server.log
- tests/upgrade_v2_script/static/metrics_server.output.yaml
Add missing `metrics-server` migration for v2 migration script.
This will cover migration between [old helm chart's `args`](https://github.com/helm/charts/blob/7e45e678e39b88590fe877f159516f85f3fd3f38/stable/metrics-server/values.yaml#L37-L39) and [bitnami's chart `extraArgs`](https://github.com/bitnami/charts/blob/2b22a217020fe3d16ef98fdcdd4a562c43f9824a/bitnami/metrics-server/values.yaml#L79-L86)
---
> Upgrade v2 script - metrics server

- deploy/helm/sumologic/Chart.yaml
Bump kube-prometheus-stack to 12.9.2
---
> Bump kube-prometheus-stack to 12.9.2

- deploy/helm/sumologic/Chart.yaml
Bump kube-prometheus-stack to 12.10.4
---
> Bump kube-prometheus-stack to 12.10.4

- deploy/helm/sumologic/upgrade-2.0.0.sh
- deploy/helm/sumologic/values.yaml
- tests/upgrade_v2_script/static/image_rename.log
- tests/upgrade_v2_script/static/image_rename.output.yaml
Bump fluentd image to 1.11.5-sumo-0
---
> Bump fluentd image to 1.11.5-sumo-0

- ci/_build_functions.sh
- deploy/docs/Kube-Prometheus.md
- deploy/docs/Non_Helm_Installation.md
- deploy/docs/additional_prometheus_configuration.md
- deploy/docs/existingPrometheusDoc.md
- deploy/docs/standAlonePrometheus.md
- tests/functions.sh
- vagrant/k8s/receiver-mock.yaml
Use newer Kubernetes Tools to profit from fixed `template` command.
Release notes:
* [template] Wait 10s for stdin (due to kubectl delay)
* [template] Fix template command
* [template] Fix skipping first line of the values.yaml if file has been provided by stdin
The full list of changes can be found here:
https://github.com/SumoLogic/sumologic-kubernetes-tools/compare/v2.2.0...v2.2.3
---
> Upgrade Sumologic Kubernetes Tool version to 2.2.3

- deploy/helm/sumologic/upgrade-2.0.0.sh
- tests/upgrade_v2_script/static/prometheus_remote_write_regexes.log
- tests/upgrade_v2_script/static/prometheus_remote_write_regexes.output.yaml
- tests/upgrade_v2_script/static/prometheus_remote_write_regexes_changed_values.log
- tests/upgrade_v2_script/static/prometheus_remote_write_regexes_changed_values.output.yaml
- tests/upgrade_v2_script/static/prometheus_remote_write_timeout.log
- tests/upgrade_v2_script/static/prometheus_remote_write_timeout.output.yaml
- tests/upgrade_v2_script/static/prometheus_service_monitors.log
- tests/upgrade_v2_script/static/prometheus_service_monitors.output.yaml
Migrate `prometheus-config-reloader` only when overwritten in values.yaml
---
> Migrate prometheus-config-reloader only when overwritten in values.yaml

- deploy/helm/sumologic/upgrade-2.0.0.sh
- tests/upgrade_v2_script/static/fluent_bit.output.yaml
Lines copied from old `rawConfig` seem to have incorrectly stripped whitespace.
---
> Add v2 migration for fluent bit configs

- deploy/helm/sumologic/upgrade-2.0.0.sh
- tests/upgrade_v2_script/static/prometheus_operator_valid.input.yaml
- tests/upgrade_v2_script/static/prometheus_operator_valid.log
Add v2 migration logic for prometheus retention (`prometheus-operator.prometheus.prometheusSpec.retention`)
---
> Add v2 migration logic for prometheus retention

- deploy/helm/sumologic/upgrade-2.0.0.sh
- deploy/helm/sumologic/values.yaml
- tests/upgrade_v2_script/static/prometheus_operator_valid.output.yaml
- tests/upgrade_v2_script/static/prometheus_service_monitors.output.yaml
- tests/upgrade_v2_script/static/prometheus_whole_config.output.yaml
Fix missing `node:node_memory_bytes_available:sum` prometheus recording rule and thus unblock metrics like e.g. 
* `node:node_memory_utilisation:ratio`
* `node:node_memory_utilisation_2:`
* `node:cluster_memory_utilisation:ratio`
That depend on it.
Definition was taken from: https://github.com/helm/charts/blob/7e45e678e39b88590fe877f159516f85f3fd3f38/stable/prometheus-operator/templates/prometheus/rules/node.rules.yaml#L77-L83
---
> Add missing node:node_memory_bytes_available:sum prometheus recording rule

- deploy/helm/sumologic/Chart.yaml
Bump kube-prometheus-stack to [12.11.3](https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-12.11.3)
---
> Bump kube-prometheus-stack to 12.11.3

- deploy/helm/sumologic/values.yaml
Bumps OTC to `0.16.2-sumo`. It includes our extensions to filter processor. 
Manually tested and works fine
> Bump OTC to 0.16.2-sumo

- deploy/docs/Non_Helm_Installation.md
- deploy/docs/v2_migration_doc.md
Without CRDs update (from `v0.43.0` to `v0.44.0`) user is expected to get:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec): unknown field "shards" in com.coreos.monitoring.v1.Prometheus.spec
```
when using our chart with `kube-prometheus-stack` version >= `12.11.0`
---
> Update prometheus CRDs update instructions for 2.0 migration

- vagrant/provision.sh
Remove address flags from kube-scheduler and kube-controller-manager launch options
---
> kube-scheduler and kube-controller-manager listen on all interfaces in vagrant

- deploy/helm/sumologic/conf/buffer.output.conf
- deploy/helm/sumologic/conf/logs/logs.conf
- deploy/helm/sumologic/conf/logs/logs.output.conf
In case user overwrites default values in the following manner (i.e. without specifying a value for keys surround with conditions in this PR)
```yaml
fluentd:
buffer:
extraConf:
...
```
`helm` commands might render errors similar to:
```
Error: template: sumologic/templates/statefulset.yaml:19:28: executing "sumologic/templates/statefulset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: sumologic/templates/configmap.yaml:15:5: executing "sumologic/templates/configmap.yaml" at <tpl (.Files.Glob "conf/*.conf").AsConfig .>: error calling tpl: error during tpl function execution for "buffer.output.conf: |-\n  compress {{ .Values.fluentd.buffer.compress | quote }}\n  flush_interval {{ .Values.fluentd.buffer.flushInterval | quote }}\n …
```
> Add if conditions to fluentd configuration templates

- deploy/helm/sumologic/upgrade-2.0.0.sh
- tests/upgrade_v2_script/static/fluentd_whole_config.input.yaml
- tests/upgrade_v2_script/static/fluentd_whole_config.log
- tests/upgrade_v2_script/static/fluentd_whole_config.output.yaml
- tests/upgrade_v2_script/static/prometheus_whole_config.output.yaml
When using `yq` to write empty values (the ones with only `|-` or without values at all) it writes no values at all causing some helm templates to fail to render:
```
Error: template: sumologic/templates/statefulset.yaml:19:28: executing "sumologic/templates/statefulset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: sumologic/templates/configmap.yaml:15:5: executing "sumologic/templates/configmap.yaml" at <tpl (.Files.Glob "conf/*.conf").AsConfig .>: error calling tpl: error during tpl function execution for "buffer.output.conf: |-\n  compress {{ .Values.fluentd.buffer.compress | quote }}\n  flush_interval {{ .Values.fluentd.buffer.flushInterval | quote }}\n  flush_thread_count {{ .Values.fluentd.buffer.numThreads | quote }}\n …
```
> Update v2 migration script - quote empty values

- deploy/docs/SideBySidePrometheus.md
- deploy/docs/existingPrometheusDoc.md
Add prom oper compatibility note to docs
Backport of #1320 
---
> Add prom oper compatibility note to docs

- deploy/docs/Best_Practices.md
- deploy/docs/FluentdPersistence.md
- deploy/docs/v2_migration_doc.md
- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/values.yaml
Related #1214
Some of changes because of differences between helm2 and helm3 related to --force option, for details see : https://github.com/helm/helm/issues/7082#issuecomment-559558318, https://github.com/helm/helm/pull/7431
---
> Update information about changing Fluentd persistence

- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/cleanup/cleanup-clusterrole.yaml
- deploy/helm/sumologic/templates/cleanup/cleanup-clusterrolebinding.yaml
- deploy/helm/sumologic/templates/cleanup/cleanup-job.yaml
- deploy/helm/sumologic/templates/cleanup/cleanup-serviceaccount.yaml
* Add separate `ServiceAccount`, `ClusterRole` and `ClusterRoleBinding` for cleanup job
* Change cleanup job helm hook weight from `0` to `3` so that the RBAC resources (listed above) are created before the job runs
---
> Fix secret cleanup

- vagrant/Makefile
Add new prometheus CRDs to vagrant makefile and fix removing them.
---
> Add new prometheus CRDs to vagrant makefile when removing them from cluster

- deploy/docs/Best_Practices.md
- deploy/docs/FluentdPersistence.md
- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/values.yaml
> Fix #1322, update information about changing Fluentd persistence

- deploy/docker/setup/Dockerfile
After [release of alpine 3.13](https://alpinelinux.org/posts/Alpine-3.13.0-released.html) terraform has been bumped in their repositories to `0.14.4-r0` from`0.12.25-r0` what we rely on in setup image 
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/f01a31af115730b0901757ac8a458b85b9edcd73/deploy/docker/setup/Dockerfile#L3
hence pin the version of alpine to `3.12` instead of `3`.
---
> Pin setup image to alpine:3.12

- deploy/helm/sumologic/upgrade-2.0.0.sh
- tests/upgrade_v2_script/static/fluent_bit.input.yaml
- tests/upgrade_v2_script/static/fluent_bit.output.yaml
> Fix fluent-bit extraVolumes and extraVolumeMounts migration for v2

- deploy/helm/sumologic/values.yaml
Bump fluentd image to 1.12.0
---
> Bump fluentd image to 1.12.0

- deploy/helm/sumologic/conf/setup/main.tf
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/conditional_sources.output.yaml
- tests/terraform/static/custom.output.yaml
- tests/terraform/static/default.output.yaml
- tests/terraform/static/disable_default_metrics.output.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
- tests/terraform/static/traces.output.yaml
> Bump sumologic terraform provider to 2.6 and relax kubernetes provider version constraints

- .gitignore
- .markdownlint.jsonc
- .vscode/extensions.json
Note: This configuration is used by VS Code's Markdownlint extension and is only included for convenience.
The original and primary Markdownlint configuration as used in CI is `.markdownlint/style.rb`.
> Add configuration for VS Code's Markdownlint extension

- deploy/docs/Troubleshoot_Collection.md
- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/machineconfig/machineconfig-master.yaml
- deploy/helm/sumologic/templates/machineconfig/machineconfig-worker.yaml
- deploy/helm/sumologic/values.yaml
- Add `MachineConfig` to instal on nodes `kernel-devel`. Related to https://github.com/falcosecurity/falco/issues/1505 - missing `kernel-devel` on Red Hat Enterprise Linux CoreOS 46.82.202012151054-0 (Ootpa)
- Add init container to avoid of having falco pods in` CrashLoopBackOff` when nodes are waiting for being configured. Configuration of machines takes longer period of the time. Nodes are restarted to apply changes in configuration, see [workflow for changing machine configuration](https://github.com/openshift/machine-config-operator/blob/master/docs/MachineConfigDaemon.md).
Tested with:
```
helm upgrade --install collection -n sumologic -f deploy/helm/sumologic/values.yaml \
--set kube-prometheus-stack.prometheusOperator.enabled=false \
--set sumologic.accessId="dummy" \
--set …
```
> Add support for falco on OpenShift 4.6

- deploy/docs/Troubleshoot_Collection.md
- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/values.yaml
- Fixed information about falco on GKE
- Changed information about default setting for falco.ebpf.enabled in chart Readme.md, in [falco 1.5.7](https://github.com/falcosecurity/charts/releases/tag/falco-1.5.7) there is following setting:
```
ebpf:
enabled: false
```
Related to https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1356
---
> Fix information about falco on GKE

- .markdownlint.jsonc
Disabling some rules that are disabled in `.markdownlint/style.rb`.
> Make VS Code's Markdownlint behave more like CI's Markdownlint

- deploy/docs/v1_migration_doc.md
Non_Helm_Installation.md was modified in #686 and sections "Deploy FluentBit" and "Deploy Prometheus" were removed. The last Non_Helm_Installation.md with "Deploy FluentBit" and "Deploy Prometheus" sections is available on release-v1.0 branch.
---
> Fix links to Prometheus and FluenBit deploy instuctions

- deploy/docs/Troubleshoot_Collection.md
- deploy/helm/falco-overrides.yaml
- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/templates/_helpers.tpl
- deploy/helm/sumologic/templates/machineconfig/machineconfig-master.yaml
- deploy/helm/sumologic/templates/machineconfig/machineconfig-worker.yaml
- deploy/helm/sumologic/values.yaml
Backport of #1354
Add support for falco on OpenShift with missing kernel-devel package
by extending machine configuration through Machine Config operator
On OpenShift 3.11 tested with:
```
helm upgrade --install collection -n sumologic -f deploy/helm/sumologic/values.yaml \
--set kube-prometheus-stack.prometheusOperator.enabled=false \
--set sumologic.accessId="dummy" \
--set sumologic.accessKey="dummy" \
--set sumologic.endpoint="http://receiver-mock.receiver-mock:3000/terraform/api/" \
--set sumologic.clusterName="clusterkasi" \
--set kube-prometheus-stack.prometheusOperator.enabled=false \
--set kube-prometheus-stack.prometheus-node-exporter.service.port=9200 \
--set kube-prometheus-stack.prometheus-node-exporter.service.targetPort=9200 \
--set sumologic.scc.create=true \
--set …
```
> [Backport of #1354] Add support for falco on OpenShift with missing kernel-devel package

- ci/push-helm-chart.sh
Because of ambiguous versions being produced (most likely caused by calling `git describe` on a repo with only one branch checked out on Github Actions [link](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/20922c23e213249cbd7466360b1b1e1f40124af5/ci/_build_functions.sh#L60-L75) versus the same command being called on a full repo locally) let's use a longer version for our dev helm charts, i.e. 40 SHA characters.
---
> Use 40 SHA chars in dev helm chart versions

- deploy/helm/sumologic/conf/setup/main.tf
- deploy/kubernetes/setup-sumologic.yaml.tmpl
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/conditional_sources.output.yaml
- tests/terraform/static/default.output.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
- tests/terraform/static/traces.output.yaml
This should fix crashes like the one below:
```
Initializing the backend...
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "kubernetes" (hashicorp/kubernetes) 1.11.4...
- Downloading plugin for provider "sumologic" (terraform-providers/sumologic) 2.0.3...
Warning: registry.terraform.io: For users on Terraform 0.13 or greater, this provider has moved to SumoLogic/sumologic. Please update your source in required_providers.
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this …
```
> Bump terraform sumologic provider in release v1.3

- deploy/docs/v1_conf_examples.md
Link to `logs.source.containers.conf#L51` was introduced in https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/e96ace9e02ff6bb797aee575f6c4f143b0f32465# on that day `logs.source.containers.conf` had form from this commit: https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/3e50bc0b1abc4419098f5378ae665f9142924a7a# 
Currently content from `logs.source.containers.conf#L51` is available in `logs.source.containers.conf#L75`.
---
> Fix link to Fluentd output configuration

- deploy/docs/v1_conf_examples.md
Manual backport of #1379 into release-v1.3
---
> [Manual backport] Fix link to Fluentd output configuration

- deploy/helm/sumologic/conf/setup/main.tf
- tests/terraform/static/all_fields.output.yaml
- tests/terraform/static/collector_fields.output.yaml
- tests/terraform/static/conditional_sources.output.yaml
- tests/terraform/static/custom.output.yaml
- tests/terraform/static/default.output.yaml
- tests/terraform/static/disable_default_metrics.output.yaml
- tests/terraform/static/strip_extrapolation.output.yaml
- tests/terraform/static/traces.output.yaml
NOTE: Before we bump terraform to 0.13 in setup job this PR will break main 😲 
---
> Bump setup job's main.tf to work with terraform 0.13

- deploy/helm/sumologic/values.yaml
Bump setup image to [2.0.1](https://github.com/SumoLogic/sumologic-kubernetes-setup/releases/tag/v2.0.1)
---
> Bump setup image to 2.0.1

- ci/build.sh
- ci/push.sh
- ci/tests.sh
Manual backport of https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1374
---
> Use 40 SHA chars in dev helm chart versions on release-1.3 branch

- deploy/docs/Troubleshoot_Collection.md
- deploy/helm/falco-overrides.yaml
- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/values.yaml
Manual backport of #1360 into release-v1.3
---
> [Backport] Fix information about falco on GKE

- deploy/docs/Best_Practices.md
It doesn't seem that "Excluding Logs From Specific Components" is a child topic of "Fluentd File-Based Buffer", so I have moved the topic up one level.
> docs: Fix typos

- deploy/helm/sumologic/README.md
- deploy/helm/sumologic/conf/logs/logs.source.containers.conf
- deploy/helm/sumologic/conf/logs/logs.source.default.conf
- deploy/helm/sumologic/conf/logs/logs.source.systemd.conf
- deploy/helm/sumologic/values.yaml
The `fluentd.logs.containers` section in `values.yaml` file has `extraFilterPluginConf` extensibility point to inject more plugins into the Fluentd configuration, but lacks the `extraOutputPluginConf` entry similar to existing `fluentd.metrics.extraOutputPluginConf`.
Added the `extraOutputPluginConf` entry to `containers` section and also added both `extraFilterPluginConf` and `extraOutputPluginConf` to `kubelet`, `systemd` and `default` sections.
> Add extensibility points in values.yaml for Fluentd plugins for logs

- deploy/docker/Dockerfile
- fluent-plugin-enhance-k8s-metadata/Gemfile
- fluent-plugin-enhance-k8s-metadata/fluent-plugin-enhance-k8s-metadata.gemspec
- fluent-plugin-enhance-k8s-metadata/lib/sumologic/kubernetes/connector.rb
- fluent-plugin-events/Gemfile
- fluent-plugin-events/fluent-plugin-events.gemspec
- fluent-plugin-events/lib/sumologic/kubernetes/connector.rb
- fluent-plugin-kubernetes-metadata-filter/Gemfile
- fluent-plugin-kubernetes-metadata-filter/fluent-plugin-kubernetes-metadata-filter.gemspec
- fluent-plugin-kubernetes-metadata-filter/lib/fluent/plugin/filter_kubernetes_metadata.rb
The Fluentd plugins we use make a good amount of HTTP connections to the Kubernetes API server for Kubernetes metadata enrichment. Until now, the HTTP connections were being closed after each HTTP request, requiring a new HTTP connection to be established on every request to API server. This was a suboptimal solution, and the root cause for SNAT port exhaustion in AKS clusters.
With this change, we are using a yet unreleased version of [Kubeclient](https://github.com/abonas/kubeclient/) library to be able to create persistent HTTP connections. The Kubeclient library (which is used by our Fluentd plugins to make requests to k8s API server) originally used [RestClient](https://github.com/rest-client/rest-client/) gem under the hood, which does not make it possible to create persistent …
> Make connections to k8s API server persistent

- deploy/docs/Working_with_container_registries.md
Since container images have been moved to AWS Public ECR let's update the docs accordingly and explain how to authenticate
---
> docs: Update documentation about authenticating with container registries

- deploy/helm/sumologic/values.yaml
Changelog: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/releases/tag/v1.12.0-sumo-1-rc.0
- Make connections to k8s API server persistent (https://github.com/SumoLogic/sumologic-kubernetes-fluentd/pull/111)
- Bump net-http-persistent from 3.1.0 to 4.0.1 (https://github.com/SumoLogic/sumologic-kubernetes-fluentd/pull/117)
> Bump fluentd from 1.12.0-sumo-0-rc.0 to 1.12.0-sumo-1-rc.0

- deploy/helm/fluent-bit-overrides.yaml
- deploy/helm/sumologic/Chart.lock
- deploy/helm/sumologic/values.yaml
Bump fluent-bit to newest version (1.6.10)
---
> Bump fluent-bit to 1.6.10

- deploy/helm/sumologic/values.yaml
- tests/tracing/static/collection-monitoring-false.output.yaml
- tests/tracing/static/simple.output.yaml
Update OTC to v0.19.2-sumo 
---
> Switch to OTC v0.19.2-sumo

- deploy/helm/sumologic/values.yaml
- tests/tracing/static/collection-monitoring-false.output.yaml
- tests/tracing/static/simple.output.yaml
Enable otlphttp exporter in tracing collection
---
> Enable otlphttp exporter in tracing collection

- deploy/helm/sumologic/values.yaml
Bump otelagent version from 0.16.2-sumo to 0.19.2-sumo
---
> Bump otelagent version from 0.16.2-sumo to 0.19.2-sumo

- deploy/helm/sumologic/values.yaml
Changes from 1.11.5-sumo-0:
- Upgrade Fluentd to 1.12.0
- Make connections to k8s API server persistent
- Use numeric user ID in Fluentd Dockerfile
See https://github.com/SumoLogic/sumologic-kubernetes-fluentd/compare/v1.11.5-sumo-0...v1.12.0-sumo-1
for all commits.
> Upgrade Fluentd to 1.12.0-sumo-1
